### ISSUE TITLE
single script package casts exception upon uninstall

### ISSUE THREAD

**Issue by vaab** [pypa/setuptools#1003]
To reproduce:

- Setup the simple test package:
```
mkdir /tmp/scriptpack
cd /tmp/scriptpack

cat <<EOF > setup.py
#!/usr/bin/env python                                                                                                            
from setuptools import setup

setup(name='scriptpack',
      version='0.1',
      scripts=['script.py'])

EOF

cat <<EOF > script.py
#!/usr/bin/env python

print "hello world"
EOF

chmod +x script.py
```
- Trigger the error:

```
python setup.py install &&
pip uninstall -y -v scriptpack
```

I'm having this exception on the last instruction:
```
Uninstalling scriptpack-0.1:
  Removing file or directory /usr/local/bin/script.py
  Removing file or directory /usr/local/lib/python2.7/site-packages/scriptpack-0.1-py2.7.egg
  Removing pth entries from /usr/local/lib/python2.7/site-packages/easy-install.pth:
  Removing entry: ./scriptpack-0.1-py2.7.egg
  Successfully uninstalled scriptpack-0.1
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==10.0.0.dev0', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 232, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 250, in main
    timeout=min(5, options.timeout)) as session:
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 333, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 123, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 842, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 639, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 695, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1950, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1464, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1824, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1704, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1644, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/scriptpack-0.1-py2.7.egg'
```

Note:
- The package gets correctly uninstalled (you can see this only with ``-v``)
- This behavior is not happening with old ``setuptools 9.1`` and ``pip``.
- This doesn't happen if ``zip_safe`` is set to ``False``.
- Checked failing on master version of ``pip`` and current pypi version.
- tested on debian docker, python 2.7.13
- pip list:
```
pip list
Package    Version    
---------- -----------
appdirs    1.4.3      
packaging  16.8       
pip        10.0.0.dev0
pyparsing  2.2.0      
rwt        2.14       
setuptools 34.3.3     
six        1.10.0     
virtualenv 15.1.0     
wheel      0.29.0     
```

Tell me if I'm doing anything wrong, I was expecting this to work. If this should not work I'll be happy to have links to documentation that explain why this output is expected.

**Comment by jaraco** [comment]
The problem exists in part because you're using the old and soft-deprecated `easy_install` to install the package (implicitly via `setup.py install`). Better would be to use pip to install the package with `pip install .`. You probably won't have the issue if you install that way. Can you confirm?

**Comment by vaab** [comment]
I confirm that it works properly with ``pip install .`` ... I though that ``python setup.py install`` was still wildly used and the expected default way of installing a package having a ``setup.py``. I also understand that this "deprecation" (what do you mean by "soft-deprecated" ?) probably is aiming for a better future.

Maybe what is missing is to:
- just make it work as for the previous version of ``setuptools``... if possible.
- or output a warning ("you're package was made by easy_install, and that baaad, don't use it, here's how to do it properly")... notice that previous point and this point are not incompatible.
- why is ``python setup.py install`` still using ``easy_install`` if it is not the right way and the right way is well known ?

Sorry as I'm a probably messed up with ``setuptools``, ``easy_install``, ``pip`` and other's python packaging tools.

I still feel this exception could be avoided (or have a better error message) and it would make the python packaging world a better place without impeding with the patient implementation of the big cleaning goals.

**Comment by jaraco** [comment]
I agree it would be nicer if this issue didn't occur. A similar issue was reported in pypa/pip#2545, although that issue seemed to be related primarily to uninstalling setuptools itself. 

I've updated your post to use `pip uninstall scriptpack` instead of `pip uninstall install`, which I believe was a typo.

I am able to replicate the failure, even stable pip 9.0.1.

It seems that what's happening is that during the version check following an uninstall of an egg, the construction of a working set will crash.

Let's see if we can replicate the failure without pip... Yes:

```
$ python setup.py install       
running install
...
Installed /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scriptpack-0.1-py3.6.egg
Processing dependencies for scriptpack==0.1
Finished processing dependencies for scriptpack==0.1
$ python                 
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/Users/jaraco/Library/Python/3.6/lib/python/site-packages', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyObjC', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scriptpack-0.1-py3.6.egg']
>>> import os
>>> os.remove(sys.path[-1])
>>> import pkg_resources
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
...
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scriptpack-0.1-py3.6.egg'
```

The issue seems to be that pkg_resources will choke when an egg on sys.path is removed before pkg_resources is imported then pkg_resources is imported.

**Comment by Avasam** [comment]
setuptools no longer relies on pkg_resources, so if this issue is still relevant, the symptoms will be different.

**Comment by abravalheri** [comment]
Thank you very much @Avasam .


I will close this issue as stale for now, but the author can re-open it with new information if necessary or create a new issue.
