### ISSUE TITLE
Can not install setuptools in virtualenv on Debian Wheezy/Jessie. Tries to upgrade system version

### ISSUE THREAD

**Issue by gertjanol** [pypa/setuptools#1012]
When installing `cryptography` in a virtualenv, I ran into the following. `cryptography` depends on `setuptools>=11.3`. Debian has an ancient version of setuptools, which for some reason 'bleeds' into the virtualenv.

When `setuptools` is upgraded, it results in an error like `OSError: [Errno 2] No such file or directory: '/root/my-env/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg'`

This is easily reproducible using Docker:
```
docker pull debian:wheezy
docker run -ti debian:wheezy /bin/bash

apt-get update && apt-get -y install python-virtualenv
virtualenv --python /usr/bin/python2.7 --setuptools /root/my-env
/root/my-env/bin/pip install --upgrade pip
/root/my-env/bin/pip install --upgrade setuptools
```

Results in:
```
Collecting setuptools
  Downloading setuptools-34.4.1-py2.py3-none-any.whl (390kB)
    100% |################################| 399kB 3.0MB/s 
Collecting six>=1.6.0 (from setuptools)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools)
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |################################| 61kB 9.7MB/s 
Installing collected packages: six, pyparsing, packaging, appdirs, setuptools
  Found existing installation: setuptools 0.6rc11
    Uninstalling setuptools-0.6rc11:
      Successfully uninstalled setuptools-0.6rc11
Successfully installed appdirs-1.4.3 packaging-16.8 pyparsing-2.2.0 setuptools-34.4.1 six-1.10.0
Traceback (most recent call last):
  File "/root/my-env/bin/pip", line 8, in <module>
    load_entry_point('pip==9.0.1', 'console_scripts', 'pip')()
  File "/root/my-env/local/lib/python2.7/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/root/my-env/local/lib/python2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/root/my-env/local/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/root/my-env/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/root/my-env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/root/my-env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/root/my-env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/root/my-env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/root/my-env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/root/my-env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/root/my-env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/root/my-env/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg'
```

On Debian Jessie (replace wheezy with jessie in the docker commands) the result is the same.

**Comment by jaraco** [comment]
I believe this is a pip issue, with a fix merged but not yet released.
