### ISSUE TITLE
Value error, bad marshal data, while installing pylint

### ISSUE THREAD

**Issue by ngendah** [pypa/setuptools#1020]
### Steps to reproduce:
1. Create a virtualenv, then pip install zc.buildout.
2. Create a testing directory, `cd` into it and add the following buildout.cfg file:
```
[buildout]
parts =
    tests

[tests]
recipe = zc.recipe.egg:scripts
interpreter = python
eggs =
     pylint
```
3. run `buildout`

### My Results:
`os version 4.10.10-200.fc25.x86_64`
`python version 3.5.3`
```
Creating directory '/home/home/Develop/pylint-test/eggs'.
Creating directory '/home/home/Develop/pylint-test/bin'.
Creating directory '/home/home/Develop/pylint-test/parts'.
Creating directory '/home/home/Develop/pylint-test/develop-eggs'.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Got zc.recipe.egg 2.0.3.
Installing tests.
Getting distribution for 'pylint'.
zip_safe flag not set; analyzing archive contents...

Installed /tmp/easy_install-u8n6_y2y/pylint-1.7.1/.eggs/pytest_runner-2.11.1-py3.5.egg
warning: no files found matching 'README'
warning: no files found matching 'README.Python3'
warning: no files found matching '*.jpeg' under directory 'doc'
warning: no files found matching '*.html' under directory 'doc'
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-u8n6_y2y/pylint-1.7.1/setup.py", line 173, in <module>
  File "/tmp/easy_install-u8n6_y2y/pylint-1.7.1/setup.py", line 170, in install
  File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 2280, in main
    **kw
  File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 880, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1119, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1105, in run_setup
    run_setup(setup_script, args)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-u8n6_y2y/pylint-1.7.1/setup.py", line 173, in <module>
  File "/tmp/easy_install-u8n6_y2y/pylint-1.7.1/setup.py", line 170, in install
  File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
An error occurred when trying to install /tmp/tmpm4qm6nmrget_dist/pylint-1.7.1.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing tests.
  Getting distribution for 'pylint'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/home/home/Develop/pylint-test/eggs/zc.recipe.egg-2.0.3-py3.5.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/home/Develop/pylint-test/eggs/zc.recipe.egg-2.0.3-py3.5.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/zc/buildout/easy_install.py", line 665, in install
    for dist in self._get_dist(requirement, ws):
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/zc/buildout/easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/home/.virtualenv/pyl/lib/python3.5/site-packages/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by ngendah** [comment]
Tracked down the issue to pylint current(1.7.1) distribution available on pypi.
The directory test/regrtest_data/dummy_plugin, includes a *.pyc, which is the cause of the problem.
