### ISSUE TITLE
AttributeError: '_NamespacePath' object has no attribute 'sort' (36.0.1)

### ISSUE THREAD

**Issue by FRidh** [pypa/setuptools#1056]
I noticed [one package](https://files.pythonhosted.org/packages/71/55/505702ebc7573566786385403b955ebd69cf4ee962bd8c268d7281c338ac/nix-nox-0.0.5.tar.gz) that was [broken](https://github.com/NixOS/nixpkgs/issues/26392) when we [upgraded](https://github.com/NixOS/nixpkgs/commit/bdd3f307397a9c2e7ed838865ec4e70f5c36c722) `setuptools` from 30.0.2 to 36.0.1 in Nixpkgs. Maybe others broke as well, I don't know.

```
creating build/bdist.linux-x86_64/wheel/nix_nox-0.0.5.dist-info/WHEEL
installing
/build/nix-nox-0.0.5/dist /build/nix-nox-0.0.5
Traceback (most recent call last):
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/bin/.pip-wrapped", line 2, in <module>
    import sys;from pip import main
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/nix/store/vksfzp8lwrj0cb8yfnj3pzghdfmx90bx-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

builder for ‘/nix/store/plq33y0pzhnnyqzb4l8v9y0ar8s4s2qw-nox-0.0.5.drv’ failed with exit code 1
```
The trace is entirely in `pip`, yet it happened when we upgraded `setuptools`. Nothing else changed.
cc @dstufft @jaraco

**Comment by FRidh** [comment]
Possibly related to https://github.com/pypa/setuptools/issues/885.

**Comment by jaraco** [comment]
The issue lies in pypa/pip#4216, which is rooted in #885, as you suspected. I don't believe there's anything more that Setuptools can do about it but wait for a release of pip that includes the fix.
