### ISSUE TITLE
ssl_support.opener_for fails for SNI and other cases

### ISSUE THREAD

**Issue by fschulze** [pypa/setuptools#1109]
```
>>> from setuptools.ssl_support import opener_for
>>> opener_for(None)('https://florian-schulze.net')
...
ssl.CertificateError: hostname 'florian-schulze.net' doesn't match either of 'lirrebit.de', 'www.lirrebit.de'
```

I also get SSL verification errors for a domain which I redirect to ``127.0.0.1`` via ``/etc/hosts`` but which has a valid Let's Encrypt certificate running devpi (my main use case).

Other Let's Encrypt certificates, like ``devpi.net``, work fine.

Self compiled Python 2.7.13 (https://github.com/collective/buildout.python) using OpenSSL 1.0.2l via homebrew:
```
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.2l  25 May 2017'
```

I'm on macOS Sierra (10.12.6).

This is mostly an issue with zc.buildout, which relies on setuptools.

I'm not sure when these issues started. I tried going back in setuptools versions, but it seems like it's unrelated to that. It might have been the upgrade to Sierra, but I doubt that, because I did that around March and did a lot of stuff since then.

**Comment by jaraco** [comment]
I'm able to replicate the issue on Python 3.6.1. I'm also able to replicate it on Python without Setuptools:

```
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket, ssl
>>> addr = 'florian-schulze.net', 443
>>> sock = socket.create_connection(addr)
>>> ssl_sock = ssl.wrap_socket(sock, cert_reqs=ssl.CERT_REQUIRED, ca_certs='/etc/ssl/cert.pem')
>>> ssl.match_hostname(ssl_sock.getpeercert(), 'florian-schulze.net')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 321, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'florian-schulze.net' doesn't match either of 'lirrebit.de', 'www.lirrebit.de'
>>> 
```

I did some [investigation using openssl](http://blog.chrismeller.com/testing-sni-certificates-with-openssl), but I didn't see anything that revealed the issue. Still, since the issue can be readily replicated in pure Python, I don't think the issue is with Setuptools.

**Comment by fschulze** [comment]
The weird thing is that it used to work. Also ``pip`` works fine, but afaik it uses ``requests``. Using plain ``urllib2.urlopen`` in Python 2.7 also works fine and I'm pretty sure 2.7.13 added hostname verification and SNI support, but I haven't verified that yet.

**Comment by alex** [comment]
You need to pass `hostname` to `ssl.wrap_socket`. I strongly recommend not using this code on pythons that are recent enough to validate HTTPS connections by default, it handles things like SNI correctly.

**Comment by fschulze** [comment]
Is there an easy way to detect Python versions that support it and just use urlopen for them?

**Comment by alex** [comment]
2.7.9+ and... I can't remember which py3 versions.

**Comment by kleptog** [comment]
I can confirm that the following change makes setuptools work just fine for SNI on Python 2.7.9:

```
--- eggs/setuptools-33.1.1-py2.7.egg/setuptools/package_index.py.bak	2017-08-10 14:32:43.816595309 +0200
+++ eggs/setuptools-33.1.1-py2.7.egg/setuptools/package_index.py	2017-08-10 14:32:56.296715083 +0200
@@ -305,10 +305,7 @@
             and ssl_support.is_available
             and (ca_bundle or ssl_support.find_ca_bundle())
         )
-        if use_ssl:
-            self.opener = ssl_support.opener_for(ca_bundle)
-        else:
-            self.opener = urllib.request.urlopen
+        self.opener = urllib.request.urlopen
 
     def process_url(self, url, retrieve=False):
         """Evaluate a URL as a possible download, and maybe retrieve it"""

```
