### ISSUE TITLE
Pillow fails to install on Python 3.x since 36.1.0

### ISSUE THREAD

**Issue by fschulze** [pypa/setuptools#1110]
Starting with setuptools 36.1.0 Pillow fails to install with Python >= 3.4:
```
/Users/fschulze/Development/python/parts/opt/bin/easy_install-3.5 -U --always-unzip Pillow'
Traceback (most recent call last):
  File "/Users/fschulze/Development/python/parts/opt/bin/easy_install-3.5", line 11, in <module>
    load_entry_point('setuptools==36.2.3', 'console_scripts', 'easy_install-3.5')()
  File "/Users/fschulze/Development/python/parts/opt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/fschulze/Development/python/parts/opt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Users/fschulze/Development/python/parts/opt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/fschulze/Development/python/parts/opt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/fschulze/Development/python/parts/opt/lib/python3.5/site-packages/setuptools-36.2.3-py3.5.egg/setuptools/command/easy_install.py", line 47, in <module>
  File "/Users/fschulze/Development/python/parts/opt/lib/python3.5/site-packages/setuptools-36.2.3-py3.5.egg/setuptools/sandbox.py", line 15, in <module>
ImportError: No module named 'pkg_resources.py31compat
```

**Comment by benoit-pierre** [comment]
I can't reproduce this locally. Any reason you're using easy_install over pip?

**Comment by fschulze** [comment]
I use it indirectly, because zc.buildout is built on it. But you are right, I can't reproduce it directly with easy_install. I need to investigate further. It might be caused by something in zc.buildout.

**Comment by fschulze** [comment]
The issue is a lot more complex and I don't think setuptools is to be blamed.
