### ISSUE TITLE
Unclear error when classifiers is a tuple

### ISSUE THREAD

**Issue by rpkilby** [pypa/setuptools#1163]
Apologies if this is noise/a known issue, but I didn't see a similar issue. 

On python 3.6, when `classifiers` are a tuple instead of a list, you receive the following error when uploading:

```python
running upload
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/upload.py", line 63, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/upload.py", line 161, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
```

Note that this had previously worked on python 2.7

Another report: https://reinbach.com/blog/setuptools-classifiers-upload-python3-5/

**Comment by dokterbob** [comment]
Running into same bug here.

**Comment by cryvate** [comment]
This is actually due to distutils (stdlib of Python), [in particular this is the offending line](https://github.com/python/cpython/blob/803ddd8ce22f0de3ab42fb98a225a704c000ef06/Lib/distutils/command/upload.py#L150): your tuples will end being packed into a list.

For reference, the solution is to use a list instead of tuple to specify your qualifiers.

**Comment by rpkilby** [comment]
Thanks for pinpointing the source of the issue @cryvate. Looking through the issue tracker, it has already been reported (see: https://bugs.python.org/issue19610).
