### ISSUE TITLE
Files within package_data shouldn't be syntax checked

### ISSUE THREAD

**Issue by wil93** [pypa/setuptools#1177]
You can download a short self contained correct example showing the issue here: [testbug1.zip](https://github.com/pypa/setuptools/files/1394824/testbug1.zip)

Take this setup.py file:

```
from setuptools import setup, find_packages

setup(
    name="testbug1",
    packages=find_packages(),
    package_data={"testbug1": ["just_files/*.*"]}
)
```

with this folder structure:

```
.
├── setup.py
└── testbug1
    ├── __init__.py
    └── just_files
        ├── anotherfile.cpp
        └── testfile.py
```

where `testfile.py` and `anotherfile.cpp` are just files, not source code that I want to use as part of my software.

The output produced by `python setup.py install` will be:

```
running install
...
creating build/bdist.linux-x86_64/egg/testbug1/just_files
copying build/lib/testbug1/just_files/anotherfile.cpp -> build/bdist.linux-x86_64/egg/testbug1/just_files
copying build/lib/testbug1/just_files/testfile.py -> build/bdist.linux-x86_64/egg/testbug1/just_files
byte-compiling build/bdist.linux-x86_64/egg/testbug1/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/testbug1/just_files/testfile.py to testfile.cpython-35.pyc
  File "build/bdist.linux-x86_64/egg/testbug1/just_files/testfile.py", line 1
    this file just happens to have a py extension
            ^
SyntaxError: invalid syntax

creating build/bdist.linux-x86_64/egg/EGG-INFO
...
Finished processing dependencies for testbug1==0.0.0
```

---

The issue is: `testfile.py` shouldn't get syntax checked. Especially since it's not getting installed in a package (it's there, but I can't import it, nor do I want to)

See:

```
>>> import testbug1
>>> import testbug1.just_files
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'testbug1.just_files'
```

(the output above is completely fine!)

**Comment by peterkinalex** [comment]
Ok
