### ISSUE TITLE
Add more tests for PEP 517

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#1221]
One issue with [this code](https://github.com/pypa/setuptools/blob/b729553a6c6b92dfc7cfd9c577f2399bfde3000e/setuptools/build_meta.py#L120-L124) is that it's completely untested. In some cases, setup.py egg_info can create a directory not in the `egg_base`, but in a subdirectory. We need to figure out when this can happen, and then add a test for it.

**Comment by xoviat** [comment]
Here's the test failure that occured at the time:
```

tests/functional/test_uninstall.py Collecting pd.requires==0.0.3
  Downloading pd.requires-0.0.3.tar.gz
  Installing build dependencies
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command /tmp/pytest-of-travis/pytest-0/test_uninstall_namespace_packa0/workspace/venv/bin/python3.6 -I -c "
    import importlib
    import os
    import sys
    
    py_path = '/tmp/pytest-of-travis/pytest-0/test_uninstall_namespace_packa0/workspace/tmp/pip-build-env-7b1av7_j/lib/python3.6/site-packages'
    if py_path is not None:
        sys.path[0:0] = py_path.split(os.pathsep)
    mod = importlib.import_module('setuptools.build_meta')
    res = getattr(mod, 'prepare_metadata_for_build_wheel')(*('/tmp/pytest-of-travis/pytest-0/test_uninstall_namespace_packa0/workspace/tmp/pip-install-4ayg6_0p/pd.requires/pip-dist-info',), **{})
    with open('/tmp/pytest-of-travis/pytest-0/test_uninstall_namespace_packa0/workspace/tmp/tmpmmbnxxmx', 'w') as fp:
        fp.write(repr(res))
    ":
    running dist_info
    writing src/pd.requires.egg-info/PKG-INFO
    writing dependency_links to src/pd.requires.egg-info/dependency_links.txt
    writing entry points to src/pd.requires.egg-info/entry_points.txt
    writing namespace_packages to src/pd.requires.egg-info/namespace_packages.txt
    writing requirements to src/pd.requires.egg-info/requires.txt
    writing top-level names to src/pd.requires.egg-info/top_level.txt
    reading manifest file 'src/pd.requires.egg-info/SOURCES.txt'
    writing manifest file 'src/pd.requires.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 10, in <module>
      File "/tmp/pytest-of-travis/pytest-0/test_uninstall_namespace_packa0/workspace/tmp/pip-build-env-7b1av7_j/lib/python3.6/site-packages/setuptools/build_meta.py", line 80, in prepare_metadata_for_build_wheel
        assert len(dist_infos) == 1
    AssertionError
    
    ----------------------------------------
Directory listing
pd.requires.dist-info
F
```

**Comment by xoviat** [comment]
Any ideas on how this could have happened?

**Comment by jaraco** [comment]
Given that PEP 517 support has improved and that I haven't encountered this issue and that there's no reproducer in the ticket and that the original reporter is gone and that the scope of the ticket is too broad, I'm going to close this, though I welcome a new ticket or tickets to address specific issue that remain.
