### ISSUE TITLE
.eggs cache pollutes working directory, breaking stdeb

### ISSUE THREAD

**Issue by sjlongland** [pypa/setuptools#1233]
Hi all,

I'm in the process of packaging up `bacpypes` as a Debian package.  This requires `pytest-runner`, which uses `setuptools`.  Build platform is Debian Jessie, and I have successfully packaged up `setuptools` and `setuptools-scm` as Debian packages.

My build script installs these freshly built packages, so my build environment already has latest `setuptools` and `setuptools-scm` installed.

When I come to build `pytest-runner` however, it seems `setuptools` thinks it knows better, it *ignores* the system-wide-installed `setuptools-scm` package, and decides to download and install its own *into the working directory*.

`dpkg-buildpkg` then packs a spaz because the source directory has been modified.

```
root@308631b74222:/pytest-runner# python setup.py sdist
/pytest-runner/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/git.py:56: UserWarning: "/pytest-runner" is shallow and may cause errors
running sdist
running egg_info
writing requirements to pytest_runner.egg-info/requires.txt
writing pytest_runner.egg-info/PKG-INFO
writing namespace_packages to pytest_runner.egg-info/namespace_packages.txt
writing top-level names to pytest_runner.egg-info/top_level.txt
writing dependency_links to pytest_runner.egg-info/dependency_links.txt
writing entry points to pytest_runner.egg-info/entry_points.txt
writing manifest file 'pytest_runner.egg-info/SOURCES.txt'
running check
creating pytest-runner-3.0
creating pytest-runner-3.0/docs
creating pytest-runner-3.0/pytest_runner.egg-info
creating pytest-runner-3.0/tests
copying files to pytest-runner-3.0...
copying .readthedocs.yml -> pytest-runner-3.0
copying .travis.yml -> pytest-runner-3.0
copying CHANGES.rst -> pytest-runner-3.0
copying LICENSE -> pytest-runner-3.0
copying README.rst -> pytest-runner-3.0
copying appveyor.yml -> pytest-runner-3.0
copying ptr.py -> pytest-runner-3.0
copying pytest.ini -> pytest-runner-3.0
copying setup.cfg -> pytest-runner-3.0
copying setup.py -> pytest-runner-3.0
copying tox.ini -> pytest-runner-3.0
copying docs/conf.py -> pytest-runner-3.0/docs
copying docs/history.rst -> pytest-runner-3.0/docs
copying docs/index.rst -> pytest-runner-3.0/docs
copying pytest_runner.egg-info/PKG-INFO -> pytest-runner-3.0/pytest_runner.egg-info
copying pytest_runner.egg-info/SOURCES.txt -> pytest-runner-3.0/pytest_runner.egg-info
copying pytest_runner.egg-info/dependency_links.txt -> pytest-runner-3.0/pytest_runner.egg-info
copying pytest_runner.egg-info/entry_points.txt -> pytest-runner-3.0/pytest_runner.egg-info
copying pytest_runner.egg-info/namespace_packages.txt -> pytest-runner-3.0/pytest_runner.egg-info
copying pytest_runner.egg-info/requires.txt -> pytest-runner-3.0/pytest_runner.egg-info
copying pytest_runner.egg-info/top_level.txt -> pytest-runner-3.0/pytest_runner.egg-info
copying tests/test_ptr.py -> pytest-runner-3.0/tests
Writing pytest-runner-3.0/setup.cfg
creating dist
Creating tar archive
removing 'pytest-runner-3.0' (and everything under it)
root@308631b74222:/pytest-runner# py2dsc dist/pytest-runner-3.0.tar.gz
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
running the following command in directory: deb_dist/tmp_py2dsc/pytest-runner-3.0
/usr/bin/python setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/pytest-runner/deb_dist --use-premade-distfile=/pytest-runner/dist/pytest-runner-3.0.tar.gz
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
running sdist_dsc
running egg_info
writing requirements to pytest_runner.egg-info/requires.txt
writing pytest_runner.egg-info/PKG-INFO
writing namespace_packages to pytest_runner.egg-info/namespace_packages.txt
writing top-level names to pytest_runner.egg-info/top_level.txt
writing dependency_links to pytest_runner.egg-info/dependency_links.txt
writing entry points to pytest_runner.egg-info/entry_points.txt
reading manifest file 'pytest_runner.egg-info/SOURCES.txt'
writing manifest file 'pytest_runner.egg-info/SOURCES.txt'
This version of stdeb requires python-all >= 2.6.6-3, but you do not have this package installed. Could not check compatibility.
dpkg-buildpackage: source package pytest-runner
dpkg-buildpackage: source version 3.0-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Jason R. Coombs <jaraco@jaraco.com>
 dpkg-source --before-build pytest-runner-3.0
dpkg-source: info: using options from pytest-runner-3.0/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-checkbuilddeps: Unmet build dependencies: python-all (>= 2.6.6-3)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
dpkg-buildpackage: warning: this is currently a non-fatal warning with -S, but will probably become fatal in the future
 debian/rules clean
dh clean --with python2 --buildsystem=python_distutils
   dh_testdir -O--buildsystem=python_distutils
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/pytest-runner/deb_dist/pytest-runner-3.0'
python setup.py clean -a
running clean
'build/lib.linux-x86_64-2.7' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
find . -name \*.pyc -exec rm {} \;
make[1]: Leaving directory '/pytest-runner/deb_dist/pytest-runner-3.0'
   dh_clean -O--buildsystem=python_distutils
 dpkg-source -b pytest-runner-3.0
dpkg-source: info: using options from pytest-runner-3.0/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building pytest-runner using existing ./pytest-runner_3.0.orig.tar.gz
dpkg-source: warning: file pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/entry_points.txt has no final newline (either original or modified version)
dpkg-source: warning: file pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/metadata.json has no final newline (either original or modified version)
dpkg-source: info: local changes detected, the modified files are:
 pytest-runner-3.0/.eggs/README.txt
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/DESCRIPTION.rst
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/LICENSE.txt
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/PKG-INFO
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/RECORD
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/WHEEL
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/entry_points.txt
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/metadata.json
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/top_level.txt
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/EGG-INFO/zip-safe
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/__init__.py
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/__main__.py
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/discover.py
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/git.py
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/hacks.py
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/hg.py
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/integration.py
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/utils.py
 pytest-runner-3.0/.eggs/setuptools_scm-1.15.6-py2.7.egg/setuptools_scm/version.py
dpkg-source: info: you can integrate the local changes with dpkg-source --commit
dpkg-source: error: aborting due to unexpected upstream changes, see /tmp/pytest-runner_3.0-1.diff.8foihy
dpkg-buildpackage: error: dpkg-source -b pytest-runner-3.0 gave error exit status 2
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    setuptools.setup(**params)
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/stdeb/command/sdist_dsc.py", line 141, in run
    sign_dsc=self.sign_results,
  File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 1422, in build_dsc
    dpkg_buildpackage('-S','-sa',*args,cwd=fullpath_repackaged_dirname)
  File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 534, in dpkg_buildpackage
    process_command(args, cwd=cwd)
  File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 187, in process_command
    check_call(args, cwd=cwd)
  File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 46, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 2
ERROR running: /usr/bin/python setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/pytest-runner/deb_dist --use-premade-distfile=/pytest-runner/dist/pytest-runner-3.0.tar.gz
ERROR in deb_dist/tmp_py2dsc/pytest-runner-3.0
```

I've been fighting this for the past hour or so now, how do I turn this mis-feature off?

**Comment by benoit-pierre** [comment]
If pytest-runner' setup script is trying to install setuptools-scm, it's because the requirement is not satisfied. Said requirement is: `setuptools_scm>=1.15.0`, what version are you providing?

**Comment by sjlongland** [comment]
0.1~dev1+g2521712 is the package version number… this is built straight from their git repository, commit 2521712ff… which is this commit:

https://github.com/pypa/setuptools_scm/commit/2521712ff13183a6bca7147a03ddd630795f3dd4

So clearly, something isn't getting built right… Now I'd much rather that `setuptools` had a mode in which it threw an error instead of downloading packages on its own.  *Then* I'd have a clearer place where to look.

**Comment by sjlongland** [comment]
Interestingly, `setuptools_scm` it seems isn't correctly tagged:
```
root@bneprdci0:/srv/bamboo/working/163841/EXTPY-SSCM-JOB1/src# ls
appveyor.yml   deb_dist     dist     README.rst  setup.py        setuptools_scm-0.1.dev1+g2521712.tar.gz  testing
CHANGELOG.rst  default.nix  LICENSE  setup.cfg   setuptools_scm  setuptools_scm.egg-info                  tox.ini
root@bneprdci0:/srv/bamboo/working/163841/EXTPY-SSCM-JOB1/src# git describe
fatal: No annotated tags can describe '2521712ff13183a6bca7147a03ddd630795f3dd4'.
However, there were unannotated tags: try --tags.
root@bneprdci0:/srv/bamboo/working/163841/EXTPY-SSCM-JOB1/src# git describe --tags
v1.15.6-13-g2521712
root@bneprdci0:/srv/bamboo/working/163841/EXTPY-SSCM-JOB1/src# git fetch --tags
root@bneprdci0:/srv/bamboo/working/163841/EXTPY-SSCM-JOB1/src# 
```

That'll be a separate bug.  `setuptools` itself deciding to unilaterally install its own dependencies though, is still a problem here.  I can understand the feature being there, and even it being defaulted to ON… but surely there must be a way to put `setuptools` into a mode where it reports warnings or errors when dependencies are not met instead of trying to fix the problem itself.

**Comment by WildCard65** [comment]
The purpose of setup_requires is to install dependencies required for setup to continue if they aren't already available.

**Comment by sjlongland** [comment]
@WildCard65 Agreed, but:
1. why must it put the files *there*, where it'll cause problems elsewhere?
2. supposing the user *wanted* to use *specific* builds of dependencies (for QA purposes), why can't it have a "fail if dependencies not met" mode?

Hiding the problem from the user is not helpful.
