### ISSUE TITLE
pip broken pkg

### ISSUE THREAD

**Issue by Diraio** [pypa/setuptools#1252]
Hello,

for some reason pip3 doesn't work anymore. It seems to be a problem with multiple causes. After looking for a while, I would prefer to ask before I go down a rabbit hole lol.

> Traceback (most recent call last):
  File "/home/raio/.local/bin/pip3", line 7, in <module>
    from pip import main
  File "/home/raio/.local/lib/python3.5/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/raio/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/home/raio/.local/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/home/raio/.local/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/home/raio/.local/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/home/raio/.local/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/home/raio/.local/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/raio/.local/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/raio/.local/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

> 

can you assist?

**Comment by jaraco** [comment]
The issue is that one or more of your namespace packages installed in your environment was built with Setuptools prior to 31.0.1 and that pip hasn't been patched to work around the issue (pypa/pip#4216). Nothing we can do here.
