### ISSUE TITLE
pip install -U --user <somepackage> tries to update system setuptools

### ISSUE THREAD

**Issue by JensTimmerman** [pypa/setuptools#1264]
It seems to notice it should not uninstall setuptools and tries to install it again, but fails with en error.
It should not fail since nothing was removed in the first place (I'm running with a user which has no rights to add/remove system packages)
```
wget -O get-pip.py https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
python -m pip install -U --user vsc-install
Requirement already up-to-date: vsc-install in /var/lib/jenkins/.local/lib/python2.7/site-packages/vsc_install-0.10.26-py2.7.egg
Collecting setuptools (from vsc-install)
  Downloading setuptools-38.4.0-py2.py3-none-any.whl (489kB)
Installing collected packages: setuptools
  Found existing installation: setuptools 33.1.1
    Uninstalling setuptools-33.1.1:
      Successfully uninstalled setuptools-33.1.1
  Rolling back uninstall of setuptools
Exception:
Traceback (most recent call last):
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/wheel.py", line 478, in move_wheel_files
    generated.extend(maker.make(spec))
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 372, in make
    self._make_script(entry, filenames, options=options)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 276, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 250, in _write_script
    self._fileop.write_binary_file(outname, script_bytes)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/_vendor/distlib/util.py", line 405, in write_binary_file
    self.ensure_dir(os.path.dirname(path))
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/_vendor/distlib/util.py", line 437, in ensure_dir
    self.ensure_dir(d)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/_vendor/distlib/util.py", line 437, in ensure_dir
    self.ensure_dir(d)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/_vendor/distlib/util.py", line 437, in ensure_dir
    self.ensure_dir(d)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/pip/_vendor/distlib/util.py", line 440, in ensure_dir
    os.mkdir(path)
OSError: [Errno 13] Permission denied: '/usr/lib64'
```

**Comment by benoit-pierre** [comment]
This really belongs on [pip's issue tracker](https://github.com/pypa/pip/issues). Also, according to the messages, setuptools' uninstallation was successful, and it's trying to create something in `/usr/lib64` during the install phase.
