### ISSUE TITLE
Spyder kernel died restarting

### ISSUE THREAD

**Issue by akalamoyo** [pypa/setuptools#1267]
Hello guys,

I've been stuck on this issue for a while and going through previous threads has not been able to solve it.
When I open my Spyder I keep getting kernel died, restarting.
In Anaconda prompt, when I run conda update --all i get this:

C:\Users\moyo.akala>conda update --all
Traceback (most recent call last):
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py", line 3, in <module>
    import conda.cli
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 46, in <module>
    from ..base.context import context
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\base\context.py", line 16, in <module>
    from .._vendor.auxlib.path import expand
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\path.py", line 8, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2985, in <module>
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2971, in _call_aside
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2544, in activate
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
AttributeError: '_NamespacePath' object has no attribute 'sort'

When I try to pip anything I get:
C:\Users\moyo.akala>pip install keras
Traceback (most recent call last):
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\Scripts\pip-script.py", line 3, in <module>
    import pip
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2927, in <module>
    @_call_aside
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 956, in subscribe
    callback(dist)
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "C:\Users\moyo.akala\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

I can't update. I can't install. I use windows 64bit system. I've unistalled and reinstalled Anaconda same issue. I've checked every single firewall, disabled every antivirus. I have permissions as Administrator but it won't still work. Please help

**Comment by pganssle** [comment]
I don't think this is a setuptools issue. Hopefully you got it worked out.
