### ISSUE TITLE
python2.7 setuptools 39.0.0 UnicodeEncodeError on writing egg info when installing pypandoc

### ISSUE THREAD

**Issue by ThinerDAS** [pypa/setuptools#1298]
```
[root@bfc0090bcd09 /]# pip2 install --no-cache-dir -U setuptools pypandoc
Collecting setuptools
  Downloading setuptools-39.0.0-py2.py3-none-any.whl (569kB)
Collecting pypandoc
  Downloading pypandoc-1.4.tar.gz
Requirement already up-to-date: pip>=8.1.0 in /usr/lib/python2.7/site-packages (from pypandoc)
Collecting wheel>=0.25.0 (from pypandoc)
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
Installing collected packages: setuptools, wheel, pypandoc
  Found existing installation: setuptools 37.0.0
    Uninstalling setuptools-37.0.0:
      Successfully uninstalled setuptools-37.0.0
  Running setup.py install for pypandoc ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0qD6A1/pypandoc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i2O7jm-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/pypandoc
    copying pypandoc/__init__.py -> build/lib/pypandoc
    copying pypandoc/py3compat.py -> build/lib/pypandoc
    copying pypandoc/pandoc_download.py -> build/lib/pypandoc
    running install_lib
    creating /usr/lib/python2.7/site-packages/pypandoc
    copying build/lib/pypandoc/__init__.py -> /usr/lib/python2.7/site-packages/pypandoc
    copying build/lib/pypandoc/py3compat.py -> /usr/lib/python2.7/site-packages/pypandoc
    copying build/lib/pypandoc/pandoc_download.py -> /usr/lib/python2.7/site-packages/pypandoc
    byte-compiling /usr/lib/python2.7/site-packages/pypandoc/__init__.py to __init__.pyc
    byte-compiling /usr/lib/python2.7/site-packages/pypandoc/py3compat.py to py3compat.pyc
    byte-compiling /usr/lib/python2.7/site-packages/pypandoc/pandoc_download.py to pandoc_download.pyc
    running install_egg_info
    running egg_info
    writing requirements to pypandoc.egg-info/requires.txt
    writing pypandoc.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0qD6A1/pypandoc/setup.py", line 116, in <module>
        cmdclass=cmd_classes
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 575, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install_egg_info.py", line 34, in run
        self.run_command('egg_info')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/usr/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib64/python2.7/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 76, in write_pkg_file
        file.write('%s: %s\n' % (field, attr_val))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 17: ordinal not in range(128)
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0qD6A1/pypandoc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i2O7jm-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0qD6A1/pypandoc/
[root@bfc0090bcd09 /]# LC_ALL=C pip2 install --no-cache-dir -U setuptools pypandoc
Requirement already up-to-date: setuptools in /usr/lib/python2.7/site-packages
Collecting pypandoc
  Downloading pypandoc-1.4.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pypandoc.egg-info
    writing requirements to pip-egg-info/pypandoc.egg-info/requires.txt
    writing pip-egg-info/pypandoc.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-WW4lwh/pypandoc/setup.py", line 116, in <module>
        cmdclass=cmd_classes
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/usr/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib64/python2.7/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 76, in write_pkg_file
        file.write('%s: %s\n' % (field, attr_val))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 17: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WW4lwh/pypandoc/
```

Feel free to contact me if pypandoc works on your machine with python2.7 and setuptools 39.0.0, and I can provide the Dockerfile to replay the behavior reliably.

This bug makes installing new packages impossible without [hacks](https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte), which sucks. We cannot write hacks easily in Dockerfile.

Tested, when I install pypandoc without `-U` flag, it works (as the setuptools version is 37.0.0)

Possibly duplicate of #1297 but it should not occur in 39.0.0 version?

**Comment by jaraco** [comment]
Let's address #1297 first. If that doesn't fix this issue, we can re-open this one if it turns out to be different.
