### ISSUE TITLE
setuptools 15.2   zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by gto389** [pypa/setuptools#1331]
Hey all, my team seems to be having an issue with one of your files, setuptools 15.2

`Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-15.2.zip
Extracting in /tmp/tmpnr9ihygc
Traceback (most recent call last):
  File "bootstrap.py", line 105, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 170, in use_setuptools
  File "<string>", line 122, in _do_download
  File "<string>", line 62, in _build_egg
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "<string>", line 101, in archive_context
  File "<string>", line 85, in __new__
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ImportError: No module named 'apport'

Original exception was:
Traceback (most recent call last):
  File "bootstrap.py", line 105, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 170, in use_setuptools
  File "<string>", line 122, in _do_download
  File "<string>", line 62, in _build_egg
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "<string>", line 101, in archive_context
  File "<string>", line 85, in __new__
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`

I have been able to download the setuptools file from the pypi site (https://pypi.org/simple/setuptools/) and it seems to be a zip but even local builds cannot extract as they say "File is not a zip file"

Could this issue be similar to #599 ?

**Comment by forresttanaka** [comment]
We’re running into the same error though the [status](https://status.python.org/incidents/1y1f44q6srh2) seems to say the issue is resolved. Is this a matter of waiting for CDNs to propagate? It’s been more than 12 hours since this problem started for us, and I’m seeing it on two completely different ISPs.

```
Home-iMac:encoded ftanaka$ python3 bootstrap.py --buildout-version 2.9.5 --setuptools-version 18.5
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.5.zip
Extracting in /var/folders/dn/wqpxw3vs1gn1n10rs956ldqr0000gn/T/tmpb44ev0ew
Traceback (most recent call last):
  File "bootstrap.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 170, in use_setuptools
  File "<string>", line 122, in _do_download
  File "<string>", line 62, in _build_egg
  File "/Users/ftanaka/.pyenv/versions/3.4.3/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "<string>", line 101, in archive_context
  File "<string>", line 85, in __new__
  File "/Users/ftanaka/.pyenv/versions/3.4.3/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/Users/ftanaka/.pyenv/versions/3.4.3/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by jimmyzhen** [comment]
@forresttanaka,

You may find the "working" download link on this page (`https://pypi.org/project/setuptools/18.5/#files`):
`https://files.pythonhosted.org/packages/01/e6/15b9f1d1dcbde0984c499c3775be47ea0e4063bc34d2e843c4425d164436/setuptools-18.5.zip`
