### ISSUE TITLE
Setuptools 39.2.0 packaging with PIP 10 issue

### ISSUE THREAD

**Issue by arcivanov** [pypa/setuptools#1391]
All of a sudden project installs stopped working. 

```
Could not install packages due to an EnvironmentError.
Traceback (most recent call last):
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2862, in _dep_map
    return self.__dep_map
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2669, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2853, in _parsed_pkg_info
    return self._pkg_info
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2669, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_internal/commands/install.py", line 318, in run
    self._warn_about_conflicts(to_install)
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_internal/commands/install.py", line 442, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_internal/operations/check.py", line 89, in check_install_conflicts
    state = create_package_set_from_installed()
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_internal/operations/check.py", line 39, in create_package_set_from_installed
    retval[name] = PackageDetails(dist.version, dist.requires())
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2613, in requires
    dm = self._dep_map
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2864, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2873, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2855, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1404, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/home/<hidden>//lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1516, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/<hidden>//lib/python3.6/site-packages/setuptools-39.2.0.dist-info/METADATA'
```

**Comment by arcivanov** [comment]
I can confirm that this combination results in the above error:

```
$ pip list
Package    Version
---------- -------
pip        10.0.1 
setuptools 39.2.0 
wheel      0.31.1 
```

Downgrading to pip 9.0.3 installs the same package no problem.

**Comment by benoit-pierre** [comment]
What's the exact command being used? The package being installed? Operating system? How were setuptools/pip/wheel installed?

**Comment by jaraco** [comment]
Probably whatever you're trying to install is downgrading setuptools, causing the setuptools 39.2.0 metadata to go missing during the install. I can see from the traceback that the exception is in "check_install_conflicts", which is a pip 10 feature, so it's not surprising the issue goes away with a downgrade.

**Comment by arcivanov** [comment]
@benoit-pierre 
Package is proprietary, command is pip install from a private git repo, Linux, pip/setuptools/wheel installed via Pyenv/venv. I will reiterate, that downgrade to 9.0.3 makes the problem go away.

@jaraco 
Good point! I'll check it out.

**Comment by benoit-pierre** [comment]
You'll have to find a minimal way to reproduce the bug without the need for your proprietary package. And create a bug on [pip's tracker](https://github.com/pypa/pip/issues) as it's not a setuptools issue.
