### ISSUE TITLE
"make build" on OSX fails with "urlopen error unknown url type: https"

### ISSUE THREAD

**Issue by khink** [pypa/setuptools#1397]
- checkout repo 
- `make build`

This installs a Python in `pythons/2.7` but then it fails with:
```
Traceback (most recent call last):
  File "dev.py", line 50, in <module>
    exec(urlopen('https://bootstrap.pypa.io/ez_setup.py').read(), ez)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 452, in _open
    'unknown_open', req)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/kees/Projects/buildout/pythons/2.7/lib/python2.7/urllib2.py", line 1266, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: https>
```

**Comment by jaraco** [comment]
You must be thinking of a different project. Setuptools doesn't have a Makefile. Here's what I get when I run `make build` on setuptools.

```
setuptools master $ make build
make: Nothing to be done for `build'.
```

But whatever project you have, the issue is that whatever you're using to build/install Python isn't incorporating openssl, so Python doesn't have SSL support and thus can't service HTTPS URLs (which use SSL for encryption). Almost everything these days relies on SSL, so you'll need to get a Python that has SSL.

Additionally, I'd recommend to your project that they abandon use of `ez_setup` and instead rely on pip for everything (including installing setuptools).

**Comment by khink** [comment]
Oops, why did i send that here? Sorry for the noise! (https://github.com/buildout/buildout/issues/456 for reference)

**Comment by jaraco** [comment]
No problem. For posterity, Buildout may be the one exception where `ez_setup.py` might still be viable.
