### ISSUE TITLE
When I upload a new package,get an error “TypeError: a bytes-like object is required, not 'str'”

### ISSUE THREAD

**Issue by flythinker** [pypa/setuptools#1422]
detail commands list: 
```
root@hyplinux51#python3.6 setup.py sdist upload
running sdist
running egg_info
writing ftk_email.egg-info/PKG-INFO
writing dependency_links to ftk_email.egg-info/dependency_links.txt
writing top-level names to ftk_email.egg-info/top_level.txt
package init file 'ftk_email/__init__.py' not found (or not a regular file)
reading manifest file 'ftk_email.egg-info/SOURCES.txt'
writing manifest file 'ftk_email.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
creating ftk_email-0.0.2
creating ftk_email-0.0.2/ftk_email
creating ftk_email-0.0.2/ftk_email.egg-info
copying files to ftk_email-0.0.2...
copying setup.py -> ftk_email-0.0.2
copying ftk_email/ftk_email.py -> ftk_email-0.0.2/ftk_email
copying ftk_email.egg-info/PKG-INFO -> ftk_email-0.0.2/ftk_email.egg-info
copying ftk_email.egg-info/SOURCES.txt -> ftk_email-0.0.2/ftk_email.egg-info
copying ftk_email.egg-info/dependency_links.txt -> ftk_email-0.0.2/ftk_email.egg-info
copying ftk_email.egg-info/top_level.txt -> ftk_email-0.0.2/ftk_email.egg-info
Writing ftk_email-0.0.2/setup.cfg
Creating tar archive
removing 'ftk_email-0.0.2' (and everything under it)
running upload
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    packages = ['ftk_email']
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/upload.py", line 64, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/lib64/python3.6/distutils/command/upload.py", line 162, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
root@hyplinux51#python3.6 -m pop list distutils
/usr/bin/python3.6: No module named pop
root@hyplinux51#python3.6 -m pip list distutils
Package    Version
---------- -------
ftk-email  0.0.2
pip        10.0.1
setuptools 40.0.0
wheel      0.31.1
```

**Comment by NotSureThisReallyMattersInTheLongRun** [comment]
I was getting a similar error, and the following resolved my issue.
https://reinbach.com/blog/setuptools-classifiers-upload-python3-5/

**Comment by pganssle** [comment]
@flythinker @NotSureThisReallyMattersInTheLongRun Please use `twine` instead of `setup.py upload`, which is deprecated.

@benoit-pierre @jaraco I'm tempted to go with "wontfix" on this, because I think it's a convenience issue for a deprecated function, but I suppose we could try and clean up the error message so that people aren't terribly frustrated by it.

**Comment by jaraco** [comment]
Agreed it's wontfix. Also, since the issue lies in distutils, it's not readily simple to fix.

I wish I knew more about what inputs are causing this error, because `setup.py upload` should work.

But you're right, `twine` is the solution, and it's probably not worth the effort to correct:

```
python setup.py sdist && twine upload dist/*
```

I'd say we'll accept a PR for improved behavior, but we shouldn't invest our time fixing it.
