### ISSUE TITLE
Setup of 40.0 via pip on MacOS High Sierra is not successful

### ISSUE THREAD

**Issue by adam-ah** [pypa/setuptools#1433]
I'm trying to install using pip but Mac OS X, 10.13.4 is already shipped with an old version
```
pip --version
pip 10.0.1 from /Library/Python/2.7/site-packages/pip (python 2.7)
```

```
MacBook-Pro:KerasDemo user$ sudo pip install setuptools --upgrade
Password:
The directory '/Users/user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/user/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl (567kB)
    100% |████████████████████████████████| 573kB 3.0MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 18.5
    Uninstalling setuptools-18.5:
Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-2PS_oP/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
```

OK, let's try a user install:

```
MacBook-Pro:KerasDemo user$ sudo pip install setuptools --upgrade --user
The directory '/Users/user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/user/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl (567kB)
    100% |████████████████████████████████| 573kB 3.4MB/s 
Installing collected packages: setuptools
Successfully installed setuptools-40.0.0
```

But then:

```
MacBook-Pro:KerasDemo user$ which easy_install
/Users/user/Library/Python/2.7/bin/easy_install
MacBook-Pro:KerasDemo user$ easy_install
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 11, in <module>
    load_entry_point('setuptools==18.5', 'console_scripts', 'easy_install')()
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 46, in <module>
    from setuptools.archive_util import unpack_archive
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/archive_util.py", line 15, in <module>
    from pkg_resources import ensure_directory, ContextualZipFile
ImportError: cannot import name ContextualZipFile
```

Or maybe just try to ignore and install it anyway:

```
MacBook-Pro:KerasDemo user$ sudo pip install setuptools --ignore-installed
The directory '/Users/user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/user/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl (567kB)
    100% |████████████████████████████████| 573kB 3.1MB/s 
Installing collected packages: setuptools
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/usr/local/bin/easy_install'
```

The bottom line is that I can't seem to install setuptools 40.0 so it has a valid and working binary in /usr/local/bin/easy_install

Any help would be appreciated.

**Comment by pganssle** [comment]
@adam-ah Did you ever get this resolved? I suspect that this is an issue with your specific setup, because I haven't seen other HS users having trouble installing setuptools.

I don't have access to a mac laptop, but I suspect that anything involving `sudo pip install` is a bad idea. My understanding is that the system-shipped version of Python is in a bit of a sorry state and you're best off never using system python and instead using [homebrew's python](https://docs.brew.sh/Homebrew-and-Python) and/or [pyenv](https://github.com/pyenv/pyenv). I suspect that if you do that it will fix your permissions issues.

**Comment by jaraco** [comment]
I do run on a mac. I've had High Sierra and now have Mojave... but I avoid and strongly recommend you avoid using the Python provided by the system. It's almost always old often has its own peculiarities. I don't even have pip installed in the system Python:

```
$ /usr/bin/python2.7 -m pip -V
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named pip
```

I do see that I have setuptools installed, though I suspect that was installed by macOS and not by me:

```
$ /usr/bin/python2.7 -m easy_install --version
setuptools 18.5 from /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (Python 2.7)
```

I also strongly second pganssle's recommendation to use homebrew or pyenv. I personally use Homebrew, even for when I need Python 2.7. With Homebrew's `python@2` installed, and with `/usr/local/bin` ahead on the path, my default Python 2.7 is the one from homebrew:

```
~ $ python2.7 -V
Python 2.7.15
~ $ python2.7 -c "import sys; print(sys.executable)"
/usr/local/opt/python@2/bin/python2.7
```

And with homebrew properly configured not to require sudo, setuptools installs and upgrades nicely without sudo:

```
~ $ python2.7 -m pip install -U setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/96/06/c8ee69628191285ddddffb277bd5abdf769166e7a14b867c2a172f0175b1/setuptools-40.4.3-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 39.2.0
    Uninstalling setuptools-39.2.0:
      Successfully uninstalled setuptools-39.2.0
Successfully installed setuptools-40.4.3
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Also, I want to recommend that even if you have to use `sudo` for some operations, you should avoid using `sudo` with `--user` (for any application), as that creates files in `~/.local` (or similar) that are owned by `root` and often not accessible by the user.

I hope that helps. Let us know what you find.

**Comment by adam-ah** [comment]
If anyone faces this problem, _all_ my python issues went away once I installed the official version from python.org. The Mac's own has it's own permission system so it's just too hard to use.
