### ISSUE TITLE
Can't use package_dir in setup.cfg in 40.0.0

### ISSUE THREAD

**Issue by rlalik** [pypa/setuptools#1436]
Since documentation doesn't say to much about how to use package_dir i nsetup.cfg except:

    Type names used below:
    dict - list-comma where keys are separated from values by =

and

    Options
    Key | Type
    -- | --
    package_dir | dict

I tried

    package_dir = 
        = src

but it results in:

```
./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 4, in <module>
    setup()
  File "/usr/lib64/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/lib64/python3.6/site-packages/setuptools/dist.py", line 495, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/usr/lib64/python3.6/site-packages/setuptools/config.py", line 114, in parse_configuration
    meta.parse()
  File "/usr/lib64/python3.6/site-packages/setuptools/config.py", line 400, in parse
    section_parser_method(section_options)
  File "/usr/lib64/python3.6/site-packages/setuptools/config.py", line 373, in parse_section
    self[name] = value
  File "/usr/lib64/python3.6/site-packages/setuptools/config.py", line 177, in __setitem__
    value = parser(value)
  File "/usr/lib64/python3.6/site-packages/setuptools/config.py", line 466, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/lib64/python3.6/site-packages/setuptools/config.py", line 309, in _parse_attr
    if attrs_path[0] in package_dir:
IndexError: list index out of range
```

**Comment by xnuinside** [comment]
@rlalik , just checked what all work correctly

from my setup.cfg: 

[options]
include_package_data = True
package_dir =
    = src
packages =
    laziest

my files tree:

- src:
   - laziest:
        *.py files

all work correctly and packed in whl 

setuptools    version 40.2.0  

in doc exist: 
"And such projects also need something like package_dir={'':'src'} in their setup() arguments, but that’s just a normal distutils thing.)"
and it's really described in distutils - https://docs.python.org/2/distutils/setupscript.html#listing-whole-packages 

but in setuptools not provided an example of how to write it in setup.cfg, it's true, but I don't think what it's a really critical

if smbd from contributors think what it's good to have in doc - I can send PR with documentation additions
<img width="400" alt="screen shot 2018-08-24 at 11 36 07" src="https://user-images.githubusercontent.com/15959809/44574390-f8bc8100-a791-11e8-883d-eacee7566f78.png">
