### ISSUE TITLE
[Windows] UTF-8 command line args reduced to CP1252 with console script installed from egg (but wheel works fine)

### ISSUE THREAD

**Issue by zmwangx** [pypa/setuptools#1573]
I noticed this bug when porting my app to Windows (details of my environment can be found at the end).

Consider the following single-module distribution:

`setup.py`:

```py
#!/usr/bin/env python3

import setuptools


setuptools.setup(
    name='sysargv',
    version='0.1',
    py_modules=['sysargv'],
    entry_points={
        'console_scripts': [
            'sysargv=sysargv:sysargv',
            'callsysargv=sysargv:callsysargv',
        ],
    },
)
```

`sysargv.py`:

```py
import subprocess
import sys


def sysargv():
    print(sys.argv)


def callsysargv():
    args = ['sysargv', '\u4E2D\u6587']
    print('>', ' '.join(args))
    subprocess.call(args)
```

When I install this on Windows as an egg with `python setup.py install`, here's what happens:

```console
$ callsysargv
> sysargv 中文
['C:\\Python37\\Scripts\\sysargv', '??']
```

Note the Chinese characters becomes `??` when received by `sysargv`.

However, when I install this on Windows as a wheel with `python setup.py bdist_wheel` followed by `pip install .\dist\sysargv-0.1-py3-none-any.whl`, it works correctly:

```console
$ callsysargv
> sysargv 中文
['C:\\Python37\\Scripts\\sysargv', '中文']
```

It's good to have a workaround, but it does mean I currently can't install my package as editable during development, which is quite annoying.

I'm honestly not exactly sure setuptools is to blame here, but I know precious little about Windows and not much more about eggs either, so I figured I'll ask the experts before wasting my time digging into this. Thanks.

---

My environment: I'm running Python 3.7.1 from Chocolatey (the package is based on the NuGet python package, which presumably uses an official python.org installer) on latest Windows 10.

- setuptools version: 40.5.0
- pip version: 18.1

**Comment by jaraco** [comment]
The solution here will be for pip to supply the console scripts for editable installs as it does for wheel installs so that there's no variance.

**Comment by zmwangx** [comment]
Note sure I follow. This is not only an issue with editable installs — I mean, `python setup.py install` is not editable.

**Comment by benoit-pierre** [comment]
Even when using pip, there are a number of code paths that lead to calling `python setup.py install`. And the implementation for `pip install -e` will use `python setup.py develop`.

**Comment by benoit-pierre** [comment]
Additionally, PEP 517 does not support editable installs, so the situation is unlikely to change.

**Comment by pganssle** [comment]
> Additionally, PEP 517 does not support editable installs, so the situation is unlikely to change.

This seems like a major oversight...

**Comment by zmwangx** [comment]
Just tried all four:

- `python setup.py install` — doesn't work;
- `python setup.py develop` — doesn't work;
- `pip install .` — works;
- `pip install -e .` — doesn't work.

So, gladly `pip` does better at non-editable install, but editable install is still up in the air.

**Comment by benoit-pierre** [comment]
That's because `pip install .` will build a wheel (if wheel is installed, and you don't ask for some specific build options to be passed to setuptools).

**Comment by zmwangx** [comment]
Actually, `pip install .` builds a wheel first, so it's still an egg vs wheel problem.

**Comment by zmwangx** [comment]
(Happened to post the same thing at the same time...)

**Comment by epogrebnyak** [comment]
I have a similar problem - `pip install -e .` and `python setup.py develop` fail on non-latin path.

My setup.py:

```python
from setuptools import setup

setup(name='aloh',
      version='0.0.5',
      description='Order selection and production planning MILP via PuLP',
      author='E Pogrebnyak',
      py_modules = ['aloh'],
     )
```

fails as:

```
C:\Users\Евгений\Documents\GitHub\aloh3                                                                    
λ python setup.py develop                                                                                  
running develop                                                                                            
running egg_info                                                                                           
writing aloh.egg-info\PKG-INFO                                                                             
writing dependency_links to aloh.egg-info\dependency_links.txt                                             
writing top-level names to aloh.egg-info\top_level.txt                                                     
reading manifest file 'aloh.egg-info\SOURCES.txt'                                                          
writing manifest file 'aloh.egg-info\SOURCES.txt'                                                          
running build_ext                                                                                          
Creating d:\anaconda3\lib\site-packages\aloh.egg-link (link to .)                                          
Traceback (most recent call last):                                                                         
  File "setup.py", line 10, in <module>                                                                    
    py_modules = ['aloh'],                                                                                 
  File "D:\Anaconda3\lib\site-packages\setuptools\__init__.py", line 165, in setup                         
    return distutils.core.setup(**attrs)                                                                   
  File "D:\Anaconda3\lib\distutils\core.py", line 148, in setup                                            
    dist.run_commands()                                                                                    
  File "D:\Anaconda3\lib\distutils\dist.py", line 966, in run_commands                                     
    self.run_command(cmd)                                                                                  
  File "D:\Anaconda3\lib\distutils\dist.py", line 985, in run_command                                      
    cmd_obj.run()                                                                                          
  File "D:\Anaconda3\lib\site-packages\setuptools\command\develop.py", line 38, in run                     
    self.install_for_development()                                                                         
  File "D:\Anaconda3\lib\site-packages\setuptools\command\develop.py", line 152, in install_for_development
    f.write(self.egg_path + "\n" + self.setup_path)                                                        
  File "D:\Anaconda3\lib\encodings\cp1252.py", line 19, in encode                                          
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]                                      
UnicodeEncodeError: 'charmap' codec can't encode characters in position 9-15: character maps to <undefined>
```
```

**Comment by epogrebnyak** [comment]
I had to patch two file write operations - one in `command\develop.py, line 152` and one in `command\easy_install.py", line 1611,` and add:

```
            with open(self.egg_link, "w", encoding='utf-8') as f:
                f.write(self.egg_path + "\n" + self.setup_path)
```


```
            with open(self.filename, 'wt', encoding='utf-8') as f:
                f.write(data)
```

After that `python setup.py develop` passes.
