### ISSUE TITLE
Unable to use declarative config for extras with markers

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#1579]
I'm looking to port keyring to use declarative config. Keyring has [these extras defined](https://github.com/jaraco/keyring/blob/b2d27d3dfb5423af1c38240a9956d26ed044e03d/setup.py#L52-L61), which if translated naively to setup.cfg format would look like this:

```
[options.extras_require]
testing =
	# upstream
	pytest >= 3.5, !=3.7.3
	pytest-sugar >= 0.9.1
	collective.checkdocs
	pytest-flake8

	# local

docs =
	# upstream
	sphinx
	jaraco.packaging >= 3.2
	rst.linker >= 1.9

	# local

:sys_platform=="win32" =
	pywin32-ctypes!=0.1.0,!=0.1.1

:sys_platform=="linux" and python_version>="3.5" =
	secretstorage

:(sys_platform=="linux2" or sys_platform=="linux") and python_version<"3.5" =
	secretstorage<3
```

If I attempt to run setup.py with that in setup.cfg, I get this error:

```
Traceback (most recent call last):
  File "/Users/jaraco/code/main/keyring/setup.py", line 8, in <module>
    setuptools.setup(use_scm_version=True)
  File "/Users/jaraco/code/main/keyring/.tox/python/lib/python3.7/site-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/Users/jaraco/code/main/keyring/.tox/python/lib/python3.7/site-packages/setuptools/__init__.py", line 121, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "/Users/jaraco/code/main/keyring/.tox/python/lib/python3.7/site-packages/setuptools/dist.py", line 482, in parse_config_files
    _Distribution.parse_config_files(self, filenames=filenames)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 406, in parse_config_files
    parser.read(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1091, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from 'setup.cfg' [line 59]: option '' in section 'options.extras_require' already exists
```

**Comment by jaraco** [comment]
I did some looking into the parameters for the ConfigParser and learned you can disable the `:` as a delimiter, but doing that just trips up later on the equal sign:

```
>>> cp = configparser.ConfigParser(delimiters=('=',))
>>> cp.read('setup.cfg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1091, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from 'setup.cfg' [line 59]: option ':sys_platform' in section 'options.extras_require' already exists
```

According to [the docs](https://docs.python.org/3/library/configparser.html#customizing-parser-behaviour), keys cannot contain delimiters, and since both '=' and ':' are part of the keys for extras that contain markers, it's not possible to define them in setup.cfg.

**Comment by jaraco** [comment]
Good news - I had forgotten that with more recent versions of setuptools, it's possible to supply extras using the pip syntax. The [solution was to use that syntax](https://github.com/jaraco/keyring/blob/e787e3444909ddda403e782272492a22bd66cd1a/setup.cfg#L36-L38).
