### ISSUE TITLE
Make requirement parsing errors more informative

### ISSUE THREAD

**Issue by astrojuanlu** [pypa/setuptools#1581]
When exploring new features of pip and packaging I am lately getting errors like this:

```
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 10), (line:1, col:11)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2974, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'API'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.4/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/satellite-api/docs/source/conf.py", line 28, in <module>
    v = parse_version(get_distribution(project).version)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 474, in get_distribution
    dist = Requirement.parse(dist)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3020, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2967, in parse_requirements
    yield Requirement(line)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2976, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'API'"

```

The exact error now is not important (I am about to start debugging what's going on) but it would be really useful to have more information in the traceback. My only hope now is to go here:

https://github.com/pypa/setuptools/blob/b0c746640f87ad2719a7ebfbdc226d3fd43296b6/pkg_resources/_vendor/packaging/requirements.py#L89-L94

Insert a `import pdb; pdb.set_trace()`, and try to figure out what's going on. At least, having the line that is failing, and even where is it being read from, would be great.

**Comment by blackCmd** [comment]
I met this error....
How to fix it?

**Comment by Avasam** [comment]
FWIW, both `pyparsing` and `pkg_resources` are no longer used by setuptools. Requirements are now handled with https://pypi.org/project/packaging/

Could you update the trace and MRE if this is still relevant ?

**Comment by astrojuanlu** [comment]
Don't think I'll be able to provide a MRE for this one, happy to close it
