### ISSUE TITLE
setuptools and pip

### ISSUE THREAD

**Issue by happymzw** [pypa/setuptools#1598]
enviroment:
python 3.7.1
windows 7 sp1

i download the zip file for windows [(Windows x86-64 embeddable zip file)](https://www.python.org/ftp/python/3.7.1/python-3.7.1-embed-amd64.zip), unzip the file and configure the enviroment. it works.

but,when i add pip, get the error message:
`D:\xx\work\pip-18.1>python setup.py install`
`Traceback (most recent call last):`
`  File "setup.py", line 6, in <module>`
`    from setuptools import find_packages, setup`
`ModuleNotFoundError: No module named 'setuptools'`

continue add setuptools, get the error message:
`D:\xx\work\pip-18.1>python setup.py install`
`Traceback (most recent call last):`
`  File "setup.py", line 6, in <module>`
`    from setuptools import find_packages, setup`
`ModuleNotFoundError: No module named 'setuptools'`

some people say that, can use ez_setup.py, but [(ez_setup.py )](https://bootstrap.pypa.io/ez_setup.py) get the error message:
`D:\xx\work\python-3.7.1-embed-amd64>python ez_setup.py`
`ez_setup.py is deprecated and when using it setuptools will be pinned to 40.6.2`
`since it's the last version that supports setuptools self upgrade/installation,`
`check https://github.com/pypa/setuptools/issues/581 for more info; use pip to i
stall setuptools`
`Extracting in C:\Users\ADMINI~1\AppData\Local\Temp\tmpy67lsr32`
`Now working in C:\Users\ADMINI~1\AppData\Local\Temp\tmpy67lsr32\setuptools-40.6
2`
`Installing Setuptools`
`Traceback (most recent call last):`
`  File "setup.py", line 11, in <module>`
`    import setuptools`
`ModuleNotFoundError: No module named 'setuptools'`
`Something went wrong during the installation.`
`See the error message above.`

also try the get-pip.py, [(get-pip.py)](https://bootstrap.pypa.io/get-pip.py)
`D:\xx\work\python-3.7.1-embed-amd64>python get-pip.py`
`Collecting pip`
`  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631c
f71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl`
`Collecting setuptools`
`  Using cached https://files.pythonhosted.org/packages/e7/16/da8cb8046149d50940c
6110310983abb359bbb8cbc3539e6bef95c29428a/setuptools-40.6.2-py2.py3-none-any.whl`

`Collecting wheel`
`  Using cached https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5
d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl`
`Installing collected packages: pip, setuptools, wheel`
`Successfully installed pip-18.1 setuptools-40.6.2 wheel-0.32.3`

looks like success, but get the error message below:
`D:\xx\work\python-3.7.1-embed-amd64>pip --version`
`Traceback (most recent call last):`
`  File "runpy.py", line 193, in _run_module_as_main`
`  File "runpy.py", line 85, in _run_code`
`  File "D:\victor\work\python-3.7.1-embed-amd64\Scripts\pip.exe\__main__.py", li
ne 5, in <module>`
`ModuleNotFoundError: No module named 'pip'`

how can add pip on windows with python 3.7.1?

**Comment by jaraco** [comment]
First off, I'd suggest as a user seeking to install packages, you should never need setuptools - or at the very least, you should be able to rely on pip to install setuptools. Also, you should avoid `setup.py install` if possible. Your instinct to use `get-pip` is the right one.

What's strange is how it seems that even after running that, pip isn't successfully installed. Probably there is an issue with pip on embeddable Python.
