### ISSUE TITLE
Debian v9.5: 0.7-series setuptools cannot be installed with distribute

### ISSUE THREAD

**Issue by MariusTOR** [pypa/setuptools#1662]
I am attempting to install numpy on a PocketBeagle operating under Debian v9.5.  I've successfully connected the device to the internet via USB and am using pip to install numpy for the Python 2.7 installation presently on the device.  I have setuptools v40.7.1 and pip v19.0.1 installed.

When I try to install it, however, I get the following, ending with an error.

```
debian@beaglebone:~$ pip install numpy
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/04/b6/d7faa70a3e3eac39f943cc6a6a64ce378259677de516bd899dd9eb8f9b32/numpy-1.16.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/dist.py", line 6, in <module>
        from setuptools.command.install import install
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2870, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 710, in subscribe
        callback(dist)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2870, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2302, in activate
        self.insert_on(path)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.45-py2.7.egg/pkg_resources.py", line 2403, in insert_on
        "with distribute. Found one at %s" % str(self.location))
    ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /home/debian/.local/lib/python2.7/site-packages

```

And here I'm stuck.  The fixes for this elsewhere on the site that I've found involve upgrading setuptools...but, since I already have the latest, I'm at a loss as to what to do next.  Any help would be appreciated.

**Comment by jaraco** [comment]
I forget how the distribute transition worked. Are you able to simply uninstall distribute (which has been completely superseded by setuptools)?

**Comment by MariusTOR** [comment]
Just gave it a shot...ran apt-get --purge remove distribute, and got back that Debian could not locate package "distribute".  Running dpkg --list shows no package named "distribute" (or some derivative of that word) is installed (that I can see).  Is there another name that I should be looking for it under?

**Comment by MariusTOR** [comment]
I am trying to uninstall it now (using pip uninstall distribute), but it seems to freeze up (and for a good 5 minutes) after I say yes to the uninstall.  This is problematic.

**Comment by jaraco** [comment]
If your system package manager can't uninstall it and pip can't, you may need to write a script to manually remove it. The files you'll need to remove are `easy_install.py setuptools* distribute-*.egg-info pkg_resources easy-install.pth setuptools.pth` (not sure about the last one), all in the site-packages directory.

Given the age of your OS, you may be stuck on relying on distribute. You're definitely going to run into problems with more recent packages and tools that rely on later releases. I'm afraid I'm not going to be able to provide much more help here as I don't have that environment. Your best bet will be to search for the error messages you're encountering for other people who may have had that issue around 6 years ago.

**Comment by MariusTOR** [comment]
That's unfortunate.  Really, my aim here is to just obtain a copy of numpy
that works on Debian v9.5 and an ARM processor.  I've yet to find one
around the internet, however -- is there a workaround that I wouldn't have
to worry about distribute giving me grief?

**Comment by jaraco** [comment]
Here's how I'd approach it: manually uninstall distribute. Upgrade pip. Install setuptools with pip. Install numpy.

I did not mean to let this issue become stale. I hope by now you've figured out a solution.
