### ISSUE TITLE
platform-specific dependencies failure

### ISSUE THREAD

**Issue by fersarr** [pypa/setuptools#1677]
When using platform-specific dependencies as documented in [setuptools docs](https://media.readthedocs.org/pdf/setuptools/latest/setuptools.pdf), I am running into an issue:

In Python 3.7
```
>>> import pkg_resources as pr
>>> pr.get_distribution('doesntexist;python_version<"3.0"')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/is/fsaraviarajal/workspace/conda_envs_test/test3_offlinecopyof2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 479, in get_distribution
    dist = get_provider(dist)
  File "/users/is/fsaraviarajal/workspace/conda_envs_test/test3_offlinecopyof2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 355, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range
```

However, when the dependency is for the version of python we are running on, the outcome is as expected
```
>>> pr.get_distribution('doesntexist;python_version>"3.0"')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/is/fsaraviarajal/workspace/conda_envs_test/test3_offlinecopyof2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 479, in get_distribution
    dist = get_provider(dist)
  File "/users/is/fsaraviarajal/workspace/conda_envs_test/test3_offlinecopyof2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 355, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/users/is/fsaraviarajal/workspace/conda_envs_test/test3_offlinecopyof2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/users/is/fsaraviarajal/workspace/conda_envs_test/test3_offlinecopyof2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'doesntexist; python_version > "3.0"' distribution was not found and is required by the application
```

I have reproduced this on versions of **28.8.0** and **40.7.3** of **setuptools**

The exception `IndexError: list index out of range` comes from this line:
https://github.com/pypa/setuptools/blob/c1243e96f05d3b13392a792144c97d9471581550/pkg_resources/__init__.py#L357

**Comment by pganssle** [comment]
@fersarr What is the result you expect? Another `DistributionNotFound` error? A different error type entirely? No error and returning `None` or something?

From what I can tell in [the documentation](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#getting-or-creating-distributions), the idea of environment markers is not mentioned at all. For packages that *do* exist, it seems like they return the distribution regardless of whether or not the environment marker is met.

Not sure what the right behavior is. I'm leaning in favor of raising some sort of error since that's already what happens anyway. If people want to take the environment markers into account, we could theoretically make the error raised a subclass of `DistributionNotFound` like `DistributionEnvironmentMismatch` or something.

**Comment by fersarr** [comment]
Hi @pganssle. In the docs link you provided, these are in fact mentioned. Look under "Requirement specifier" or just search for "python_version" in your link. For example, it says:

The “markers” in a requirement are used to specify when a requirement should be installed – the requirement will be installed if the marker evaluates as true in the current environment. For example, specifying argparse;python_version<"3.0" will not install in an Python 3 environment, but will in a Python 2 environment

I think the behaviour in this case should not be DistributionNotFound because it was not meant to be found anyway. And it should not stay is IndexError.

**Comment by pganssle** [comment]
Yes I understand what markers are in the context of install requirements, but not how they should modify `get_distribution `. They work fine in `install_requires ` and other similar contexts where they clearly have a meaning, but `get_distribution ` retrieves things that are already installed.

Can you clarify your use case?

**Comment by jaraco** [comment]
Obsolete.
