### ISSUE TITLE
easy_isntall3 failed to install egg (bdist_egg) package

### ISSUE THREAD

**Issue by leeexyz** [pypa/setuptools#1719]
Hi there,

I am using `easy_isntall3` on `Ubuntu 16.04.6 LTS` to install a bdist egg package. 

When I ran `easy_install3 -d /target/path package-to-be-install.egg`, I got the following error message. I googled it but cannot find any useful things. Can you please check it? Is this a bug?

```
Installed package-to-be-install.egg
Traceback (most recent call last):
  File "/usr/bin/easy_install3", line 9, in <module>
    load_entry_point('setuptools==20.7.0', 'console_scripts', 'easy_install')()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 2293, in main
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 736, in process_distribution
    requirement = Requirement(str(distreq))
TypeError: __init__() missing 2 required positional arguments: 'specs' and 'extras'
error : install package-to-be-install.egg failed
```

easy_install3 version
```
$ easy_install3 --version
setuptools 20.7.0 from /usr/lib/python3/dist-packages (Python 3.5)
```

**Comment by pganssle** [comment]
@leeexyz That's quite an old version of `setuptools`, and `easy_install` is not recommended or supported for direct use anymore. Can you try:

1. updating your `setuptools` to the latest version
2. Using the `pip` instead of `easy_install`

And see if this solves your issue?

**Comment by leeexyz** [comment]
Hi @pganssle thanks for you reply. That is the default version on `Ubuntu 16.04.06 LTS` and maybe we cannot ask users to upgrade it for now. Anyway, I will try the two methods to see if it works. :)

**Comment by pganssle** [comment]
@leeexyz If you can't update the version of `setuptools` there's not much we can do about it, since you can't use any of the code we release without updating your `setuptools` version. In any case, hopefully `pip` will work for you.

**Comment by leeexyz** [comment]
Hi @pganssle I will try it. Thanks!
