### ISSUE TITLE
pip upgrade error

### ISSUE THREAD

**Issue by DawnEve** [pypa/setuptools#1760]
wangjl@ngs2:~/software$ **pip install --upgrade pip**
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2562, in version
    return self._version
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2669, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 318, in run
    self._warn_about_conflicts(to_install)
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 442, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 89, in check_install_conflicts
    state = create_package_set_from_installed()
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 39, in create_package_set_from_installed
    retval[name] = PackageDetails(dist.version, dist.requires())
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2567, in version
    raise ValueError(tmpl % self.PKG_INFO, self)
ValueError: ("Missing 'Version:' header and/or METADATA file", Unknown [unknown version] (/home/wangjl/.local/lib/python3.7/site-packages))
You are using pip version 19.0, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

wangjl@ngs2:~/software$ **pip install --user --upgrade pip**
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2562, in version
    return self._version
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2669, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 318, in run
    self._warn_about_conflicts(to_install)
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 442, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 89, in check_install_conflicts
    state = create_package_set_from_installed()
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 39, in create_package_set_from_installed
    retval[name] = PackageDetails(dist.version, dist.requires())
  File "/software/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2567, in version
    raise ValueError(tmpl % self.PKG_INFO, self)
ValueError: ("Missing 'Version:' header and/or METADATA file", Unknown [unknown version] (/home/wangjl/.local/lib/python3.7/site-packages))
You are using pip version 19.0, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by benoit-pierre** [comment]
It's going to be hard to help without more info: at the very least the version of setuptools installed, and possibly adding some traces to figure out which package the invalid metadata belongs to.

**Comment by DawnEve** [comment]
much before I install any package, it remind me to update pip, then the pip malfunctions.
all the invalid metadata belongs to pip update.

pip install --upgrade pip

 pip install --user --upgrade pip
