### ISSUE TITLE
setuptools outputs "ERROR: command '/usr/bin/ccache' failed with exit status 1" during build_ext with no further details - would more detail output be possible?

### ISSUE THREAD

**Issue by JonasT** [pypa/setuptools#1783]
I am trying to build a self-written package in a cross compile environment with the Android NDK. I am building other packages in the same environment successfully, so in theory the compiler and such should work.

However, this specific package the `cpp` extension runs through perfectly, but the `.pyx`/Cython extensions abort during build_ext with a very weird error:

```
  running build_ext
  building 'sfxscan._scan' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/sfxscan
  /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /ndk/sysroot/usr/include/arm-linux-androideabi -I/ndk/sysroot/usr/include/arm-linux-androideabi -isysroot /ndk/sysroot -I/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/include/python3.7 -DNDEBUG -g -fwrapv -O2 -Wall -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /ndk/sysroot/usr/include/arm-linux-androideabi -I/ndk/sysroot/usr/include/arm-linux-androideabi -isysroot /ndk/sysroot -I/home/userhome/.local/share/python-for-android/build/python-installs/unnamed_dist_1/include/python3.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -I/home/userhome/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/userhome/.local/share/python-for-android/build/venv/include/python3.6m -c sfxscan/_scan.cpp -o build/temp.linux-x86_64-3.6/sfxscan/_scan.o  -Ivendor-include -Lvendor-lib  -lz
  arm-linux-androideabi-gcc: error: : No such file or directory
  arm-linux-androideabi-gcc: error: : No such file or directory
  Android detected, will not build taglib!
  RUNNING BUILD_EXT...
  ERROR: command '/usr/bin/ccache' failed with exit status 1
  DONE RUNNING BUILD_EXT.
  error: command '/usr/bin/ccache' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for sfxscan
```

As you can see here, "RUNNING_BUILD_EXT" ... "DONE RUNNING BUILD_EXT." I've put such that they frame the build_ext command run:  https://github.com/JonasT/sfxscan/blob/753c5bedae81401829ea25ab76b3e60584c45fec/setup.py#L43 (with the `ERROR` being a printed out exception).

This is most likely my own fault. However, the thing is that `build_ext` doesn't even tell me here what it tried to build before it just crashes with that error. So why I'm filing this ticket is basically, wouldn't it be better to provide actual useful output here before spilling out that error? Like for example, what extension did it even try to build? It would be neat if that could be improved

The bogus `  arm-linux-androideabi-gcc: error: : No such file or directory` might also be related in some way, I haven't seen them for any other package and that seems pretty weird. But I really can't tell why they're output or what it even tried to compile

**Comment by JonasT** [comment]
Ok so I managed to collect the full error backtrace with more debug output hackery:

```
[DEBUG]:   	  Traceback (most recent call last):
[DEBUG]:   	    File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
[DEBUG]:   	      extra_postargs)
[DEBUG]:   	    File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
[DEBUG]:   	      spawn(cmd, dry_run=self.dry_run)
[DEBUG]:   	    File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
[DEBUG]:   	      _spawn_posix(cmd, search_path, dry_run=dry_run)
[DEBUG]:   	    File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
[DEBUG]:   	      % (cmd, exit_status))
[DEBUG]:   	  distutils.errors.DistutilsExecError: command '/usr/bin/ccache' failed with exit status 1
[DEBUG]:   	
[DEBUG]:   	  During handling of the above exception, another exception occurred:
[DEBUG]:   	
[DEBUG]:   	  Traceback (most recent call last):
[DEBUG]:   	    File "setup.py", line 47, in run
[DEBUG]:   	      super().run()
[DEBUG]:   	    File "/tmp/pip-build-env-o2ie9anp/overlay/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
[DEBUG]:   	      _build_ext.run(self)
[DEBUG]:   	    File "/tmp/pip-build-env-o2ie9anp/overlay/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
[DEBUG]:   	      _build_ext.build_ext.run(self)
[DEBUG]:   	    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
[DEBUG]:   	      self.build_extensions()
[DEBUG]:   	    File "/tmp/pip-build-env-o2ie9anp/overlay/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
[DEBUG]:   	      self.build_extension(ext)
[DEBUG]:   	    File "/tmp/pip-build-env-o2ie9anp/overlay/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
[DEBUG]:   	      _build_ext.build_extension(self, ext)
[DEBUG]:   	    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
[DEBUG]:   	      depends=ext.depends)
[DEBUG]:   	    File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
[DEBUG]:   	      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
[DEBUG]:   	    File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
[DEBUG]:   	      raise CompileError(msg)
[DEBUG]:   	  distutils.errors.CompileError: command '/usr/bin/ccache' failed with exit status 1
[DEBUG]: 
```
It would be nice if right before doing `raise CompileError` it would tell me what extension it tried to compile, or even better also print the full compiler output. (I'm not sure if the `No such file or directory` is related at all, since it seems to be possibly before the build_ext call, unless stdout/stderr buffering is doing super weird  things)

**Comment by JonasT** [comment]
Ok this appears to be just an stdout flushing abnormality, I've dug deeper and it seems the ccache-line is actually the it fails, my added bug print lines just occur afterwards since I don't flush. oopsies
