### ISSUE TITLE
No such file or directory error in wheel.py:157 _convert_metadata

### ISSUE THREAD

**Issue by tristanaj** [pypa/setuptools#1796]
Hi - 

I keep getting the following exception raised on my system when running python setup.py test or python setup.py build for my python project:

`Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    setup(**config)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/vagrant/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/vagrant/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/vagrant/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 855, in install_eggs
    return [self.install_wheel(dist_filename, tmpdir)]
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1073, in install_wheel
    os.path.dirname(destination)
  File "/usr/lib/python2.7/distutils/cmd.py", line 349, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "/usr/lib/python2.7/distutils/util.py", line 309, in execute
    func(*args)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/wheel.py", line 101, in install_as_egg
    self._install_as_egg(destination_eggdir, zf)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/wheel.py", line 109, in _install_as_egg
    self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
  File "/home/vagrant/.local/lib/python2.7/site-packages/setuptools/wheel.py", line 157, in _convert_metadata
    os.path.join(egg_info, 'PKG-INFO'),
OSError: [Errno 2] No such file or directory
`

Any ideas what I'm doing wrong?

Thanks in advance!

**Comment by benoit-pierre** [comment]
Can you provide the contents of your `setup.py`/`setup.cfg`?

**Comment by tristanaj** [comment]
Sure. The anonymised setup.py is:

`from setuptools import setup, find_packages


def read_version():
    with open('version') as ver:
        return ver.read().strip()


config = {
    'description': 'package',
    'author': 'Me',
    'author_email': 'email@email.com',
    'version': read_version(),
    'packages': find_packages(),
    'package_data': {
        'manager.resources': ['*.yaml'],
    },
    'scripts': [],
    'name': 'company.packagename',
    'namespace_packages': ['company'],
    'test_suite': 'tests',
    'entry_points': {
        'console_scripts': [
            'launcher = manager_launcher:main',
            'managerschemas = manager.validation:export',
            'managertypes = manager.types:export',
        ]
    },
    'setup_requires': ['pytest-runner'],
    'tests_require': [
        'flake8',
        'pylint',
        'pytest',
        'pytest-cov',
        'pytest-mock',
    ],
}

if __name__ == '__main__':
    setup(**config)`

and setup.cfg:

`[aliases]
test = pytest

[flake8]
max-line-length = 120
exclude = venv,.eggs

[tool:pytest]
addopts = -vvvv --cov=manager --cov-branch --cov-fail-under=100 --cov-report=term --cov-report=html --junitxml=junit.xml
testpaths = tests
`

**Comment by benoit-pierre** [comment]
Use ``` to delimit multi-lines code blocks.

**Comment by benoit-pierre** [comment]
I can't reproduce your issue with Python 2.7.16 and the above `setup.py`/`setup.cfg`. I do get an error if I try to run the test command: `python2 setup.py test`, but that's because setuptools ends up installing an incompatible version of Pytest (`pytest>=5.0` dropped support for Python 2).

Anyway, from the look of your traceback, the issue occurs when installing setup's requirements (`pytest-runner` which itself has no dependencies). What's the contents of your `.eggs` directory? Are you using a custom package index?

**Comment by tristanaj** [comment]
Thanks for the fast reply. I'm currently using Python 2.7.12. My .eggs directory looks like this:

```
drwxr-xr-x 1 vagrant vagrant 4096 Jul  2 11:50 pytest_runner-5.1-py2.7.egg
-rw-r--r-- 1 vagrant vagrant  211 Jul  1 16:02 README.txt
```

and the sub-directory looks like:

```
/.eggs/pytest_runner-5.1-py2.7.egg/EGG-INFO$ ls -l
total 28
-rw-r--r-- 1 vagrant vagrant   59 Jul  2 11:50 entry_points.txt
-rw-r--r-- 1 vagrant vagrant 1050 Jul  2 11:50 LICENSE
-rw-r--r-- 1 vagrant vagrant 5509 Jul  2 11:50 METADATA
-rw-r--r-- 1 vagrant vagrant  568 Jul  2 11:50 RECORD
-rw-r--r-- 1 vagrant vagrant    4 Jul  2 11:50 top_level.txt
-rw-r--r-- 1 vagrant vagrant  110 Jul  2 11:50 WHEEL
```

**Comment by benoit-pierre** [comment]
What kind of filesystem are you using?

**Comment by tristanaj** [comment]
The folder this is in, is being shared from my host file system which is ext4, to my guest vagrant VM, using Virtualbox's default folder syncing.

**Comment by benoit-pierre** [comment]
Dos it work with this patched version: [setuptools-41.0.1.post20190702.zip](https://github.com/pypa/setuptools/files/3350292/setuptools-41.0.1.post20190702.zip)?

**Comment by tristanaj** [comment]
Thanks so much for the patched version. Now I'm getting:
```
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    setup(**config)
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 144, in setup
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 139, in _install_setup_requires
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 718, in fetch_build_eggs
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 782, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1065, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1077, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 785, in fetch_build_egg
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 679, in easy_install
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 705, in install_item
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 855, in install_eggs
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1073, in install_wheel
    
  File "/usr/lib/python2.7/distutils/cmd.py", line 349, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "/usr/lib/python2.7/distutils/util.py", line 309, in execute
    func(*args)
  File "build/bdist.linux-x86_64/egg/setuptools/wheel.py", line 101, in install_as_egg
  File "build/bdist.linux-x86_64/egg/setuptools/wheel.py", line 109, in _install_as_egg
  File "build/bdist.linux-x86_64/egg/setuptools/wheel.py", line 157, in _convert_metadata
OSError: [Errno 22] Invalid argument
```

**Comment by tristanaj** [comment]
I've just tried running it outside the synced directory, and it goes through fine. So as you implied it looks like it's some file system weirdness with the Vagrant synced folders...

**Comment by benoit-pierre** [comment]
Yes.

**Comment by tristanaj** [comment]
It's a horrible hack, but adding a time.sleep(1) on wheel.py:157 before the os.rename is working as a work-around...

**Comment by benoit-pierre** [comment]
Yeah, my patch was trying to fsync the parent directory, to ensure the previous rename is committed before trying the second one.

**Comment by cjerdonek** [comment]
I think it would be helpful if the error message included the path it was trying to write when the error occurs. That would help users and make it easier to troubleshoot generally.
