### ISSUE TITLE
PEP-518 build env is not preserved for backend subprocess

### ISSUE THREAD

**Issue by abitrolly** [pypa/setuptools#1857]
PEP-517 `backend` should be a Python script that runs in build environment with installed `requires` from `[build-system]`. The packages listed in `requires` are importable from `setup.py` executed by default [`setuptools.build_meta:__legacy__`](https://github.com/pypa/setuptools/blob/master/setuptools/build_meta.py) backend, but not available in Python scripts executed in `setup.py`  subprocesses.

https://github.com/grumpyhome/grumpy/pull/140 demonstrates the issue. Given the file below.
```
[build-system]
requires = ["setuptools", "wheel", "grumpy-tools>0.2.2"]
```
The output of `sys.path` when the line https://github.com/grumpyhome/grumpy/blob/ed590012cefa85da8720daaac7916f88e9065e52/grumpy-runtime-src/setup.py#L75
```
    subprocess.check_call(["""echo "print 'Make Runtime Success'" | make run --debug=bjm -r"""], shell=True)
```
is the following
```
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib/python2.7/site-packages/pip/_vendor/pep517
  /tmp/pip-build-env-OE7ua4/site
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib/python27.zip
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/plat-linux2
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/lib-tk
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/lib-old
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/lib-dynload
  /usr/lib64/python2.7
  /usr/lib/python2.7
  /tmp/pip-build-env-OE7ua4/overlay/lib/python2.7/site-packages
  /tmp/pip-build-env-OE7ua4/overlay/lib64/python2.7/site-packages
  /tmp/pip-build-env-OE7ua4/normal/lib/python2.7/site-packages
  /tmp/pip-build-env-OE7ua4/normal/lib64/python2.7/site-packages
```

And when inside this subprocess `make` executes [`build/bin/pydeps`](https://github.com/grumpyhome/grumpy/blob/ed590012cefa85da8720daaac7916f88e9065e52/grumpy-runtime-src/tools/pydeps), the line `from grumpy_tools import cli` fails with `ImportError: o module named grumpy_tools`.

Tracing `sys.path` from `pydeps` shows that build env path `/tmp/pip-build-env-OE7ua4` is gone and instead there is a different `pip` tmp present `/tmp/pip-req-build-nK1nBr`.
```
  /tmp/pip-req-build-nK1nBr/build/bin
  /tmp/pip-req-build-nK1nBr/build/lib/python2.7/site-packages
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib/python27.zip
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/plat-linux2
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/lib-tk
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/lib-old
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/lib-dynload
  /usr/lib64/python2.7
  /usr/lib/python2.7
  /home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib/python2.7/site-packages
```

The problems seems to stem from `setuptools` mocking the build env inprocess instead of creating proper virtual env that is propagated to subprocesses.

https://github.com/pypa/setuptools/blob/cb64d3a84fab15aacbdf31a0a5632690ca9f49b2/setuptools/build_meta.py#L225-L244

**Comment by abitrolly** [comment]
A workaround by passing `sys.path` through `PYTHONPATH`.
```
    syspath = os.pathsep.join(sys.path)
    os.environ['PYTHONPATH'] = syspath

    subprocess.check_call(["""echo "print 'Make Runtime Success'" | make run --debug=bjm -r"""], shell=True, env=os.environ)
```
It fails.
```
  Reading makefiles...                                                             
  Traceback (most recent call last):                                               
    File "/home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/site.py", line 791, in <module>                                                      
      main()                                                                       
    File "/home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/site.py", line 781, in main                                                          
      execsitecustomize()                                                          
    File "/home/anatoli/.local/share/virtualenvs/grumpy-PkJvE47S/lib64/python2.7/site.py", line 553, in execsitecustomize                                             
      import sitecustomize                                                         
    File "/tmp/pip-build-env-FWZ6LX/site/sitecustomize.py", line 22, in <module>   
      assert not path in sys.path                              
```

Any ideas how to make that build possible?

**Comment by benoit-pierre** [comment]
It looks like the issue is with the Makefile unconditionally overriding `PYTHONPATH`, so try with this additional patch (on top of adding `pyproject.toml`):
```diff
 Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git i/Makefile w/Makefile
index 9c9424e..97a196a 100644
--- i/Makefile
+++ w/Makefile
@@ -50,7 +50,7 @@ PY_DIR := build/lib/python2.7/site-packages
 PY_INSTALL_DIR := $(shell $(PYTHON) -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
 
 export GOPATH := $(ROOT_DIR)/build
-export PYTHONPATH := $(ROOT_DIR)/$(PY_DIR)
+export PYTHONPATH := $(ROOT_DIR)/$(PY_DIR)$(if $(PYTHONPATH),:$(PYTHONPATH),)
 export PATH := $(ROOT_DIR)/build/bin:$(PATH)
 
 GOPATH_PY_ROOT := $(GOPATH)/src/__python__
```

**Comment by abitrolly** [comment]
@benoit-pierre the `PYTHONPATH` reassignment in the `Makefile` was the problem. Thanks!
