### ISSUE TITLE
package metadata is no longer picklable

### ISSUE THREAD

**Issue by rotu** [pypa/setuptools#1888]
Since switching to OrderedDict, package metadata can no longer be pickled.

This can cause problems if you try to use setuptools with multiprocessing.

```
Traceback (most recent call last):
  File "/Users/dan/Documents/colcon_ws/src/colcon-python-setup-py/colcon_python_setup_py/package_identification/python_setup_py.py", line 257, in get_setup_information
    'stop_after': 'config'
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 261, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<distutils.dist.DistributionMetadata object at 0x10c1fcd50>'. Reason: 'PicklingError("Can't pickle <class 'setuptools._vendor.ordered_set.OrderedSet'>: it's not the same object as setuptools._vendor.ordered_set.OrderedSet")'
```

_Originally posted by @rotu in https://github.com/pypa/setuptools/pull/1690#issuecomment-545992670_

**Comment by rotu** [comment]
Minimal example:

```
import setuptools
import multiprocessing

def f():
	import setuptools
	return setuptools.Distribution().metadata.provides_extras

with multiprocessing.Pool(1) as p:
	p.apply(f)
```

**Comment by rotu** [comment]
I think this is due to vendor module trickery here: https://github.com/pypa/setuptools/blob/297f2adceda3af402fc08311e42505c8cdc9c54b/setuptools/extern/__init__.py
I'm on Ubuntu 18.04

```
import setuptools
from setuptools.extern.ordered_set import OrderedSet as os_extern
from setuptools._vendor.ordered_set import OrderedSet as os_vendor

e = setuptools.Distribution().metadata.provides_extras
print(os_extern is os_vendor)  # False
print(type(e).__module__)  # setuptools._vendor.ordered_set
print(type(e) is os_extern)  # True
print(type(e) is os_vendor)  # _False
```
