### ISSUE TITLE
Better handling of Unicode filenames on Python 2

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#193]
Originally reported by: **philip_thiem (Bitbucket: [philip_thiem](http://bitbucket.org/philip_thiem), GitHub: Unknown)**

---

_Edit_: Following b0a2fcc ([Pull Request 43](/pypa/setuptools/pull-request/43)), some tests in Python 2 began to fail. This ticket starts with the failure, then goes into discussion about a better approach.

```
#!python

ERROR: test_sdist_with_utf8_encoded_filename (setuptools.tests.test_sdist.TestSdistTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\development\setuptools\setuptools\tests\test_sdist.py", line 340, in test_sdist_with_utf8_encoded_filename
    cmd.run()
  File "C:\development\setuptools\setuptools\command\sdist.py", line 92, in run
    self.run_command('egg_info')
  File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "c:\python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\development\setuptools\setuptools\command\egg_info.py", line 163, in run
    self.find_sources()
  File "C:\development\setuptools\setuptools\command\egg_info.py", line 187, in find_sources
    mm.run()
  File "C:\development\setuptools\setuptools\command\egg_info.py", line 253, in run
    self.write_manifest()
  File "C:\development\setuptools\setuptools\command\egg_info.py", line 276, in write_manifest
    "writing manifest file '%s'" % self.manifest)
  File "c:\python27\lib\distutils\cmd.py", line 349, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "c:\python27\lib\distutils\util.py", line 324, in execute
    func(*args)
  File "C:\development\setuptools\setuptools\command\egg_info.py", line 309, in write_file
    contents = contents.encode("utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 79: ordinal not in range(128)
```

This started occurring for me recently on python 2.x, when encoding a str type in python 2.x first an decoding is performed using the default encoding (as opposed to the preferred coding) before encoding to utf-8.  If skipping the encode as was fixed in b0a2fcc was causing a bug, then we need to make sure that content is decoded to unicode before passing it to the function.  

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/193

**Comment by abravalheri** [comment]
Since Python 2 is no longer supported, I think it makes sense to close this issue for now, right?

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
