### ISSUE TITLE
cmdclass problem 

### ISSUE THREAD

**Issue by somewheve** [pypa/setuptools#1945]
code 
```
from setuptools.command.install import install
class Autofix(install):
    """
    """

    description = 'fix install '
    user_options = install.user_options + [
        ('fix=', None, 'whether to install fix'),
        ("uri=", None, "trusted host to install package")
    ]


    def initialize_options(self):
        self.fix = "false"
        self.uri = None

    def finalize_options(self):
        assert type(self.uri) == str or self.uri is None
        assert self.fix in ['false', "true"]

    def fix_install(self):
        command_base = [sys.executable, "-m"]
        command_un = copy.deepcopy(command_base) + ['pip', "uninstall", "pytdx"]
        command_in = copy.deepcopy(command_base) + ['pip', "install", "pytdx"]
        if self.fix == "true":
            if self.uri:
                command_in += ["-i", self.uri, "--trusted-hos", self.get_domian(self.uri)]
        else:
            return
        self.announce(
            'Running uninstall: %s' % str(command_un),
            level=distutils.log.INFO)
        subprocess.check_call(command_un)
        self.announce(
            'Running reinstall pytdx: %s' % str(command_in),
            level=distutils.log.INFO)
        subprocess.check_call(command_in)
        self.announce("fix successful, hope you can enjoy it", level=distutils.log.INFO)

    @staticmethod
    def get_domian(uri) -> str:
        """
    返回解析的的域名信息
    """
        parse = urlparse(uri)
        return parse.netloc

    def run(self):
        """
        Run
        command.
        """
        install.run(self)
        atexit.register(self.fix_install)

```

I try to add `Autofix` in setup.py like this
```
setup(
cmdclass={
   "install": Autofix
}
)
```
and run 
```
python setup.py install
```
but an error occurs, the is the output, 
```
running install
Traceback (most recent call last):
  File "setup.py", line 131, in <module>
    'console_scripts': ['ctpbee = ctpbee.cmdline:execute']
  File "/home/somewheve/PycharmProjects/ctpbee/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 72, in run
    install.run(self)
  File "/home/somewheve/PycharmProjects/ctpbee/venv/lib/python3.7/site-packages/setuptools/command/install.py", line 60, in run
    if self.old_and_unmanageable or self.single_version_externally_managed:
  File "/usr/lib/python3.7/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: old_and_unmanageable
```
I try search it on google, but no useful information .

Hope for your reply,  ^_^

**Comment by somewheve** [comment]
I got fixed it
