### ISSUE TITLE
`pkg_resources.evaluate_marker` ignores the `extra` argument

### ISSUE THREAD

**Issue by ender-wieczorek** [pypa/setuptools#2007]
**Problem:**

Trying to evaluate markers like `extra == "test" and python_version == "2.7"` gives an error:
```
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1378, in evaluate_marker
 return marker.evaluate()
 File "/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 301, in evaluate
 return _evaluate_markers(self._markers, current_environment)
 File "/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 226, in _evaluate_markers
 lhs_value = _get_env(environment, lhs.value)
 File "/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 208, in _get_env
 "{0!r} does not exist in evaluation environment.".format(name)
pkg_resources._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```

An example of such marker is in the `testpath` distribution that `jupyter` depends on.

**Fix:**

```
diff --git a/pkg_resources/__init__.py b/pkg_resources/__init__.py
index 75563f95..db089550 100644
--- a/pkg_resources/__init__.py
+++ b/pkg_resources/__init__.py
@@ -1376,7 +1376,7 @@ def evaluate_marker(text, extra=None):
     """
     try:
         marker = packaging.markers.Marker(text)
-        return marker.evaluate()
+        return marker.evaluate({'extra': extra})
     except packaging.markers.InvalidMarker as e:
         raise SyntaxError(e)
```

**Comment by sksDonni** [comment]
@ender-wieczorek I am encountering the same problem while working on another project. I tried the fix that was suggested to no avail. The log is something like this-

T```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/workspace/oppia/oppia/scripts/start.py", line 32, in <module>
    from . import install_third_party_libs
  File "scripts/install_third_party_libs.py", line 54, in <module>
    from . import install_backend_python_libs  # isort:skip  pylint: disable=wrong-import-position, wrong-import-order
  File "scripts/install_backend_python_libs.py", line 30, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1367
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
```
If someone could please suggest me a way out it would be great
