### ISSUE TITLE
test_setup_requires failing on Python 3.4

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#201]
Originally reported by: **jaraco (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

In d597181958a3, I disabled a test for Python 3.3 and earlier. Today, thanks to Travis' new Python 3.4 support, I added Python 3.4 to the Python versions tested, but now the test is failing on Python 3.4 also:

```
ERROR: test_setup_requires (setuptools.tests.test_easy_install.TestUserInstallTest)
Regression test for Distribute issue #318
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/jaraco/setuptools/setuptools/tests/test_easy_install.py", line 246, in test_setup_requires
  run_setup(test_setup_py, ['install'])
File "/home/travis/build/jaraco/setuptools/setuptools/sandbox.py", line 50, in run_setup
  lambda: execfile(
File "/home/travis/build/jaraco/setuptools/setuptools/sandbox.py", line 100, in run
  return func()
File "/home/travis/build/jaraco/setuptools/setuptools/sandbox.py", line 52, in <lambda>
  {'__file__':setup_script, '__name__':'__main__'}
File "/home/travis/build/jaraco/setuptools/setuptools/compat.py", line 78, in execfile
  exec(compile(source, fn, 'exec'), globs, locs)
File "setup.py", line 2, in <module>
  """Distutils setup file, used to install or test 'setuptools'"""
File "/opt/python/3.4.0/lib/python3.4/distutils/core.py", line 149, in setup
  dist.run_commands()
File "/opt/python/3.4.0/lib/python3.4/distutils/dist.py", line 955, in run_commands
  self.run_command(cmd)
File "/opt/python/3.4.0/lib/python3.4/distutils/dist.py", line 974, in run_command
  cmd_obj.run()
File "/home/travis/build/jaraco/setuptools/setuptools/command/install.py", line 61, in run
  if not self._called_from_setup(inspect.currentframe()):
File "/home/travis/build/jaraco/setuptools/setuptools/command/install.py", line 85, in _called_from_setup
  res = inspect.getouterframes(run_frame)[2]
File "/opt/python/3.4.0/lib/python3.4/inspect.py", line 1321, in getouterframes
  framelist.append((frame,) + getframeinfo(frame, context))
File "/opt/python/3.4.0/lib/python3.4/inspect.py", line 1296, in getframeinfo
  lines, lnum = findsource(frame)
File "/opt/python/3.4.0/lib/python3.4/inspect.py", line 709, in findsource
  if pat.match(lines[lnum]): break
IndexError: list index out of range
```

Curiously, this test doesn't fail on my Windows box against Python 3.4.0.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/201

**Comment by jaraco** [comment]
The workaround is ad7c41a6e717a7d91a8dc08a2530e1187139b799.
