### ISSUE TITLE
Cannot `bootstrap.py`

### ISSUE THREAD

**Issue by KOLANICH** [pypa/setuptools#2030]
```
git clone https://github.com/pypa/setuptools repoPath
cd repoPath
python3 ./bootstrap.py 
adding minimal entry_points
Regenerating egg_info
Traceback (most recent call last):
  File "/repoPath/pkg_resources/__init__.py", line 2684, in version
    return self._version
  File "/repoPath/pkg_resources/__init__.py", line 2818, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    dist = setuptools.setup(**setup_params)
  File "/repoPath/setuptools/__init__.py", line 143, in setup
    _install_setup_requires(attrs)
  File "/repoPath/setuptools/__init__.py", line 132, in _install_setup_requires
    (k, v) for k, v in attrs.items()
  File "/repoPath/setuptools/dist.py", line 425, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/repoPath/setuptools/dist.py", line 711, in finalize_options
    ep.load()(self)
  File "/repoPath/pkg_resources/__init__.py", line 2445, in load
    self.require(*args, **kwargs)
  File "/repoPath/pkg_resources/__init__.py", line 2468, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/repoPath/pkg_resources/__init__.py", line 770, in resolve
    if dist is None or (dist not in req and replace_conflicting):
  File "/repoPath/pkg_resources/__init__.py", line 3136, in __contains__
    item = item.version
  File "/repoPath/pkg_resources/__init__.py", line 2692, in version
    raise ValueError(msg, self)
ValueError: ("Missing 'Version:' header and/or PKG-INFO file at path: /repoPath/setuptools.egg-info/PKG-INFO", setuptools [unknown version] (/repoPath))
Traceback (most recent call last):
  File "./bootstrap.py", line 59, in <module>
    __name__ == '__main__' and ensure_egg_info()
  File "./bootstrap.py", line 40, in ensure_egg_info
    run_egg_info()
  File "./bootstrap.py", line 56, in run_egg_info
    subprocess.check_call(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', 'egg_info']' returned non-zero exit status 1.
```

The OS is Ubuntu eoan.

**Comment by KOLANICH** [comment]
The issue was introduced (as determined by git bisect) in 4c22a6ca57753d3b5604a90b61a0c6c5efe53a1d

**Comment by KOLANICH** [comment]
The problem exists because of a conflict between hooks. It is proposed to modify the API. I'll send a PR.

**Comment by KOLANICH** [comment]
The problem is not because of conflict, but has unknown origin.

**Comment by jaraco** [comment]
In an attempt to replicate this issue, I created this Dockerfile:

```
FROM ubuntu:eoan
RUN apt update
RUN apt install -y python3-distutils git
RUN git clone https://github.com/pypa/setuptools
WORKDIR /setuptools
RUN python3 bootstrap.py
```

When I build an image using that Dockerfile (`docker build .`), it succeeds without error.

It seems to me there may be a race condition where some package is installed that implements a `finalize_distribution_options` hook but also attempts to load the setuptools version, which may not be valid before bootstrapping is complete. Can you do more investigation to determine what other factors are implicated?
