### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by SriZbi84** [pypa/setuptools#2053]
**OS**: Windows 10
**Python**: Python 3.8.2
**PIP**: pip 20.0.2

I am encountering an error installing Python Twitch IRC:

`pip install python-twitch-irc`

Full error message:

```
Collecting python-twitch-irc
  Using cached python_twitch_irc-1.1.0-py3-none-any.whl (6.2 kB)
Collecting pendulum
  Using cached pendulum-2.1.0.tar.gz (80 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pydle
  Using cached pydle-0.9.3-py3-none-any.whl (43 kB)
Collecting python-dateutil<3.0,>=2.6
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytzdata>=2018.3
  Using cached pytzdata-2019.3-py2.py3-none-any.whl (489 kB)
Requirement already satisfied: six>=1.5 in c:\users\nigel\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from python-dateutil<3.0,>=2.6->pendulum->python-twitch-irc) (1.14.0)
Building wheels for collected packages: pendulum
  Building wheel for pendulum (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\nigel\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Users\nigel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\nigel\AppData\Local\Temp\tmph3lnsr6j'
       cwd: C:\Users\nigel\AppData\Local\Temp\pip-install-vj7m5mv2\pendulum
  Complete output (24 lines):
  Traceback (most recent call last):
    File "setup.py", line 2, in <module>
      from setuptools import setup
  ModuleNotFoundError: No module named 'setuptools'
  Traceback (most recent call last):
    File "C:\Users\nigel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
      main()
    File "C:\Users\nigel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\nigel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py", line 181, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\nigel\AppData\Local\Temp\pip-build-env-6ft1gs0c\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 57, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "C:\Users\nigel\AppData\Local\Temp\pip-build-env-6ft1gs0c\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 56, in make_in
      wb.build()
    File "C:\Users\nigel\AppData\Local\Temp\pip-build-env-6ft1gs0c\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 82, in build
      self._build(zip_file)
    File "C:\Users\nigel\AppData\Local\Temp\pip-build-env-6ft1gs0c\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 102, in _build
      self._run_build_command(setup)
    File "C:\Users\nigel\AppData\Local\Temp\pip-build-env-6ft1gs0c\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 130, in _run_build_command
      subprocess.check_call(
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\nigel\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\python.exe', 'setup.py', 'build', '-b', 'build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pendulum
Failed to build pendulum
ERROR: Could not build wheels for pendulum which use PEP 517 and cannot be installed directly
```

Projects are up-to-date:

Command:

`python -m pip install --upgrade pip setuptools wheel`

Output:

```
Requirement already up-to-date: pip in c:\users\nigel\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (20.0.2)
Requirement already up-to-date: setuptools in c:\users\nigel\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (46.1.3)
Requirement already up-to-date: wheel in c:\users\nigel\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (0.34.2)
```

**Comment by Ambika-Gowda** [comment]
Hi,
I was able to solve this by running below command

**python3 -m pip3 install --upgrade pip3 setuptools wheel**
pip3 install imagecodecs
then finally,

pip3 install albumentations

**Comment by abravalheri** [comment]
Hi @SriZbi84, thank you very much for reporting this issue.

It seems that `pendulum` is a package that uses `poetry` instead of `setuptools`, so I don't understand exactly what is happening there...

Have you tried to use a more updated version of that package? Or maybe using the pre-build wheel?

**Comment by abravalheri** [comment]
Hi @SriZbi84, I will close this issue for the time being since it seems unrelated to setuptools, but please let us know if you have any other evidence to a specific setuptools behaviour that causes the error.
