### ISSUE TITLE
Ubuntu 20.04 virtualenv python2 pip setuptools will stop working

### ISSUE THREAD

**Issue by dwhea** [pypa/setuptools#2068]
OS: Ubuntu 20.04

Steps:

```
$ sudo apt-get update && sudo apt-get upgrade
$ sudo apt install python3-virtualenv
$ sudo apt install python2
$ virtualenv -p python2 tmp
$ tmp/bin/pip
/home/$USER/Documents/tmp/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Traceback (most recent call last):
  File "tmp/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/home/$USER/Documents/tmp/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/$USER/Documents/tmp/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/$USER/Documents/tmp/lib/python2.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/$USER/Documents/tmp/lib/python2.7/site-packages/pip/_internal/cli/cmdoptions.py", line 25, in <module>
    from pip._internal.locations import USER_CACHE_DIR, get_src_prefix
  File "/home/$USER/Documents/tmp/lib/python2.7/site-packages/pip/_internal/locations.py", line 20, in <module>
    from pip._internal.utils.compat import WINDOWS
  File "/home/$USER/Documents/tmp/lib/python2.7/site-packages/pip/_internal/utils/compat.py", line 29, in <module>
    import ipaddr as ipaddress  # type: ignore
ImportError: No module named ipaddr
```

What steps should I be taking to avoid the setup tools warning?

What do I need to do to "Pensure you are installing Setuptools using pip 9.x or later or pin to `setuptools<45` in your environment." when using virtualenv?

**Comment by dwhea** [comment]
The warning and "ImportError: No module named ipaddr" does not happen for python3.

$ virtualenv -p python3 tmp3
$ tmp3/bin/pip

works fine.

**Comment by jaraco** [comment]
It sounds like a bug with virtualenv.

Also, looks like it's been fixed upstream:

```
draft $ cat Dockerfile
from ubuntu:focal
run apt update && apt upgrade -y
run apt install -y python3-virtualenv python2
run virtualenv -p python2 env
draft $ docker run -it @($(docker build -q .).strip())
root@ca9325198056:/# env/bin/pip --version
pip 20.0.2 from /env/lib/python2.7/site-packages/pip (python 2.7)
```
