### ISSUE TITLE
Incompatible install in Ubuntu 20.04 Beta

### ISSUE THREAD

**Issue by leon-matthews** [pypa/setuptools#2072]
I've been contracted to upgrade some legacy systems to Python 3. I know Python 2 is EOL, but I do need to be able to run the old system under a virtualenv while I'm working on it.

These are the steps I expected to work, and the error they caused:

```
$ sudo apt install python-virtualenv
$ cd ~/Temp
$ virtualenv -p python2 test2
$ cd test2
$ . bin/activate
$ which pip
/home/leon/Temp/test2/bin/pip
$ pip
/home/leon/Temp/test2/lib/python2.7/site-packages/pkg_resources/py2_warn.py:22: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please comment in
https://github.com/pypa/setuptools/issues/1458
about the steps that led to this unsupported combination.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Traceback (most recent call last):
  File "/home/leon/Temp/test2/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/home/leon/Temp/test2/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/leon/Temp/test2/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/leon/Temp/test2/lib/python2.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/leon/Temp/test2/lib/python2.7/site-packages/pip/_internal/cli/cmdoptions.py", line 25, in <module>
    from pip._internal.locations import USER_CACHE_DIR, get_src_prefix
  File "/home/leon/Temp/test2/lib/python2.7/site-packages/pip/_internal/locations.py", line 20, in <module>
    from pip._internal.utils.compat import WINDOWS
  File "/home/leon/Temp/test2/lib/python2.7/site-packages/pip/_internal/utils/compat.py", line 29, in <module>
    import ipaddr as ipaddress # type: ignore
ImportError: No module named ipaddr
```

**Comment by jaraco** [comment]
Dupe with #2068
