### ISSUE TITLE
TypeError: unsupported operand type(s) for ^: 'str' and 'int                >.<

### ISSUE THREAD

**Issue by cnseu** [pypa/setuptools#2140]
Hi,I meet a ploblem.

```
Traceback (most recent call last):
  File "/usr/local/bin/xortool", line 4, in <module>
    __import__('pkg_resources').run_script('xortool==0.99', 'xortool')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/xortool-0.99-py2.7.egg/EGG-INFO/scripts/xortool", line 401, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/xortool-0.99-py2.7.egg/EGG-INFO/scripts/xortool", line 101, in main
    
  File "/usr/local/lib/python2.7/dist-packages/xortool-0.99-py2.7.egg/EGG-INFO/scripts/xortool", line 277, in guess_probable_keys_for_chars
    
  File "/usr/local/lib/python2.7/dist-packages/xortool-0.99-py2.7.egg/EGG-INFO/scripts/xortool", line 299, in guess_keys
    
TypeError: unsupported operand type(s) for ^: 'str' and 'int'
```

how to deal this problem ?
Please...

**Comment by McSinyx** [comment]
Hi, looking at the traceback, I believe the problem is rather with `xortool` than `setuptools`.

**Comment by cnseu** [comment]
> Hi, looking at the traceback, I believe the problem is rather with `xortool` than `setuptools`.

thankyou so much. 
I try to reinstall xortool. or use python3/python2 run xortool. But both of it are not work.
Do you mean its xortool core code problem?

**Comment by McSinyx** [comment]
I do not know for sure.  It's best trying to contact them for better support.

**Comment by cnseu** [comment]
> I do not know for sure. It's best trying to contact them for better support.

thanks for your advice. I will try to contact them for better sup.

**Comment by Egorello** [comment]
> > I do not know for sure. It's best trying to contact them for better support.
> 
> thanks for your advice. I will try to contact them for better sup.

Hi! Did you get an answer? I have the same problem.
