### ISSUE TITLE
Retry downloads to avoid error: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#217]
Originally reported by: **lrowe (Bitbucket: [lrowe](http://bitbucket.org/lrowe), GitHub: [lrowe](http://github.com/lrowe))**

---

I'm seeing frequent Travis CI build failure of my current project due to transient network errors. Perhaps downloads could be retried to potentially avoid them.

```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 1942, in main
    getattr(buildout, command)(args)
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 622, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/buildout.py", line 1366, in _call
    return f()
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/zc.recipe.egg-2.0.1-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/zc.recipe.egg-2.0.1-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/easy_install.py", line 812, in install
    return installer.install(specs, working_set)
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/easy_install.py", line 626, in install
    for dist in self._get_dist(requirement, ws):
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/easy_install.py", line 498, in _get_dist
    dist = self._fetch(avail, tmp, self._download_cache)
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/zc.buildout-2.2.1-py2.7.egg/zc/buildout/easy_install.py", line 455, in _fetch
    new_location = self._index.download(dist.location, tmp)
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/setuptools-3.6-py2.7.egg/setuptools/package_index.py", line 518, in download
    found = self._download_url(scheme.group(1), spec, tmpdir)
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/setuptools-3.6-py2.7.egg/setuptools/package_index.py", line 766, in _download_url
    return self._attempt_download(url, filename)
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/setuptools-3.6-py2.7.egg/setuptools/package_index.py", line 772, in _attempt_download
    headers = self._download_to(url, filename)
  File "/home/travis/build/ENCODE-DCC/encoded/eggs/setuptools-3.6-py2.7.egg/setuptools/package_index.py", line 682, in _download_to
    block = fp.read(bs)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 561, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer
```

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/217

**Comment by pganssle** [comment]
I think these transient errors are not an issue anymore. If it comes up again we'll make a new issue.
