### ISSUE TITLE
setuptools>=42 encounters TypeError when installing a package with an extension that was built with setuptools<42.

### ISSUE THREAD

**Issue by kwvanderlinde** [pypa/setuptools#2312]
# Description of the problem

There is a breaking change in setuptools 42 that prevents it (and any newer version) from consuming certain packages built with older version of setuptools. If the package contains a Cython extension and is built using setuptools 41.6.0 or older, then setuptools 42 or newer will trigger a `TypeError` when installing the package. It looks like an internal object is not being fully initialized for some reason.

# Steps to reproduce

I've attached archives of a minimal test library and minimal application that shows the problem:
[application.tar.gz](https://github.com/pypa/setuptools/files/5043272/application.tar.gz)
[library.tar.gz](https://github.com/pypa/setuptools/files/5043273/library.tar.gz)

First build the library:
```bash
mkdir library
tar -C library -xzf library.tar.gz
pushd library

python3 -m venv .venv --prompt "$(basename $(pwd))"
. .venv/bin/activate
  python setup.py sdist
deactivate
popd
```
Copy/upload `library/dist/test-library-0.0.0.tar.gz` to a repo that can be accessed later when we set up the application.

Now try to set up the virtual environment for the application:
```bash
mkdir application
tar -C application -xzf application.tar.gz
pushd application

python3 -m venv .venv --prompt "$(basename $(pwd))"
. .venv/bin/activate
  pip install 'wheel==0.34.2' 'setuptools==42.0.0'  # Can be any newer version of setuptools as well. E.g., 49.2.1
  pip install --no-cache-dir -e .                   # <-- problem is here
deactivate
popd
```

When running the last `pip install` step, I get this error:
```
Building wheels for collected packages: test-library
  Building wheel for test-library (setup.py): started
  Building wheel for test-library (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /tmp/setuptools-bug-mcve/application/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fh10g_zv/test-library/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fh10g_zv/test-library/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1g5vplsd
       cwd: /tmp/pip-install-fh10g_zv/test-library/
  Complete output (44 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/somepkg
  copying somepkg/__init__.py -> build/lib.linux-x86_64-3.6/somepkg
  running egg_info
  writing test_library.egg-info/PKG-INFO
  writing dependency_links to test_library.egg-info/dependency_links.txt
  writing top-level names to test_library.egg-info/top_level.txt
  reading manifest file 'test_library.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'test_library.egg-info/SOURCES.txt'
  copying somepkg/hello.pyx -> build/lib.linux-x86_64-3.6/somepkg
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-fh10g_zv/test-library/setup.py", line 17, in <module>
      Extension('somepkg.hello', sources=[os.path.join('somepkg', 'hello.pyx')])
    File "/tmp/setuptools-bug-mcve/application/.venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/setuptools-bug-mcve/application/.venv/lib64/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/setuptools-bug-mcve/application/.venv/lib64/python3.6/site-packages/setuptools/command/build_py.py", line 53, in run
      self.build_package_data()
    File "/tmp/setuptools-bug-mcve/application/.venv/lib64/python3.6/site-packages/setuptools/command/build_py.py", line 126, in build_package_data
      srcfile in self.distribution.convert_2to3_doctests):
  TypeError: argument of type 'NoneType' is not iterable
  ----------------------------------------
  ERROR: Failed building wheel for test-library
  Running setup.py clean for test-library
Failed to build test-library
DEPRECATION: Could not build wheels for test-library which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: test-library, test-application
    Running setup.py install for test-library: started
    Running setup.py install for test-library: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /tmp/setuptools-bug-mcve/application/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fh10g_zv/test-library/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fh10g_zv/test-library/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0r3n4uiw/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/setuptools-bug-mcve/application/.venv/include/site/python3.6/test-library
         cwd: /tmp/pip-install-fh10g_zv/test-library/
    Complete output (46 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/somepkg
    copying somepkg/__init__.py -> build/lib.linux-x86_64-3.6/somepkg
    running egg_info
    writing test_library.egg-info/PKG-INFO
    writing dependency_links to test_library.egg-info/dependency_links.txt
    writing top-level names to test_library.egg-info/top_level.txt
    reading manifest file 'test_library.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'test_library.egg-info/SOURCES.txt'
    copying somepkg/hello.pyx -> build/lib.linux-x86_64-3.6/somepkg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fh10g_zv/test-library/setup.py", line 17, in <module>
        Extension('somepkg.hello', sources=[os.path.join('somepkg', 'hello.pyx')])
      File "/tmp/setuptools-bug-mcve/application/.venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/setuptools-bug-mcve/application/.venv/lib64/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/setuptools-bug-mcve/application/.venv/lib64/python3.6/site-packages/setuptools/command/build_py.py", line 53, in run
        self.build_package_data()
      File "/tmp/setuptools-bug-mcve/application/.venv/lib64/python3.6/site-packages/setuptools/command/build_py.py", line 126, in build_package_data
        srcfile in self.distribution.convert_2to3_doctests):
    TypeError: argument of type 'NoneType' is not iterable
    ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/setuptools-bug-mcve/application/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fh10g_zv/test-library/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fh10g_zv/test-library/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0r3n4uiw/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/setuptools-bug-mcve/application/.venv/include/site/python3.6/test-library Check the logs for full command output.
```
This is as reported by pip==20.2.1, but the same error (albeit less verbose) occurs with versions as old as pip==9.0.1.

In case it is pertinent, this is running with Python 3.6 on CentOS 7.

**Comment by jaraco** [comment]
I've been able to replicate the issue without the application. I use [httpie](https://httpie.org/) and [pip-run](https://pypi.org/project/pip-run).

```
draft $ mkdir library; http --follow https://github.com/pypa/setuptools/files/5043273/library.tar.gz | tar xz -C library
draft $ pushd library; pip-run -q 'setuptools<42' -- setup.py sdist; popd
~/draft/library ~/draft
running sdist
running egg_info
creating test_library.egg-info
writing test_library.egg-info/PKG-INFO
writing dependency_links to test_library.egg-info/dependency_links.txt
writing top-level names to test_library.egg-info/top_level.txt
writing manifest file 'test_library.egg-info/SOURCES.txt'
reading manifest file 'test_library.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'test_library.egg-info/SOURCES.txt'
running check
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating test-library-0.0.0
creating test-library-0.0.0/somepkg
creating test-library-0.0.0/test_library.egg-info
copying files to test-library-0.0.0...
copying MANIFEST.in -> test-library-0.0.0
copying setup.py -> test-library-0.0.0
copying somepkg/__init__.py -> test-library-0.0.0/somepkg
copying somepkg/hello.pyx -> test-library-0.0.0/somepkg
copying test_library.egg-info/PKG-INFO -> test-library-0.0.0/test_library.egg-info
copying test_library.egg-info/SOURCES.txt -> test-library-0.0.0/test_library.egg-info
copying test_library.egg-info/dependency_links.txt -> test-library-0.0.0/test_library.egg-info
copying test_library.egg-info/top_level.txt -> test-library-0.0.0/test_library.egg-info
Writing test-library-0.0.0/setup.cfg
creating dist
Creating tar archive
removing 'test-library-0.0.0' (and everything under it)
~/draft
```

```
draft $ pip-run library/dist/test-library-0.0.0.tar.gz
Processing ./library/dist/test-library-0.0.0.tar.gz
Using legacy 'setup.py install' for test-library, since package 'wheel' is not installed.
Installing collected packages: test-library
    Running setup.py install for test-library ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-3gcqzbxy/setup.py'"'"'; __file__='"'"'/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-3gcqzbxy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-record-1b_uvtto/install-record.txt --single-version-externally-managed --home /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-target-jy1h390n --compile --install-headers /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-target-jy1h390n/include/python/test-library
         cwd: /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-3gcqzbxy/
    Complete output (48 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/somepkg
    copying somepkg/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/somepkg
    running egg_info
    writing test_library.egg-info/PKG-INFO
    writing dependency_links to test_library.egg-info/dependency_links.txt
    writing top-level names to test_library.egg-info/top_level.txt
    reading manifest file 'test_library.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'test_library.egg-info/SOURCES.txt'
    copying somepkg/hello.pyx -> build/lib.macosx-10.9-x86_64-3.8/somepkg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-3gcqzbxy/setup.py", line 4, in <module>
        setup(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/build_py.py", line 58, in run
        self.build_package_data()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/build_py.py", line 132, in build_package_data
        srcfile in self.distribution.convert_2to3_doctests):
    TypeError: argument of type 'NoneType' is not iterable
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-3gcqzbxy/setup.py'"'"'; __file__='"'"'/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-3gcqzbxy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-record-1b_uvtto/install-record.txt --single-version-externally-managed --home /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-target-jy1h390n --compile --install-headers /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-target-jy1h390n/include/python/test-library Check the logs for full command output.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/pip-run", line 8, in <module>
    sys.exit(run())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip_run/__init__.py", line 18, in run
    with deps.load(*deps.not_installed(pip_args)) as home:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip_run/deps.py", line 48, in load
    _installable(args) and subprocess.check_call(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8', '-m', 'pip', 'install', '-t', '/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-ve74c6zl', 'library/dist/test-library-0.0.0.tar.gz')' returned non-zero exit status 1.
```

It seems there's something in the sdist that newer versions of setuptools can't support.

The [implicated line](https://github.com/pypa/setuptools/blob/9d7b246c0f40fabb25741a023849bf14919e408d/setuptools/command/build_py.py#L132) leads me to suspect 6b210c65938527a4bbcea34942fe43971be3c014 as the implicated change.

**Comment by jaraco** [comment]
When I break into the code where the error occurs, I see that the entry points for `setuptools.finalize_distribution_options` is empty.

```
TypeError: argument of type 'NoneType' is not iterable
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-ptn60iw0/setuptools/command/build_py.py(132)build_package_data()
-> srcfile in self.distribution.convert_2to3_doctests):
(Pdb) self.distribution
<setuptools.dist.Distribution object at 0x7fa8ed500a00>
(Pdb) self.distribution.finalize_options()
(Pdb) self.distribution.convert_2to3_doctests
(Pdb) pkg_resources
*** NameError: name 'pkg_resources' is not defined
(Pdb) import pkg_resources
(Pdb) eps = list(map(lambda e: e.load(), pkg_resources.iter_entry_points('setuptools.finalize_distribution_options')))
(Pdb) eps
[]
```

That's not good, but that's the proximate symptom, leading to `distribution.convert_2to3_doctests` being `None` instead of a list.

**Comment by jaraco** [comment]
I've been able to replicate the issue even more simply without building any sdists:

```
draft $ mkdir library; http --follow https://github.com/pypa/setuptools/files/5043273/library.tar.gz | tar xz -C library; pushd library
~/draft/library ~/draft
library $ pip-run -q setuptools==49.3 -- setup.py build
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
running build
running build_py
creating build
creating build/lib.macosx-10.9-x86_64-3.8
creating build/lib.macosx-10.9-x86_64-3.8/somepkg
copying somepkg/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/somepkg
running egg_info
creating test_library.egg-info
writing test_library.egg-info/PKG-INFO
writing dependency_links to test_library.egg-info/dependency_links.txt
writing top-level names to test_library.egg-info/top_level.txt
writing manifest file 'test_library.egg-info/SOURCES.txt'
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-h1xl7d0b/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-h1xl7d0b/setuptools/command/build_py.py", line 58, in run
    self.build_package_data()
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-h1xl7d0b/setuptools/command/build_py.py", line 132, in build_package_data
    srcfile in self.distribution.convert_2to3_doctests):
TypeError: argument of type 'NoneType' is not iterable
reading manifest file 'test_library.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'test_library.egg-info/SOURCES.txt'
copying somepkg/hello.pyx -> build/lib.macosx-10.9-x86_64-3.8/somepkg
```

**Comment by jaraco** [comment]
I found the issue - it's the presence of `setup_requires=['setuptools']`. Removing that allows the project to build properly:

```
draft $ mkdir library; http --follow https://github.com/pypa/setuptools/files/5043273/library.tar.gz | tar xz -C library; pushd library
~/draft/library ~/draft
library $ sed -ie "/setuptools ==/d" setup.py
library $ pip-run -q setuptools==49.3 -- setup.py build
WARNING: The wheel package is not available.
running build
running build_py
creating build
creating build/lib.macosx-10.9-x86_64-3.8
creating build/lib.macosx-10.9-x86_64-3.8/somepkg
copying somepkg/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/somepkg
running egg_info
creating test_library.egg-info
writing test_library.egg-info/PKG-INFO
writing dependency_links to test_library.egg-info/dependency_links.txt
writing top-level names to test_library.egg-info/top_level.txt
writing manifest file 'test_library.egg-info/SOURCES.txt'
reading manifest file 'test_library.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'test_library.egg-info/SOURCES.txt'
copying somepkg/hello.pyx -> build/lib.macosx-10.9-x86_64-3.8/somepkg
running build_ext
cythoning somepkg/hello.pyx to somepkg/hello.c
/Users/jaraco/draft/library/.eggs/Cython-0.29.21-py3.8-macosx-10.9-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/jaraco/draft/library/somepkg/hello.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'somepkg.hello' extension
creating build/temp.macosx-10.9-x86_64-3.8
creating build/temp.macosx-10.9-x86_64-3.8/somepkg
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c somepkg/hello.c -o build/temp.macosx-10.9-x86_64-3.8/somepkg/hello.o
gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.8/somepkg/hello.o -o build/lib.macosx-10.9-x86_64-3.8/somepkg/hello.cpython-38-darwin.so
```

Here's what I think's happening - the presence of `setup_requires` with a pinned setuptools version means that setuptools will attempt to download and install that specific version of setuptools if it's not already present. Moreover, it will attempt to inject that version into setuptools into the working set at run time, leading to undefined behaviors (such as metadata like entry points being missing).

Is the easy fix here to simply remove the `setuptools` declaration there?

**Comment by kwvanderlinde** [comment]
@jaraco I've gone and removed `setuptools` from `setup_requires` and am not seeing any further issues on our end. It turns out I don't need a specific setuptools version when installing the package, just when building it, so there is no reason for us to declare this dependency.
