### ISSUE TITLE
_distutils_hack uses importlib.util.abc.Loader instead of importlib.abc.Loader

### ISSUE THREAD

**Issue by ammaraskar** [pypa/setuptools#2362]
The following error is [being thrown](https://mail.python.org/archives/list/python-dev@python.org/message/TJE5XWLKRC3EQUXKSHCJNA25H3WGVP5B/) on the latest Python built from source:

```
Traceback (most recent call last):
  File "/root/cpython/Doc/./venv/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/root/cpython/Doc/venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/root/cpython/Doc/venv/lib/python3.10/site-packages/sphinx/application.py", line 28, in <module>
    from sphinx.config import Config
  File "/root/cpython/Doc/venv/lib/python3.10/site-packages/sphinx/config.py", line 22, in <module>
    from sphinx.util import logging
  File "/root/cpython/Doc/venv/lib/python3.10/site-packages/sphinx/util/__init__.py", line 40, in <module>
    from sphinx.util import smartypants  # noqa
  File "/root/cpython/Doc/venv/lib/python3.10/site-packages/sphinx/util/smartypants.py", line 33, in <module>
    from sphinx.util.docutils import __version_info__ as docutils_version
  File "/root/cpython/Doc/venv/lib/python3.10/site-packages/sphinx/util/docutils.py", line 17, in <module>
    from distutils.version import LooseVersion
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/root/cpython/Doc/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 74, in find_spec
    return method()
  File "/root/cpython/Doc/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 79, in spec_for_distutils
    class DistutilsLoader(importlib.util.abc.Loader):
AttributeError: module 'importlib.util' has no attribute 'abc'
```

The curlprit commit is https://github.com/python/cpython/commit/9e09849d20987c131b28bcdd252e53440d4cd1b3

It seems to me like the fact that `importlib.abc` was exported through `importlib.util.abc` was an implementation detail and this code should be using `importlib.abc.Loader` directly:

https://github.com/pypa/setuptools/blob/04e3df22df840c6bb244e9b27bc56750c44b7c85/_distutils_hack/__init__.py#L79

**Comment by ammaraskar** [comment]
Pinging @pganssle / @jaraco as the last people to touch this code.

**Comment by encukou** [comment]
See https://github.com/pypa/setuptools/pull/2361

**Comment by ammaraskar** [comment]
Thanks for the pointer! Sorry for the duplicate.
