### ISSUE TITLE
setuptools>=48 broken on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [pypa/setuptools#2364]
The switch to the included distutils that happened in 48.0.0 broke the build on NetBSD, at least in the way setuptools is built from pkgsrc:
````
(cd /scratch/devel/py-setuptools/work/setuptools-48.0.0/ && /usr/bin/env <some environment vars elided>  /usr/pkg/bin/python3.7 setup.py  "install"  -c -O1  --root=/scratch/devel/py-setuptools/work/.destdir)
running install
Traceback (most recent call last):
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/_distutils/sysconfig.py", line 460, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__netbsd9_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    dist = setuptools.setup(**setup_params)
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/__init__.py", line 164, in setup
    return distutils.core.setup(**attrs)
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/_distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/_distutils/dist.py", line 985, in run_command
    cmd_obj.ensure_finalized()
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/_distutils/command/install.py", line 298, in finalize_options
    (prefix, exec_prefix) = get_config_vars('prefix', 'exec_prefix')
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/_distutils/sysconfig.py", line 504, in get_config_vars
    func()
  File "/scratch/devel/py-setuptools/work/setuptools-48.0.0/setuptools/_distutils/sysconfig.py", line 464, in _init_posix
    '_sysconfigdata', globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata'
*** Error code 1
````

setuptools 47.3.2 works when built the same way.

**Comment by jaraco** [comment]
@0-wiz-0 I don't have a NetBSD environment. Can you inspect the CPython distutils code (ideally 3.9, or 3.8) and determine what's different about the stdlib distutils that it doesn't encounter the error you're getting with the Setuptools-hosted copy? Can you confirm the error is the same with Setuptools 50.0.1?

**Comment by 0-wiz-0** [comment]
Thanks for the idea of comparing to the CPython copy of distutils. There were no obvious differences, but pkgsrc has two patches for CPython's distutils:

https://github.com/NetBSD/pkgsrc/blob/trunk/lang/python38/patches/patch-Lib_distutils_sysconfig.py
https://github.com/NetBSD/pkgsrc/blob/trunk/lang/python38/patches/patch-Lib_distutils_unixccompiler.py

50.0.1 is broken in the same way as above, but when I apply these two patches to it, it builds fine.
(I'm not sure what we should do about these patches in general, so all this FYI for now.)

**Comment by jaraco** [comment]
Thanks for confirming. I'm going to transfer this issue to the distutils project (which Setuptools 48 incorporates).

My recommendation is that we reach out to the maintainers of those patches and ask them to devise a suitable replacement, something that achieves the differential behavior, but only when appropriate (for NetBSD or some other factor in NetBSD). How does that sound?
