### ISSUE TITLE
Setuptools 50.0.0 breaks if we add `import pip`

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [pypa/setuptools#2365]
Very simply, the following works:

```python
from setuptools import setup

setup(
    name="my_package",
    version="1.0.0"
)
```
Packaged as follows: `python setup.py sdist`

Now we just add `import pip`:

```python
from setuptools import setup

import pip

setup(
    name="my_package",
    version="1.0.0"
)
```
Packaged as follows: `python setup.py sdist`

And the whole commands crashes:
```bash
python setup_test.py sdist

/path/to/my_project/venv/lib/python3.6/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "setup_test.py", line 7, in <module>
    version="1.0.0"
  File "/path/to/my_project/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/path/to/my_project/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "/path/to/my_project/venv/lib/python3.6/site-packages/_virtualenv.py", line 21, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
  File "/path/to/my_project/venv/lib/python3.6/site-packages/setuptools/dist.py", line 665, in parse_config_files
    self._parse_config_files(filenames=filenames)
  File "/path/to/my_project/venv/lib/python3.6/site-packages/setuptools/dist.py", line 572, in _parse_config_files
    filenames = self.find_config_files()
  File "/path/to/my_project/venv/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 353, in find_config_files
    sys_dir = os.path.dirname(sys.modules['distutils'].__file__)
KeyError: 'distutils'
```

**Comment by encukou** [comment]
You should not `import pip`. See [pip's documentation](https://pip.pypa.io/en/stable/user_guide/#id9) on how to use it programmatically (using `subprocess` or a smaller library).
