### ISSUE TITLE
ruamel-yaml-clib: TypeError: dist must be a Distribution instance

### ISSUE THREAD

**Issue by 0-wiz-0** [pypa/setuptools#2375]
With latest setuptools 50.0.1 and latest ruamel-yaml-clib (from hg) I see:
````
# pkg_info
libffi-3.3nb4       Foreign function interface
libuuid-2.32.1      Generate unique identifiers for objects
python37-3.7.9nb1   Interpreted, interactive, object-oriented programming language
py37-expat-3.7.9    Python interface to expat
py37-setuptools-50.0.1 New Python packaging system
py37-curses-3.7.9nb5 Curses module for Python
py37-mercurial-5.5  Fast, lightweight source control management system
# hg clone http://hg.code.sf.net/p/ruamel-yaml-clib/code ruamel-yaml-clib-code
requesting all changes
adding changesets
adding manifests
adding file changes
added 12 changesets with 38 changes to 26 files
new changesets 9e9f48d33d34:52bf0eb35c43
updating to branch default
26 files updated, 0 files merged, 0 files removed, 0 files unresolved
# cd ruamel-yaml-clib-code
# python3.7 setup.py build
/usr/pkg/lib/python3.7/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
sys.argv ['setup.py', 'build']
test compiling test_ruamel_yaml
running build
Traceback (most recent call last):
  File "setup.py", line 960, in <module>
    main()
  File "setup.py", line 957, in main
    setup(**kw)
  File "/usr/pkg/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/pkg/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/pkg/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/pkg/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 984, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/pkg/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 859, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/usr/pkg/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
````
From some googling I guess this is a bug in ruamel-yaml-clib. I tried adding 'import setuptools' right at the start of `setup.py` and switching a couple of lines around, but I didn't get to a working install. Can you please help me with the proper fix. I'm happy to report that to the ruamel-yaml-clib developers.

**Comment by 0-wiz-0** [comment]
Ok, and just after opening this I found
https://github.com/pypa/setuptools/issues/2355#issuecomment-685159580
which works for me. Sorry for the noise.
