### ISSUE TITLE
`import pkg_resources` triggers a DeprecationWarning on Python 3.9

### ISSUE THREAD

**Issue by alexhenrie** [pypa/setuptools#2466]
I'm pretty sure this is a bug because I don't think pkg_resources is deprecated in its entirety.

```
$ PYTHONWARNINGS=error python3 -c 'import pkg_resources'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '/usr/lib/python3.9/site'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 558, in _build_master
    ws = cls()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 551, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 607, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2056, in find_on_path
    path_item_entries = _by_version_descending(filtered)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2026, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2024, in _by_version
    return [packaging.version.parse(part) for part in parts]
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2024, in <listcomp>
    return [packaging.version.parse(part) for part in parts]
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 59, in parse
    return LegacyVersion(version)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 127, in __init__
    warnings.warn(
DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
```

**Comment by alexhenrie** [comment]
Cross-posted to https://github.com/pypa/packaging/issues/368 because I'm not sure whether the bug is in packaging or in setuptools.

**Comment by yan12125** [comment]
The issue seems to be that `_by_version_descending()` in setuptools attempts to pass invalid version strings to packaging. With this patch
```diff
diff --git a/pkg_resources/__init__.py b/pkg_resources/__init__.py
index 737f4d5f..6ca1c7b4 100644
--- a/pkg_resources/__init__.py
+++ b/pkg_resources/__init__.py
@@ -2020,7 +2020,8 @@ def _by_version_descending(names):
         Parse each component of the filename
         """
         name, ext = os.path.splitext(name)
-        parts = itertools.chain(name.split('-'), [ext])
+        parts = list(itertools.chain(name.split('-'), [ext]))
+        print(parts)
         return [packaging.version.parse(part) for part in parts]
 
     return sorted(names, key=_by_version, reverse=True)
```
I got
```
['/usr/lib/python3.9/site', 'packages/MarkupSafe', '1.1.1', 'py3.9', '.egg-info']
```

With that observation, I created a fix(?)
```diff
diff --git a/pkg_resources/__init__.py b/pkg_resources/__init__.py
index 737f4d5f..84df31dd 100644
--- a/pkg_resources/__init__.py
+++ b/pkg_resources/__init__.py
@@ -2020,8 +2020,15 @@ def _by_version_descending(names):
         Parse each component of the filename
         """
         name, ext = os.path.splitext(name)
-        parts = itertools.chain(name.split('-'), [ext])
-        return [packaging.version.parse(part) for part in parts]
+        parts = list(itertools.chain(name.split('-'), [ext]))
+
+        def parse_version_ignore_invalid(version):
+            try:
+                return packaging.version.Version(version)
+            except packaging.version.InvalidVersion:
+                return version
+
+        return [parse_version_ignore_invalid(part) for part in parts]
 
     return sorted(names, key=_by_version, reverse=True)
 
```

**Comment by bnavigator** [comment]
This is also hit in https://github.com/dask/fastparquet/issues/558. @yan12125's investigation makes it clear: passing an invalid version (the first parts of the name here) throws the DeprecationWarning of `LegacyVersion`.

https://github.com/pypa/setuptools/blob/c121d289da5d19cf6df2bf6b64ac28916a060161/pkg_resources/__init__.py#L2025-L2027


https://github.com/pypa/setuptools/blob/c121d289da5d19cf6df2bf6b64ac28916a060161/setuptools/_vendor/packaging/version.py#L48-L58
