### ISSUE TITLE
Error Updating SetupTools

### ISSUE THREAD

**Issue by martynbristow** [pypa/setuptools#2513]
Error Installing SetupTools via upgrade
Release: setuptools-51.1.0.post20201221 says "yanked" and its unclear why its still downloading and trying to install
```
pi@pizero1:~ $ pip install --upgrade setuptools
Downloading/unpacking setuptools from https://files.pythonhosted.org/packages/dc/10/903b6f02c98789b1341c9ba61f72ca2d37340f79239e8e8fe2cc9d79c2d7/setuptools-51.1.0.post20201221.tar.gz#sha256=2bb28dd69df43800ed69bc415d6af73eeaf59c5ca3a6d759daf528f72f5b76bf
  Downloading setuptools-51.1.0.post20201221.tar.gz (2.0MB): 2.0MB downloaded
  Running setup.py (path:/tmp/pip-build-jmOU21/setuptools/setup.py) egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 16, in <module>
        import setuptools.version
      File "setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "pkg_resources/__init__.py", line 1365
        raise SyntaxError(e) from e
                                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 16, in <module>

    import setuptools.version

  File "setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "pkg_resources/__init__.py", line 1365

    raise SyntaxError(e) from e

                            ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-jmOU21/setuptools
Storing debug log for failure in /home/pi/.pip/pip.log
```

**Comment by martynbristow** [comment]
**Environment**

pip version: 1.5.6
Python version: 2.7
OS: rasping buster

**Comment by abravalheri** [comment]
Hi @martynbristow thank you for reporting this.

I am afraid Python 2.7 is no longer supported (and also your version of pip might be too old).

Do you still face these issues in Python >= 3.7?

For the time being, I think the best is to close this issue (I believe it should not be a problem for modern versions of Python and pip), but please feel free to "re-open" it (by commenting here with more information regarding Python >= 3.7).
