### ISSUE TITLE
Tags missing from package built from source

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#2536]
In [this test](https://github.com/python/importlib_resources/runs/1715566941?check_suite_focus=true), I see an emergent failure.

```
Collecting black
  Downloading black-20.8b1.tar.gz (1.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
ERROR: Requested black from https://files.pythonhosted.org/packages/dc/7b/5a6bbe89de849f28d7c109f5ea87b65afa5124ad615f3419e71beb29dc96/black-20.8b1.tar.gz#sha256=1c02557aa099101b9d21496f8a914e9ed2222ef70336404eeeac8edba836fbea (from pytest-black>=0.3.7->importlib-resources==0.1) has different version in metadata: '20.8'
```

I suspect the issue is the change in #2533.

**Comment by jaraco** [comment]
I can confirm the 50.3 release is implicated:

```
draft $ pip-run 'setuptools==51.3' wheel setuptools_scm -- -m pip-run --no-build-isolation --no-binary black black
Collecting setuptools_scm
  Using cached setuptools_scm-5.0.1-py2.py3-none-any.whl (28 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools==51.3
  Using cached setuptools-51.3.0-py3-none-any.whl (786 kB)
Installing collected packages: setuptools, wheel, setuptools-scm
Successfully installed setuptools-51.3.0 setuptools-scm-5.0.1 wheel-0.36.2
Collecting black
  Using cached black-20.8b1.tar.gz (1.1 MB)
    Preparing wheel metadata ... done
ERROR: Requested black from https://files.pythonhosted.org/packages/dc/7b/5a6bbe89de849f28d7c109f5ea87b65afa5124ad615f3419e71beb29dc96/black-20.8b1.tar.gz#sha256=1c02557aa099101b9d21496f8a914e9ed2222ef70336404eeeac8edba836fbea has different version in metadata: '20.8'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip-run.py", line 4, in <module>
    __name__ == '__main__' and run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip_run/__init__.py", line 18, in run
    with deps.load(*deps.not_installed(pip_args)) as home:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip_run/deps.py", line 48, in load
    _installable(args) and subprocess.check_call(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/usr/local/bin/python', '-m', 'pip', 'install', '-t', '/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-m107jew4', '--no-build-isolation', '--no-binary', 'black', 'black')' returned non-zero exit status 1.
```

```
draft $ pip-run 'setuptools<51.3' wheel setuptools_scm -- -m pip-run --no-build-isolation --no-binary black black -- -c pass
Collecting setuptools_scm
  Using cached setuptools_scm-5.0.1-py2.py3-none-any.whl (28 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools<51.3
  Using cached setuptools-51.2.0-py3-none-any.whl (784 kB)
Installing collected packages: setuptools, wheel, setuptools-scm
Successfully installed setuptools-51.2.0 setuptools-scm-5.0.1 wheel-0.36.2
Collecting black
  Using cached black-20.8b1.tar.gz (1.1 MB)
    Preparing wheel metadata ... done
Collecting click>=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting pathspec<1,>=0.6
  Using cached pathspec-0.8.1-py2.py3-none-any.whl (28 kB)
Collecting regex>=2020.1.8
  Using cached regex-2020.11.13-cp39-cp39-macosx_10_9_x86_64.whl (284 kB)
Collecting toml>=0.10.1
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting typed-ast>=1.4.0
  Using cached typed_ast-1.4.2-cp39-cp39-macosx_10_9_x86_64.whl (225 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Building wheels for collected packages: black
  Building wheel for black (PEP 517) ... done
  Created wheel for black: filename=black-20.8b1-py3-none-any.whl size=124184 sha256=b5d6e65076ae18dcb249a74dc0d9559504383db819557f1545e9ab957fce1f91
  Stored in directory: /Users/jaraco/Library/Caches/pip/wheels/4e/57/9a/e704bdd859ee892dc46fff03fd499422dc9e99fd9bd5c446d3
Successfully built black
Installing collected packages: typing-extensions, typed-ast, toml, regex, pathspec, mypy-extensions, click, appdirs, black
Successfully installed appdirs-1.4.4 black-20.8b1 click-7.1.2 mypy-extensions-0.4.3 pathspec-0.8.1 regex-2020.11.13 toml-0.10.2 typed-ast-1.4.2 typing-extensions-3.7.4.3
```

**Comment by jaraco** [comment]
I had to manually upload the 50.3.1 release as automated releases were also blocked by this issue.

**Comment by henryiii** [comment]
Before example: `pybind11_global-2.6.2.dev1.dist-info/RECORD`
After example: `pybind11_global-2.6.2.dist-info/RECORD`

And updating to 52.3.1 fixes it! Thanks for a _quick_ fix!

**Comment by henryiii** [comment]
Are you yanking 51.3.0 or should I filter it in my pyproject.toml?

**Comment by jaraco** [comment]
Given that the release was only out for a few hours, I doubt yanking will help much. Those affected are already pulling latest, so should get the fix.
