### ISSUE TITLE
`AttributeError` with `version = attr:` and variable annotation syntax type hints

### ISSUE THREAD

**Issue by homeworkprod** [pypa/setuptools#2563]
**Observed behavior**

`setup.cfg` contains:
```ini
[metadata]
version = attr: mypackage.VERSION
```

`mypackage/__init__.py` contains:
```py
VERSION: str = '42.0-dev'
```

`pip install -e .` results in:
```pytb
Obtaining […]
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /projectpath/venv/bin/python3.7 /projectpath/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpwip8xxcd
       cwd: /projectpath
  Complete output (64 lines):
  Traceback (most recent call last):
    File "/tmp/pip-build-env-tprf3sb3/overlay/lib/python3.7/site-packages/setuptools/config.py", line 35, in __getattr__
      for statement in self.module.body
  StopIteration
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/tmp/pip-build-env-tprf3sb3/overlay/lib/python3.7/site-packages/setuptools/config.py", line 387, in _parse_attr
      return getattr(StaticModule(module_name), attr_name)
    File "/tmp/pip-build-env-tprf3sb3/overlay/lib/python3.7/site-packages/setuptools/config.py", line 43, in __getattr__
      ) from e
  AttributeError: [mypackage] has no attribute VERSION
  
  During handling of the above exception, another exception occurred:

  […]
```

**Expectation**

It works.

**Workaround**

Updating `mypackage/__init__.py` to
```py
VERSION = '42.0-dev'
```
works.

**Comment by abravalheri** [comment]
Hi @homeworkprod, thank you very much for bringing this topic up.

I did a quick investigation and it seems that this problem has already been solved 👏 

I tried to verify this problem, by using one of your opensource repositories in GitHub:

```bash
> docker run -it --rm python:3.7 /bin/bash
$ git clone https://github.com/homeworkprod/syslog2irc.git
$ cd syslog2irc
$ sed -i 's/VERSION =/VERSION: str =/' src/syslog2irc/__init__.py
$ python3.7 -m pip install -U pip build
$ python3.7 -m build
...
Successfully built syslog2irc-0.14.dev0.tar.gz and syslog2irc-0.14.dev0-py3-none-any.whl
```

Is that the outcome you had in mind? Would this approach work for you?

---

Since it looks like this problem was solved, I will go ahead and close this issue, but please let me know if you still have problems and I will re-open it.

**Comment by homeworkprod** [comment]
Thanks a lot, @abravalheri, for getting back to this!

Yes, I can confirm that this works for me now.
