### ISSUE TITLE
[BUG] 56.0.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [pypa/setuptools#2638]
### setuptools version

56.0.0

### Python version

Python 3.8.8

### OS

Linux

### Additional environment information

None.

### Description

pytest based test suite i sfailing.

### Expected behavior

test suite should finish without errors

### How to Reproduce

Run pytest after build.

### Output

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-setuptools-56.0.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-setuptools-56.0.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/python3 -Bm pytest -ra --ignore=pavement.py
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/setuptools-56.0.0, configfile: pytest.ini
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, asyncio-0.14.0, expect-1.1.0, cov-2.11.1, mock-3.5.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, flaky-3.7.0, hypothesis-6.9.1
collected 710 items / 2 skipped / 708 selected

pkg_resources/__init__.py ...                                                                                                                                        [  0%]
pkg_resources/api_tests.txt .                                                                                                                                        [  0%]
pkg_resources/tests/test_find_distributions.py ....                                                                                                                  [  1%]
pkg_resources/tests/test_markers.py .                                                                                                                                [  1%]
pkg_resources/tests/test_pkg_resources.py ................ssss                                                                                                       [  4%]
pkg_resources/tests/test_resources.py ..................................................................................                                             [ 15%]
pkg_resources/tests/test_working_set.py ..................................                                                                                           [ 20%]
setuptools/namespaces.py .                                                                                                                                           [ 20%]
setuptools/package_index.py ..                                                                                                                                       [ 20%]
setuptools/sandbox.py .                                                                                                                                              [ 20%]
setuptools/command/develop.py .                                                                                                                                      [ 21%]
setuptools/command/install_lib.py .                                                                                                                                  [ 21%]
setuptools/tests/test_archive_util.py X                                                                                                                              [ 21%]
setuptools/tests/test_bdist_egg.py .F                                                                                                                                [ 21%]
setuptools/tests/test_build_clib.py .                                                                                                                                [ 21%]
setuptools/tests/test_build_ext.py ...                                                                                                                               [ 22%]
setuptools/tests/test_build_meta.py ................................................................................................................................ [ 40%]
......                                                                                                                                                               [ 41%]
setuptools/tests/test_build_py.py ...                                                                                                                                [ 41%]
setuptools/tests/test_config.py ............................................                                                                                         [ 47%]
setuptools/tests/test_dep_util.py .                                                                                                                                  [ 47%]
setuptools/tests/test_depends.py .                                                                                                                                   [ 48%]
setuptools/tests/test_develop.py .s....F                                                                                                                             [ 49%]
setuptools/tests/test_dist.py ........x.x.....................                                                                                                       [ 53%]
setuptools/tests/test_dist_info.py ..                                                                                                                                [ 53%]
setuptools/tests/test_distutils_adoption.py F..                                                                                                                      [ 54%]
setuptools/tests/test_easy_install.py ..................................F.............                                                                               [ 60%]
setuptools/tests/test_egg_info.py .........................x.........................................                                                                [ 70%]
setuptools/tests/test_extern.py ...                                                                                                                                  [ 70%]
setuptools/tests/test_find_packages.py ............                                                                                                                  [ 72%]
setuptools/tests/test_glob.py ....                                                                                                                                   [ 73%]
setuptools/tests/test_install_scripts.py .s.s                                                                                                                        [ 73%]
setuptools/tests/test_manifest.py ...................................................................                                                                [ 83%]
setuptools/tests/test_msvc14.py ssss                                                                                                                                 [ 83%]
setuptools/tests/test_namespaces.py ....                                                                                                                             [ 84%]
setuptools/tests/test_packageindex.py ....................                                                                                                           [ 87%]
setuptools/tests/test_register.py .                                                                                                                                  [ 87%]
setuptools/tests/test_sandbox.py ..........                                                                                                                          [ 88%]
setuptools/tests/test_sdist.py ...............                                                                                                                       [ 90%]
setuptools/tests/test_setopt.py .                                                                                                                                    [ 90%]
setuptools/tests/test_setuptools.py .....................                                                                                                            [ 93%]
setuptools/tests/test_sphinx_upload_docs.py .                                                                                                                        [ 93%]
setuptools/tests/test_test.py ....                                                                                                                                   [ 94%]
setuptools/tests/test_unicode_utils.py .                                                                                                                             [ 94%]
setuptools/tests/test_upload.py .                                                                                                                                    [ 94%]
setuptools/tests/test_upload_docs.py ..                                                                                                                              [ 95%]
setuptools/tests/test_virtualenv.py .....X....                                                                                                                       [ 96%]
setuptools/tests/test_wheel.py ......................                                                                                                                [ 99%]
setuptools/tests/test_windows_wrappers.py sss                                                                                                                        [100%]

================================================================================= FAILURES =================================================================================
______________________________________________________________________ Test.test_exclude_source_files ______________________________________________________________________

self = <setuptools.tests.test_bdist_egg.Test object at 0x7facb598cf10>, setup_context = local('/tmp/pytest-of-tkloczko/pytest-28/test_exclude_source_files0')
user_override = None

    @pytest.mark.xfail(
        os.environ.get('PYTHONDONTWRITEBYTECODE'),
        reason="Byte code disabled",
    )
    def test_exclude_source_files(self, setup_context, user_override):
        dist = Distribution(dict(
            script_name='setup.py',
            script_args=['bdist_egg', '--exclude-source-files'],
            name='foo',
            py_modules=['hi'],
        ))
        with contexts.quiet():
            dist.parse_command_line()
            dist.run_commands()
        [dist_name] = os.listdir('dist')
        dist_filename = os.path.join('dist', dist_name)
        zip = zipfile.ZipFile(dist_filename)
        names = list(zi.filename for zi in zip.filelist)
>       assert 'hi.pyc' in names
E       AssertionError: assert 'hi.pyc' in ['EGG-INFO/PKG-INFO', 'EGG-INFO/SOURCES.txt', 'EGG-INFO/dependency_links.txt', 'EGG-INFO/top_level.txt', 'EGG-INFO/zip-safe']

/home/tkloczko/rpmbuild/BUILD/setuptools-56.0.0/setuptools/tests/test_bdist_egg.py:65: AssertionError
___________________________________________________________________ TestNamespaces.test_editable_prefix ____________________________________________________________________

self = <setuptools.tests.test_develop.TestNamespaces object at 0x7facb56f9400>, tmp_path = PosixPath('/tmp/pytest-of-tkloczko/pytest-28/test_editable_prefix0')
sample_project = PosixPath('/tmp/pytest-of-tkloczko/pytest-28/test_editable_prefix0/sampleproject')

    @pytest.mark.xfail(
        platform.python_implementation() == 'PyPy',
        reason="Workaround fails on PyPy (why?)",
    )
    def test_editable_prefix(self, tmp_path, sample_project):
        """
        Editable install to a prefix should be discoverable.
        """
        prefix = tmp_path / 'prefix'
        prefix.mkdir()

        # figure out where pip will likely install the package
        site_packages = prefix / next(
            pathlib.Path(path).relative_to(sys.prefix)
            for path in sys.path
            if 'site-packages' in path
            and path.startswith(sys.prefix)
        )

        # install the workaround
        self.install_workaround(site_packages)

        env = dict(os.environ, PYTHONPATH=str(site_packages))
        cmd = [
            sys.executable,
            '-m', 'pip',
            'install',
            '--editable',
            str(sample_project),
            '--prefix', str(prefix),
            '--no-build-isolation',
        ]
        subprocess.check_call(cmd, env=env)

        # now run 'sample' with the prefix on the PYTHONPATH
        bin = 'Scripts' if platform.system() == 'Windows' else 'bin'
        exe = prefix / bin / 'sample'
        if sys.version_info < (3, 7) and platform.system() == 'Windows':
            exe = str(exe)
>       subprocess.check_call([exe], env=env)

setuptools/tests/test_develop.py:255:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = ([PosixPath('/tmp/pytest-of-tkloczko/pytest-28/test_editable_prefix0/prefix/bin/sample')],)
kwargs = {'env': {'BASH_FUNC_which%%': '() {  ( alias;\n eval ${_declare} ) | /usr/bin/which --tty-only --read-alias --read-fun...on -fdata-sections -ffunction-sections -flto=auto -flto-partition=none', 'CONFIG_SITE': 'NONE', 'CVS_RSH': 'ssh', ...}}
retcode = 1, cmd = [PosixPath('/tmp/pytest-of-tkloczko/pytest-28/test_editable_prefix0/prefix/bin/sample')]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the call function.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '[PosixPath('/tmp/pytest-of-tkloczko/pytest-28/test_editable_prefix0/prefix/bin/sample')]' returned non-zero exit status 1.

/usr/lib64/python3.8/subprocess.py:364: CalledProcessError
-------------------------------------------------------------------------- Captured stderr setup ---------------------------------------------------------------------------
Cloning into 'sampleproject'...
--------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------
Obtaining file:///tmp/pytest-of-tkloczko/pytest-28/test_editable_prefix0/sampleproject
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting peppercorn
  Downloading peppercorn-0.6-py3-none-any.whl (4.8 kB)
Installing collected packages: peppercorn, sampleproject
  Running setup.py develop for sampleproject
Successfully installed peppercorn-0.6 sampleproject
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pytest-of-tkloczko/pytest-28/test_editable_prefix0/prefix/bin/sample", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sampleproject' distribution was not found and is required by the application
__________________________________________________________________________ test_distutils_stdlib ___________________________________________________________________________

venv = <setuptools.tests.test_distutils_adoption.VirtualEnv object at 0x7facb50b54c0>

    def test_distutils_stdlib(venv):
        """
        Ensure stdlib distutils is used when appropriate.
        """
        env = dict(SETUPTOOLS_USE_DISTUTILS='stdlib')
>       assert venv.name not in find_distutils(venv, env=env).split(os.sep)
E       AssertionError: assert '.env' not in ['', 'tmp', 'pytest-of-tkloczko', 'pytest-28', 'test_distutils_stdlib0', 'venv', ...]
E        +  where '.env' = <setuptools.tests.test_distutils_adoption.VirtualEnv object at 0x7facb50b54c0>.name
E        +  and   ['', 'tmp', 'pytest-of-tkloczko', 'pytest-28', 'test_distutils_stdlib0', 'venv', ...] = <built-in method split of str object at 0x7facb5404e90>('/')
E        +    where <built-in method split of str object at 0x7facb5404e90> = '/tmp/pytest-of-tkloczko/pytest-28/test_distutils_stdlib0/venv/.env/lib64/python3.8/distutils/__init__.py\n'.split
E        +      where '/tmp/pytest-of-tkloczko/pytest-28/test_distutils_stdlib0/venv/.env/lib64/python3.8/distutils/__init__.py\n' = find_distutils(<setuptools.tests.test_distutils_adoption.VirtualEnv object at 0x7facb50b54c0>, env={'SETUPTOOLS_USE_DISTUTILS': 'stdlib'})
E        +    and   '/' = os.sep

setuptools/tests/test_distutils_adoption.py:52: AssertionError
-------------------------------------------------------------------------- Captured stdout setup ---------------------------------------------------------------------------
Using base prefix '/usr'
  No LICENSE.txt / LICENSE found in source
New python executable in /tmp/pytest-of-tkloczko/pytest-28/test_distutils_stdlib0/venv/.env/bin/python3
Also creating executable in /tmp/pytest-of-tkloczko/pytest-28/test_distutils_stdlib0/venv/.env/bin/python
Installing setuptools, pip, wheel...
done.
Processing /tmp/pytest-of-tkloczko/pytest-28/test_distutils_stdlib0/src
Building wheels for collected packages: setuptools
  Building wheel for setuptools (setup.py): started
  Building wheel for setuptools (setup.py): finished with status 'done'
  Created wheel for setuptools: filename=setuptools-56.0.0-py3-none-any.whl size=561538 sha256=5db394cc9a699269f07d51c244175a795ebe95206de35ae98f3b4ecdd2a343e9
  Stored in directory: /tmp/pip-ephem-wheel-cache-ify5ksqr/wheels/4d/92/0c/e75923a5dc3ad56ae95a547baea202ff72b53da68f138cd683
Successfully built setuptools
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Not uninstalling setuptools at /home/tkloczko/rpmbuild/BUILDROOT/python-setuptools-56.0.0-2.fc35.x86_64/usr/lib/python3.8/site-packages, outside environment /tmp/pytest-of-tkloczko/pytest-28/test_distutils_stdlib0/venv/.env
    Can't uninstall 'setuptools'. No files were found to uninstall.
Successfully installed setuptools-56.0.0
__________________________________________________________ TestSetupRequires.test_setup_requires_with_allow_hosts __________________________________________________________

self = <setuptools.tests.test_easy_install.TestSetupRequires object at 0x7fac923de7c0>, mock_index = <MockServer(Thread-4, started daemon 140373760497216)>

    def test_setup_requires_with_allow_hosts(self, mock_index):
        ''' The `allow-hosts` option in not supported anymore. '''
        with contexts.save_pkg_resources_state():
            with contexts.tempdir() as temp_dir:
                test_pkg = os.path.join(temp_dir, 'test_pkg')
                test_setup_py = os.path.join(test_pkg, 'setup.py')
                test_setup_cfg = os.path.join(test_pkg, 'setup.cfg')
                os.mkdir(test_pkg)
                with open(test_setup_py, 'w') as fp:
                    fp.write(DALS(
                        '''
                        from setuptools import setup
                        setup(setup_requires='python-xlib')
                        '''))
                with open(test_setup_cfg, 'w') as fp:
                    fp.write(DALS(
                        '''
                        [easy_install]
                        allow_hosts = *
                        '''))
                with pytest.raises(distutils.errors.DistutilsError):
>                   run_setup(test_setup_py, [str('--version')])
E                   Failed: DID NOT RAISE <class 'distutils.errors.DistutilsError'>

setuptools/tests/test_easy_install.py:691: Failed
--------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------
0.0.0
========================================================================= short test summary info ==========================================================================
SKIPPED [2] setuptools/tests/test_msvc.py:17: could not import 'distutils.msvc9compiler': No module named 'winreg'
SKIPPED [1] pkg_resources/tests/test_pkg_resources.py:382: Testing case-insensitive filesystems.
SKIPPED [3] pkg_resources/tests/test_pkg_resources.py:399: Testing systems using backslashes as path separators.
SKIPPED [1] setuptools/tests/test_develop.py:107: TODO: needs a fixture to cause 'develop' to be invoked without mutating environment.
SKIPPED [1] setuptools/tests/test_install_scripts.py:50: Windows only
SKIPPED [1] setuptools/tests/test_install_scripts.py:78: Windows only
SKIPPED [1] setuptools/tests/test_msvc14.py:16: These tests are only for win32
SKIPPED [1] setuptools/tests/test_msvc14.py:34: These tests are only for win32
SKIPPED [1] setuptools/tests/test_msvc14.py:52: These tests are only for win32
SKIPPED [1] setuptools/tests/test_msvc14.py:68: These tests are only for win32
SKIPPED [1] setuptools/tests/test_windows_wrappers.py:69: Windows only
SKIPPED [1] setuptools/tests/test_windows_wrappers.py:110: Windows only
SKIPPED [1] setuptools/tests/test_windows_wrappers.py:169: Windows only
XFAIL setuptools/tests/test_dist.py::test_read_metadata[Metadata Version 1.2: Project-Url-attrs6]
  Issue #1578: project_urls not read
XFAIL setuptools/tests/test_dist.py::test_read_metadata[Metadata Version 2.1: Provides Extra-attrs8]
  provides_extras not read
XFAIL setuptools/tests/test_egg_info.py::TestEggInfo::test_requires[extras_require_with_marker_in_setup_cfg]
XPASS setuptools/tests/test_archive_util.py::test_unicode_files #710 and #712
XPASS setuptools/tests/test_virtualenv.py::test_pip_upgrade_from_source[pip==19.3.1] pypa/pip#6599
FAILED setuptools/tests/test_bdist_egg.py::Test::test_exclude_source_files - AssertionError: assert 'hi.pyc' in ['EGG-INFO/PKG-INFO', 'EGG-INFO/SOURCES.txt', 'EGG-INFO/d...
FAILED setuptools/tests/test_develop.py::TestNamespaces::test_editable_prefix - subprocess.CalledProcessError: Command '[PosixPath('/tmp/pytest-of-tkloczko/pytest-28/tes...
FAILED setuptools/tests/test_distutils_adoption.py::test_distutils_stdlib - AssertionError: assert '.env' not in ['', 'tmp', 'pytest-of-tkloczko', 'pytest-28', 'test_dis...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_allow_hosts - Failed: DID NOT RAISE <class 'distutils.errors.DistutilsError'>
=============================================== 4 failed, 687 passed, 16 skipped, 3 xfailed, 2 xpassed in 312.00s (0:05:12) ================================================
```

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by webknjaz** [comment]
Hey @kloczek, the tests are passing in typical environments as proven by our CI — it's green. So there must be something different about yours. Please provide us with more details on how to reproduce this or we'll have to close this issue as invalid if there is no minimum verifiable example.

**Comment by kloczek** [comment]
I just started updating my rpm package to 60.0.0 and forund that soem units are failing `DeprecationWarning`.
Just in case my build procesdure consif from:
- `python3 -sBm build -w`
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Here is pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-setuptools-60.0.0-2.fc35.x86_64//usr/lib/python3.8/site-packages
+ pytest -ra -p no:randomly setuptools --deselect setuptools/tests/test_develop.py::TestNamespaces::test_editable_prefix --deselect setuptools/tests/test_easy_install.py::TestUserInstallTest::test_local_index
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/setuptools-60.0.0, configfile: pytest.ini
plugins: forked-1.4.0, shutil-1.7.0, virtualenv-1.7.0, xdist-2.5.0, cov-2.12.1, flake8-1.0.7
collected 584 items / 2 deselected / 2 skipped / 580 selected

setuptools/dist.py .                                                                                                                                                 [  0%]
setuptools/namespaces.py .                                                                                                                                           [  0%]
setuptools/package_index.py ..                                                                                                                                       [  0%]
setuptools/sandbox.py .                                                                                                                                              [  0%]
setuptools/command/develop.py .                                                                                                                                      [  1%]
setuptools/command/install_lib.py .                                                                                                                                  [  1%]
setuptools/tests/test_archive_util.py X                                                                                                                              [  1%]
setuptools/tests/test_bdist_deprecations.py .                                                                                                                        [  1%]
setuptools/tests/test_bdist_egg.py .x                                                                                                                                [  1%]
setuptools/tests/test_build_clib.py .                                                                                                                                [  2%]
setuptools/tests/test_build_ext.py ....                                                                                                                              [  2%]
setuptools/tests/test_build_meta.py ................................................................................................................................ [ 24%]
......                                                                                                                                                               [ 25%]
setuptools/tests/test_build_py.py ...                                                                                                                                [ 26%]
setuptools/tests/test_config.py .............................................                                                                                        [ 34%]
setuptools/tests/test_dep_util.py .                                                                                                                                  [ 34%]
setuptools/tests/test_depends.py .                                                                                                                                   [ 34%]
setuptools/tests/test_develop.py s....                                                                                                                               [ 35%]
setuptools/tests/test_dist.py F......x...x..........................                                                                                                 [ 41%]
setuptools/tests/test_dist_info.py ..                                                                                                                                [ 42%]
setuptools/tests/test_distutils_adoption.py ...                                                                                                                      [ 42%]
setuptools/tests/test_easy_install.py .F...FFF......FF...FFFFFFFFFFFFFFFFFFF.........                                                                                [ 50%]
setuptools/tests/test_egg_info.py .........................x...............................................                                                          [ 63%]
setuptools/tests/test_extern.py ...                                                                                                                                  [ 63%]
setuptools/tests/test_find_packages.py ............                                                                                                                  [ 65%]
setuptools/tests/test_glob.py ....                                                                                                                                   [ 66%]
setuptools/tests/test_install_scripts.py .s.s                                                                                                                        [ 67%]
setuptools/tests/test_integration.py sssss                                                                                                                           [ 68%]
setuptools/tests/test_manifest.py ...................................................................                                                                [ 79%]
setuptools/tests/test_msvc14.py ssss                                                                                                                                 [ 80%]
setuptools/tests/test_namespaces.py ....                                                                                                                             [ 80%]
setuptools/tests/test_packageindex.py ....................                                                                                                           [ 84%]
setuptools/tests/test_register.py .                                                                                                                                  [ 84%]
setuptools/tests/test_sandbox.py ..........                                                                                                                          [ 86%]
setuptools/tests/test_sdist.py .................                                                                                                                     [ 89%]
setuptools/tests/test_setopt.py ..                                                                                                                                   [ 89%]
setuptools/tests/test_setuptools.py .....................                                                                                                            [ 93%]
setuptools/tests/test_sphinx_upload_docs.py .                                                                                                                        [ 93%]
setuptools/tests/test_test.py .                                                                                                                                      [ 93%]
setuptools/tests/test_unicode_utils.py .                                                                                                                             [ 93%]
setuptools/tests/test_upload.py .                                                                                                                                    [ 93%]
setuptools/tests/test_upload_docs.py ..                                                                                                                              [ 94%]
setuptools/tests/test_virtualenv.py ..x......                                                                                                                        [ 95%]
setuptools/tests/test_wheel.py ......................                                                                                                                [ 99%]
setuptools/tests/test_windows_wrappers.py sss                                                                                                                        [100%]

================================================================================= FAILURES =================================================================================

[..]

========================================================================= short test summary info ==========================================================================
SKIPPED [2] setuptools/tests/test_msvc.py:17: could not import 'distutils.msvc9compiler': No module named 'winreg'
SKIPPED [1] setuptools/tests/test_develop.py:66: TODO: needs a fixture to cause 'develop' to be invoked without mutating environment.
SKIPPED [1] setuptools/tests/test_install_scripts.py:50: Windows only
SKIPPED [1] setuptools/tests/test_install_scripts.py:78: Windows only
SKIPPED [5] setuptools/tests/test_integration.py:31: Integration tests cannot run when pbr is installed
SKIPPED [1] setuptools/tests/test_msvc14.py:16: These tests are only for win32
SKIPPED [1] setuptools/tests/test_msvc14.py:34: These tests are only for win32
SKIPPED [1] setuptools/tests/test_msvc14.py:52: These tests are only for win32
SKIPPED [1] setuptools/tests/test_msvc14.py:68: These tests are only for win32
SKIPPED [1] setuptools/tests/test_windows_wrappers.py:80: Windows only
SKIPPED [1] setuptools/tests/test_windows_wrappers.py:121: Windows only
SKIPPED [1] setuptools/tests/test_windows_wrappers.py:180: Windows only
XFAIL setuptools/tests/test_bdist_egg.py::Test::test_exclude_source_files
  Byte code disabled
XFAIL setuptools/tests/test_dist.py::test_read_metadata[Metadata Version 1.2: Project-Url-attrs5]
  Issue #1578: project_urls not read
XFAIL setuptools/tests/test_dist.py::test_read_metadata[Metadata Version 2.1: Provides Extra-attrs9]
  provides_extras not read
XFAIL setuptools/tests/test_egg_info.py::TestEggInfo::test_requires[extras_require_with_marker_in_setup_cfg]
XFAIL setuptools/tests/test_virtualenv.py::test_pip_upgrade_from_source[pip<20]
  pypa/pip#6599
XPASS setuptools/tests/test_archive_util.py::test_unicode_files #710 and #712
FAILED setuptools/tests/test_dist.py::test_dist_fetch_build_egg - DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major ...
FAILED setuptools/tests/test_easy_install.py::TestEasyInstallTest::test_no_find_links - DeprecationWarning: Creating a LegacyVersion has been deprecated and will be remo...
FAILED setuptools/tests/test_easy_install.py::TestEasyInstallTest::test_unicode_filename_in_sdist - DeprecationWarning: Creating a LegacyVersion has been deprecated and ...
FAILED setuptools/tests/test_easy_install.py::TestEasyInstallTest::test_unicode_content_in_sdist - DeprecationWarning: Creating a LegacyVersion has been deprecated and w...
FAILED setuptools/tests/test_easy_install.py::TestEasyInstallTest::test_script_install - DeprecationWarning: Creating a LegacyVersion has been deprecated and will be rem...
FAILED setuptools/tests/test_easy_install.py::TestUserInstallTest::test_user_install_not_implied_user_site_enabled - DeprecationWarning: Creating a LegacyVersion has bee...
FAILED setuptools/tests/test_easy_install.py::TestUserInstallTest::test_user_install_not_implied_user_site_disabled - DeprecationWarning: Creating a LegacyVersion has be...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_overrides_version_conflict[use_setup_cfg0] - DeprecationWarning: Creating a LegacyVe...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_overrides_version_conflict[use_setup_cfg1] - DeprecationWarning: Creating a LegacyVe...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_overrides_version_conflict[use_setup_cfg2] - DeprecationWarning: Creating a LegacyVe...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_overrides_version_conflict[use_setup_cfg3] - DeprecationWarning: Creating a LegacyVe...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_override_nspkg[use_setup_cfg0] - DeprecationWarning: Creating a LegacyVersion has be...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_override_nspkg[use_setup_cfg1] - DeprecationWarning: Creating a LegacyVersion has be...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_override_nspkg[use_setup_cfg2] - DeprecationWarning: Creating a LegacyVersion has be...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_override_nspkg[use_setup_cfg3] - DeprecationWarning: Creating a LegacyVersion has be...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_attr_version[use_setup_cfg0] - DeprecationWarning: Creating a LegacyVersion has...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_attr_version[use_setup_cfg1] - DeprecationWarning: Creating a LegacyVersion has...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_attr_version[use_setup_cfg2] - DeprecationWarning: Creating a LegacyVersion has...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_attr_version[use_setup_cfg3] - DeprecationWarning: Creating a LegacyVersion has...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_honors_pip_env - DeprecationWarning: Creating a LegacyVersion has been deprecated an...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_pep508_url - DeprecationWarning: Creating a LegacyVersion has been deprecated a...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_allow_hosts - DeprecationWarning: Creating a LegacyVersion has been deprecated ...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_python_requires - DeprecationWarning: Creating a LegacyVersion has been depreca...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_find_links_in_setup_cfg[False] - DeprecationWarning: Creating a LegacyVersion h...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_find_links_in_setup_cfg[True] - DeprecationWarning: Creating a LegacyVersion ha...
FAILED setuptools/tests/test_easy_install.py::TestSetupRequires::test_setup_requires_with_transitive_extra_dependency - DeprecationWarning: Creating a LegacyVersion has ...
======================================== 26 failed, 535 passed, 17 skipped, 2 deselected, 5 xfailed, 1 xpassed in 192.80s (0:03:12) ========================================```

Full log is quite long so please let me know if you may need full output.

**Comment by webknjaz** [comment]
Just add `-W ignore::DeprecationWarning` to your invocation, these are only important for the upstream.

**Comment by kloczek** [comment]
I think that this ticket can be closed now as I'm trying to build latest version of the `setuptools` and this issue is no longer valid on that version.
