### ISSUE TITLE
[BUG] replace INSTALL_SCHEMES in distutils with the versions in sysconfig

### ISSUE THREAD

**Issue by mattip** [pypa/setuptools#2647]
### setuptools version

Any

### Python version

Mainly PyPy, but implementing this would benefit the entire ecosystem

### OS

Any

### Description

Over at PyPy, we extend the sysconfig._INSTALL_SCHEMES, exposed from `sysconfig` as `get_scheme_names()`, `get_paths()` and `get_path()`, with implementation-specific schemes. Copying the changes to `distutils/command/install.py` failed, as evidenced in [issue 3436](https://foss.heptapod.net/pypy/pypy/-/issues/3436). While we can make our changes work via something like [PR 817](https://foss.heptapod.net/pypy/pypy/-/merge_requests/817) I think it would make more sense to remove the duplicate code.

### Expected behavior

Code in `sysconfig` should not be duplicated in `distutils`

### How to Reproduce

The minimum reproducer is to create a setup.py and then call it with `develop --user` which fails on PyPy. Here is a Dockerfile that will error out:
```
FROM pypy:3.7-7.3.4-slim

RUN echo 'from setuptools import setup; setup(name="foo", packages=[])' > setup.py

RUN pypy setup.py develop --user

```

### Output

```console
Traceback (most recent call last):
  File "/opt/pypy/lib-python/3/distutils/util.py", line 192, in subst_vars
    return re.sub(r'\$([a-zA-Z_][a-zA-Z_0-9]*)', _subst, s)
  File "/opt/pypy/lib-python/3/re.py", line 194, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/opt/pypy/lib-python/3/distutils/util.py", line 189, in _subst
    return os.environ[var_name]
  File "/opt/pypy/lib-python/3/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'implementation_lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup; setup(name="foo", packages=[])
  File "/opt/pypy/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/pypy/lib-python/3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/pypy/lib-python/3/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/pypy/lib-python/3/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/opt/pypy/lib-python/3/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/opt/pypy/site-packages/setuptools/command/develop.py", line 52, in finalize_options
    easy_install.finalize_options(self)
  File "/opt/pypy/site-packages/setuptools/command/easy_install.py", line 260, in finalize_options
    self.expand_dirs()
  File "/opt/pypy/site-packages/setuptools/command/easy_install.py", line 395, in expand_dirs
    self._expand_attrs(dirs)
  File "/opt/pypy/site-packages/setuptools/command/easy_install.py", line 377, in _expand_attrs
    val = subst_vars(val, self.config_vars)
  File "/opt/pypy/lib-python/3/distutils/util.py", line 194, in subst_vars
    raise ValueError("invalid variable '$%s'" % var)
ValueError: invalid variable '$'implementation_lower''

```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mattip** [comment]
I amended the title. It would be better to deprecate `get_config_vars`, `get_config_var`, `get_python_inc` and anything else already provided by `sysconfig` from `_distutils.sysconfig`.
