### ISSUE TITLE
[BUG] package_dir in setuptools.setup() does not work as expected when installing with editable option

### ISSUE THREAD

**Issue by cvcore** [pypa/setuptools#2662]
### setuptools version

56.0.0

### Python version

Python 3.8.5

### OS

Ubuntu 18.04.4 LTS (Bionic Beaver)

### Description

Hello,

I followed the instructions in https://github.com/pypa/setuptools/blob/main/docs/deprecated/distutils/setupscript.rst#listing-whole-packages by using
```
setuptools.setup(
    ...
    package_dir={'awesome_pkg': 'my_awesome_package'}
    package=['awesome_pkg']
)
```
in order to package `my_awesome_package` and later use it `import awesome_pkg` after install.

But this unfortunately didn't work.

Later I found out the reason is because I've installed the package with editable `pip install -e .` option. There is unfortunately no documentation on this and I would consider it as a hidden bug / discrepancy of the API (please correct me if I'm wrong).

I have the following path structure:

```
setup.py
my_awesome_pkg/
    __init__.py
    module_1/
        __init__.py
        ...
    module_2/
        __init__.py
        ...
```

### Expected behavior

`import awesome_pkg` should work with the package installed by `pip install -e` option

### How to Reproduce

Please refer to bug report.

### Output

```console
<ipython-input-1-25a6a57694c2> in <module>
----> 1 import awesome_package
ModuleNotFoundError: No module named 'awesome_package'
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cvcore** [comment]
Related: https://stackoverflow.com/questions/64838393/package-dir-in-setup-py-not-working-as-expected

**Comment by johanek2** [comment]
Oh it is a bug that explains a lot.

**Comment by pedrorrivero** [comment]
In editable mode (i.e. `pip install -e .`) the package name set through `package_dir={'package_name':'dir_name'}` is not recognized. The only way to access the modules is through the actual directory name where they are located.

As @cvcore points out, this functionality works fine outside of editable mode.

When `mkdir tmp && cd tmp`, the same behavior occurs: in editable mode you need to do `import dir_name` whereas in regular mode you do `import package_name`. @pganssle 

Any updates on this?

**Comment by pedrorrivero** [comment]
## Reproducible example

### Environment
#### Tree
All files are empty except for `setup.py`.
```
./
├── dir_name/
│   ├── __init__.py
│   └── module.py
├── setup.py
└── tmp/
```

#### _setup.py_
```python
from setuptools import setup

if __name__ == "__main__":
    setup(
        name='package_name',
        packages=['package_name'],
        package_dir={'package_name':'dir_name'}
    )
```

### Steps
From the root directory of the tree (i.e. `./`):
1. `python3 -m venv .venv`
2. `source .venv/bin/activate`
3. `pip install [-e] .` (Only add `-e` for editable mode)
4. `cd tmp`
5. `python3`

### Results
#### Standard mode:
```python
>>> import package_name
>>> import dir_name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dir_name'
```

#### Editable mode:
```python
>>> import package_name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'package_name'
>>> import dir_name
```

**Comment by abravalheri** [comment]
@cvcore, @pedrorrivero, could you please just checkout if v64.0.3+ solves your problem?
