### ISSUE TITLE
[BUG] setuptools does pass invalid python_requires through, causing breakage in distlib

### ISSUE THREAD

**Issue by mgorny** [pypa/setuptools#2689]
### setuptools version

57.0.0

### Python version

3.9.5

### OS

Gentoo Linux (using venv)

### Description

Setuptools seems to permit invalid values for `python_requires` that cause the resulting metadata to be rejected by `distlib` (e.g. `>=3.5.*`).

### Expected behavior

I would expect setuptools to at least warn that `python_requires` is invalid, as these issues are hard to debug afterwards. It might be helpful to even sanitize or ignore the values for a transitional period, then reject them.

### How to Reproduce

In a virtualenv:

```
pip install nltk==3.6.2 distlib
python -c "import distlib.database; distlib.database.DistributionPath().get_distribution('nltk')"
```

I'm listing specific nltk version because I've submitted a PR to fix `python_requires`. The specific problem is: https://github.com/nltk/nltk/blob/902dbeb523b0816ee38c9a100e4e6a54f06e7d14/setup.py#L111

### Output

```console
$ pip install nltk==3.6.2 distlib
Collecting nltk==3.6.2
  Using cached nltk-3.6.2-py3-none-any.whl (1.5 MB)
Collecting distlib
  Using cached distlib-0.3.2-py2.py3-none-any.whl (338 kB)
Collecting tqdm
  Using cached tqdm-4.61.0-py2.py3-none-any.whl (75 kB)
Collecting joblib
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting regex
  Using cached regex-2021.4.4-cp39-cp39-manylinux2014_x86_64.whl (730 kB)
Collecting click
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Installing collected packages: tqdm, regex, joblib, click, nltk, distlib
Successfully installed click-8.0.1 distlib-0.3.2 joblib-1.0.1 nltk-3.6.2 regex-2021.4.4 tqdm-4.61.0
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/tmp/venv2/bin/python -m pip install --upgrade pip' command.
$ python -c "import distlib.database; distlib.database.DistributionPath().get_distribution('nltk')"
Traceback (most recent call last):
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/metadata.py", line 677, in __init__
    self._data = json.loads(data)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/database.py", line 240, in get_distribution
    self._generate_cache()
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/database.py", line 167, in _generate_cache
    for dist in self._yield_distributions():
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/database.py", line 148, in _yield_distributions
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/metadata.py", line 686, in __init__
    self._legacy = LegacyMetadata(fileobj=StringIO(data),
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/metadata.py", line 261, in __init__
    self.read_file(fileobj)
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/metadata.py", line 359, in read_file
    self.set(field, value)
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/metadata.py", line 459, in set
    if not scheme.is_valid_constraint_list(value):
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/version.py", line 716, in is_valid_constraint_list
    return self.is_valid_matcher('dummy_name (%s)' % s)
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/version.py", line 703, in is_valid_matcher
    self.matcher(s)
  File "/tmp/venv2/lib/python3.9/site-packages/distlib/version.py", line 115, in __init__
    raise ValueError('\'.*\' not allowed for '
ValueError: '.*' not allowed for '>=' constraints
```

As you can see, the error is not very readable and when you try to get all distributions, you end up having to dig up which package causes it (and how because it's not even clear that it is because of `python_requires`).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mgorny** [comment]
Another example of package with broken metadata is openpyxl, that uses:
```
    python_requires=">=3.6, ",
```
