### ISSUE TITLE
[FEATURE] Allow paths outiside of the source code for long_description

### ISSUE THREAD

**Issue by airvzxf** [pypa/setuptools#2699]
### setuptools version

setuptools>=57.0.0

### Python version

Python 3.9

### OS

Arch Linux

### Additional environment information

It happens when I try to use a README.md file outside the source folder.

### Description

In the file `setup.cfg`, when I try to use the read me file `../README.md` it is not working.

Error: 
```text
distutils.errors.DistutilsOptionError: `file:` directive can not access /home/wolf/workspace/projects/sniparinject/README.md

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist
```

The file exists, looks the parsing of the `setup.cfg` is not recognized in the paths outside the source code, for example `../README.md` is not working but `./other_folder/README.md` works.

I found this issue https://github.com/pypa/setuptools/issues/1635, which was related to my problem, but I am not agreed. 

### Expected behavior

Same as the `setup.py`, which recognize the paths outside the source code.

```python
import setuptools

with open('../README.md', 'r', encoding="utf-8") as fh:
    long_description = fh.read()

setuptools.setup(
    long_description=long_description,
)
```

### How to Reproduce

```bash
git clone --no-checkout https://github.com/airvzxf/sniparinject.git
cd sniparinject || exit 123
git checkout af2215e3661e06c2d2569949d9b19f6f549a90e8

./script/setup-dev.bash

# Display read me file.
ls -lha README.md

cd ./src || exit

# Display read me file.
ls -lha ../README.md

# Check if the setup cfg has the parameter: long_description = file: ../README.md
cat setup.cfg

rm -fR build dist ./*.egg-info
source ../venv/bin/activate
python3 -m pip install --upgrade pip build twine
python3 -m build
```

### Output

```console
/home/wolf/workspace/projects/sniparinject/script/pypi-build.bash

CURRENT_PATH=$(dirname "${0}")
cd "${CURRENT_PATH}" || exit

cd ../src || exit
rm -fR build dist ./*.egg-info
source ../venv/bin/activate
# This file must be used with "source bin/activate" *from bash*
# you cannot run it directly

deactivate () {
    # reset old environment variables
    if [ -n "${_OLD_VIRTUAL_PATH:-}" ] ; then
        PATH="${_OLD_VIRTUAL_PATH:-}"
        export PATH
        unset _OLD_VIRTUAL_PATH
    fi
    if [ -n "${_OLD_VIRTUAL_PYTHONHOME:-}" ] ; then
        PYTHONHOME="${_OLD_VIRTUAL_PYTHONHOME:-}"
        export PYTHONHOME
        unset _OLD_VIRTUAL_PYTHONHOME
    fi

    # This should detect bash and zsh, which have a hash command that must
    # be called to get it to forget past commands.  Without forgetting
    # past commands the $PATH changes we made may not be respected
    if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ] ; then
        hash -r 2> /dev/null
    fi

    if [ -n "${_OLD_VIRTUAL_PS1:-}" ] ; then
        PS1="${_OLD_VIRTUAL_PS1:-}"
        export PS1
        unset _OLD_VIRTUAL_PS1
    fi

    unset VIRTUAL_ENV
    if [ ! "${1:-}" = "nondestructive" ] ; then
    # Self destruct!
        unset -f deactivate
    fi
}

# unset irrelevant variables
deactivate nondestructive

VIRTUAL_ENV="/home/wolf/workspace/projects/sniparinject/venv"
export VIRTUAL_ENV

_OLD_VIRTUAL_PATH="$PATH"
PATH="$VIRTUAL_ENV/bin:$PATH"
export PATH

# unset PYTHONHOME if set
# this will fail if PYTHONHOME is set to the empty string (which is bad anyway)
# could use `if (set -u; : $PYTHONHOME) ;` in bash
if [ -n "${PYTHONHOME:-}" ] ; then
    _OLD_VIRTUAL_PYTHONHOME="${PYTHONHOME:-}"
    unset PYTHONHOME
fi

if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT:-}" ] ; then
    _OLD_VIRTUAL_PS1="${PS1:-}"
    PS1="(venv) ${PS1:-}"
    export PS1
fi

# This should detect bash and zsh, which have a hash command that must
# be called to get it to forget past commands.  Without forgetting
# past commands the $PATH changes we made may not be respected
if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ] ; then
    hash -r 2> /dev/null
fi
python3 -m pip install --upgrade pip build twine
Requirement already satisfied: pip in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (21.1.2)
Requirement already satisfied: build in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (0.4.0)
Requirement already satisfied: twine in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (3.4.1)
Requirement already satisfied: pep517>=0.9.1 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from build) (0.10.0)
Requirement already satisfied: packaging>=19.0 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from build) (20.9)
Requirement already satisfied: toml>=0.10.0 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from build) (0.10.2)
Requirement already satisfied: pyparsing>=2.0.2 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from packaging>=19.0->build) (2.4.7)
Requirement already satisfied: colorama>=0.4.3 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from twine) (0.4.4)
Requirement already satisfied: requests-toolbelt!=0.9.0,>=0.8.0 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from twine) (0.9.1)
Requirement already satisfied: rfc3986>=1.4.0 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from twine) (1.5.0)
Requirement already satisfied: tqdm>=4.14 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from twine) (4.61.1)
Requirement already satisfied: pkginfo>=1.4.2 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from twine) (1.7.0)
Requirement already satisfied: readme-renderer>=21.0 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from twine) (29.0)
Requirement already satisfied: requests>=2.20 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from twine) (2.25.1)
Requirement already satisfied: keyring>=15.1 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from twine) (23.0.1)
Requirement already satisfied: importlib-metadata>=3.6 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from twine) (4.5.0)
Requirement already satisfied: zipp>=0.5 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from importlib-metadata>=3.6->twine) (3.4.1)
Requirement already satisfied: SecretStorage>=3.2 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from keyring>=15.1->twine) (3.3.1)
Requirement already satisfied: jeepney>=0.4.2 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from keyring>=15.1->twine) (0.6.0)
Requirement already satisfied: docutils>=0.13.1 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from readme-renderer>=21.0->twine) (0.17.1)
Requirement already satisfied: bleach>=2.1.0 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from readme-renderer>=21.0->twine) (3.3.0)
Requirement already satisfied: six in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from readme-renderer>=21.0->twine) (1.16.0)
Requirement already satisfied: Pygments>=2.5.1 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from readme-renderer>=21.0->twine) (2.9.0)
Requirement already satisfied: webencodings in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from bleach>=2.1.0->readme-renderer>=21.0->twine) (0.5.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from requests>=2.20->twine) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from requests>=2.20->twine) (1.26.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from requests>=2.20->twine) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from requests>=2.20->twine) (2.10)
Requirement already satisfied: cryptography>=2.0 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from SecretStorage>=3.2->keyring>=15.1->twine) (3.4.7)
Requirement already satisfied: cffi>=1.12 in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine) (1.14.5)
Requirement already satisfied: pycparser in /home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine) (2.20)
python3 -m build
Found existing installation: setuptools 56.0.0
Uninstalling setuptools-56.0.0:
  Successfully uninstalled setuptools-56.0.0
Collecting wheel>=0.36.2
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting pip>=21.1.2
  Using cached pip-21.1.2-py3-none-any.whl (1.5 MB)
Collecting setuptools>=57.0.0
  Using cached setuptools-57.0.0-py3-none-any.whl (821 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
      Successfully uninstalled pip-21.1.1
Successfully installed pip-21.1.2 setuptools-57.0.0 wheel-0.36.2
Traceback (most recent call last):
  File "/home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File "/home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/wolf/workspace/projects/sniparinject/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 219, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/dist.py", line 772, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/config.py", line 157, in parse_configuration
    meta.parse()
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/config.py", line 463, in parse
    section_parser_method(section_options)
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/config.py", line 436, in parse_section
    self[name] = value
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/config.py", line 220, in __setitem__
    value = parser(value)
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/config.py", line 330, in _parse_file
    return '\n'.join(
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/config.py", line 333, in <genexpr>
    if (cls._assert_local(path) or True)
  File "/tmp/build-env-kalupbcw/lib/python3.9/site-packages/setuptools/config.py", line 340, in _assert_local
    raise DistutilsOptionError(
distutils.errors.DistutilsOptionError: `file:` directive can not access /home/wolf/workspace/projects/sniparinject/README.md

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist

Process finished with exit code 1
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by webknjaz** [comment]
As I mentioned in the related PR. This doesn't sound like a bug but rather is a security-related sandboxing feature.

**Comment by airvzxf** [comment]
Well, the first time it happen to me, I assumed that it was a defect, then investigating and check this logic was intentionally. Let's continue the discussion in the PR.

**Comment by jaraco** [comment]
See the comments in the PR for more background on why this is not a good idea.
