### ISSUE TITLE
[BUG] `file:` for `[metadata]version` declarative config breaks for PEP 517 builder

### ISSUE THREAD

**Issue by lmmarsano** [pypa/setuptools#2719]
### setuptools version

57.1.0

### Python version

3.9.4

### OS

Linux

### Description

For a `setup.cfg` with `[metadata]version` line
https://github.com/lmmarsano/setuptools-demo/blob/8830f58cfe98168a5b62f9169553897fe6e4c93b/setup.cfg#L3
and `VERSION` file
https://github.com/lmmarsano/setuptools-demo/blob/8830f58cfe98168a5b62f9169553897fe6e4c93b/VERSION
`python -m build` raises an exception.
```console
distutils.errors.DistutilsOptionError: Version loaded from file: VERSION does not comply with PEP 440: 

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```

### Expected behavior

Successful exit code.

### How to Reproduce

```shell
git clone https://github.com/lmmarsano/setuptools-demo.git
cd setuptools-demo
python -m venv --upgrade-deps .venv
. .venv/bin/activate
pip install -U build
python -m build
```

### Output

Output that includes traceback
```console
Installing collected packages: setuptools, wheel
Successfully installed setuptools-57.1.0 wheel-0.36.2
WARNING: You are using pip version 20.2.3; however, version 21.1.3 is available.
You should consider upgrading via the '/tmp/build-env-tcsoswid/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/home/LOM0227/project/setuptools-test/.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File "/home/LOM0227/project/setuptools-test/.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/LOM0227/project/setuptools-test/.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 4, in <module>
    ST.setup()
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/LOM0227/.pyenv/versions/miniconda3-latest/lib/python3.9/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/dist.py", line 778, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/config.py", line 157, in parse_configuration
    meta.parse()
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/config.py", line 463, in parse
    section_parser_method(section_options)
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/config.py", line 436, in parse_section
    self[name] = value
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/config.py", line 220, in __setitem__
    value = parser(value)
  File "/tmp/build-env-tcsoswid/lib/python3.9/site-packages/setuptools/config.py", line 553, in _parse_version
    raise DistutilsOptionError(tmpl.format(**locals()))
distutils.errors.DistutilsOptionError: Version loaded from file: VERSION does not comply with PEP 440: 

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @lmmarsano, I think the error message here is misleading...

What seems to be happening is that the file `VERSION` is not included in the built package, so setuptools cannot read its content and ends up with an empty version.

You need to make sure the `VERSION` file is included by either using a plugin such as [`setuptools-scm`](https://pypi.org/project/setuptools-scm/) or by [writing a `MANIFEST.in` file](https://packaging.python.org/en/latest/guides/using-manifest-in/).

**Comment by lmmarsano** [comment]
@abravalheri Confirmed: duplicating `file:` directive values in `MANIFEST.in` resolves build failure.

Is automatically including `file:` directive values beyond the realm of possibility for `setuptools` with PEP 517 builder?
It would seem reasonable to expect that.

**Comment by abravalheri** [comment]
Glad to here it works for you 😄 

> Is automatically including files listed as file: directive values beyond the realm of possibility for setuptools with PEP 517 builder?

Wheel, everything is possible if you throw enough code at it... It might not be worth the complexity though...
Would you like to give it a shot? I am more than happy to review a PR.

Personally, I would encourage people to use the correct plugin for their VCS system (e.g. `setuptools-scm` for git). This solves a lot of problems and makes the VCS the single source of truth...
