### ISSUE TITLE
[BUG] v57.1.0 on Python v3.6 SSL Errors

### ISSUE THREAD

**Issue by philthompson10** [pypa/setuptools#2728]
### setuptools version

57.1.0

### Python version

3.6

### OS

macOS, Windows

### Additional environment information

The problem doesn't seem to occur on Linux. setuptools v57.0.0 works fine.

### Description

Running "python setup.py install" on my project fails to install the project's dependencies from PyPI.

### Expected behavior

Normal installation.

### How to Reproduce

python setup.py install

### Output

```Processing dependencies for sip==6.2.0.dev2107131757
Searching for toml
Reading https://pypi.org/simple/toml/
Download error on https://pypi.org/simple/toml/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748) -- Some packages may not be found!
Couldn't find index page for 'toml' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748) -- Some packages may not be found!
No local packages or working download links found for toml
error: Could not find suitable distribution for Requirement.parse('toml')
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by domdfcoding** [comment]
Out of curiosity why are you running `setup.py install` rather than using `pip install`? Can you try with pip and see if you get the same error?

**Comment by philthompson10** [comment]
On 15/07/2021 17:12, Dominic Davis-Foster wrote:
> Out of curiosity why are you running `setup.py install` rather than
> using `pip install`? Can you try with pip and see if you get the same
> error?

I'm using it for historical reasons - it's always worked before.

'pip install .' does work, although with a deprecation warning for 
v21.3. I assume there is a more up to date command I could use to get 
rid of that warning.

**Comment by jaraco** [comment]
The reason it stopped working is #2715. Python has deprecated the functionality that Setuptools previously depended on to perform downloads safely. Now instead, Setuptools defers entirely to the default Python implementation to open URLs.

The underlying error can be replicated very simply:

```
$ python3.6 -c "import urllib.request; urllib.request.urlopen('https://pypi.org')"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
```

I'm able to work around the error readily by installing the certifi package:

```
$ python3.6 -m pip install -q certifi
$ python3.6 -c "import urllib.request; urllib.request.urlopen('https://pypi.org')" && echo 'works!'
works!
```

So it seems to me you have several options (in my recommended order of preference):

1. Use pip to install.
2. Update your environments to include `certifi` in them.
3. Pin to older Setuptools.
4. Develop an extension to Setuptools that 

Setuptools plans to drop support for easy_install (and setup.py install) soon, so you'll probably want to work out a solution that avoids those code paths sooner than later.

Sorry for the inconvenience.
