### ISSUE TITLE
[BUG] Can't use cmdclass in setup.cfg for babel

### ISSUE THREAD

**Issue by kujiu** [pypa/setuptools#2738]
### setuptools version

57.4.0

### Python version

3.9

### OS

Debian Sid

### Additional environment information

babel in version 2021.1

### Description

Using cmdclass in setup.cfg with babel fails with an AttributeError.

It seems to be a problem in config.py with the use of discouraged ```__import__``` method. Replacing ```__import__``` by importlib.import_module seems to work on line 614. ```__import__``` does not have always the expected behavior (like with babel).

```
>>> __import__('babel.messages.frontend').__name__
'babel'
>>> import importlib
>>> importlib.import_module('babel.messages.frontend').__name__
'babel.messages.frontend'
```

### Expected behavior

I expect to have a built package with support of babel.

### How to Reproduce

1. Create a setup.cfg file with no setup.py, add babel as dependency.
2. Add following cmdclass in [options] section:
```
   cmdclass =
       compile_catalog = babel.messages.frontend.compile_catalog
       extract_messages = babel.messages.frontend.extract_messages
       init_catalog = babel.messages.frontend.init_catalog
       update_catalog = babel.messages.frontend.update_catalog                 
```
3. Launch ```python3 -m build -s```

### Output

```console
>>> python3 -m build . -o ./dist -sn
Traceback (most recent call last):
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 349, in <module>
    main()
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 301, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/build_meta.py", line 225, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
    self.run_setup()
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/_virtualenv.py", line 21, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/dist.py", line 778, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/config.py", line 152, in parse_configuration
    options.parse()
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/config.py", line 463, in parse
    section_parser_method(section_options)
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/config.py", line 436, in parse_section
    self[name] = value
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/config.py", line 220, in __setitem__
    value = parser(value)
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/config.py", line 616, in _parse_cmdclass
    return {
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/config.py", line 617, in <dictcomp>
    k: resolve_class(v)
  File "/home/kujiu/nervtnvenv/lib/python3.9/site-packages/setuptools/config.py", line 614, in resolve_class
    return getattr(module, class_name)
AttributeError: module 'babel' has no attribute 'compile_catalog'
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @kujiu, would it be possible for you to check if [this experimental branch](https://github.com/pypa/setuptools/tree/separte-setup-cfg-config) works for your package?

To do that you have to modify your `pyproject.toml` to get setuptools directly from github:

```toml
[build-system]
requires = [
    "setuptools @ git+https://github.com/pypa/setuptools@separte-setup-cfg-config",
    ...
]
```

**Comment by kujiu** [comment]
Sorry for the delay, I did a burnout. I write this issue when it was not possible to include babel config in a pyproject.toml.

 All works fine now.
