### ISSUE TITLE
[BUG] set object has no attribute get

### ISSUE THREAD

**Issue by DarkPhily** [pypa/setuptools#2794]
### setuptools version

setuptools==57.0.0

### Python version

Python 3.8

### OS

Ubuntu & Windows

### Description

I tried to create a package from my project.

### Expected behavior

The necessary files would be created to be able to install the project easily via pip.

### How to Reproduce

1. Type `python setup.py bdist_wheel` into the terminal
[setup.txt](https://github.com/pypa/setuptools/files/7192439/setup.txt)
l

### Output

```console
running bdist_wheel
running build
installing to build/bdist.linux-x86_64/wheel
running install
running install_data
running install_egg_info
Traceback (most recent call last):
  File "/home/-/Git/switchmanager/setup.py", line 5, in <module>
    setup(
  File "/home/-/Git/switchmanager/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/-/Git/switchmanager/venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 335, in run
    self.run_command('install')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/-/Git/switchmanager/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib/python3.8/distutils/command/install.py", line 601, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/-/Git/switchmanager/venv/lib/python3.8/site-packages/setuptools/command/install_egg_info.py", line 25, in finalize_options
    ei_cmd = self.get_finalized_command("egg_info")
  File "/usr/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/-/Git/switchmanager/venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
    self.egg_base = (dirs or {}).get('', os.curdir)
AttributeError: 'set' object has no attribute 'get'
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
I can see from the traceback, the egg_info command is attempting to invoke `dirs.get()` where `dirs = self.distribution.package_dir`. I'm pretty sure the issue here is that the `setup.py` script is setting `package_dir` to a `set` object instead of a dict [as documented](https://docs.python.org/3/distutils/setupscript.html#listing-whole-packages).

**Comment by jaraco** [comment]
To be sure, the behavior could be improved and provide a nicer error message, but this project currently has some higher priority goals (namely, adopting distutils).
