### ISSUE TITLE
[BUG] setuptools 58.5 breaks installation of docutils==0.10.0

### ISSUE THREAD

**Issue by anntzer** [pypa/setuptools#2849]
### setuptools version

58.5.{0,1}

### Python version

3.9

### OS

Arch Linux

### Description

Installing docutils==0.10 in a clean venv with setuptools 58.5.{0,1} fails with an internal(?) AttributeError.

### Expected behavior

Successful installation.

### How to Reproduce

```sh
python -mvenv /tmp/testenv && source /tmp/testenv/bin/activate &&
  pip install -U pip setuptools wheel && pip install docutils==0.10
```
(To repro the issue, you may need to `pip cache purge` first if you happen to already have a wheel for docutils==0.10 in your pip cache.)

### Output

```console
  ERROR: Command errored out with exit status 1:
   command: /tmp/testenv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r8b4xqgi/docutils_459783958fce4136b27e3bc6ec961dba/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r8b4xqgi/docutils_459783958fce4136b27e3bc6ec961dba/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_qz_txff
       cwd: /tmp/pip-install-r8b4xqgi/docutils_459783958fce4136b27e3bc6ec961dba/
  Complete output (35 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-_qz_txff/docutils.egg-info
  writing /tmp/pip-pip-egg-info-_qz_txff/docutils.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-_qz_txff/docutils.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-pip-egg-info-_qz_txff/docutils.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-_qz_txff/docutils.egg-info/SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-r8b4xqgi/docutils_459783958fce4136b27e3bc6ec961dba/setup.py", line 221, in <module>
      do_setup()
    File "/tmp/pip-install-r8b4xqgi/docutils_459783958fce4136b27e3bc6ec961dba/setup.py", line 98, in do_setup
      dist = setup(**kwargs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/testenv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 299, in run
      self.find_sources()
    File "/tmp/testenv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
      mm.run()
    File "/tmp/testenv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 541, in run
      self.add_defaults()
    File "/tmp/testenv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
      sdist.add_defaults(self)
    File "/usr/lib/python3.9/distutils/command/sdist.py", line 226, in add_defaults
      self._add_defaults_python()
    File "/tmp/testenv/lib/python3.9/site-packages/setuptools/command/sdist.py", line 113, in _add_defaults_python
      self._add_data_files(self._safe_data_files(build_py))
    File "/tmp/testenv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 621, in _safe_data_files
      return build_py.get_data_files_without_manifest()
    File "/usr/lib/python3.9/distutils/cmd.py", line 103, in __getattr__
      raise AttributeError(attr)
  AttributeError: get_data_files_without_manifest
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/66/40/2b11ec2ec96d527ef933332a5847cc90860fd8bbee46da2cc468794ea25b/docutils-0.10.tar.gz#sha256=370624e61b6773da2f2fb17cc2a4eaea4bb596c3585d13f75ff193c1c738603e (from https://pypi.org/simple/docutils/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement docutils==0.10 (from versions: 0.3, 0.3.5, 0.3.7, 0.3.9, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.9, 0.9.1, 0.10, 0.11, 0.12, 0.13.1, 0.14rc1, 0.14rc2, 0.14, 0.15, 0.15.1.post1, 0.15.2, 0.16b0.dev0, 0.16rc1, 0.16, 0.17b1, 0.17, 0.17.1b1.dev0, 0.17.1, 0.18b1, 0.18)
ERROR: No matching distribution found for docutils==0.10
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jerryz1982** [comment]
breaks pycrypto too

**Comment by jiasli** [comment]
Breaks `python setup.py bdist_wheel -d build`:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1178162&view=logs&jobId=e725b3e9-648f-510f-a0a1-f18bdc151d12&j=e725b3e9-648f-510f-a0a1-f18bdc151d12&t=7dda8e6e-5520-5cbf-e881-69c151aecb23

```
Traceback (most recent call last):
  File "/home/vsts/work/1/s/src/azure-cli/setup.py", line 160, in <module>
    setup(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in setup
    return distutils.core.setup(**attrs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 335, in run
    self.run_command('install')
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
    return orig.install.run(self)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/distutils/command/install.py", line 558, in run
    self.run_command(cmd_name)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
```

**Comment by abravalheri** [comment]
This seems to be related to the replacement of https://github.com/pypa/setuptools/commit/8a0e63a586674676fa13b0ee4cfde46228f8a266 with https://github.com/pypa/setuptools/commit/b6ce5368a439ad55cd1ada777676f387be895946.

Those entry-points should point to the setuptools version of the commands, but for some reason, the original distutils commands are being used instead.

**Comment by nshgraph** [comment]
This appears to be a breaking change introduced in https://github.com/pypa/setuptools/commit/2e66eb7147ae1e8a799b2276c7340f48f63a7220 when custom commands are used as it forces the new function `get_data_files_without_manifest` to be present.

**Comment by jjerphan** [comment]
> This appears to be a breaking change introduced in [2e66eb7](https://github.com/pypa/setuptools/commit/2e66eb7147ae1e8a799b2276c7340f48f63a7220) when custom commands are used as it forces the new function `get_data_files_without_manifest` to be present.

I confirm that compiling at 1812f8db08e32c72b4e1e419ad178ed0e66b2958 works but at 2e66eb7 fails (tested on scikit-learn).

**Comment by Alphare** [comment]
Also breaks install for Mercurial: https://foss.heptapod.net/mercurial/mercurial-devel/-/jobs/260776#L53

**Comment by abravalheri** [comment]
I think we have 2 separated problems here:

1. If packages define their own `build_py` inheriting from `distutils` instead of setuptools, and don't define a `get_data_files_without_manifest`, there will be a problem.

2. Installing `sdist` packages with pip might result in error, since the `distutils` version of `build_py` is being used instead of the `setuptools` version.
   This can be reproduced with `docutils==0.10.0`.
   Interestingly, `pypa/build` isolated environments don't seem to have the same problem.
   This second issue seems more difficult to track down.

**Comment by anntzer** [comment]
I certainly can, this was just a version I had pinned in CI to test an "oldest-supported-version-of-dependency" for another package.  I guess the other commenters here may want a more robust solution, though...

**Comment by abravalheri** [comment]
> I certainly can, this was just a version I had pinned in CI to test an "oldest-supported-version-of-dependency" for another package. I guess the other commenters here may want a more robust solution, though...

Yes, I understand that.

I am having a look to try to identify what can be done:

- Some packages listed here use `build_py_2to3` (e.g. docutils, pycrypto)
- Others define a custom `build_py` inheriting directly from `distutils` (e.g. pycryptodome)
- There is a third case that I am still trying to find a connection. This is the case of packages that redefine `build_ext` or `sdist` but not `build_py`.

**Comment by abravalheri** [comment]
Guys, I submitted a PR with a fix for that, let's see what the maintainers think.

However if anyone wants to contribute with other **unit** tests, that would be awesome! (so we prevent changes like this in the future)

Some people suggested trying to install entire packages directly, but I am afraid that would be a kind of integration test that needs more discussion. I also asked about this approach in the PR.

**Comment by jaraco** [comment]
I'll review this tonight and get out a fix or yank the release. Thanks for your patience through this unintentional disruption.
