### ISSUE TITLE
[BUG] `python setup.py install` doesn't preserve file permissions when install dependencies as egg

### ISSUE THREAD

**Issue by sighingnow** [pypa/setuptools#2864]
### setuptools version

setuptools==58.2.0

### Python version

Python 3.9

### OS

Linux

### Description

When installing a package using `python3 setup.py install --user` to install a package, if there are exectable in its dependencies, the `exec` permission bit will be discarded.

It is caused by the usage of `zipfile.ZipFile.extractall` to install wheels as `egg`,

https://github.com/pypa/setuptools/blob/8af23a41194ae747faf3e60f9cc19141b5e7ad24/setuptools/wheel.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L125

However the `ZipFile.extractall` is known to have bug that cannot perserve file permissions, see also https://bugs.python.org/issue15795.

It if can be confirmed as a bug of setuptools, I could submit a PR then.

### Expected behavior

The file permission in installed `egg` should be consistent with the permission bits in wheel package.

### How to Reproduce

1. prepare a `setup.py` file:

```
from setuptools import setup

setup(
    name="deps-no-permission-issue",
    install_requires=["cmake"],
)
```

2. run `python3 setup.py install --user`
3. run `$HOME/.local/bin/cmake`

### Output

It will fail to execute as permission denied:

```console
[graphscope@76e7c3cfda7b ~]$ ~/.local/bin/cmake
Traceback (most recent call last):
  File "/home/graphscope/.local/bin/cmake", line 33, in <module>
    sys.exit(load_entry_point('cmake==3.21.4', 'console_scripts', 'cmake')())
  File "/home/graphscope/.local/lib/python3.9/site-packages/cmake-3.21.4-py3.9-linux-x86_64.egg/cmake/__init__.py", line 47, in cmake
    raise SystemExit(_program('cmake', sys.argv[1:]))
  File "/home/graphscope/.local/lib/python3.9/site-packages/cmake-3.21.4-py3.9-linux-x86_64.egg/cmake/__init__.py", line 43, in _program
    return subprocess.call([os.path.join(CMAKE_BIN_DIR, name)] + args)
  File "/opt/python/cp39-cp39/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/python/cp39-cp39/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/python/cp39-cp39/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/graphscope/.local/lib/python3.9/site-packages/cmake-3.21.4-py3.9-linux-x86_64.egg/cmake/data/bin/cmake'
```

However if we uninstall `cmake`, and first `python3 setup.py bdist_wheel`, then install the generated wheel under `dist/`, and `$HOME/.local/bin/cmake` will run as expected:

```
[graphscope@76e7c3cfda7b ~]$ $HOME/.local/bin/cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Setuptools has deprecated `setup.py install`. Please use `pip install --user .` instead. I expect that will also address your issue.

**Comment by sighingnow** [comment]
> Setuptools has deprecated `setup.py install`. Please use `pip install --user .` instead. I expect that will also address your issue.

Thanks for the information!
