### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pawl** [pypa/setuptools#2936]
### setuptools version

v59.8.0

### Python version

3.8.12

### OS

Ubuntu 21.04

### Description

Until recently, [kombu](https://github.com/celery/kombu/pull/1467) was using some code like [this hack](https://stackoverflow.com/a/3042436) to copy data files into the module directory. 

Now we're seeing this error:
```
Traceback (most recent call last):
File "setup.py", line 60, in
scheme['data'] = scheme['purelib']
KeyError: 'purelib'
```

Because in v59.8.0 `osx_framework_user` [was added to](https://github.com/pypa/setuptools/commit/f32af4e73a3f994f3a76898bb404919c5722508d) `INSTALL_SCHEMES` and it doesn't defined the purelib part of the dict.

Should that new `osx_framework_user` have purelib defined? If it's not necessary, maybe it's best these old hacks break and requiring changing code to use `MANIFEST.in` like this other SO post suggests?: https://stackoverflow.com/a/1857436

### Expected behavior

That new `osx_framework_user` in `INSTALL_SCHEMES` should have purelib defined?

### How to Reproduce

Run:
```
from distutils.command.install import INSTALL_SCHEMES

for scheme in list(INSTALL_SCHEMES.values()):
    scheme['data'] = scheme['purelib']
```
on v59.8.0

### Output

```console
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
KeyError: 'purelib'
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Thank you for the report. The reason that only headers is defined for osx framework user is because that scheme is meant to extend a scheme in sysconfig and is only relevant if that scheme is in sysconfig. It would be possible to add a full copy of what is likely found in sysconfig in order to meet the expectations of the aforementioned hack.

My preference would be for the hack to adjust its expectations or to remove the hack altogether if possible, but I realize that may not be possible in all scenarios.

How much disruption would it be to leave the issue in place given there are workarounds, such as pinning old Setuptools or using SETUPTOOLS_USE_DISTUTILS=stdlib in affected environments?
