### ISSUE TITLE
[BUG] python setup.py develop --user is broken on linux

### ISSUE THREAD

**Issue by liuzhe-lz** [pypa/setuptools#2937]
### setuptools version

60.0.0

### Python version

3.10 & 3.8

### OS

Arch Linux & Ubuntu

### Description

`python setup.py develop --user` is broken on Linux.

setuptools 60.0 overrides distutils with its built-in version, and unfortunately this version is not compatible with easy_install.

### Expected behavior

It should just work.

### How to Reproduce

Write a simple setup.py:
```python
from setuptools import setup
setup(name='hello', version='1.0')
```

Install it:
```bash
python setup.py develop --user
```

### Output

```console
running develop
/home/USER/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/PATH/TO/setup.py", line 2, in <module>
    setup(name='hello', version='1.0')
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 985, in run_command
    cmd_obj.ensure_finalized()
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 52, in finalize_options
    easy_install.finalize_options(self)
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 263, in finalize_options
    self._fix_install_dir_for_user_site()
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 375, in _fix_install_dir_for_user_site
    self.select_scheme(scheme_name)
  File "/home/USER/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 716, in select_scheme
    scheme = INSTALL_SCHEMES[name]
KeyError: 'unix_user'
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Although you filed first, I’m going to dedupe with #2938 .
