### ISSUE TITLE
[BUG] pkg_resources do not handle "new" escaping of .dist-info names correctly

### ISSUE THREAD

**Issue by mgorny** [pypa/setuptools#3146]
### setuptools version

60.9.3

### Python version

3.8.12

### OS

Gentoo Linux

### Description

The [wheel spec](https://packaging.python.org/en/latest/specifications/binary-distribution-format/) says:

> In distribution names, any run of -_. characters (HYPHEN-MINUS, LOW LINE and FULL STOP) should be replaced with _ (LOW LINE), and uppercase characters should be replaced with corresponding lowercase ones. This is equivalent to [PEP 503](https://www.python.org/dev/peps/pep-0503) normalisation followed by replacing - with _. Tools consuming wheels must be prepared to accept . (FULL STOP) and uppercase letters, however, as these were allowed by an earlier version of this specification.

However, pkg_resources doesn't seem to correctly handle package names containing `.` if it is escaped into `_`.

### Expected behavior

```
>>> import pkg_resources
>>> pkg_resources.require('jaraco.functools')
[jaraco.functools 3.5.0 (/tmp/.venv/lib/python3.8/site-packages), more-itertools 8.12.0 (/tmp/.venv/lib/python3.8/site-packages)]
```

### How to Reproduce

This is a simple reproducer on top of a package using setuptools (that doesn't escape full stop according to the current version of the spec). This e.g. happens to packages using flit build system but I don't know any published flit wheels that are affected by this.

```
python -m venv .venv
. .venv/bin/activate
pip install -U setuptools jaraco.functools
# correct the dist-info name
mv .venv/lib/python3.8/site-packages/jaraco.functools-3.5.0.dist-info .venv/lib/python3.8/site-packages/jaraco_functools-3.5.0.dist-info
python -c 'import pkg_resources; pkg_resources.require("jaraco.functools")'
```

### Output

```console
$ python -m venv .venv
$ . .venv/bin/activate
(.venv) $ pip install -U setuptools jaraco.functools
Requirement already satisfied: setuptools in ./.venv/lib/python3.8/site-packages (56.0.0)
Collecting setuptools
  Using cached setuptools-60.9.3-py3-none-any.whl (1.1 MB)
Collecting jaraco.functools
  Using cached jaraco.functools-3.5.0-py3-none-any.whl (7.0 kB)
Collecting more-itertools
  Using cached more_itertools-8.12.0-py3-none-any.whl (54 kB)
Installing collected packages: more-itertools, setuptools, jaraco.functools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
Successfully installed jaraco.functools-3.5.0 more-itertools-8.12.0 setuptools-60.9.3
WARNING: You are using pip version 21.1.1; however, version 22.0.3 is available.
You should consider upgrading via the '/tmp/.venv/bin/python -m pip install --upgrade pip' command.
(.venv) $ mv .venv/lib/python3.8/site-packages/jaraco.functools-3.5.0.dist-info .venv/lib/python3.8/site-packages/jaraco_functools-3.5.0.dist-info
(.venv) $ python -c 'import pkg_resources; pkg_resources.require("jaraco.functools")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/tmp/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jaraco.functools' distribution was not found and is required by the application
```

**Comment by abravalheri** [comment]
Hi @mgorny, any chance this might have been fixed via #3153?

**Comment by Avasam** [comment]
setuptools no longer uses pkg_resources, are you still encountering this issue ? (issue might need to be updated)

**Comment by jaraco** [comment]
pkg_resources has long been deprecated and is now being removed. Closing as obsolete.
