### ISSUE TITLE
[BUG] test_pip_upgrade_from_source fails if no internet connection is available

### ISSUE THREAD

**Issue by befeleme** [pypa/setuptools#3149]
### setuptools version

60.9.3

### Python version

Python 3.10.2

### OS

Fedora Linux 35

### Additional environment information

This happens when no internet connection is available.

### Description

There is a [test_pip_upgrade_from_source](https://github.com/pypa/setuptools/blob/main/setuptools/tests/test_virtualenv.py#L84) that parametrizes pip versions and tries to detect whether the network is available or not (in that case the test is skipped). But, the network test and resulting skip is only performed for the pips in `network_versions`, not for the first case with [None](https://github.com/pypa/setuptools/blob/main/setuptools/tests/test_virtualenv.py#L72). As a result the first test is always run and in no network environment fails as [pip install --upgrade](https://github.com/pypa/setuptools/blob/main/setuptools/tests/test_virtualenv.py#L102) spawns another virtual env with `build` and tries to install `wheel` from the package index to build sdist.

### Expected behavior

The "no network" marker should be extended to check all the parametrized inputs of the test.

### How to Reproduce

Install all required dependencies and run `test_virtualenv.py` in an environment without the internet connection.

### Output

```console
_____________ ERROR at setup of test_pip_upgrade_from_source[None] _____________

tmp_path_factory = TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x7f7b3b9f2f50>, _basetemp=PosixPath('/tmp/pytest-of-mockbuild/pytest-0'))
request = <SubRequest 'setuptools_sdist' for <Function test_pip_upgrade_from_source[None]>>

    @pytest.fixture(scope="session")
    def setuptools_sdist(tmp_path_factory, request):
        with contexts.session_locked_tmp_dir(
                request, tmp_path_factory, "sdist_build") as tmp:
            dist = next(tmp.glob("*.tar.gz"), None)
            if dist:
                return dist
    
>           subprocess.check_call([
                sys.executable, "-m", "build", "--sdist",
                "--outdir", str(tmp), str(request.config.rootdir)
            ])

setuptools/tests/fixtures.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/usr/bin/python3', '-m', 'build', '--sdist', '--outdir', '/tmp/pytest-of-mockbuild/pytest-0/sdist_build', ...],)
kwargs = {}, retcode = 1
cmd = ['/usr/bin/python3', '-m', 'build', '--sdist', '--outdir', '/tmp/pytest-of-mockbuild/pytest-0/sdist_build', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'build', '--sdist', '--outdir', '/tmp/pytest-of-mockbuild/pytest-0/sdist_build', '/builddir/build/BUILD/setuptools-60.9.3']' returned non-zero exit status 1.

/usr/lib64/python3.10/subprocess.py:369: CalledProcessError
---------------------------- Captured stdout setup -----------------------------
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 372, in main
    built = build_call(
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 202, in build_package
    out = _build(isolation, builder, outdir, distribution, config_settings, skip_dependency_check)
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 140, in _build
    return _build_in_isolated_env(builder, outdir, distribution, config_settings)
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 108, in _build_in_isolated_env
    env.install(builder.build_system_requires)
  File "/usr/lib/python3.10/site-packages/build/env.py", line 211, in install
    _subprocess(cmd)
  File "/usr/lib/python3.10/site-packages/build/env.py", line 81, in _subprocess
    raise e
  File "/usr/lib/python3.10/site-packages/build/env.py", line 78, in _subprocess
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/build-env-ely02ro0/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-8w8muu0c.txt']' returned non-zero exit status 1.

ERROR Command '['/tmp/build-env-ely02ro0/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-8w8muu0c.txt']' returned non-zero exit status 1.
---------------------------- Captured stderr setup -----------------------------
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb26da64df0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/wheel/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb26da654e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/wheel/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb26da655d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/wheel/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb26da65e40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/wheel/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb26e5560b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/wheel/
ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
ERROR: No matching distribution found for wheel

```

**Comment by abravalheri** [comment]
Hi @befeleme thank you very much for pointing that problem out.

So if I understood correctly the problem comes from these 2 lines right?

https://github.com/pypa/setuptools/blob/e30999503add90052a1bbf4526c3025baed947f7/setuptools/tests/test_virtualenv.py#L92

https://github.com/pypa/setuptools/blob/e30999503add90052a1bbf4526c3025baed947f7/setuptools/tests/test_virtualenv.py#L102

I wonder if could move the first line just before the second one, and just execute them together if the network is available...

**Comment by befeleme** [comment]
Hi, @abravalheri, do you have another suggestion? Skipping it altogether was the first thing that came to my mind seeing the network failure (that's what we're about to do in Fedora). Even if I point to an already pre-built sdist, the test will attempt to build a wheel from it, failing again on the `wheel` installation.

**Comment by abravalheri** [comment]
> *thinking*: We could skip the `wheel` update and trust the virtual environment to already have the wheel. However it is very likely that the `virtualenv` team will drop the behaviour of having the `wheel` installed by default at some point in the future.

The more stable solution would be also *XFAIL-ing* this test in case of no internet (we can mention #3149 and #2986[^1] in the reason).

@befeleme would you like to give it a try?


[^1]: As pointed out in #2986 in the case setuptools decides to vendor `wheel` or re-implement `bdist_wheel`, then `wheel` would be no longer a dependency for the build and therefore we could perform the test offline.

If at some point in time `setuptools` decide to vendor `wheel` (or re-implement the `bdist_wheel` command, then

**Comment by befeleme** [comment]
@abravalheri Thank you very much for taking this issue forward!
