### ISSUE TITLE
[BUG] Generated console scripts which depend on pkgs with dots in name fail if the dep was specified in setup.py with dashes instead

### ISSUE THREAD

**Issue by AndydeCleyre** [pypa/setuptools#3157]
### setuptools version

60.9.3

### Python version

3.9.7

### OS

Arch Linux

### Description

I think the issue is really that `dist.key`'s normalization should converge dots and dashes, as they are interchangeable.

When:
- a `setup.py` file specifies a "normally" dotted requirement (with a `.` in its name), but uses a dash instead
- that requirement is installed with `pip`

Then:
- the launcher exits early with an error because the deps don't match

I see in [docs/pkg_resources.rst](https://github.com/pypa/setuptools/blob/main/docs/pkg_resources.rst):

```rst
``dist.key`` is short for ``dist.project_name.lower()``. It's used for case-insensitive comparison and indexing of distributions by project name.
```

I think the following are relevant:

```python
In [1]: from pip._vendor.packaging.utils import canonicalize_name, _canonicalize_regex

In [2]: canonicalize_name??
Signature: canonicalize_name(name)
Docstring: <no docstring>
Source:
def canonicalize_name(name):
    # type: (str) -> NormalizedName
    # This is taken from PEP 503.
    value = _canonicalize_regex.sub("-", name).lower()
    return cast(NormalizedName, value)
File:      /usr/share/python-wheels/packaging-20.9-py2.py3-none-any.whl/packaging/utils.py
Type:      function

In [3]: _canonicalize_regex??
Type:        Pattern
String form: re.compile('[-_.]+')
File:        /usr/lib/python3.9/re.py
Docstring:   Compiled regular expression object.
```

### Expected behavior

I would expect the launch script to succeed, as installing `ruamel.yaml` (for example) is happily interchangeable with `ruamel-yaml` as far as `pip` is concerned. If one of these is installed, the requirement is truly met.

### How to Reproduce

```console
$ git clone https://github.com/laurence-kobold/1576
$ cd 1576
$ python3 -m venv venv
$ . ./venv/bin/activate
$ pip install .
$ test-with-editable-dots
```

### Output

```console
$ git clone https://github.com/laurence-kobold/1576
Cloning into '1576'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 19 (delta 2), reused 19 (delta 2), pack-reused 0
Receiving objects: 100% (19/19), done.
Resolving deltas: 100% (2/2), done.

$ cd 1576
$ cat setup.py
from distutils.core import setup

setup(
  name='testing_editable_dots',
  install_requires=["ruamel-yaml"],
  entry_points={
          "console_scripts": [
              "test-with-editable-dots=testing_editable_dots.main:main",
          ],
      },
)

$ python3 -m venv venv

$ . ./venv/bin/activate

$ pip install .
Processing /home/andy/ANOTHER1576/1576
Collecting ruamel-yaml
  Using cached ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
Collecting ruamel.yaml.clib>=0.2.6
  Using cached ruamel.yaml.clib-0.2.6-cp39-cp39-manylinux1_x86_64.whl (539 kB)
Using legacy 'setup.py install' for testing-editable-dots, since package 'wheel' is not installed.
Installing collected packages: ruamel.yaml.clib, ruamel-yaml, testing-editable-dots
    Running setup.py install for testing-editable-dots ... done
Successfully installed ruamel-yaml ruamel.yaml.clib-0.2.6 testing-editable-dots-0.0.0

$ test-with-editable-dots
Traceback (most recent call last):
  File "/home/andy/ANOTHER1576/1576/venv/bin/test-with-editable-dots", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/andy/ANOTHER1576/1576/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/andy/ANOTHER1576/1576/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/andy/ANOTHER1576/1576/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/andy/ANOTHER1576/1576/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/andy/ANOTHER1576/1576/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/andy/ANOTHER1576/1576/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ruamel-yaml' distribution was not found and is required by testing-editable-dots
```

**Comment by AndydeCleyre** [comment]
Also including here a quote from [PEP 503](https://www.python.org/dev/peps/pep-0503/):

> This PEP references the concept of a "normalized" project name. As per PEP 426 the only valid characters in a name are the ASCII alphabet, ASCII numbers, ., -, and _. The name should be lowercased with all runs of the characters ., -, or _ replaced with a single - character.
