### ISSUE TITLE
[BUG] [pyproject.toml] `%(otherextra)s` in `[project.optional-dependencies]`

### ISSUE THREAD

**Issue by marvinpfoertner** [pypa/setuptools#3221]
### setuptools version

setuptools==61.1.1

### Python version

Python 3.9.7

### OS

macOS

### Description

In `setup.cfg` it is possible to define extras that depend on other extras:

```ini
[options.extras_require]
extra1 =
    numpy
    scipy

extra2 =
    %(extra1)s
    jax
```

In `pyproject.toml`-based configuration, this is no longer possible.

### Expected behavior

The following configuration in `pyproject.toml` config should behave exactly as the `setup.cfg` config above:

```toml
[project.optional-dependencies]
extra1 = [
    "numpy",
    "scipy",
]
extra2 = [
    "%(extra1)s",
    "jax",
]
```

### How to Reproduce

1. clone the gist https://gist.github.com/marvinpfoertner/c5ec8a5bf0f1193d9a123892259e0ebb
2. run `pip wheel .` or `python -m build`

### Output

```console
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (build, setuptools>=61.0.0)
* Getting dependencies for sdist...
/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:100: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
configuration error: `project.optional-dependencies.{data__optionaldependencies_key}[{data__optionaldependencies_val_x}]` must be pep508
DESCRIPTION:
    Project dependency specification according to PEP 508

GIVEN VALUE:
    "%(extra1)s"

OFFENDING RULE: 'format'

DEFINITION:
    {
        "$id": "#/definitions/dependency",
        "title": "Dependency",
        "type": "string",
        "format": "pep508"
    }
ignored error: ValueError - invalid pyproject.toml config: `project.optional-dependencies.{data__optionaldependencies_key}[{data__optionaldependencies_val_x}]`
Traceback (most recent call last):
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marvin/.local/miniconda3/envs/probnum/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/Users/marvin/.local/miniconda3/envs/probnum/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/marvin/.local/miniconda3/envs/probnum/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 297, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/build_meta.py", line 181, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/__init__.py", line 78, in setup
    _install_setup_requires(attrs)
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/__init__.py", line 70, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/_virtualenv.py", line 21, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/dist.py", line 836, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 53, in apply_configuration
    return apply(dist, config, filepath)
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 56, in apply
    dist._finalize_requires()
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/dist.py", line 551, in _finalize_requires
    self._convert_extras_requirements()
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/setuptools/dist.py", line 565, in _convert_extras_requirements
    for r in _reqs.parse(v):
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3089, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/private/var/folders/kv/d8qqy4d14rz7qhqchrb0l6l00000gn/T/build-env-tot0a9_u/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'%(extra1'": Expected W:(abcd...)

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist
```

**Comment by abravalheri** [comment]
Hi @marvinpfoertner thank you very much for bringing this topic to discussion.

I think I understand the main idea here (to re-use extras) and I like it.
However, the format of `pyproject.toml` is very strict and standardised via PEPs.
The latest standard (PEP 621) limits which formats of values can be accepted in `dependencies` or `optional-dependencies`.

To add the feature you are looking for, it would be necessary to trigger a discussion and possibly a follow-up PEP. If you want to pursue that, please start a discussion in the PyPA-related section of Python Discourse: https://discuss.python.org/c/packaging.

An example of related discussion can be seen at: https://discuss.python.org/t/adding-a-default-extra-require-environment/4898

Until there is some level of agreement on the proposed changes for the standard, I think there is not much action from setuptools side.

I will close this issue for now, but please feel free to ping again once there is some advacement on the standards.

---

P.S.:
Depending on the version of `pip` being used to install this package, you might have some luck if you specify:

```toml
[project.optional-dependencies]
extra1 = [
    "numpy",
    "scipy",
]
extra2 = [
    "your-project-name[extra1]",
    "jax",
]
```

i.e. `pip` detects extra cycles and resolve them accordingly.
However, if this works, please have in mind that it is a non-standard feature supported only by some versions of `pip`.
