### ISSUE TITLE
Problems with local `queue.py` file overshadowing stdlib

### ISSUE THREAD

**Issue by Husky22** [pypa/setuptools#3316]
### setuptools version

60.10.0

### Python version

Python 3.10

### OS

macOS

### Description

When running `python setup.py` the file `queue.py` in the same directory as `setup.py` is being called as well. 
This may lead to a crash of the setup process.

### Expected behavior

`queue.py` should not be called

### How to Reproduce

1. Create a project with a setuptools `setup.py` file.
2. Create a `queue.py` file with a print("Hello") statement for example
3. Run `python setup.py install`

### Output

```console
Hello
Traceback (most recent call last):
  File "/Users/nvm/Documents/Programmieren/Python/testsetuptools/setup.py", line 1, in <module>
    from setuptools import setup
  File "/Users/nvm/.virtualenvs/testsetuptools/lib/python3.10/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/Users/nvm/.virtualenvs/testsetuptools/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/Users/nvm/.virtualenvs/testsetuptools/lib/python3.10/site-packages/pkg_resources/__init__.py", line 74, in <module>
    from pkg_resources.extern.jaraco.text import (
  File "/Users/nvm/.virtualenvs/testsetuptools/lib/python3.10/site-packages/pkg_resources/_vendor/jaraco/text/__init__.py", line 11, in <module>
    from pkg_resources.extern.jaraco.functools import compose, method_cache
  File "/Users/nvm/.virtualenvs/testsetuptools/lib/python3.10/site-packages/pkg_resources/_vendor/jaraco/functools.py", line 8, in <module>
    import pkg_resources.extern.more_itertools
  File "/Users/nvm/.virtualenvs/testsetuptools/lib/python3.10/site-packages/pkg_resources/extern/__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "/Users/nvm/.virtualenvs/testsetuptools/lib/python3.10/site-packages/pkg_resources/extern/__init__.py", line 44, in load_module
    raise ImportError(
ImportError: The 'more_itertools' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

**Comment by abravalheri** [comment]
Hi @Husky22, my understanding of what is happening here is that your file `queue.py` is effectively overwriting the `queue` module in the standard library, which causes the error.

This behaviour happens because when you run a script with `python myscript.py`, Python automatically inserts `""` (empty string) as the first entry in `sys.path`, which corresponds to the current working directory. Therefore any module in the CWD will take precedence over the modules in the standard library.

Setuptools depends on `queue` for its implementation, and your `queue` file does not provide the same APIs as the standard library.

Please note that this is not a bug with setuptools itself but rather an accident with file naming.
The best would be avoiding having any files in your CWD that might overshadow parts of the stdlib (this also includes things like `_queue`, which is also is used in the stdlib), otherwise not only the installation may be broken, but also the runtime if any dependencies depend on the stdlib.

**Comment by abravalheri** [comment]
@Husky22 is there any doubts left here?

I feel like we can close this issue now, since the behaviour you observe is derived from the way Python works (it is a limitation of the language, there is very little we can do about it).

**Comment by Husky22** [comment]
No doubts left! Thanks a lot for clarification.
