### ISSUE TITLE
[BUG] distutils.msvccompiler does not work with any currently available VS build tools

### ISSUE THREAD

**Issue by rwarren** [pypa/setuptools#3329]
### setuptools version

setuptools == 62.3.1

### Python version

Python 3.10

### OS

Win10

### Additional environment information

I have tried to make this work on Win10 with various combinations of:

* Python 3.10 64-bit
* Python 3.10 32-bit
* Python 3.8 32-bit
* Build Tools for Visual Studio 2019 (version 16.11)
    * this is the latest version of VS2019 (which the [compiler wiki](https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29) recommends)
* Build Tools for Visual Studio 2019 (version 16.0) <-- in case higher versions broke things
* Build Tools for Visual Studio 2022 (version 17.2) <-- just in case!
* Build Tools for Visual Studio 2022 (version 17.0) <-- also just in case!

With the latest VS2019 build tools, I'm installing these components (as directed by the compiler wiki):
![image](https://user-images.githubusercontent.com/2751728/169025860-12c5ce3f-2d57-4979-9626-618fbe3052ea.png)

### Description

**Main problem**: Basic MS builds do not currently work _at all_ on Win10 with currently available VS2019 Build Tools!

The fastest way to see/reproduce this is to try and initialize a `distutils.msvccompiler.MSVCCompiler` with any clean Win10 environment combination and the a VS2019 C++ Build Tools install (with any variety of combinations, as as indicated in the env section).

Specifically, this code throws a `DistutilsPlatformError` exception because it can't find Microsoft Visual C++ 14.2:

```python
import distutils.msvccompiler as msvc 
mc = msvc.MSVCCompiler()
mc.initialize()  # <-- BOOM
```

The specific exception thrown, with message, is:

```
DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

This error seems like it is due to the following things:

1. setuptools is looking for the VC tools in a dotted-version based dir schema, while all available VS build tools install to a year-based dir schema
    * What setup tools expects: `C:\Program Files (x86)\Microsoft Visual Studio 14.2\VC\Tools\MSVC`
    * What is actually installed: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools`
2. setuptools *really* wants to find build tools version 14.2, but no installer is available from MS that gives the expected dir structure
    * even though the latest `MSVC 142 - VS 2019 C++ x64/x86` build tools are installed, it does not install them to the version-dotted dir schema that setuptools is expecting

When installing build tools today (with the MSVC142 tools selected), the proper location for executables like `cl.exe` is in dirs like this:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe
```

**There are no older MSVC build tools installers available to get a 14.2-based install dir**. The URL I am trying to downlad build tools from is https://visualstudio.microsoft.com/vs/older-downloads/, as given by the [compiler wiki](https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29).

----

**Further details:**

Stepping through the `setuptools.msvc` implementation, the following things can be seen:

* `setuptools` _does_ pick up the VS 2019 build tools dir as follows (in `SystemInfo.known_vs_paths`): 
    * `{16.11: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools'}`
    * Note that the version is 16.11, not 14.2
    * Also note that the dir has a date-based schema (with a `2019` dir in the path)
* The version that `setuptools` is looking for is 14.2
* With no version match, the fallback is to assume a dir structure with dotted versions (instead of the 2019 year)
    * specifically: `C:\Program Files (x86)\Microsoft Visual Studio 14.2`
    * the code that assumes this is [here](https://github.com/pypa/setuptools/blob/main/setuptools/msvc.py#L810)

----

For search purposes, I ran into this problem when trying to build [WxPython](https://www.wxpython.org/) with a simple `pip install wxpython`.

### Expected behavior

setuptools should work with the currently available VS2019 build tools from Microsoft.

Alternatively, the [compiler wiki](https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29) (or other docs?) should be corrected to point to whatever location has compatible build tools.

### How to Reproduce

As described in the description. Essentially:

1. Get a fresh Win10 install (no Visual Studio or Build tools installed)
2. Install the latest VS2019 C++ build tools from https://visualstudio.microsoft.com/vs/older-downloads/
    * this is the link currently provided by the python [compiler wiki](https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29)
3. Install python 3.10 (or down to 3.8)
4. `pip install setuptools -U` to get the latest (just in case)
5. Run the code below

```python
import distutils.msvccompiler as msvc 
mc = msvc.MSVCCompiler()
mc.initialize()  # <-- BOOM
```

### Output

```console
In [1]: import distutils.msvccompiler as msvc
   ...: mc = msvc.MSVCCompiler()
   ...: mc.initialize()  # <-- BOOM
---------------------------------------------------------------------------
DistutilsPlatformError                    Traceback (most recent call last)
Input In [1], in <cell line: 3>()
      1 import distutils.msvccompiler as msvc
      2 mc = msvc.MSVCCompiler()
----> 3 mc.initialize()

File C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\_distutils\msvc9compiler.py:371, in MSVCCompiler.initialize(self, plat_name)
    366 else:
    367     # cross compile from win32 -> some 64bit
    368     plat_spec = PLAT_TO_VCVARS[get_platform()] + '_' + \
    369                 PLAT_TO_VCVARS[plat_name]
--> 371 vc_env = query_vcvarsall(VERSION, plat_spec)
    373 self.__paths = vc_env['path'].split(os.pathsep)
    374 os.environ['lib'] = vc_env['lib']

File C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\msvc.py:140, in msvc9_query_vcvarsall(ver, arch, *args, **kwargs)
    138 # If error, try to set environment directly
    139 try:
--> 140     return EnvironmentInfo(arch, ver).return_env()
    141 except distutils.errors.DistutilsPlatformError as exc:
    142     _augment_exception(exc, ver, arch)

File C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\msvc.py:1740, in EnvironmentInfo.return_env(self, exists)
   1724 def return_env(self, exists=True):
   1725     """
   1726     Return environment dict.
   1727
   (...)
   1736         environment
   1737     """
   1738     env = dict(
   1739         include=self._build_paths('include',
-> 1740                                   [self.VCIncludes,
   1741                                    self.OSIncludes,
   1742                                    self.UCRTIncludes,
   1743                                    self.NetFxSDKIncludes],
   1744                                   exists),
   1745         lib=self._build_paths('lib',
   1746                               [self.VCLibraries,
   1747                                self.OSLibraries,
   1748                                self.FxTools,
   1749                                self.UCRTLibraries,
   1750                                self.NetFxSDKLibraries],
   1751                               exists),
   1752         libpath=self._build_paths('libpath',
   1753                                   [self.VCLibraries,
   1754                                    self.FxTools,
   1755                                    self.VCStoreRefs,
   1756                                    self.OSLibpath],
   1757                                   exists),
   1758         path=self._build_paths('path',
   1759                                [self.VCTools,
   1760                                 self.VSTools,
   1761                                 self.VsTDb,
   1762                                 self.SdkTools,
   1763                                 self.SdkSetup,
   1764                                 self.FxTools,
   1765                                 self.MSBuild,
   1766                                 self.HTMLHelpWorkshop,
   1767                                 self.FSharp],
   1768                                exists),
   1769     )
   1770     if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
   1771         env['py_vcruntime_redist'] = self.VCRuntimeRedist

File C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\msvc.py:1282, in EnvironmentInfo.VCIncludes(self)
   1272 @property
   1273 def VCIncludes(self):
   1274     """
   1275     Microsoft Visual C++ & Microsoft Foundation Class Includes.
   1276
   (...)
   1280         paths
   1281     """
-> 1282     return [join(self.si.VCInstallDir, 'Include'),
   1283             join(self.si.VCInstallDir, r'ATLMFC\Include')]

File C:\venvs\udbs_unit_copy\lib\site-packages\setuptools\msvc.py:840, in SystemInfo.VCInstallDir(self)
    838 if not isdir(path):
    839     msg = 'Microsoft Visual C++ directory not found'
--> 840     raise distutils.errors.DistutilsPlatformError(msg)
    842 return path

DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

**Comment by abravalheri** [comment]
Hi @rwarren thank you for reporting this.

I had a quick look on your reproducer and I think I will leave this issue for the other maintainers since I don't have any familiarity with this part of the code, but I would like to ask, if possible if you can update your reproducer to do a `import setuptools` as the first thing before importing any `distutils`, just to make sure all the `setuptools` patches are applied before starting to investigate.

**Comment by rwarren** [comment]
Over at the downstream location where I encountered this problem ([here](https://github.com/wxWidgets/Phoenix/issues/2165#issuecomment-1150432580)), @DKMR figured out how to fool `distutils` into locating the VS2019 build tools.

If you manually create the the following registry keys (what I'm showing is a `.reg` file contents), the `mc.initialize()` in the above script works fine.

```ini
Windows Registry Editor Version 5.00

; These registry keys are needed to coerce python into detecting VS2019 build tools
;  - adjust `ProductDir` paths as necessary (the dir should be where `vcvarsall.bat` is located)

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.2\Setup\VC]
"ProductDir"="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\Setup\VC]
"ProductDir"="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build"
```

I think this just confirms that Microsoft made some adjustments to where they keep stuff and/or register stuff.

**Comment by wawan-ikhwan** [comment]
@rwarren can you explain detail where should I edit ```ProductDir```. I open registry editor from win + R I don't see such variabel

**Comment by liudonghua123** [comment]
I have the same problems when I install wxPython via `pip install -U wxPython`.

Since I installed vs 2019 Community version, so the path I changed as follows. And then I installed wxPython successfully.

```reg
Windows Registry Editor Version 5.00

; setuptools-vs-fix.reg
; These registry keys are needed to coerce python into detecting VS2019 build tools
;  - adjust `ProductDir` paths as necessary (the dir should be where `vcvarsall.bat` is located)

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.2\Setup\VC]
"ProductDir"="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\Setup\VC]
"ProductDir"="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build"

```

**Comment by DKMR** [comment]
@liudonghua123 since Python 3.10 has no available wheels for wxPython and you're building the whole package from ground up, I'd suggest you try building the [latest](wxPython-4.2.0a1.dev5447+fd6b4814.tar.gz) snapshot of wxPython and see if that works out.

**Comment by liudonghua123** [comment]
@DKMR Thanks for the suggestions, I tried to build on the master branch. But after I fix `from collections import Mapping` issue on python 3.9+, I still got the following errors, `configure.in No such file or directory` primarily.

```shell
D:\code\python\Phoenix>pip install .
Processing d:\code\python\phoenix
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\code\python\Phoenix\setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "D:\code\python\Phoenix\buildtools\config.py", line 30, in <module>
          from attrdict import AttrDict
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\attrdict\__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\attrdict\mapping.py", line 8, in <module>
          from attrdict.mixins import MutableAttr
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\attrdict\mixins.py", line 5, in <module>
          from collections import Mapping, MutableMapping, Sequence
      ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

D:\code\python\Phoenix>pip install .
Processing d:\code\python\phoenix
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from wxPython==4.2.0a1) (9.0.1)
Requirement already satisfied: six in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from wxPython==4.2.0a1) (1.16.0)
Requirement already satisfied: numpy in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from wxPython==4.2.0a1) (1.22.3)
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:771: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\config\setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:317: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running bdist_wheel
      running build
      Will build using: "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\python.exe"
      3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
      Python's architecture is 64bit
      cfg.VERSION: 4.2.0a1

      Running command: build
      Running command: build_wx
      CL.exe: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe
      Downloading microsoft.web.webview2 1.0.1185.39...
      Connection successful...
      Data downloaded...
      wxWidgets build options: ['--wxpython', '--unicode']
      ERROR: failed building wxWidgets
      Traceback (most recent call last):
        File "D:\code\python\Phoenix\build.py", line 1560, in cmd_build_wx
          wxbuild.main(wxDir(), build_options)
        File "D:\code\python\Phoenix\buildtools\build_wxwidgets.py", line 174, in main
          VERSION = tuple([int(i) for i in getWxRelease().split('.')[:2]])
        File "D:\code\python\Phoenix\buildtools\build_wxwidgets.py", line 81, in getWxRelease
          with open(os.path.join(wxRoot, "configure.in"), "r") as fid:
      FileNotFoundError: [Errno 2] No such file or directory: 'D:\\code\\python\\Phoenix\\ext\\wxWidgets\\configure.in'
      Finished command: build_wx (0m8.749s)
      Finished command: build (0m8.749s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\python.exe" -u build.py build
      Command '"C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\python.exe" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
Installing collected packages: wxPython
  Running setup.py install for wxPython ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wxPython did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:771: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\config\setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py:317: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running install
      C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      Will build using: "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\python.exe"
      3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
      Python's architecture is 64bit
      cfg.VERSION: 4.2.0a1

      Running command: build
      Running command: build_wx
      CL.exe: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe
      wxWidgets build options: ['--wxpython', '--unicode']
      ERROR: failed building wxWidgets
      Traceback (most recent call last):
        File "D:\code\python\Phoenix\build.py", line 1560, in cmd_build_wx
          wxbuild.main(wxDir(), build_options)
        File "D:\code\python\Phoenix\buildtools\build_wxwidgets.py", line 174, in main
          VERSION = tuple([int(i) for i in getWxRelease().split('.')[:2]])
        File "D:\code\python\Phoenix\buildtools\build_wxwidgets.py", line 81, in getWxRelease
          with open(os.path.join(wxRoot, "configure.in"), "r") as fid:
      FileNotFoundError: [Errno 2] No such file or directory: 'D:\\code\\python\\Phoenix\\ext\\wxWidgets\\configure.in'
      Finished command: build_wx (0m2.300s)
      Finished command: build (0m2.300s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\python.exe" -u build.py build
      Command '"C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\python.exe" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxPython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

D:\code\python\Phoenix>
```

**Comment by DKMR** [comment]
@liudonghua123 I'm not sure you followed the instructions contained in _README.rst_ file you extracted from the snapshot. TL;DR, install these packages with pip if you don't have them already:

- appdirs
- setuptools
- sip == 6.6.2
- wheel
- twine
- requests
- requests[security]
- cython==0.29.24
- pytest
- pytest-xdist
- pytest-forked
- pytest-timeout
- sphinx==2.2.0 ; python_version >= '3.0'
- Jinja2==2.10
- doc2dash==2.3.0
- beautifulsoup4
- attrdict3

Then you'll need VS Studio 2015 or newer and a copy of MS SDK.

After you have all of the above, build wxPython with `python build.py dox etg --nodoc sip build`. Run `python build.py install` afterwards to copy wx files to the right place.

**Comment by zooba** [comment]
```
import setuptools  # as requested
import distutils.msvccompiler as msvc 
```

This is incorrect. The proper module is `distutils._msvccompiler`, because you're _not_ supposed to access it directly.

The one you're importing is the ~2.7 implementation, which would have been removed when the new one was added, but I was told to leave it there for compatibility. So yeah, it is totally busted, but the proper one should be fine.

**Comment by EvgenKo423** [comment]
@zooba It's [in the API](https://docs.python.org/3.10/distutils/apiref.html#module-distutils.msvccompiler), so it's expected to be correct. That's why [it was patching itself](https://github.com/pypa/setuptools/blob/v65.0.2/setuptools/_distutils/msvccompiler.py#L689-L695).

**Comment by zooba** [comment]
Perhaps, but the point is that it's not been updated for building in Python 3.5 and later (and now that it's removed from core, those docs are basically irrelevant).

If setuptools decides to update it to work again, that's on them, but my point was that the code people are writing to test things in this thread are all using the wrong class, and the registry keys being suggested aren't ever referenced in the current implementation. So if those people want to prove any points, they need to import a different class.

**Comment by oddsmatcheraustralia** [comment]
Command:

python setup.py build_ext --inplace
running build_ext
building 'helloworld' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
I have tried adjusting the path and deleting regedit entries that are not relevant.  
I am running version 3.10 python, I have tried anaconda 3.7 and 3.9 still no luck. I have install visual studio Build Tools 2022 and Visual Studio Community 2022 all files which is around 200gb as well as added C:\Program Files (x86)\Microsoft Visual Studio 14.0 and C:\Program Files (x86)\Microsoft Visual Studio 14.0/Vc to path. I have tried https://github.com/abbodi1406/vcredist/releases/tag/v0.62.0

**Comment by zooba** [comment]
@oddsmatcheraustralia Try running this command and see whether your installs are there:

```
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
```

If they're not showing up, remove the `-requires` argument and try again. If they're there now, you need to add the C++ compiler. If they're still not there, they probably need to be repaired. Either way, run "Visual Studio Installer" from Start to do it.

**Comment by shimizukawa** [comment]
I encountered the same problem at first, but eventually I was able to build it.

In my case, the problem was that `vcvarsall.bat` was not installed, but this was solved by specifying the appropriate package in the Build Tools vor Visual Studio 2022 installer.

- Windows 11 SDK (10.0.22000.0)
- MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)
  - note: `MSVC v143 - VS 2022 C++ x64/x86 build tools (v14.35-17.5)` does not works for me. it doesn't install `vcvarsall.bat`.

After installation, `vcvarsall.bat` is installed in `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build` .
> ![image](https://user-images.githubusercontent.com/151623/222934961-8aa34c46-733f-4e51-9f14-d58d28585977.png)

Here is the configuration file `.vsconfig` exported after installation

```json
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.CoreBuildTools",
    "Microsoft.VisualStudio.Workload.MSBuildTools",
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Microsoft.VisualStudio.Component.Windows11SDK.22000",
    "Microsoft.VisualStudio.Component.VC.14.35.17.5.ATL.Spectre",
    "Microsoft.VisualStudio.Component.VC.14.35.17.5.MFC.Spectre"
  ]
}
```
