### ISSUE TITLE
[BUG] setup.py check -r results in TypeError when package has no long_description

### ISSUE THREAD

**Issue by ni-balexand** [pypa/setuptools#3356]
### setuptools version

setuptools==62.2.0

### Python version

Python 3.7

### OS

Windows 10

### Description

Running the command `python setup.py check -r` with setuptools==62.2.0 installed causes a TypeError when the setup call in setup.py has not specified a long_description.  This issue is not present in setuptools==62.1.0 .

It's kind of a silly problem, since `check -r` only seems to check the long_description anyways, but at least there should be a useful error message and not a cryptic TypeError.  I'd probably just do nothing and let the check succeed if long_description is None.  This worked before a7cfb56a7b1eaa95824d81a34e8e70b85d42f784 because the check was done on the internal string value "UNKNOWN", which turns out to be valid reStructuredText by itself.

### Expected behavior

`python setup.py check -r` should succeed if there is no long_description.

### How to Reproduce

1. Start with a very bare-bones pyproject with `setup.py`.  Do not define a `long_description`.
2. `pip install docutils` (needed by -r option)
3. `pip install setuptools==62.2.0`
4. `python setup.py check -r`

### Output

```console
> type pyproject.toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

> type setup.py
from setuptools import setup

setup(
    name='pkg',
    version='0.0.1',
    packages=['pkg'],
    install_requires=[],
)

> python -m pip install docutils
Collecting docutils
  Downloading docutils-0.18.1-py2.py3-none-any.whl (570 kB)
     ---------------------------------------- 570.0/570.0 kB 9.0 MB/s eta 0:00:00
Installing collected packages: docutils
Successfully installed docutils-0.18.1

> python -m pip install setuptools==62.2.0
Collecting setuptools==62.2.0
  Downloading setuptools-62.2.0-py3-none-any.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 12.1 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 47.1.0
    Uninstalling setuptools-47.1.0:
      Successfully uninstalled setuptools-47.1.0
Successfully installed setuptools-62.2.0

> python setup.py check -r
running check
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    install_requires=[],
  File "C:\venv\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\venv\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\venv\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\venv\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\venv\lib\site-packages\setuptools\dist.py", line 1224, in run_command
    super().run_command(command)
  File "C:\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\venv\lib\site-packages\setuptools\_distutils\command\check.py", line 72, in run
    self.check_restructuredtext()
  File "C:\venv\lib\site-packages\setuptools\_distutils\command\check.py", line 102, in check_restructuredtext
    for warning in self._check_rst_data(data):
  File "C:\venv\lib\site-packages\setuptools\_distutils\command\check.py", line 130, in _check_rst_data
    parser.parse(data, document)
  File "C:\venv\lib\site-packages\docutils\parsers\rst\__init__.py", line 175, in parse
    convert_whitespace=True)
  File "C:\venv\lib\site-packages\docutils\statemachine.py", line 1512, in string2lines
    astring = whitespace.sub(' ', astring)
TypeError: expected string or bytes-like object
```

**Comment by abravalheri** [comment]
Hi @ni-balexand , thank you for reporting this.

The `setuptools/_distutils` folder is periodically merged from another repository ([pypa/distutils](https://github.com/pypa/distutils)), so we avoid modifying it directly in the `pypa/setuptools` project. Would you like to contact the team in `pypa/setuptools` and provide a PR with the fix? There is a chance they will accept it there (and eventually it will find its way into this project). 

I imagine that you can add a condition ensuring that the field is a string in https://github.com/pypa/distutils/blob/75ed79d1ad1bfbb30dd684cd3cc55cb1139dc31b/distutils/command/check.py#L114.
