### ISSUE TITLE
[BUG] Bad MANIFEST.in exclude can globally break sdist

### ISSUE THREAD

**Issue by jaseg** [pypa/setuptools#3369]
### setuptools version

59.5.0

### Python version

3.10.5

### OS

Arch Linux

### Description

I discovered an interesting setuptools foot-gun that took me a few hours to figure out.

1. Using wildcard global excludes in MANIFEST.in, it is possible to create installable but broken packages by excluding certain metadata files. Minimal example:
```console
$ tar -taf normal-sdist.tar.gz
fnord-23.0.42/
fnord-23.0.42/MANIFEST.in
fnord-23.0.42/PKG-INFO
fnord-23.0.42/fnord.egg-info/
fnord-23.0.42/fnord.egg-info/PKG-INFO
fnord-23.0.42/fnord.egg-info/SOURCES.txt
fnord-23.0.42/fnord.egg-info/dependency_links.txt
fnord-23.0.42/fnord.egg-info/top_level.txt
fnord-23.0.42/setup.cfg
fnord-23.0.42/setup.py
$ tar -taf broken-sdist.tar.gz
fnord-23.0.42/
fnord-23.0.42/PKG-INFO
fnord-23.0.42/fnord.egg-info/
fnord-23.0.42/fnord.egg-info/SOURCES.txt
fnord-23.0.42/setup.cfg
```
Notice how the following files are missing:
```
fnord-23.0.42/fnord.egg-info/PKG-INFO
fnord-23.0.42/fnord.egg-info/dependency_links.txt
fnord-23.0.42/fnord.egg-info/top_level.txt
```

2. setuptools'es sdist command trips up with a ```TypeError: expected string or bytes-like object``` when it finds such a package installed in the user's ```~/.local/lib/python*/site-packages``` (stack trace below).

### Expected behavior

* setuptools should refuse to build a package that is missing essential metadata files.
* I'm not sure what the intended semantics of MANIFEST.in are, but matching its includes/excludes against package-internal metadata files that are autogenerated during the package build seems counter-intuitive to me. If this is required behavior, it would be good if it were hidden behind a switch.
* sdist should not break when encountering an invalid package on disk
* When sdist due to a bug errors out while parsing package meta from site-packages, it should print the name and path of the offending package along with the error to give the user some hint on how to fix the issue.

### How to Reproduce

1. Create a minimal package with a MANIFEST.in containing only the line ```global-exclude *```

```shell
$ cat fnord.py
print('fnord!')
$ cat setup.py
from setuptools import setup, find_packages

setup(
    name='fnord',
    version='23.0.42',
    python_modules=['fnord']
)
$ cat MANIFEST.in
global-exclude *
```

2. Install it user-local using setup.py:
```shell
$ python3 setup.py install --user
/usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_modules'
  warnings.warn(msg)
running install
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing fnord.egg-info/PKG-INFO
writing dependency_links to fnord.egg-info/dependency_links.txt
writing top-level names to fnord.egg-info/top_level.txt
listing git files failed - pretending there aren't any
reading manifest file 'fnord.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found anywhere in distribution
writing manifest file 'fnord.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/fnord-23.0.42-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing fnord-23.0.42-py3.10.egg
Removing /home/jaseg/.local/lib/python3.10/site-packages/fnord-23.0.42-py3.10.egg
Copying fnord-23.0.42-py3.10.egg to /home/jaseg/.local/lib/python3.10/site-packages
fnord 23.0.42 is already the active version in easy-install.pth

Installed /home/jaseg/.local/lib/python3.10/site-packages/fnord-23.0.42-py3.10.egg
Processing dependencies for fnord==23.0.42
Finished processing dependencies for fnord==23.0.42
```

### Output

3. Future calls to ```setup.py sdist``` will fail with a ```TypeError: expected string or bytes-like object```, **even in setup.py of completely unrelated projects under the same account**:
```shell
$ cd ~/totally-different-project
$ python3 setup.py sdist
/usr/lib/python3.10/site-packages/setuptools/dist.py:490: UserWarning: Normalizing '0.23.0-3' to '0.23.0.post3'
  warnings.warn(tmpl.format(**locals()))
running sdist
running egg_info
writing resvg_wasi.egg-info/PKG-INFO
writing dependency_links to resvg_wasi.egg-info/dependency_links.txt
writing entry points to resvg_wasi.egg-info/entry_points.txt
writing requirements to resvg_wasi.egg-info/requires.txt
writing top-level names to resvg_wasi.egg-info/top_level.txt
Traceback (most recent call last):
  File "/home/jaseg/proj/resvg-wasi/setup.py", line 40, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 46, in run
    self.run_command('egg_info')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 299, in run
    self.find_sources()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
    mm.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 541, in run
    self.add_defaults()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 581, in add_defaults
    rcfiles = list(walk_revctrl())
  File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 18, in walk_revctrl
    for item in ep.load()(dirname):
  File "/usr/lib/python3.10/site-packages/setuptools_scm/integration.py", line 79, in find_files
    for ep in iter_entry_points("setuptools_scm.files_command"):
  File "/usr/lib/python3.10/site-packages/setuptools_scm/utils.py", line 144, in iter_entry_points
    return iter_entry_points(*k, **kw)
  File "/usr/lib/python3.10/site-packages/setuptools_scm/_entrypoints.py", line 51, in iter_entry_points
    all_eps = entry_points()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1009, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1006, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 941, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Comment by abravalheri** [comment]
Hi @jaseg, thanks for reporting this. Unfortunately, I cannot reproduce the behaviour you are seeing in an isolated fashion:

```powershell
> docker run --rm -it fedora:36

python3 -m ensurepip
python3 -m pip install -UI 'setuptools==59.5.0'

mkdir /tmp/testpkg
cd /tmp/testpkg
cat <<EOS > setup.py
from setuptools import setup, find_packages

setup(
    name='fnord',
    version='23.0.42',
    python_modules=['fnord']
)
EOS
cat <<EOS > MANIFEST.in
global-exclude *
EOS
python3 setup.py install --user
python3 setup.py sdist
python3 setup.py sdist  # once again ...
```

This example runs successfully.

Could you provide a modified reproducer that don't depend on the specific state of your machine? (You can work in a modified version of the example above that uses containers for isolation).

Please also note the following:

- Setuptools don't provide patches for old releases, so please verify if the behaviour still exists in the latest version.
- Please don't use the `python setup.py install` command, as it is considered deprecated.
  Instead you can try [`python -m pip install .`](https://pip.pypa.io/en/stable/cli/pip_install/)
- Please don't use the `python setup.py sdist` command. It is considered deprecated.
  Instead you can try [`python -m build --sdist`](https://pypa-build.readthedocs.io/en/stable/) (`build` needs to be installed first). (`python -m build --wheel` is also "equivalent" to `python setup.py bdist_wheel`)

I am still trying to think about the expected behaviour you proposed. Somethings seem fair. However the `*.egg-info` directory is not something that is standardised, and currently considered an internal mechanism for setuptools.

What is a standardised metadata file is the `PKG-INFO` file on the root directory of the sdist, and this file seems to be there...

**Comment by jaseg** [comment]
Hmm, after some debugging I found that the issue only happens if the ```setuptools_scm``` package is installed. 
I'm not sure if maybe this is a setuptools_scm issue then? This reproduces the issue on fedora:

```shell
python3 -m ensurepip
python3 -m pip install -UI 'setuptools'
python3 -m pip install -UI 'setuptools_scm'

mkdir /tmp/testpkg
cd /tmp/testpkg
cat <<EOS > setup.py
from setuptools import setup, find_packages

setup(
    name='fnord',
    version='23.0.42',
    python_modules=['fnord']
)
EOS
cat <<EOS > MANIFEST.in
global-exclude *
EOS
python3 setup.py install --user
python3 setup.py sdist
python3 setup.py sdist  # once again ...
```

Output:

```console
[root@1d65ff136570 /]# python3 -m ensurepip
WARNING: Running pip install with root privileges is generally not a good idea. Try `python3 -m pip install --user` instead.
Looking in links: /tmp/tmphags28qn
Processing /tmp/tmphags28qn/setuptools-49.1.3-py3-none-any.whl
Processing /tmp/tmphags28qn/pip-20.2.2-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-20.2.2 setuptools-49.1.3
[root@1d65ff136570 /]# python3 -m pip install -UI 'setuptools'
WARNING: Running pip install with root privileges is generally not a good idea. Try `python3 -m pip install --user` instead.
Collecting setuptools
  Downloading setuptools-62.4.0-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 36.6 MB/s 
Installing collected packages: setuptools
Successfully installed setuptools-62.4.0
WARNING: You are using pip version 20.2.2; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
[root@1d65ff136570 /]# python3 -m pip install -UI 'setuptools_scm'
WARNING: Running pip install with root privileges is generally not a good idea. Try `python3 -m pip install --user` instead.
Collecting setuptools_scm
  Downloading setuptools_scm-6.4.2-py3-none-any.whl (37 kB)
Collecting setuptools
  Using cached setuptools-62.4.0-py3-none-any.whl (1.2 MB)
Collecting packaging>=20.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 14.6 MB/s 
Collecting tomli>=1.0.0
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 26.3 MB/s 
Installing collected packages: setuptools, pyparsing, packaging, tomli, setuptools-scm
Successfully installed packaging-21.3 pyparsing-3.0.9 setuptools-62.4.0 setuptools-scm-6.4.2 tomli-2.0.1
WARNING: You are using pip version 20.2.2; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
[root@1d65ff136570 /]# 
[root@1d65ff136570 /]# mkdir /tmp/testpkg
[root@1d65ff136570 /]# cd /tmp/testpkg
[root@1d65ff136570 testpkg]# cat <<EOS > setup.py
> from setuptools import setup, find_packages
> 
> setup(
>     name='fnord',
>     version='23.0.42',
>     python_modules=['fnord']
> )
> EOS
[root@1d65ff136570 testpkg]# cat <<EOS > MANIFEST.in
> global-exclude *
> EOS
[root@1d65ff136570 testpkg]# python3 setup.py install --user
/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py:257: UserWarning: Unknown distribution option: 'python_modules'
  warnings.warn(msg)
running install
/usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating fnord.egg-info
writing fnord.egg-info/PKG-INFO
writing dependency_links to fnord.egg-info/dependency_links.txt
writing top-level names to fnord.egg-info/top_level.txt
writing manifest file 'fnord.egg-info/SOURCES.txt'
reading manifest file 'fnord.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'fnord.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/fnord-23.0.42-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing fnord-23.0.42-py3.9.egg
Copying fnord-23.0.42-py3.9.egg to /root/.local/lib/python3.9/site-packages
Adding fnord 23.0.42 to easy-install.pth file

Installed /root/.local/lib/python3.9/site-packages/fnord-23.0.42-py3.9.egg
Processing dependencies for fnord==23.0.42
Finished processing dependencies for fnord==23.0.42
[root@1d65ff136570 testpkg]# python3 setup.py sdist
Traceback (most recent call last):
  File "/tmp/testpkg/setup.py", line 3, in <module>
    setup(
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 57, in __init__
    super().__init__(filtered)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 475, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 931, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 600, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 855, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib64/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

It affects the latest versions of both packages:
```console
[root@1d65ff136570 testpkg]# python3 -m pip list setuptools
Package        Version
-------------- -------
gpg            1.14.0
libcomps       0.1.15
packaging      21.3
pip            20.2.2
pyparsing      3.0.9
rpm            4.16.0
setuptools     62.4.0
setuptools-scm 6.4.2
tomli          2.0.1
WARNING: You are using pip version 20.2.2; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

The issue only appears when the package is installed using ```python3 setup.py install --user``` and when using ```python3 setup.py sdist```.

When using ```python3 setup.py install --user```, the following egg-zip gets copied to the user's site-packages:
```console
[root@cdefa744e88c testpkg]# unzip -l ~/.local/lib/python3.9/site-packages/fnord-23.0.42-py3.9.egg 
Archive:  /root/.local/lib/python3.9/site-packages/fnord-23.0.42-py3.9.egg
  Length      Date    Time    Name
---------  ---------- -----   ----
        1  06-14-2022 09:40   EGG-INFO/zip-safe
---------                     -------
        1                     1 file
```

When the package is installed using ```python3 -m pip install --user .```,  the following directory gets created instead. This does not cause a problem with any sdist invocation:
```console
[root@cdefa744e88c testpkg]# ls -lh ~/.local/lib/python3.9/site-packages/fnord-23.0.42-py3.9.egg-info/
total 16K
-rw-r--r-- 1 root root 51 Jun 14 09:44 PKG-INFO
-rw-r--r-- 1 root root  0 Jun 14 09:44 SOURCES.txt
-rw-r--r-- 1 root root  1 Jun 14 09:44 dependency_links.txt
-rw-r--r-- 1 root root 56 Jun 14 09:44 installed-files.txt
-rw-r--r-- 1 root root  1 Jun 14 09:44 top_level.txt
```

The issue disappears when using ```python3 -m build --sdist``` due to the automatic venv isolation. It re-appears when using the following invocation:

```console
[root@cdefa744e88c testpkg]# python3 -m build --sdist -n
* Getting dependencies for sdist...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 297, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 181, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 3, in <module>
    setup(
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 57, in __init__
    super().__init__(filtered)
  File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 475, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 931, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 600, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 855, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib64/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
```

I suspect that the venv-isolation hides the setuptools_scm package that triggers the issue.

**Comment by jaseg** [comment]
I have updated the issue description with repro instructions. I find it weird that ```python3 setup.py install --user``` and ```python3 -m pip install --user .``` produce different results given the same input.

**Comment by abravalheri** [comment]
Hi @jaseg, thank you very much for checking that and for the detailed investigation.
What seems to be happening here is the following:

- The `.egg-info` directory is not exactly part of any standard created by PyPA.
  The `PKG-INFO` file at the root of the `sdist` is the only thing that seems to be required.
  The `sdist` created by setuptools *does seem* to conform with that spec...
- `importlib.metadata` seems to be making an extra effort to support existing `.egg-info` folders (which are in theory would only be installed via deprecated mechanisms such as an `.egg` distribution or `python setup.py install`). But seems to assume (understandably) that `.egg-info` directories would contain a `PKG-INFO`.

There are several things that could be done in this situation:
  - Modify `setuptools` to ensure `.egg-info` contains `PKG-INFO`
  - Modify `importlib.metadata` to ignore `.egg-info` directories that don't contain `PKG-INFO` files
  - Modify `setuptools-scm` to catch the error and ignore it
  - Modify `setuptools` to catch the error and ignore it.

However, it is important to recognise that the situation just seems to be problematic when a deprecated installation/build method is used. Moreover, we can also consider that the cause of the problem is a edge case very unlikely to happen...

With all these things in mind, I don't think it is worth right now to diverge the setuptools development efforts to fix a feature that is inevitably going to be removed and that we actively tell the users to not use...

That said, I would be more than happy to review any PR addressing this issue. If you would like to work on this, I think we can leave this issue open for a while, otherwise it seems to make little sense to me to keep it open (unless another person would like to tackle it).

If you (or other member of the community) would like to provide a PR, the following is an important tip:

- Avoid changing `setuptools/_distutils` directory. This directory is periodically pulled from the https://github.com/pypa/distutils repository and any changes made there are likely to be overwritten.
  If anyone would like to change code in `setuptools/_distutils`, the recommendation is that they contact the `pypa/distutils` team to see if they are supportive of the change, and then provide the PR directly to that repository.

What are your thoughts?

**Comment by abravalheri** [comment]
> I have updated the issue description with repro instructions. I find it weird that python3 setup.py install --user and python3 -m pip install --user . produce different results given the same input.

`python3 setup.py install --user` uses `easy_install` behind the scenes, while `pip install --user` relies on, well, `pip`. `easy_install` is long deprecated.

**Comment by jaseg** [comment]
Hi @abravalheri,

I think there are two things that would be good to change.

1. When any error is thrown inside setuptools during parsing of a package, setuptools should augment the error with human-readable information on the path of the package it tried to parse. Something like ```raise SystemError(f'Cannot parse package at {path}') from e ```. This would allow easier troubleshooting by users and would make sense regardless if you think this particular bug is likely or not. Some python users might not even be aware that ~/.local/lib/pythonX.XX/site-packages is a thing, and if they encountered an issue like this that would make it really difficult for them to debug. This is compounded by the fact that a crash like this might happen long after the questionable package was installed.

2. Given that broken packages can happen in practice, and it may not even be the user's fault (e.g. they downloaded a broken package from somewhere else, or they had a system crash and some package metadata files got lost in that), I think setuptools should never throw an error while parsing a package. The brute-force approach would be to catch any exception inside the package parsing code and transform it into a warning, the nicer way would be to make sure everything that parses packages properly checks the package for correctness first.

I think setuptools_scm is totally not at fault here, because AFAICT it only uses the setuptools API as intended. Though I think the fact that merely having it installed changes the behavior of setuptools is odd and may cause more trouble in the future, I think that is a separate issue.

**Comment by abravalheri** [comment]
Hi @jaseg, I would be very happy to review a PR addressing the suggestions you provided, they seem pretty reasonable to me. Would you be interested in submitting one?

**Comment by sandersantema** [comment]
It seems I've ran into this bug in the wild. I'm running OpenSuSE Tumbleweed, ans so far it seems that I'm experiencing this bug with both `python3.9` and `python3.10` system wide installs. Is this issue solved already by the approach suggested by @jaseg ? If not I'd like to post whichever info would be relevant, if you could provide me with some instructions as to which information is important exactly and how to get it. 

I'm experiencing this bug with and without `setuptools_scm` installed.

Could any of you advise me on the best way to find and remove the invalid package(s)?

**Comment by jaseg** [comment]
@sandersantema I used pdb to debug the issue. By running setup.py with pdb (something like `python3 -m pdb setup.py ...`), pdb will break and give you a debug prompt when setuptools encounters the error parsing the invalid package. You can then walk up the stack using `where` and `up`, and print variables using `p [expr]`. If you haven't used it before, the pdb manual is [in the python docs](https://docs.python.org/3/library/pdb.html).

**Comment by sandersantema** [comment]
Thank you very much for that recommendation. Can't believe I didn't learn about pdb earlier, such a useful tool. I unfortunately wasn't able to learn much about the what caused the bug itself, but I did find the package causing the error. I was thinking it might be useful for me to upload a zip of the package directory but it seems that the whole package consists of nothing but directories.

Here's the output of `tree -a` (with repeating non-unique directories omitted) :

```
├── EGG-INFO
│   └── scripts
├── pynicotine
│   ├── plugins
│   │   ├── anti_shout
│   │   │   └── __pycache__
│   ├── __pycache__
│   └── upnp
│       └── __pycache__
└── share
    ├── applications
    ├── doc
    │   └── nicotine
    ├── icons
    │   └── hicolor
    │       ├── scalable
    │       │   ├── apps
    │       └── symbolic
    │           └── apps
    ├── locale
    ├── man
    │   └── man1
    └── metainfo

```

Given that I install this package from their git repo manually with `setup.py` I assume something went wrong once, so that might explain why the package is there.
