### ISSUE TITLE
[BUG] plat_name attribute is None with setuptools 64.0.1 and editable install

### ISSUE THREAD

**Issue by alex** [pypa/setuptools#3513]
### setuptools version

64.0.1

### Python version

3.10.6

### OS

macOS

### Description

While setting up a local virtual environment with `pip install -e .` I received an error I had not previously seen.

### Expected behavior

The package installs properly.

### How to Reproduce

1. `git clone https://github.com/pyca/cryptography`
2. `cd cryptography`
3. `python3 -m venv .venv`
4. `source .venv/bin/activate`
5. `CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS='1' LDFLAGS='/opt/homebrew/opt/openssl@3/lib/libcrypto.a /opt/homebrew/opt/openssl@3/lib/libssl.a' CFLAGS='-I/opt/homebrew/opt/openssl@3/include' pip install -r dev-requirements.txt` (environment variables are specific to macOS)

### Output

```console
[...]
Building wheels for collected packages: cryptography
  Building editable for cryptography (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for cryptography (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      running editable_wheel
      creating /private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-wheel-mpo_h63u/tmp2d0kyx1o/cryptography.egg-info
      writing /private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-wheel-mpo_h63u/tmp2d0kyx1o/cryptography.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-wheel-mpo_h63u/tmp2d0kyx1o/cryptography.egg-info/dependency_links.txt
      writing requirements to /private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-wheel-mpo_h63u/tmp2d0kyx1o/cryptography.egg-info/requires.txt
      writing top-level names to /private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-wheel-mpo_h63u/tmp2d0kyx1o/cryptography.egg-info/top_level.txt
      writing manifest file '/private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-wheel-mpo_h63u/tmp2d0kyx1o/cryptography.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-wheel-mpo_h63u/tmp2d0kyx1o/cryptography.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files found matching 'vectors'
      warning: no previously-included files matching '*' found under directory 'vectors'
      warning: no previously-included files matching '*' found under directory '.github'
      warning: no previously-included files found matching 'release.py'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'dev-requirements.txt'
      warning: no previously-included files found matching 'tox.ini'
      warning: no previously-included files found matching 'mypy.ini'
      warning: no previously-included files matching '*' found under directory '.circleci'
      adding license file 'LICENSE'
      adding license file 'LICENSE.APACHE'
      adding license file 'LICENSE.BSD'
      adding license file 'LICENSE.PSF'
      writing manifest file '/private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-wheel-mpo_h63u/tmp2d0kyx1o/cryptography.egg-info/SOURCES.txt'
      creating '/private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-wheel-mpo_h63u/tmp2d0kyx1o/cryptography-38.0.0.dev1.dist-info'
      adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
      adding license file "LICENSE.PSF" (matched pattern "LICEN[CS]E*")
      adding license file "LICENSE.APACHE" (matched pattern "LICEN[CS]E*")
      adding license file "LICENSE.BSD" (matched pattern "LICEN[CS]E*")
      Traceback (most recent call last):
        File "/private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-build-env-k9m_30lt/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 136, in run
          bdist_wheel.write_wheelfile(self.dist_info_dir)
        File "/private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-build-env-k9m_30lt/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 389, in write_wheelfile
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/private/var/folders/tc/9_n6gvsx251b2j70g7bny1lm0000gn/T/pip-build-env-k9m_30lt/overlay/lib/python3.10/site-packages/setuptools_rust/setuptools_ext.py", line 254, in get_tag
          if self.plat_name.startswith("macosx-") and arch_flags:
      AttributeError: 'NoneType' object has no attribute 'startswith'
      
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation/ for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq/
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation/#rust
      
          Python: 3.10.6
          platform: macOS-12.5-arm64-arm-64bit
          pip: n/a
          setuptools: 64.0.1
          setuptools_rust: 1.5.0
          rustc: 1.63.0 (4b91a6ea7 2022-08-08)
          =============================DEBUG ASSISTANCE=============================
      
      error: Support for editable installs via PEP 660 was recently introduced
      in `setuptools`. If you are seeing this error, please report to:
      
      https://github.com/pypa/setuptools/issues
      
      Meanwhile you can try the legacy behavior by setting an
      environment variable and trying to install again:
      
      SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

```

**Comment by abravalheri** [comment]
Hi @alex, thank you very much for reporting this.

I created #3517 which will hopefully fix this problem. I plan to wait until the CI finishes running (which will likely take ages) and then create a new release.

Unfortunately, I don't have access to a macOS machine to ensure the issue is fixed for that platform, so please feel free to try it out (either from the open PR or after the release is out) and let me know if there are problems left.

(If the issue automatically closes because of the PR, and the problem still persists, let me know and I will reopen it - or a new one if it is a different problem).

**Comment by alex** [comment]
If you're on Linux you should be able to reproduce by simply omitting those environment variables. If you're on Windows, it's more complicated :-)

**Comment by abravalheri** [comment]
Yes, I did a test on Linux and managed to reproduce the problem.
When I apply the patch, the project installs in editable mode without a problem. Let's hope the fix also works on macOS.

**Comment by alex** [comment]
Great, thanks!
