### ISSUE TITLE
ImportError: <module 'setuptools.command.egg_info' from '/usr/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/egg_info.pyc'> has no 'write_setup_requirements' attribute

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#356]
Originally reported by: **bbbco (Bitbucket: [bbbco](http://bitbucket.org/bbbco), GitHub: [bbbco](http://github.com/bbbco))**

---

We are using setuptools on several Jenkins jobs in our environment. Yesterday, jobs ran fine. Today, some of them are failing while installing setuptools on a Python 2.7 environment. It now throws this error:

```
#!python

[root@jenkins workspace]# virtualenv .
New python executable in ./bin/python2.7
Not overwriting existing python script ./bin/python (you must use ./bin/python2.7)
Installing setuptools...............................................
  Complete output from command /var/lib/jenkins/jobs/FFS-Scal...on2.7 -c "#!python
\"\"\"Bootstrap setuptoo...




" --always-copy -U setuptools:
  Searching for setuptools
Reading http://pypi.python.org/simple/setuptools/
Best match: setuptools 12.4
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-12.4.zip#md5=b088ed7a43a93a1fd1fcabdf73bfa0bf
Processing setuptools-12.4.zip
Running setuptools-12.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jZFvKz/setuptools-12.4/egg-dist-tmp-jyRZ8E
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'src_root'
  warnings.warn(msg)
Traceback (most recent call last):
  File "<string>", line 278, in <module>
  File "<string>", line 239, in main
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1712, in main
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1716, in <lambda>
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 211, in run
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 446, in easy_install
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 476, in install_item
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 655, in install_eggs
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 930, in build_and_install
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 919, in run_setup
  File "build/bdist.linux-i686/egg/setuptools/sandbox.py", line 62, in run_setup
  File "build/bdist.linux-i686/egg/setuptools/sandbox.py", line 105, in run
  File "build/bdist.linux-i686/egg/setuptools/sandbox.py", line 64, in <lambda>
  File "setup.py", line 186, in <module>
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/bdist_egg.py", line 167, in run
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/egg_info.py", line 169, in run
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1959, in load
ImportError: <module 'setuptools.command.egg_info' from '/usr/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/egg_info.pyc'> has no 'write_setup_requirements' attribute
----------------------------------------
...Installing setuptools...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 8, in <module>
    load_entry_point('virtualenv==1.5.1', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python2.7/site-packages/virtualenv-1.5.1-py2.7.egg/virtualenv.py", line 558, in main
    prompt=options.prompt)
  File "/usr/lib/python2.7/site-packages/virtualenv-1.5.1-py2.7.egg/virtualenv.py", line 654, in create_environment
    install_setuptools(py_executable, unzip=unzip_setuptools)
  File "/usr/lib/python2.7/site-packages/virtualenv-1.5.1-py2.7.egg/virtualenv.py", line 384, in install_setuptools
    _install_req(py_executable, unzip)
  File "/usr/lib/python2.7/site-packages/virtualenv-1.5.1-py2.7.egg/virtualenv.py", line 360, in _install_req
    cwd=cwd)
  File "/usr/lib/python2.7/site-packages/virtualenv-1.5.1-py2.7.egg/virtualenv.py", line 624, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /var/lib/jenkins/jobs/FFS-Scal...on2.7 -c "#!python
\"\"\"Bootstrap setuptoo...




" --always-copy -U setuptools failed with error code 1

```

I have tracked it down to this recent commit. https://bitbucket.org/pypa/setuptools/commits/8bff4399a7af3d4d41d437248691f99818d1babd

This is an issue because we require the use of setuptools, but are not yet ready to upgrade python to python 3.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/356

**Comment by Bra1nsen** [comment]
any updates?
