### ISSUE TITLE
[BUG] IndentError in tmp file during editable install of dependency

### ISSUE THREAD

**Issue by rbracco** [pypa/setuptools#3623]
### setuptools version

setuptools==65.4.1

### Python version

3.8.10

### OS

Ubuntu 20.04

### Additional environment information

pip 22.2.2

### Description

I recently switched over to poetry from pipenv. I have two local repos that I want to install as editable dependencies, and one was installed successfully, but when I added the other and ran `poetry install`, and it causes an error saying there is an indentation error coming from a string of code that is being executed in `setuptools/build_meta.py` during `run_setup`

This is happening in a tmp file that gets cleaned up, so I can't debug it on my own. Please let me know if I can share anything else about my env or system that would be helpful. Thank you. 

### Relevant portion of stack trace
```python
    × Getting requirements to build editable did not run successfully.
    │ exit code: 1
    ╰─> [21 lines of output]
        Traceback (most recent call last):
          File "/home/rob/code/thunder_fresh/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/home/rob/code/thunder_fresh/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/home/rob/code/thunder_fresh/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
            return hook(config_settings)
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
            return self.get_requires_for_build_wheel(config_settings)
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 18
            classifiers=[
            ^
        IndentationError: unexpected indent
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
```

### Full stack trace
```python
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing speechdata (0.1.0 /home/rob/code/speechdata): Failed

  CalledProcessError

  Command '['/home/rob/code/thunder_fresh/.venv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--prefix', '/home/rob/code/thunder_fresh/.venv', '--upgrade', '--no-deps', '-e', '/home/rob/code/speechdata']' returned non-zero exit status 1.

  at /usr/lib/python3.8/subprocess.py:516 in run
       512│             # We don't call process.wait() as .__exit__ does that for us.
       513│             raise
       514│         retcode = process.poll()
       515│         if check and retcode:
    →  516│             raise CalledProcessError(retcode, process.args,
       517│                                      output=stdout, stderr=stderr) was installed successfully, but when I added the other and ran `poetry install`, I get the following trace

```
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing speechdata (0.1.0 /home/rob/code/speechdata): Failed

  CalledProcessError

  Command '['/home/rob/code/thunder_fresh/.venv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--prefix', '/home/rob/code/thunder_fresh/.venv', '--upgrade', '--no-deps', '-e', '/home/rob/code/speechdata']' returned non-zero exit status 1.

  at /usr/lib/python3.8/subprocess.py:516 in run
       512│             # We don't call process.wait() as .__exit__ does that for us.
       513│             raise
       514│         retcode = process.poll()
       515│         if check and retcode:
    →  516│             raise CalledProcessError(retcode, process.args,
       517│                                      output=stdout, stderr=stderr)
       518│     return CompletedProcess(process.args, retcode, stdout, stderr)
       519│ 
       520│ 

The following error occurred when trying to handle this error:

  EnvCommandError

  Command ['/home/rob/code/thunder_fresh/.venv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--prefix', '/home/rob/code/thunder_fresh/.venv', '--upgrade', '--no-deps', '-e', '/home/rob/code/speechdata'] errored with the following return code 1, and output: 
  Obtaining file:///home/rob/code/speechdata
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Checking if build backend supports build_editable: started
    Checking if build backend supports build_editable: finished with status 'done'
    Getting requirements to build editable: started
    Getting requirements to build editable: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build editable did not run successfully.
    │ exit code: 1
    ╰─> [21 lines of output]
        Traceback (most recent call last):
          File "/home/rob/code/thunder_fresh/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/home/rob/code/thunder_fresh/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main

       518│     return CompletedProcess(process.args, retcode, stdout, stderr)
       519│ 
       520│ 

The following error occurred when trying to handle this error:

  EnvCommandError

  Command ['/home/rob/code/thunder_fresh/.venv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--prefix', '/home/rob/code/thunder_fresh/.venv', '--upgrade', '--no-deps', '-e', '/home/rob/code/speechdata'] errored with the following return code 1, and output: 
  Obtaining file:///home/rob/code/speechdata
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Checking if build backend supports build_editable: started
    Checking if build backend supports build_editable: finished with status 'done'
    Getting requirements to build editable: started
    Getting requirements to build editable: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build editable did not run successfully.
    │ exit code: 1
    ╰─> [21 lines of output]
        Traceback (most recent call last):
          File "/home/rob/code/thunder_fresh/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/home/rob/code/thunder_fresh/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/home/rob/code/thunder_fresh/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
            return hook(config_settings)
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
            return self.get_requires_for_build_wheel(config_settings)
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/tmp/pip-build-env-clseqd9l/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 18
            classifiers=[
            ^
        IndentationError: unexpected indent
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/utils/env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│ 
      1478│         return decode(output)
      1479│ 
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:

  PoetryException

  Failed to install /home/rob/code/speechdata

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/utils/pip.py:51 in pip_install
       47│ 
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│ 
```

### Expected behavior

The editable install should complete successfully as it does with pipenv. 

### How to Reproduce

Unfortunately this is some combo of setuptools and my environment not liking each other, so I don't have a way to reproduce it. Locally I am doing the following 
1. cd into project folder
2. Add `speechdata = {path = "./../speechdata", develop = true}` to my pyproject.toml dependencies
3. `poetry install`

### Output

```console

```

**Comment by rbracco** [comment]
Ugh sorry to anyone who read, it was an indentation issue in the setup.py of that repo. I thought it was untouched but a character got inserted and caused this. Closing and leaving in case anyone searches for a similar issue in the future.
