### ISSUE TITLE
[BUG] project.script-files is a configuration error

### ISSUE THREAD

**Issue by anntzer** [pypa/setuptools#3665]
### setuptools version

65.5.1

### Python version

3.10

### OS

fedora37

### Description

The project.script-files key is currently described as deprecated (https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration), but using it crashes setuptools.

### Expected behavior

No crash.  (Or if the key is now unsupported, it should just be removed from the docs, not listed as deprecated.)

### How to Reproduce

Create the following pyproject.toml
```
[build-system]
requires = ["setuptools==65.5.1"]
build-backend = "setuptools.build_meta"

[project]
name = "testpkg"
version = "0.0.1"
script-files = ["myscript.py"]
```
and an empty `myscript.py` next to it.

Then run `pip wheel .` (for example).

### Output

```console
Processing /tmp/foo
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "/home/antony/miniconda3/envs/default/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/antony/miniconda3/envs/default/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/antony/miniconda3/envs/default/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-yi7zcr_g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-yi7zcr_g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-yi7zcr_g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-yi7zcr_g/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-yi7zcr_g/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-yi7zcr_g/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 868, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-yi7zcr_g/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 62, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/tmp/pip-build-env-yi7zcr_g/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 126, in read_configuration
          validate(subset, filepath)
        File "/tmp/pip-build-env-yi7zcr_g/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 51, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must not contain {'script-files'} properties
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by abravalheri** [comment]
Hi @anntzer, please note that in [our docs](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration), we describe `script-files` as part of the `[tool.setuptools]` table, not the `[project]` table.

**Comment by anntzer** [comment]
Oops, sorry for the noise!
