### ISSUE TITLE
[BUG] `_distutils_hack` sometimes breaks in `virtualenv`s

### ISSUE THREAD

**Issue by KOLANICH** [pypa/setuptools#3706]
### setuptools version

e5156411d97a683db3365e2b778c0936b5fb620a

### Python version

cpython 3.9

### OS

Ubuntu 21.10 Impish

### Additional environment information

```
Package                   Version
------------------------- -------------------
asttokens                 2.1.0
build                     0.9.0
certifi                   2022.9.24
colorama                  0.4.7.dev1
editables                 0.3
executing                 0.1.dev1+g32c2388
flit_core                 3.8.0
hatch-fancy-pypi-readme   22.8.0
hatch-vcs                 0.2.0
hatchling                 1.11.1
httpcore                  0.16.1
httpx                     0.23.1
icecream                  2.1.3
installer                 0.6.0.dev0
ipi                       0.1.dev1+g58bf835
packaging                 21.4.dev0
pathspec                  0.10.2
peval                     0.1.dev1+g2f68c8c
pip                       23.0.dev0
pluggy                    0.1.dev1+gd0c0cac
plumbum                   0.1.dev1+g4ea4a2c
Pygments                  2.13.0
pyproject_hooks           1.0.0
requests                  2.28.1
requests-file             0.1.dev1+g675c7a6
rfc3986                   2.0.0
RichConsole               0.1.dev1+g954197c
securesystemslib          0.1.dev1+gfccaee8
securesystemslib-KOLANICH 0.1.dev1+g49c432c
setuptools                65.6.2.post20221123
setuptools-scm            0.1.dev1+ga70d44b
sh                        1.14.3
sniffio                   1.3.0+dev
tomli                     2.0.1
transformerz              0.1.dev1+g607eef8
tuf                       2.0.0
tuft                      0.1.dev1+g1a99478
typing_extensions         4.4.0
wheel                     0.38.4
```

### Description

It seems that `setuptools` breaks when the check sees a path from a venv. It is strange. It started happening only after installation of the bunch of packages into the venv.

### Expected behavior

No assertion

### How to Reproduce

I have encountered it when debugging `ipi` (my new package manager, replacement for pip) self-bootstrapping within a venv. I'm not sure you should try 

### Output

```console
File "~/ipi.py/ipi/utils/metadataExtractor.py", line 24, in <module>
  from setuptools.config import read_configuration as parseSetupCfg
File "~/ipi.py/test_venv/lib/python3.9/site-packages/setuptools/__init__.py", line 8, in <module>
  import _distutils_hack.override  # noqa: F401
File "~/ipi.py/test_venv/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
  __import__('_distutils_hack').do_override()
File "~/ipi.py/test_venv/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 77, in do_override
  ensure_local_distutils()
File "~/ipi.py/test_venv/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
  assert '_distutils' in core.__file__, core.__file__
AssertionError: /usr/lib/python3.9/distutils/core.py
```

**Comment by KOLANICH** [comment]
Condition when triggered `distutils` imported before `setuptools`. Workaround: import `setuptools` before importing any package that can import `distutils` internally, in my case it was `pip`.

**Comment by joshuataylor** [comment]
(Sorry for the "me too!" comment).

I am also getting this with Poetry, when installing a package (future).

Here is the attached Github action log, incase it's helpful:

<details>
<summary>click to fold out, it's long (sorry)</summary>

```
#11 18.51   CalledProcessError
#11 18.51 
#11 18.51   Command '['/opt/myapp/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/opt/myapp/.venv', '--no-deps', '/root/.cache/pypoetry/artifacts/fe/fb/57/2ea5240ca6b3bb2a9a622a4cbbc48bfbe0f64b53a125648925dda6919d/future-0.18.2.tar.gz']' returned non-zero exit status 2.
#11 18.51 
#11 18.51   at /usr/local/lib/python3.10/subprocess.py:526 in run
#11 18.56        522│             # We don't call process.wait() as .__exit__ does that for us.
#11 18.56        523│             raise
#11 18.56        524│         retcode = process.poll()
#11 18.56        525│         if check and retcode:
#11 18.56     →  526│             raise CalledProcessError(retcode, process.args,
#11 18.56        527│                                      output=stdout, stderr=stderr)
#11 18.56        528│     return CompletedProcess(process.args, retcode, stdout, stderr)
#11 18.56        529│ 
#11 18.56        530│ 
#11 18.56 
#11 18.56 The following error occurred when trying to handle this error:
#11 18.56 
#11 18.56 
#11 18.56   EnvCommandError
#11 18.56 
#11 18.56   Command ['/opt/myapp/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/opt/myapp/.venv', '--no-deps', '/root/.cache/pypoetry/artifacts/fe/fb/57/2ea5240ca6b3bb2a9a622a4cbbc48bfbe0f64b53a125648925dda6919d/future-0.18.2.tar.gz'] errored with the following return code 2, and output: 
#11 18.56   Processing /root/.cache/pypoetry/artifacts/fe/fb/57/2ea5240ca6b3bb2a9a622a4cbbc48bfbe0f64b53a125648925dda6919d/future-0.18.2.tar.gz
#11 18.56     Installing build dependencies: started
#11 18.56     Installing build dependencies: finished with status 'done'
#11 18.56     Getting requirements to build wheel: started
#11 18.56     Getting requirements to build wheel: finished with status 'done'
#11 18.56     Preparing metadata (pyproject.toml): started
#11 18.56     Preparing metadata (pyproject.toml): finished with status 'done'
#11 18.56   ERROR: Exception:
#11 18.56   Traceback (most recent call last):
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
#11 18.56       status = run_func(*args)
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
#11 18.56       return func(self, options, args)
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 400, in run
#11 18.56       requirement_set = resolver.resolve(
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
#11 18.56       collected = self.factory.collect_root_requirements(root_reqs)
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
#11 18.56       req = self._make_requirement_from_install_req(
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
#11 18.56       cand = self._make_candidate_from_link(
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
#11 18.56       self._link_candidate_cache[link] = LinkCandidate(
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
#11 18.56       super().__init__(
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
#11 18.56       self.dist = self._prepare()
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
#11 18.56       dist = self._prepare_distribution()
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
#11 18.56       return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
#11 18.56       return self._prepare_linked_requirement(req, parallel_builds)
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
#11 18.56       dist = _get_prepared_distribution(
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
#11 18.56       abstract_dist.prepare_distribution_metadata(
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
#11 18.56       self.req.prepare_metadata()
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 535, in prepare_metadata
#11 18.56       self.metadata_directory = generate_metadata(
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
#11 18.56       distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 706, in prepare_metadata_for_build_wheel
#11 18.56       return super().prepare_metadata_for_build_wheel(
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 189, in prepare_metadata_for_build_wheel
#11 18.56       return self._call_hook('prepare_metadata_for_build_wheel', {
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 319, in _call_hook
#11 18.56       raise BackendUnavailable(data.get('traceback', ''))
#11 18.56   pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
#11 18.56     File "/opt/myapp/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 77, in _build_backend
#11 18.56       obj = import_module(mod_path)
#11 18.56     File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
#11 18.56       return _bootstrap._gcd_import(name[level:], package, level)
#11 18.56     File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
#11 18.56     File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
#11 18.56     File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
#11 18.56     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
#11 18.56     File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
#11 18.56     File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
#11 18.56     File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
#11 18.56     File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
#11 18.56     File "<frozen importlib._bootstrap_external>", line 883, in exec_module
#11 18.56     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
#11 18.56     File "/tmp/pip-build-env-ilufj6fg/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 8, in <module>
#11 18.56       import _distutils_hack.override  # noqa: F401
#11 18.56   ModuleNotFoundError: No module named '_distutils_hack.override'
#11 18.56   
#11 18.56   
#11 18.56 
#11 18.56   at /opt/poetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1476 in _run
#11 18.61       1472│                 output = subprocess.check_output(
#11 18.61       1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
#11 18.61       1474│                 )
#11 18.61       1475│         except CalledProcessError as e:
#11 18.61     → 1476│             raise EnvCommandError(e, input=input_)
#11 18.61       1477│ 
#11 18.61       1478│         return decode(output)
#11 18.61       1479│ 
#11 18.61       1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
#11 18.61 
#11 18.61 The following error occurred when trying to handle this error:
#11 18.61 
#11 18.61 
#11 18.61   PoetryException
#11 18.61 
#11 18.61   Failed to install /root/.cache/pypoetry/artifacts/fe/fb/57/2ea5240ca6b3bb2a9a622a4cbbc48bfbe0f64b53a125648925dda6919d/future-0.18.2.tar.gz
#11 18.61 
#11 18.61   at /opt/poetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:51 in pip_install
#11 18.61        47│ 
#11 18.61        48│     try:
#11 18.61        49│         return environment.run_pip(*args)
#11 18.61        50│     except EnvCommandError as e:
#11 18.61     →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
#11 18.61        52│ 
#11 18.61 
#11 ERROR: executor failed running [/bin/sh -c poetry install --only main]: exit code: 1
```
</details>
