### ISSUE TITLE
setuptools.setup() should print warning / error for invalid value of version parametre

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#372]
Originally reported by: **arfrever (Bitbucket: [arfrever](http://bitbucket.org/arfrever), GitHub: [arfrever](http://github.com/arfrever))**

---

setuptools.setup() should print warning / error for invalid value of version parametre.

E.g. setup.py of python-hglib-1.6 passes version="unknown", which results in installation (without any warnings / errors) of /usr/lib/pythonX.Y/site-packages/python_hglib-unknown-pyX.Y.egg-info. Then using of pip fails:

```
$ pip install --user ${something}
Exception:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/pip/basecommand.py", line 246, in main
    status = self.run(options, args)
  File "/usr/lib64/python2.7/site-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib64/python2.7/site-packages/pip/req/req_set.py", line 345, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/usr/lib64/python2.7/site-packages/pip/req/req_set.py", line 290, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/usr/lib64/python2.7/site-packages/pip/req/req_set.py", line 415, in _prepare_file
    req_to_install, finder)
  File "/usr/lib64/python2.7/site-packages/pip/req/req_set.py", line 366, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib64/python2.7/site-packages/pip/req/req_install.py", line 986, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 539, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 419, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 940, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 817, in resolve
    env = Environment(self.entries)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 997, in __init__
    self.scan(search_path)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1027, in scan
    self.add(dist)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1047, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2474, in hashcmp
    self.parsed_version,
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2521, in parsed_version
    self._parsed_version = parse_version(self.version)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 209, in parse_version
    return SetuptoolsVersion(v)
  File "/usr/lib64/python2.7/site-packages/packaging/version.py", line 212, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
InvalidVersion: Invalid version: 'unknown'

```

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/372

**Comment by jaraco** [comment]
This was fixed in 9382fa0c05.
