### ISSUE TITLE
error: Support for editable installs via PEP 660 was recently introduced in `setuptools`.

### ISSUE THREAD

**Issue by ldenisse42** [pypa/setuptools#3736]
Hi, 

I was installing the python package Biogeme, by cloning the repository fron its source and then executing "pip install -ve ." where the file setup.py is located. However, the following error is shown:

File "C:\Users\ldtorreschavez\AppData\Local\Temp\pip-build-env-my58_d43\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 423, in compile
      raise CompileError(msg)
  distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  error: Support for editable installs via PEP 660 was recently introduced
  in `setuptools`.
 

Does anyone know how to sort this out?

Thanks!

**Comment by abravalheri** [comment]
Hi @ldenisse42 can you try to install the package in the "normal mode" (without the `-e/--editable` flag), just to see if it works?

**Comment by burakatakan** [comment]
I seem to have a similar problem, while trying to install pyapprox:
(I also set the system variable, as given at the end)


pyapprox-base) C:\Users\a\Progs\pyapprox>pip install -e . --no-build-isolation
Obtaining file:///C:/Users/a/Progs/pyapprox
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: scipy>=1.0.0 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (1.9.3)
Requirement already satisfied: sympy in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (1.11.1)
Requirement already satisfied: pytest-cov in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (3.0.0)
Requirement already satisfied: Cython in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (0.29.32)
Requirement already satisfied: torch in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (1.12.1)
Requirement already satisfied: pytest>=4.6 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (7.1.2)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (1.1.3)
Requirement already satisfied: numba in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (0.56.4)
Requirement already satisfied: networkx in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (2.8.4)
Requirement already satisfied: numpy>=1.16.4 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (1.23.4)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pyapprox==1.0.0) (3.6.2)
Requirement already satisfied: attrs>=19.2.0 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pytest>=4.6->pyapprox==1.0.0) (22.1.0)
Requirement already satisfied: iniconfig in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pytest>=4.6->pyapprox==1.0.0) (1.1.1)
Requirement already satisfied: packaging in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pytest>=4.6->pyapprox==1.0.0) (22.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pytest>=4.6->pyapprox==1.0.0) (1.0.0)
Requirement already satisfied: py>=1.8.2 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pytest>=4.6->pyapprox==1.0.0) (1.11.0)
Requirement already satisfied: tomli>=1.0.0 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pytest>=4.6->pyapprox==1.0.0) (2.0.1)
Requirement already satisfied: atomicwrites>=1.0 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pytest>=4.6->pyapprox==1.0.0) (1.4.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pytest>=4.6->pyapprox==1.0.0) (0.4.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from matplotlib->pyapprox==1.0.0) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from matplotlib->pyapprox==1.0.0) (9.3.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from matplotlib->pyapprox==1.0.0) (4.25.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from matplotlib->pyapprox==1.0.0) (1.0.5)
Requirement already satisfied: pyparsing>=2.2.1 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from matplotlib->pyapprox==1.0.0) (3.0.9)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from matplotlib->pyapprox==1.0.0) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from matplotlib->pyapprox==1.0.0) (1.4.2)
Requirement already satisfied: importlib-metadata in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from numba->pyapprox==1.0.0) (4.11.3)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from numba->pyapprox==1.0.0) (0.39.1)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from numba->pyapprox==1.0.0) (65.5.0)
Requirement already satisfied: coverage[toml]>=5.2.1 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from pytest-cov->pyapprox==1.0.0) (6.3.2)
Requirement already satisfied: joblib>=1.0.0 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from scikit-learn->pyapprox==1.0.0) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from scikit-learn->pyapprox==1.0.0) (2.2.0)
Requirement already satisfied: mpmath>=0.19 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from sympy->pyapprox==1.0.0) (1.2.1)
Requirement already satisfied: typing_extensions in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from torch->pyapprox==1.0.0) (4.4.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from python-dateutil>=2.7->matplotlib->pyapprox==1.0.0) (1.16.0)
Requirement already satisfied: zipp>=0.5 in c:\programdata\anaconda3\envs\pyapprox-base\lib\site-packages (from importlib-metadata->numba->pyapprox==1.0.0) (3.8.0)
Building wheels for collected packages: pyapprox
  Building editable for pyapprox (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for pyapprox (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [64 lines of output]
      CYTHONIZING
      running editable_wheel
      creating C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox.egg-info
      writing C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox.egg-info\PKG-INFO
      writing dependency_links to C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox.egg-info\dependency_links.txt
      writing requirements to C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox.egg-info\requires.txt
      writing top-level names to C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox.egg-info\top_level.txt
      writing manifest file 'C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox.egg-info\SOURCES.txt'
      reading manifest file 'C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox.egg-info\SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox.egg-info\SOURCES.txt'
      creating 'C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox-1.0.0.dist-info'
      adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
      creating C:\Users\atakan\AppData\Local\Temp\pip-wheel-y2aqt8y9\tmpqkpsr8ea\pyapprox-1.0.0.dist-info\WHEEL
      running build_py
      running build_ext
      building 'pyapprox.cython.adaptive_sparse_grid' extension
      C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\wheel\bdist_wheel.py:80: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
        if get_flag('Py_DEBUG',
      Traceback (most recent call last):
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\command\editable_wheel.py", line 140, in run
          self._create_wheel_file(bdist_wheel)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\command\editable_wheel.py", line 330, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\command\editable_wheel.py", line 261, in _run_build_commands
          self._run_build_subcommands()
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\command\editable_wheel.py", line 288, in _run_build_subcommands
          self.run_command(name)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 344, in compile
          self.initialize()
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\ProgramData\Anaconda3\envs\pyapprox-base\lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      error: Support for editable installs via PEP 660 was recently introduced
      in `setuptools`. If you are seeing this error, please report to:

      https://github.com/pypa/setuptools/issues

      Meanwhile you can try the legacy behavior by setting an
      environment variable and trying to install again:

      SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for pyapprox
Failed to build pyapprox
ERROR: Could not build wheels for pyapprox, which is required to install pyproject.toml-based projects

(pyapprox-base) C:\Users\atakan\sciebo\Progs\pyapprox>pip install -e . --no-build-isolation

**Comment by abravalheri** [comment]
Hi @burakatakan could you please try without the `-e` first? Does the error still persist? Is the error message without the `-e` any helpful to identify the problem?

**Comment by burakatakan** [comment]
I had this -e included, because this was given on the pyapprox installation site. In the meanwhile I installed Microsoft Visual C++ 14.0 as said above. Now it works.

@ abravalheri :Thanks for your help!

**Comment by Twistedsnail** [comment]
Hi @abravalheri, I was having an issue similar to above except my symptoms were:
 - Install works both without the `-e` flag
 - Install works with `-e` flag
 - Install fails when passing custom flag `--config-settings="--build-option=editable_wheel --my-option"`

The error was surprising as it complained about `bdist_wheel`:
```
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      /tmp/pip-build-env-3nabylca/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running egg_info
      writing MyPackage.egg-info/PKG-INFO
      writing dependency_links to MyPackage.egg-info/dependency_links.txt
      writing top-level names to MyPackage.egg-info/top_level.txt
      reading manifest file 'MyPackage.egg-info/SOURCES.txt'
      writing manifest file 'MyPackage.egg-info/SOURCES.txt'
      running editable_wheel
      writing dist/MyPackage.egg-info/PKG-INFO
      writing dependency_links to dist/MyPackage.egg-info/dependency_links.txt
      writing top-level names to dist/MyPackage.egg-info/top_level.txt
      reading manifest file 'dist/MyPackage.egg-info/SOURCES.txt'
      writing manifest file 'dist/MyPackage.egg-info/SOURCES.txt'
      creating '/home/nathan/pipeline/unstable/ProjectRoot/tests/integration_tests/test_packages/example_package/dist/MyPackage-1.0.0.dist-info'
      Traceback (most recent call last):
        File "/tmp/pip-build-env-3nabylca/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 133, in run
          self._ensure_dist_info()
        File "/tmp/pip-build-env-3nabylca/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 161, in _ensure_dist_info
          dist_info.run()
        File "/tmp/pip-build-env-3nabylca/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 101, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-3nabylca/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-3nabylca/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-3nabylca/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 956, in get_command_class
          return _Distribution.get_command_class(self, command)
        File "/tmp/pip-build-env-3nabylca/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 844, in get_command_class
          raise DistutilsModuleError("invalid command '%s'" % command)
      distutils.errors.DistutilsModuleError: invalid command 'bdist_wheel'
      error: Support for editable installs via PEP 660 was recently introduced
      in `setuptools`. If you are seeing this error, please report to:
      
      https://github.com/pypa/setuptools/issues
      
      Meanwhile you can try the legacy behavior by setting an
      environment variable and trying to install again:
      
      SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
```

Another hint was that another package that supported a custom flag WASN'T failing despite using the same technique.
Going from the info above, I eventually found that I was missing `wheel` from the `build_requires` section.

**Comment by abravalheri** [comment]
@Twistedsnail, I am afraid don't understand what you are trying to achieve in this example...

My (limited) understand of what is happening is the following:

- When you run `pip install . --config-settings="--build-option=editable_wheel --my-option"`, you are trying to *sneak in a command* to run while other commands are running (the `--build-option` will be passed when creating both sdists and wheels, and for the `get_requires_for_build_wheel` hook).
- Since you are sneaking in `editable_wheel` when setuptools is preparing to run `get_requires_for_build_wheel` it is expected that the build will fail because of the absence of the build dependency.
- If you add `wheel` to `pyproject.toml`'s `[build-system] requires` attribute, then the build will proceed, because it will not depend on setuptools automatically telling pip that `wheel` is needed.

If my understanding is correct, the way you are running `pip` is expected to fail.

Please also try to not use the `editable_wheel` command directly. As stated in `editable_wheel` docstring this command is reserved for setuptools internal use.

**Comment by Twistedsnail** [comment]
@abravalheri, that's not quite right.

`pip install <flags> --config-settings ... <package>` and `python3 -m build --config-settings ... <package>` allow you to pass  `KEY=VALUE` items to the build backend.

In setuptools, setting `KEY` to the name of a command class that has a matching item `VALUE` in `additional_user_options` will result in the attribute `VALUE` being passed set at `finalize_options` time. This can be used to write custom command classes to extend setuptools behaviour.

So `--config-settings="--build-option=editable_wheel --my-option"` doesn't try to sneak in a command, but tries to pass a custom flag to the `editable_wheel` command class passed to `setuptools.setup`.

I should mention that if you pass a `KEY` that doesn't match a setuptools command that is expected to run then setuptools will correctly exit with an error message. `editable_wheel` (previously `editable`, previously previously `develop`) only runs when `-e` or `--editable` is passed to `pip`

Anyway, the error message was surprising and there wasn't much of a hint as to why `bdist_wheel` was suddenly not a valid command class when `config-settings`  were passed. It was the above hint from @burakatakan that maybe a prerequisite wasn't satisfied that helped solve this.

**Comment by abravalheri** [comment]
> In setuptools, setting `KEY` to the name of a command class that has a matching item `VALUE` in `additional_user_options` will result in the attribute `VALUE` being passed set at `finalize_options` time. This can be used to write custom command classes to extend setuptools behaviour.

Hi @Twistedsnail, could you please point out where did you find this information (about how setuptools handles `KEY=VALUE`)? I went through the docs and did not find any reference to that... I also went through PEP 517 again and it does not specify specifically how the key value pairs should be handled[^0]... It is up to each backend.

Please let me know if you find this information somewhere, because we need to correct it.

[^0]: I find it interesting that you mention specifically `additional_user_options`, I did a code grep in the setuptools repository + looked it up in https://grep.app and I could not find this being used in the code/docs. I might be missing something...

---

##### [DEEP DIVE BELOW][^1]

That is not really how setuptools handles `KEY=VALUE` in `config_settings`. Instead, there are only 4 things you can do with `config_settings`:

- `verbose=True`: here the key is `verbose` (or `--verbose`, so `python -m build -C--verbose` also works)
- `quiet=True`: here the key is `quiet` (or `--quiet`, so `python -m build -C--quiet` also works)
- `--global-option=...`: here the key is `--global-option` and the part after `=` is the value
- `--build-option=...`: here the key is `--build-option` and the part after `=` is the value

All the rest is ignored.
The way `setuptools` uses these values (right now[^1]) is the following:

- We have a "internal command" template which is roughly equivalent to the following:
  `python setup.py [--verbose | --quiet] <*--global-option> COMMAND <*--build-option>`


- `<*--global-option>` and `<*--build-option>` are replaced by their contents in `config_settings`
- `--verbose` or `--quiet` might appear depending on `config_settings`
- `COMMAND` is replaced according to the PEP 517/660 hook that is called.
  - In `get_requires_for_build_*`, `COMMAND` is `egg_info`
  - In `prepare_metadata_for_*`, `COMMAND` is `dist_info`
  - In `build_wheel`, `COMMAND` is `bdist_wheel`
  - In `build_sdist`, `COMMAND` is `sdist`
  - In `build_editable`, `COMMAND` is `editable_wheel`

Please not that `--build-option` and `--config-option` are *escape hatches* for advanced devs that need some level of compatibility with `python setup.py`. They are supported in a best effort basis and the implementation has no intention to cover every single use case.

If you pass a command inside `--build-option` or `--global-option`, you are effectively (and maybe accidentally) sneaking in a command to run while other commands are being executed.

With that in mind, a failure is expected for this example.

[^1]: This reflects how setuptools works right now and is subject to change in the future.


---

> I should mention that if you pass a KEY that doesn't match a setuptools command that is expected to run then setuptools will correctly exit with an error message. editable_wheel (previously editable, previously previously develop) only runs when -e or --editable is passed to pip

That's not quite right: `--build-option` or `--global-option` are advanced escape hatches that are added to the command template unconditionally. The developer that wants to use them needs to understand the implications of doing so.

<details>
<summary>We can verify that they run unconditionally with the following experiment:</summary>

```bash
> docker run --rm -it python:3.10 /bin/bash

mkdir /tmp/mypkg
cd /tmp/mypkg
touch pyproject.toml
touch mypkg.py
python -m venv .venv
.venv/bin/python -m pip install -vvv --config-settings="--build-option=bdist_egg --keep-temp" -e .


# Using pip 22.2.1 from /tmp/mypkg/.venv/lib/python3.10/site-packages/pip (python 3.10)
# Non-user install because user site-packages disabled
# Created temporary directory: /tmp/pip-ephem-wheel-cache-a2pyz892
# Created temporary directory: /tmp/pip-build-tracker-6dfr6opc
# Initialized build tracking at /tmp/pip-build-tracker-6dfr6opc
# Created build tracker: /tmp/pip-build-tracker-6dfr6opc
# Entered build tracker: /tmp/pip-build-tracker-6dfr6opc
# Created temporary directory: /tmp/pip-install-6_p732fi
# Processing /tmp/mypkg
#   Added file:///tmp/mypkg to build tracker '/tmp/pip-build-tracker-6dfr6opc'
#   Created temporary directory: /tmp/pip-build-env-kaazl35w
#   Running command pip subprocess to install build dependencies
#   Using pip 22.2.1 from /tmp/mypkg/.venv/lib/python3.10/site-packages/pip (python 3.10)
#   Collecting setuptools>=40.8.0
#     Using cached setuptools-67.0.0-py3-none-any.whl (1.1 MB)
#   Collecting wheel
#     Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
#   Installing collected packages: wheel, setuptools
#     Creating /tmp/pip-build-env-kaazl35w/overlay/bin
#     changing mode of /tmp/pip-build-env-kaazl35w/overlay/bin/wheel to 755
#   Successfully installed setuptools-67.0.0 wheel-0.38.4
# 
#   [notice] A new release of pip available: 22.2.1 -> 23.0
#   [notice] To update, run: python -m pip install --upgrade pip
#   Installing build dependencies ... done
#   Running command Getting requirements to build wheel               # <--- this is PEP 517 get_requires_for_build_wheel
#   running egg_info                                                  # <--- COMMAND=egg_info
#   creating mypkg.egg-info
#   writing mypkg.egg-info/PKG-INFO
#   writing dependency_links to mypkg.egg-info/dependency_links.txt
#   writing top-level names to mypkg.egg-info/top_level.txt
#   writing manifest file 'mypkg.egg-info/SOURCES.txt'
#   reading manifest file 'mypkg.egg-info/SOURCES.txt'
#   writing manifest file 'mypkg.egg-info/SOURCES.txt'
#   running bdist_egg                                                               # <--- this is the command that sneaks in via --build-option and is not related to wheel
#   installing library code to build/bdist.linux-x86_64/egg
#   setuptools/command/install.py:34: SetuptoolsDeprecationWarning:
#     Setup.py install is deprecated. Use build and pip and other standards-based tools.
#     warnings.warn(
#   running install_lib
#   running build_py
#   creating build
#   creating build/lib
#   copying mypkg.py -> build/lib
#   creating build/bdist.linux-x86_64
#   creating build/bdist.linux-x86_64/egg
#   copying build/lib/mypkg.py -> build/bdist.linux-x86_64/egg
#   byte-compiling build/bdist.linux-x86_64/egg/mypkg.py to mypkg.cpython-310.pyc
#   creating build/bdist.linux-x86_64/egg/EGG-INFO
#   copying mypkg.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
#   copying mypkg.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
#   copying mypkg.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
#   copying mypkg.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
#   zip_safe flag not set; analyzing archive contents...
#   creating dist
#   creating 'dist/mypkg-0.0.0-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
#   removing 'build/bdist.linux-x86_64/egg' (and everything under it)
#   Getting requirements to build wheel ... done
#   Created temporary directory: /tmp/pip-modern-metadata-tyrp1di1
#   Running command Preparing metadata (pyproject.toml)
#   running dist_info
#   creating /tmp/pip-modern-metadata-tyrp1di1/mypkg.egg-info
#   writing /tmp/pip-modern-metadata-tyrp1di1/mypkg.egg-info/PKG-INFO
#   writing dependency_links to /tmp/pip-modern-metadata-tyrp1di1/mypkg.egg-info/dependency_links.txt
#   writing top-level names to /tmp/pip-modern-metadata-tyrp1di1/mypkg.egg-info/top_level.txt
#   writing manifest file '/tmp/pip-modern-metadata-tyrp1di1/mypkg.egg-info/SOURCES.txt'
#   reading manifest file '/tmp/pip-modern-metadata-tyrp1di1/mypkg.egg-info/SOURCES.txt'
#   writing manifest file '/tmp/pip-modern-metadata-tyrp1di1/mypkg.egg-info/SOURCES.txt'
#   creating '/tmp/pip-modern-metadata-tyrp1di1/mypkg-0.0.0.dist-info'
#   Preparing metadata (pyproject.toml) ... done
#   Source in /tmp/mypkg has version 0.0.0, which satisfies requirement mypkg==0.0.0 from file:///tmp/mypkg
#   Removed mypkg==0.0.0 from file:///tmp/mypkg from build tracker '/tmp/pip-build-tracker-6dfr6opc'
# Created temporary directory: /tmp/pip-unpack-wf_naxyq
# ...


# You can also run a similar command, like:
# .venv/bin/python -m pip install -vvv --config-settings="--build-option=install_scripts" .
```

</details>

Note here how the command `bdist_egg` "sneaks in" while other commands run, unconditionally.


---

> Anyway, the error message was surprising and there wasn't much of a hint as to why bdist_wheel was suddenly not a valid command class when config-settings were passed.

Please feel free to submit a PR that results in a better error handling. Setuptools is a community project so contributions are welcome! (There is so much time regular contributors can commit so the best way of implementing/changing something important to you is to provide a PR 😄).
