### ISSUE TITLE
[BUG] "Failed building editable" / "Could not build wheels"

### ISSUE THREAD

**Issue by SunyataZero** [pypa/setuptools#3783]
### setuptools version

66.1.0 (have tried earlier versions back to 65.6.3)

### Python version

3.10.6

### OS

XUbuntu 22.04 (Also problem on CI server which runs Debian)

### Additional environment information

Yesterday everything was working fine on the gitlab CI server, but today it failed. So i tried building locally and got the same error as on the CI server (see description)

My first thought was to try an earlier version of setuptools, esp. after seeing that 66.1.0 was recently released. This didn't help though

Another thing i tried was checking out an earlier version of my own software, but that didn't help either. (Also i can't see why it would)

I am using the latest versions of various packages (i don't lock the versions) and so i've tried downgrading the `build` package (which had a new release on 11 jan) but that didn't help

(The `wheel` package hasn't been updated in a while so i don't think that's the issue)

### Description

When i try building i get this:

```
distutils.errors.DistutilsSetupError: Error: setup script specifies an absolute path:
```

```
  ERROR: Failed building editable for mindfulness-at-the-computer
Failed to build mindfulness-at-the-computer
ERROR: Could not build wheels for mindfulness-at-the-computer, which is required to install pyproject.toml-based projects
```

### Expected behavior

I can build the package locally and on the CI server

### How to Reproduce

1. pip3 install -e .

or

1. pip3 install .

I've included both these because the first way to produce the issue gives a traceback, and the second way is more minimal (in the sense that it doesn't seem to be an issue with editable installs)

### Output

# When running pip3 install -e .

```console

Requirement already satisfied: pycparser in ./venv/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring>=15.1->twine->mindfulness-at-the-computer==1.0.0b2.dev5) (2.21)
Building wheels for collected packages: mindfulness-at-the-computer
  Building editable for mindfulness-at-the-computer (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for mindfulness-at-the-computer (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      /tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running editable_wheel
      creating /tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer.egg-info
      writing /tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer.egg-info/entry_points.txt
      writing requirements to /tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file '/tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer-1.0.0b2.dev5.dist-info'
      creating /tmp/pip-wheel-bx07g450/.tmp-eckljrek/mindfulness_at_the_computer-1.0.0b2.dev5.dist-info/WHEEL
      running build_py
      running egg_info
      creating /tmp/tmpssu414li.build-temp/mindfulness_at_the_computer.egg-info
      writing /tmp/tmpssu414li.build-temp/mindfulness_at_the_computer.egg-info/PKG-INFO
      writing dependency_links to /tmp/tmpssu414li.build-temp/mindfulness_at_the_computer.egg-info/dependency_links.txt
      writing entry points to /tmp/tmpssu414li.build-temp/mindfulness_at_the_computer.egg-info/entry_points.txt
      writing requirements to /tmp/tmpssu414li.build-temp/mindfulness_at_the_computer.egg-info/requires.txt
      writing top-level names to /tmp/tmpssu414li.build-temp/mindfulness_at_the_computer.egg-info/top_level.txt
      writing manifest file '/tmp/tmpssu414li.build-temp/mindfulness_at_the_computer.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file '/tmp/tmpssu414li.build-temp/mindfulness_at_the_computer.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 140, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 330, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 262, in _run_build_commands
          files, mapping = self._collect_build_outputs()
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 251, in _collect_build_outputs
          files.extend(cmd.get_outputs() or [])
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py", line 131, in get_outputs
          return list(self.get_output_mapping().keys())
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py", line 140, in get_output_mapping
          return dict(sorted(mapping, key=lambda x: x[0]))
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py", line 151, in _get_package_data_output_mapping
          for package, src_dir, build_dir, filenames in self.data_files:
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py", line 72, in __getattr__
          self.data_files = self._get_data_files()
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py", line 84, in _get_data_files
          self.analyze_manifest()
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py", line 188, in analyze_manifest
          d, f = os.path.split(assert_relative(path))
        File "/tmp/pip-build-env-xbo0_3s7/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py", line 322, in assert_relative
          raise DistutilsSetupError(msg)
      distutils.errors.DistutilsSetupError: Error: setup script specifies an absolute path:
      
          /
      
      setup() arguments must *always* be /-separated paths relative to the
      setup.py directory, *never* absolute paths.
      
      error: Support for editable installs via PEP 660 was recently introduced
      in `setuptools`. If you are seeing this error, please report to:
      
      https://github.com/pypa/setuptools/issues
      
      Meanwhile you can try the legacy behavior by setting an
      environment variable and trying to install again:
      
      SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for mindfulness-at-the-computer
Failed to build mindfulness-at-the-computer
ERROR: Could not build wheels for mindfulness-at-the-computer, which is required to install pyproject.toml-based projects
make[1]: *** [Makefile:20: install] Error 1
make[1]: Leaving directory '/home/sunyata/PycharmProjects/mindfulness-at-the-computer'
make: *** [Makefile:66: build-pypi-test] Error 2
(venv) sunyata@sunyata-HP-Laptop:~/PycharmProjects/mindfulness-at-the-computer$ 

```

# When running pip3 install .

```

Building wheels for collected packages: mindfulness-at-the-computer
  Building wheel for mindfulness-at-the-computer (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for mindfulness-at-the-computer (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      /tmp/pip-build-env-lhac_3bt/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing mindfulness_at_the_computer.egg-info/PKG-INFO
      writing dependency_links to mindfulness_at_the_computer.egg-info/dependency_links.txt
      writing entry points to mindfulness_at_the_computer.egg-info/entry_points.txt
      writing requirements to mindfulness_at_the_computer.egg-info/requires.txt
      writing top-level names to mindfulness_at_the_computer.egg-info/top_level.txt
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file 'mindfulness_at_the_computer.egg-info/SOURCES.txt'
      error: Error: setup script specifies an absolute path:
      
          /
      
      setup() arguments must *always* be /-separated paths relative to the
      setup.py directory, *never* absolute paths.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mindfulness-at-the-computer
Failed to build mindfulness-at-the-computer
ERROR: Could not build wheels for mindfulness-at-the-computer, which is required to install pyproject.toml-based projects
(venv) sunyata@sunyata-HP-Laptop:~/PycharmProjects/mindfulness-at-the-computer$

**Comment by abravalheri** [comment]
Hi @SunyataZero this is probably a duplicate of https://github.com/pypa/setuptools/issues/3781 right?

If it is a duplicate would you mind close the ticket?
If it is not a duplicate, could you please provide a [reproducer](https://stackoverflow.com/help/minimal-reproducible-example) which contains a simplified version of the package you are trying to build (e.g. pyproject.toml and other files)

**Comment by SunyataZero** [comment]
@abravalheri It works now after installing 66.1.1! I'm closing the issue (but i'm confused why it didn't work when i downgraded, maybe a caching issue?)

**Comment by abravalheri** [comment]
Yes, there is some cache involved in this process I am afraid 😅
