### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jja67** [pypa/setuptools#3785]
### setuptools version

setuptools == 66.1.1

### Python version

python 3.9.8

### OS

Kali 64bit

### Additional environment information

This is only happening when i run in the pipenv

### Description

i tried to insall pcapy in the pipenv but it failed with the output as shown in the console. 

### Expected behavior

expect to install the pcapy properly in the pipenv

### How to Reproduce

1. create env by running pipenv shell --python python3
2. pipenv install pcapy

### Output

```└─$ pipenv install pypacker pcapy untangle requests 

Installing pypacker...
Installing pcapy...
⠋ Installing pcapy...[31m[1mError: [0m An error occurred while installing [32mpcapy[0m!
Error text: Collecting pcapy
  Using cached pcapy-0.11.4.tar.gz (37 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

[36m  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ujvd4y9h/pcapy_3219c8c9c8754c259483025e05a155a0/setup.py", line 49, in 
<module>
          save_init_posix = sysconfig._init_posix
      AttributeError: module 'distutils.sysconfig' has no attribute '_init_posix'

```

**Comment by abravalheri** [comment]
@jja67 thank you very much for reporting this.

I am not sure how to handle the report though, it seems that the `setup.py` file is trying to access an explicitly private attribute of the module, which is not exactly a supported use case.

Do you know if this attribute usage is documented?

Maybe the best approach would be contacting the package author.
