### ISSUE TITLE
[BUG] setuptools 66.1.1 fail to install on windows-latest github actions

### ISSUE THREAD

**Issue by 12rambau** [pypa/setuptools#3789]
### setuptools version

66.1.1

### Python version

Pyhton 3.9

### OS

Microsoft Windows Server 2022 4   10.0.20348

### Description

We had a working CI testing the pydata-sphinx-theme. Since 21/01/2023 the windos build fails (we only test Python 3.9) when installing the lib.

### Expected behavior

I was expecting setuptools to continue installing itself on windows

### How to Reproduce

on a windows CI build run: 
```
pip install setuptools
```

### Output

copied from https://github.com/pydata/pydata-sphinx-theme/actions/runs/3975640870/jobs/6815790378

```console
Collecting setuptools
Downloading setuptools-66.1.1-py3-none-any.whl (1.3 MB)
    ---------------------------------------- 1.3/1.3 MB 16.0 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
Successfully installed setuptools-66.1.1 wheel-0.38.4
Obtaining file:///D:/a/pydata-sphinx-theme/pydata-sphinx-theme
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  Preparing editable metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [16 lines of output]
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
      main()
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 179, in prepare_metadata_for_build_editable
      return hook(metadata_directory, config_settings)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-v4e4d6e1\overlay\Lib\site-packages\sphinx_theme_builder\__init__.py", line 80, in prepare_metadata_for_build_wheel
      return _generate_metadata(project, destination=Path(metadata_directory))
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-v4e4d6e1\overlay\Lib\site-packages\sphinx_theme_builder\_internal\distributions.py", line 132, in generate_metadata
      (dist_info / "METADATA").write_text(project.get_metadata_file_contents())
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\pathlib.py", line 1286, in write_text
      return f.write(data)
    File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\encodings\cp1252.py", line 19, in encode
      return codecs.charmap_encode(input,self.errors,encoding_table)[0]
  UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4da' in position 4812: character maps to <undefined>
```

**Comment by 12rambau** [comment]
my bad that's not setuptools that's from sphinx_theme_builder. sorry for the noise
