### ISSUE TITLE
[BUG] Cannot define stub-only packages

### ISSUE THREAD

**Issue by b-kamphorst** [pypa/setuptools#3796]
### setuptools version

setuptools==65.5.0

### Python version

Python 3.10.9, 3.11.1

### OS

WSL2 Ubuntu

### Description

I tried to define a stubs-package through `pyproject.toml`. A stubs-only package [MUST](https://peps.python.org/pep-0561/#stub-only-packages) follow the scheme `pkgname-stubs`, but this name is not allowed via `pyproject.toml`. More specifically:
- if `name=pkgname-stubs`, then all files are put into `pkgname_stubs` in the distribution (automatic discovery);
- manually defining `packages` and/or `package-dir` does not accept a hypen in a package name and crashes.

### Expected behavior

A package with name `pgkname-stubs` is accepted in both `name` and `packages`, and produces a valid stubs-only package.

### How to Reproduce

In an empty directory, create the `pyproject.toml` below:

```toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mypkg-stubs"
version = "0.0.0"

[tool.setuptools]
platforms = ["any"]
packages = ["mypkg-stubs"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
"*" = ["*.pyi"]
```

Also create an empty file `__init__.pyi` in `src/mypkg-stubs/`. Now, `python -m build` will crash since `pkgname-stubs` is not a valid `python-module-name`.

### Output

<details><summary>Click to see output.</summary>

```console
$ python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools, setuptools-scm)
* Getting build dependencies for sdist...
/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
configuration error: `tool.setuptools.packages` must be valid exactly by one definition (0 matches found):

    - type: array
      items: {type: string, format: 'python-module-name'}
    - type: table
      additional keys: False
      keys:
        'find':
          type: table
          additional keys: False
          keys:
            'where':
              type: array
              items: {type: string}
            'exclude':
              type: array
              items: {type: string}
            'include':
              type: array
              items: {type: string}
            'namespaces': {type: boolean}

DESCRIPTION:
    Packages that should be included in the distribution. It can be given either
    as a list of package identifiers or as a ``dict``-like structure with a
    single key ``find`` which corresponds to a dynamic call to
    ``setuptools.config.expand.find_packages`` function. The ``find`` key is
    associated with a nested ``dict``-like structure that can contain ``where``,
    ``include``, ``exclude`` and ``namespaces`` keys, mimicking the keyword
    arguments of the associated function.

GIVEN VALUE:
    [
        "mypkg-stubs"
    ]

OFFENDING RULE: 'oneOf'

DEFINITION:
    {
        "oneOf": [
            {
                "title": "Array of Python package identifiers",
                "type": "array",
                "items": {
                    "type": "string",
                    "format": "python-module-name"
                }
            },
            {
                "$id": "#/definitions/find-directive",
                "title": "'find:' directive",
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "find": {
                        "type": "object",
                        "$$description": [
                            "Dynamic `package discovery",
                            "<https://setuptools.pypa.io/en/latest/userguide/package_discovery.html>`_."
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "where": {
                                "description": "Directories to be searched for packages (Unix-style relative path)",
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "exclude": {
                                "type": "array",
                                "$$description": [
                                    "Exclude packages that match the values listed in this field.",
                                    "Can container shell-style wildcards (e.g. ``'pkg.*'``)"
                                ],
                                "items": {
                                    "type": "string"
                                }
                            },
                            "include": {
                                "type": "array",
                                "$$description": [
                                    "Restrict the found packages to just the ones listed in this field.",
                                    "Can container shell-style wildcards (e.g. ``'pkg.*'``)"
                                ],
                                "items": {
                                    "type": "string"
                                }
                            },
                            "namespaces": {
                                "type": "boolean",
                                "$$description": [
                                    "When ``True``, directories without a ``__init__.py`` file will also",
                                    "be scanned for :pep:`420`-style implicit namespaces"
                                ]
                            }
                        }
                    }
                }
            }
        ]
    }
Traceback (most recent call last):
  File "/home/bart/git/mpclab/setuptools-tester/.venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/bart/git/mpclab/setuptools-tester/.venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bart/git/mpclab/setuptools-tester/.venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 287, in get_requires_for_build_sdist
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/dist.py", line 872, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 62, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 126, in read_configuration
    validate(subset, filepath)
  File "/tmp/build-env-j_gmor26/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 51, in validate
    raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `tool.setuptools.packages`.
configuration error: `tool.setuptools.packages` must be valid exactly by one definition (0 matches found):

    - type: array
      items: {type: string, format: 'python-module-name'}
    - type: table
      additional keys: False
      keys:
        'find':
          type: table
          additional keys: False
          keys:
            'where':
              type: array
              items: {type: string}
            'exclude':
              type: array
              items: {type: string}
            'include':
              type: array
              items: {type: string}
            'namespaces': {type: boolean}


ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
```

</details>

**Comment by b-kamphorst** [comment]
Locally, I can fix the issue by changing [this line](https://github.com/pypa/setuptools/blob/6510d128c4068fbd6dc31f84ac3548d0bdbed027/setuptools/config/_validate_pyproject/formats.py#L217) to `return value.replace("-stubs","").isidentifier()`. Happy to provide a PR if this is deemed valid.

**Comment by abravalheri** [comment]
Hi @b-kamphorst thank you very much for reporting this.

It is indeed something that needs to be addressed.
Meanwhile, as a workaround, you should be able to achieve the intended result if you rely only on the autodiscovery as indicated below:

```bash
mkdir -p /tmp/mypkg-stubs/src/mypkg-stubs
touch  /tmp/mypkg-stubs/src/mypkg-stubs/__init__.pyi

cd /tmp/mypkg-stubs
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mypkg-stubs"
version = "0.0.0"

[tool.setuptools]
platforms = ["any"]

[tool.setuptools.package-data]
"*" = ["*.pyi"]
EOF

pipx run build
unzip -l dist/*.whl
# Archive:  dist/mypkg_stubs-0.0.0-py3-none-any.whl
#   Length      Date    Time    Name
# ---------  ---------- -----   ----
#         0  2023-01-25 16:32   mypkg-stubs/__init__.pyi  <---------------
#        70  2023-01-25 16:34   mypkg_stubs-0.0.0.dist-info/METADATA
#        92  2023-01-25 16:34   mypkg_stubs-0.0.0.dist-info/WHEEL
#        12  2023-01-25 16:34   mypkg_stubs-0.0.0.dist-info/top_level.txt
#       390  2023-01-25 16:34   mypkg_stubs-0.0.0.dist-info/RECORD
# ---------                     -------
#       564                     5 files
```

 

> Locally, I can fix the issue by changing [this line](https://github.com/pypa/setuptools/blob/6510d128c4068fbd6dc31f84ac3548d0bdbed027/setuptools/config/_validate_pyproject/formats.py#L217) to `return value.replace("-stubs","").isidentifier()`. Happy to provide a PR if this is deemed valid.

I think that the best approach to fix the problem would be modifying the [JSON schema](https://github.com/abravalheri/validate-pyproject/blob/v0.11/src/validate_pyproject/plugins/setuptools.schema.json#L62) to appropriate describe the valid value for this attribute.

**Comment by abravalheri** [comment]
I tried the same experiment preserving `package-dir` and the outcome is the same:

```bash
rm -rf /tmp/mypkg-stubs
mkdir -p /tmp/mypkg-stubs/src/mypkg-stubs
touch  /tmp/mypkg-stubs/src/mypkg-stubs/__init__.pyi

cd /tmp/mypkg-stubs
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mypkg-stubs"
version = "0.0.0"

[tool.setuptools]
platforms = ["any"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
"*" = ["*.pyi"]
EOF

pipx run build
unzip -l dist/*.whl
# Archive:  dist/mypkg_stubs-0.0.0-py3-none-any.whl
#   Length      Date    Time    Name
# ---------  ---------- -----   ----
#         0  2023-01-25 16:44   mypkg-stubs/__init__.pyi
#        70  2023-01-25 16:45   mypkg_stubs-0.0.0.dist-info/METADATA
#        92  2023-01-25 16:45   mypkg_stubs-0.0.0.dist-info/WHEEL
#        12  2023-01-25 16:45   mypkg_stubs-0.0.0.dist-info/top_level.txt
#       390  2023-01-25 16:45   mypkg_stubs-0.0.0.dist-info/RECORD
# ---------                     -------
#       564                     5 files
```

The problems seems to be exclusively related to `packages`.

**Comment by b-kamphorst** [comment]
Wow you are fast with that PR! Thank you so much 👍
