### ISSUE TITLE
[BUG] Import process in submodule fails under certain conditions when using pyproject.toml

### ISSUE THREAD

**Issue by alfa0112** [pypa/setuptools#3842]
### setuptools version

setuptools===65.5.0

### Python version

Python 3.11.2

### OS

Windows 10 Home

### Additional environment information

```
$ pip list
Package    Version
---------- -------
numpy      1.24.2
pip        23.0.1
setuptools 65.5.0
```

```
$ tree test_project /f
test_project
├─pkg
│  │  module1.py
│  │  __init__.py
│  └─ __version__.py
│
└─pyproject.toml
```

### Description

In the `__init__.py` of the package

- Import `__version__` from `__version__.py`
- Import classes from submodules

An error occurs during the submodule import process if I do.

---

Also, the phenomenon did not occur when the following changes were made
- When `__version__` is declared in `__init__.py`
```python
#__init__.py
# from .__version__ import __version__
__version__ = "0.1.0"

from .module1 import AwesomeClass

```
- When `import numpy` is deleted from `module1.py`
```python
# import numpy

class AwesomeClass:
    pass

```

The following changes caused the problem
- Create module2.py and change `import numpy` in `module1.py` to `import .module2`
```python
# import numpy
import .module2

class AwesomeClass:
    pass

```

Thanks for your help!

### Expected behavior

Installation is completed.

### How to Reproduce

The following is a minimally configured reproducible script.

```python
# __init__.py
from .__version__ import __version__

from .module1 import AwesomeClass

```

```python
# __version__.py
__version__ = "0.1.0"

```

```python
# module1.py
import numpy

class AwesomeClass:
    pass

```

```toml
# pyproject.toml
[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "test"
dynamic = ["version"]
dependencies = [
  "numpy"
]

[tool.setuptools.dynamic]
version = {attr = "pkg.__version__"}
```

### Output

```console
$ pip install test_project/
Processing d:\users\alfa\desktop\dev\python\test
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*. 
        warnings.warn(msg, _BetaConfiguration)
      No `packages` or `py_modules` configuration, performing automatic discovery.
      `src-layout` detected -- analysing .\src
      discovered packages -- ['pkg']
      discovered py_modules -- []
      Traceback (most recent call last):
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\expand.py", line 81, in __getattr__
          return next(
                 ^^^^^
      StopIteration
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\expand.py", line 191, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\expand.py", line 87, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: pkg has no attribute __version__
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "D:\Users\Alfa\Desktop\Dev\python\test\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Users\Alfa\Desktop\Dev\python\test\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Users\Alfa\Desktop\Dev\python\test\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\dist.py", line 885, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 62, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 140, in read_configuration
          return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 195, in expand_configuration
          return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 243, in expand
          self._expand_all_dynamic(dist, package_dir)
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 288, in _expand_all_dynamic
          version=self._obtain_version(dist, package_dir),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 337, in _obtain_version
          return _expand.version(self._obtain(dist, "version", package_dir))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 326, in _obtain
          return self._expand_directive(
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 320, in _expand_directive
          return _expand.read_attr(directive["attr"], package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\expand.py", line 194, in read_attr
          module = _load_spec(spec, module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\syana\AppData\Local\Temp\pip-build-env-9tepn12u\overlay\Lib\site-packages\setuptools\config\expand.py", line 214, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "D:\Users\Alfa\Desktop\Dev\python\test\src\pkg\__init__.py", line 3, in <module>
          from .module1 import AwesomeClass
        File "D:\Users\Alfa\Desktop\Dev\python\test\src\pkg\module1.py", line 1, in <module>
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by abravalheri** [comment]
Hi @alfa0112, please note that if you want setuptools to read `version = {attr = "..."}` you need to provide the means for this to be done... In practice this means either:

- Ensuring the attribute can be read statically using `ast.literal_eval` without having to execute any statement or expression (e.g. `import`-statements), *or*
- Ensuring all modules used during the build time are installed in the build environment, and that your modules can be executed in the build environment.

I hope that you understand that in the example you reported, it is impossible for setuptools to:

- Read your module statically with `ast.literal_eval`, because the way you have written it uses an `import`-statement that needs to be executed before the `__version__` attribute is made available.
- Execute your module, because the `numpy` dependency is missing while the project is built.

---

If you want to ensure `numpy` will be available in the build environment, please add it to your `[build-system] requires` (in `pyproject.toml`).

But I think a better alternative would be for you to modify `version = {attr = `pkg.__version__.__version__`}. You can see that working in the example below:

```bash
> docker run --rm -it python:3.11 /bin/bash

mkdir -p /tmp/test_project/pkg
cd /tmp/test_project
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "test"
dynamic = ["version"]
dependencies = [
  "numpy"
]

[tool.setuptools.dynamic]
version = {attr = "pkg.__version__.__version__"}
EOF


cat <<EOF > pkg/__init__.py
from .__version__ import __version__
from .module1 import AwesomeClass
EOF

cat <<EOF > pkg/module1.py
import numpy

class AwesomeClass:
    pass
EOF

echo '__version__ = "0.1.0"' > pkg/__version__.py

cd /
pip install /tmp/test_project
# ...
# Successfully built test
# Installing collected packages: numpy, test
# Successfully installed numpy-1.24.2 test-0.1.0
```
