### ISSUE TITLE
[FR] Using setuptools as a build backend with only pyproject.toml doesn't work with PEP 660

### ISSUE THREAD

**Issue by hauntsaninja** [pypa/setuptools#3869]
### What's the problem this feature will solve?

I must be doing something wrong, because I can't find any duplicate issues about this.

Project layout:
```
λ tree                     
.
├── example
│   └── __init__.py
└── pyproject.toml

2 directories, 2 files
```

pyproject.toml:
```
λ cat pyproject.toml 
[project]
name = "example"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"
```

But:
```
λ pip --version
pip 23.0.1 from /Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip (python 3.10)
λ pip install -e .
Obtaining file:///Users/shantanu/tmp/tmptest
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///Users/shantanu/tmp/tmptest has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

### Describe the solution you'd like

I should get an editable install. It's unfortunate if the instructions in https://packaging.python.org/en/latest/tutorials/packaging-projects/ set things up in a way such that setuptools users cannot get editable installs.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @hauntsaninja, this is already supported by setuptools.

```bash
> docker run --rm -it python:3.10 /bin/bash
mkdir -p /tmp/myproj/example/
cd /tmp/myproj
touch example/__init__.py

cat <<EOF > pyproject.toml 
[project]
name = "example"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"
EOF

python -m pip install -U 'pip==23.0.1'
python -m pip install -e .
# WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
# Obtaining file:///tmp/myproj
#   Installing build dependencies ... done
#   Checking if build backend supports build_editable ... done
#   Getting requirements to build editable ... done
#   Installing backend dependencies ... done
#   Preparing editable metadata (pyproject.toml) ... done
# Building wheels for collected packages: example
#   Building editable for example (pyproject.toml) ... done
#   Created wheel for example: filename=example-0.0.1-0.editable-py3-none-any.whl size=2411 sha256=55a48c8c4ac81b753326d00d455c95cd2282997d954d00d00144811d6e41ff37
#   Stored in directory: /tmp/pip-ephem-wheel-cache-jhmlakp1/wheels/7c/e0/00/53c1244963f4638250213d58f896a41449d4d2ce6e09690064
# Successfully built example
# Installing collected packages: example
# Successfully installed example-0.0.1
# WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

python -c 'import example; print(example.__path__)'
# ['/tmp/myproj/example']
```

If I had to do a wild guess, I would say that there might be a "leak" on the virtual environment used to build your project and then an older version of setuptools installed somewhere else is being accidentally used... (of course, I might be wrong)

**Comment by hauntsaninja** [comment]
Thanks, yeah, it's got to be something like that.

Your docker example works as expected for me.

Things also work for me with `python -m pip install -e . --no-build-isolation`

Weirdly, pip's verbose logs do seem to indicate setuptools 67.6 being installed:
<details>

```
λ python -m pip install -e . -vvv                
Using pip 23.0.1 from /Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip (python 3.10)
Non-user install because user site-packages disabled
Created temporary directory: /private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-build-tracker-ff4i6mbz
Initialized build tracking at /private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-build-tracker-ff4i6mbz
Created build tracker: /private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-build-tracker-ff4i6mbz
Entered build tracker: /private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-build-tracker-ff4i6mbz
Created temporary directory: /private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-install-99w4lrlr
Created temporary directory: /private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-ephem-wheel-cache-3i8nkx14
Obtaining file:///Users/shantanu/tmp/tmptest
  Added file:///Users/shantanu/tmp/tmptest to build tracker '/private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-build-tracker-ff4i6mbz'
  Created temporary directory: /private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-build-env-lavreq3h
  Running command pip subprocess to install build dependencies
  Using pip 23.0.1 from /Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip (python 3.10)
  Collecting setuptools>=64.0
    Using cached setuptools-67.6.0-py3-none-any.whl (1.1 MB)
  Installing collected packages: setuptools
  Successfully installed setuptools-67.6.0
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
ERROR: Project file:///Users/shantanu/tmp/tmptest has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
Exception information:
Traceback (most recent call last):
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 185, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 322, in __init__
    super().__init__(
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 332, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 633, in prepare_editable_requirement
    dist = _get_prepared_distribution(
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 46, in prepare_distribution_metadata
    self.req.isolated_editable_sanity_check()
  File "/Users/shantanu/.virtualenvs/tmptest-qmhl/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 509, in isolated_editable_sanity_check
    raise InstallationError(
pip._internal.exceptions.InstallationError: Project file:///Users/shantanu/tmp/tmptest has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
Remote version of pip: 23.0.1
Local version of pip:  23.0.1
Was pip installed by pip? True
Removed file:///Users/shantanu/tmp/tmptest from build tracker '/private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-build-tracker-ff4i6mbz'
Removed build tracker: '/private/var/folders/0y/wt5dx2vj6t16wq97pglrkynm0000gp/T/pip-build-tracker-ff4i6mbz'
```
</details>

Any ideas? I guess the fact that it works without build isolation indicates that it's a pip bug?

**Comment by abravalheri** [comment]
It is hard to tell. As far as I know pip does not use `venv` isolation, instead it "hacks" something up [using `sitecustomize` to "cleanup" `sys.path`](https://github.com/pypa/pip/blob/23.0.1/src/pip/_internal/build_env.py#L105-L134). But if the Python distribution messes around with the installation layouts and variables in `sysconfig` there might be problems...

I remember in the past we had trouble with Debian and Homebrew based systems leaking packages, e.g.:
- `https://github.com/pypa/pip/issues/11539`
- `https://github.com/pypa/setuptools/issues/3291`
- `https://github.com/pypa/pip/issues/6264`
- `https://github.com/pypa/pip/issues/11004`

I am not saying that this is definitely the cause of the problem, but you may find something useful in the discussions above.

In the end of the day, it might even be a problem with setuptools (although I find it difficult because it looks like the wrong version of setuptools is getting imported), but we would need further evidence.

Unfortunately I don't have a macOS system to help investigate further...
I would suggest however start by inspecting `python -m site` and `python -c 'import sys; print(sys.path)'` to see if there would be something not conventional there that might be left over after pip's cleanup of `sys.path`.

There is a discussion in `https://github.com/pypa/pip/issues/11812` and `https://github.com/pypa/pip/pull/11619` to move `pip` towards using `venv`.

**Comment by hauntsaninja** [comment]
Thanks! I'll investigate and report back!
