### ISSUE TITLE
[BUG] invalid pyproject.toml config: data.project.entry-points

### ISSUE THREAD

**Issue by Torxed** [pypa/setuptools#3967]
### setuptools version

68.0.0

### Python version

3.11.3

### OS

Arch Linux

### Additional environment information

This only happens using `pyproject.toml`.
If instead `setup.cfg` & `setup.py` is used, it works:
```python
[metadata]
name = timmins-plugin
version = 0.1
description = A test
author = Anton Hvornum
author_email = anton@hvornum.se
long_description = a test
license = GPL
license_files =
    LICENSE
project_urls =
    Source = https://github.com/Torxed/timmins
    Documentation = https://timmins.readthedocs.io/
classifers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.11
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Operating System :: POSIX :: Linux

[options]
packages = find:
python_requires = >= 3.11

[options.entry_points]
timmins.display =
    excl = timmins_plugin_fancy:excl_display
```

### Description

Unable to build plugins with `pyproject.toml`.

### Expected behavior

The plugin to be built, installed and to be accessible with:
```python
import importlib.metadata
for plugin_definition in importlib.metadata.entry_points().select(group='timmins.display'):
	plugin_entrypoint = plugin_definition.load()
```

### How to Reproduce

1. Download [timmins-plugin-fancy.zip](https://github.com/pypa/setuptools/files/11883235/timmins-plugin-fancy.zip) (or follow https://setuptools.pypa.io/en/stable/userguide/entry_point.html#entry-points-for-plugins to create the same structure and files)
2. `pip install . --break-system-packages`

### Output

```console
Defaulting to user installation because normal site-packages is not writeable
WARNING: Skipping /usr/lib/python3.11/site-packages/uvicorn-0.21.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib/python3.11/site-packages/anyio-3.6.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib/python3.11/site-packages/starlette-0.26.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib/python3.11/site-packages/fastapi-0.95.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib/python3.11/site-packages/uvicorn-0.21.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib/python3.11/site-packages/anyio-3.6.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib/python3.11/site-packages/starlette-0.26.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/lib/python3.11/site-packages/fastapi-0.95.1.dist-info due to invalid metadata entry 'name'
Processing /home/anton/timmins-plugin-fancy
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      configuration error:

      Traceback (most recent call last):
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g8jj5rh6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g8jj5rh6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-g8jj5rh6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-g8jj5rh6/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g8jj5rh6/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-g8jj5rh6/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 898, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-g8jj5rh6/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g8jj5rh6/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 128, in read_configuration
          validate(subset, filepath)
        File "/tmp/pip-build-env-g8jj5rh6/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: data.project.entry-points.
      configuration error:
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Here's the `pyproject.toml`:
```toml
[build-system]
requires = ["setuptools>=67.5"]
build-backend = "setuptools.build_meta"

[project]
name = "timmins"
dynamic = ["version", "entry-points"]
description = "A test"
authors = [
	{name = "Anton Hvornum", email = "anton@hvornum.se"},
]
license = {text = "AGPL-1.0-or-later"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

keywords = ["linux", "timmins"]

classifiers = [
	"Programming Language :: Python :: 3.11",
	"Operating System :: POSIX :: Linux",
]

[project.urls]
Home = "https://timmins.archlinux.life"
Documentation = "https://timmins.readthedocs.io/"
Source = "https://github.com/Torxed/timmins"

# https://setuptools.pypa.io/en/latest/userguide/entry_point.html#entry-points-syntax
# Note the quotes around timmins.display in order to escape the dot .
[project.entry-points."timmins.display"]
excl = "timmins_plugin_fancy:excl_display"

[options]
package_dir="src"
include_package_data = true

[options.packages.find]
where="src"

[options.package_data]
src = "*.py"
```

**Comment by abravalheri** [comment]
Hi @Torxed, please note that you cannot provide a value for `project.entry-points` and list it under `project.dynamic` at the same time. This is the reference: https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dynamic.

**Comment by Torxed** [comment]
@abravalheri you are correct! Oversight, I just went plainly on the error message stating it was a invalid config of value `entry-points`.

Thank you!
