### ISSUE TITLE
[BUG] incremental-22.10.0-py2.7.egg package requires python 3

### ISSUE THREAD

**Issue by adrian-kurzeja** [pypa/setuptools#3993]
### setuptools version

44.1.0

### Python version

2.7

### OS

Linux alpine

### Additional environment information

Docker image:
python:2.7-alpine

### Description

As I understand correctly `.egg` files are downloaded from `pkg_resources` server (probably `https://packaging.python.org` because setuptools is one of the projects). If not just close this ticket, I assumed this is the case after reading this line in `pkg_resources` package documentation 

> The pkg_resources module distributed with setuptools provides an API for Python libraries to access their resource files, and for extensible applications and frameworks to automatically discover plugins.

I was trying to install `Twisted==16.6.0` with pip install in python 2.7 inside docker image `python:2.7-alpine`. Pip downloaded file `Twisted-16.6.0.tar.bz2` from `pypi` and tried to install it.
Twisted requires package `incremental >= 16.10.1`, and during installation it downloads `.egg` file `incremental-22.10.0-py2.7.egg` and tries to install it.
During installation I got an error:
```
44.81       File "/tmp/pip-install-8VDJsv/twisted/.eggs/incremental-22.10.0-py2.7.egg/incremental/__init__.py", line 14, in <module>
44.81         from typing import TYPE_CHECKING, Any, TypeVar, Union, Optional, Dict
44.81     ImportError: No module named typing
```
It seems like this package requires python 3, even though it says `-py2.7.egg`.

Solution I used was just to install `incremental==16.10.1` in docker file `RUN pip install incremental==16.10.1`, before installing Twisted, but this is just a workaround.

I don't know if you still care about python 2.7, but still decided to add this ticket, if you don't please just close it

### Expected behavior

Twisted installed properly.

### How to Reproduce

Just build this Dockerfile
```
FROM python:2.7-alpine

RUN apk add --update \
    jpeg-dev \
    zlib-dev \
    freetype-dev \
    lcms2-dev \
    openjpeg-dev \
    tiff-dev \
    postgresql-dev \
    build-base \
    linux-headers \
    libffi-dev \
    supervisor \
    && rm -rf /var/cache/apk/*
RUN pip install Twisted==16.6.0

```

### Output

```console
20.98 Collecting Twisted==16.6.0
21.02   Downloading Twisted-16.6.0.tar.bz2 (3.0 MB)
24.02     ERROR: Command errored out with exit status 1:
24.02      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p_d5Fn/twisted/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p_d5Fn/twisted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-KdJc6F
24.02          cwd: /tmp/pip-install-p_d5Fn/twisted/
24.02     Complete output (24 lines):
24.02     DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
24.02     Traceback (most recent call last):
24.02       File "<string>", line 1, in <module>
24.02       File "/tmp/pip-install-p_d5Fn/twisted/setup.py", line 21, in <module>
24.02         setuptools.setup(**_setup["getSetupArgs"]())
24.02       File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
24.02         return distutils.core.setup(**attrs)
24.02       File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
24.02         _setup_distribution = dist = klass(attrs)
24.02       File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 448, in __init__
24.02         k: v for k, v in attrs.items()
24.02       File "/usr/local/lib/python2.7/distutils/dist.py", line 287, in __init__
24.02         self.finalize_options()
24.02       File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 740, in finalize_options
24.02         ep(self)
24.02       File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
24.02         ep.load()(self, ep.name, value)
24.02       File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
24.02         return self.resolve()
24.02       File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
24.02         module = __import__(self.module_name, fromlist=['__name__'], level=0)
24.02       File "/tmp/pip-install-p_d5Fn/twisted/.eggs/incremental-22.10.0-py2.7.egg/incremental/__init__.py", line 14, in <module>
24.02         from typing import TYPE_CHECKING, Any, TypeVar, Union, Optional, Dict
24.02     ImportError: No module named typing
24.02     ----------------------------------------
24.02 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
------
failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
```

**Comment by abravalheri** [comment]
Hi @adrian-kurzeja please note that Python 2.7 is no longer supported.

If you manage to try performing the installation with Python and the latest version of setuptools and find any problems, please let us know.
