### ISSUE TITLE
[BUG] New version 68.2.1 breaks `python setup.py --version` when using pyproject.toml

### ISSUE THREAD

**Issue by bitbier** [pypa/setuptools#4047]
### setuptools version

setuptools==68.2.1

### Python version

Python 3.9.13

### OS

Mac OS X

### Description

When using pyproject.toml's `[project]` descriptors's `version` attribute, the newest version of setup tools breaks with the following exception:

```
$ python setup.py --version
Traceback (most recent call last):
  File "/workspace/setup.py", line 2, in <module>
    setup(
  File "/Users/jstarker/.pyenv/versions/setup-version-failed/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/Users/jstarker/.pyenv/versions/setup-version-failed/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 172, in setup
    ok = dist.parse_command_line()
  File "/Users/jstarker/.pyenv/versions/setup-version-failed/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 467, in parse_command_line
    args = parser.getopt(args=self.script_args, object=self)
  File "/Users/jstarker/.pyenv/versions/setup-version-failed/lib/python3.9/site-packages/setuptools/_distutils/fancy_getopt.py", line 274, in getopt
    val = getattr(object, attr, 0) + 1
TypeError: can only concatenate str (not "int") to str
```

This works with `68.2.0`.

### Expected behavior

Expected to display the version of the test project

### How to Reproduce

1. Create two files:

```
# setup.py
from setuptools import setup
setup()
```

```
# pyproject.toml
[project]
name = "test"
version = "1.0.0"
```

2. Install `setuptools==68.2.1`
3. Run `python setup.py --version`

### Output

```console
$ python setup.py --version
Traceback (most recent call last):
  File "/workspace/setup.py", line 2, in <module>
    setup(
  File "/Users/jstarker/.pyenv/versions/setup-version-failed/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/Users/jstarker/.pyenv/versions/setup-version-failed/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 172, in setup
    ok = dist.parse_command_line()
  File "/Users/jstarker/.pyenv/versions/setup-version-failed/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 467, in parse_command_line
    args = parser.getopt(args=self.script_args, object=self)
  File "/Users/jstarker/.pyenv/versions/setup-version-failed/lib/python3.9/site-packages/setuptools/_distutils/fancy_getopt.py", line 274, in getopt
    val = getattr(object, attr, 0) + 1
TypeError: can only concatenate str (not "int") to str
```

**Comment by bitbier** [comment]
Hey @abravalheri,

Thanks for the quick response. I can confirm that the version above fixes the issue.

Also thanks for the information regarding the `setup.py` being deprecated. We are only using it as part of some custom built CI/CD tool. I'll bring this information back to our team to see if we can start looking into other things that would be more purpose built for us instead. Do you know when `setup.py` would be deprecated or is this just some time in the distance future?

**Comment by abravalheri** [comment]
> Do you know when setup.py would be deprecated or is this just some time in the distance future?

Running `python setup.py` as a CLI tool is already deprecated ([it actually has been deprecated for a while](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)).

Depending on how your custom CI/CD tool is built/expected to work, you can replace it with things like "reading the `pyproject.toml` file yourself"[^1].

Regarding when we are going to "remove" the CLI capabilities, that is undefined. What is more likely to happen is that CLI capabilities are going to stay around for a while as long as it is not costly to keep them, but with no promise of full backwards compatibility. If we receive a report that someone stopped working, we might just let it as it is (depending on the trade-off between maintenance cost and "level of breakage on the ecosystem").

In this case, it was easy to fix, so I just did it. But I cannot guarantee that is always going to be the case.

Note that having a `setup.py` file as a configuration file is **not deprecated** (and there is no expectation for doing that for the foreseeable future). `setup.py` is a completely fine configuration file that happens to be written in Python language (e.g. `conftest.py` for Pytest, `noxfile.py` for Nox, etc...).

[^1]: This is quick and easy and works if you know that all your packages define the version inside `pyproject.toml`. If you need something generic that always work for all packages regarding of how they are implemented https://pypa-build.readthedocs.io/en/stable/api.html#build.util.project_wheel_metadata would probably do a better job, however it is slower.
