### ISSUE TITLE
[BUG] AssertionError: Multiple .egg-info directories found

### ISSUE THREAD

**Issue by zariiii9003** [pypa/setuptools#4095]
### setuptools version

setuptools-68.2.2-py3-none-any.whl

### Python version

PyPy 7.3.13 with Python (3.9.18)

### OS

ubuntu-22.04

### Description

Building and installing [bitstruct](https://github.com/eerimoq/bitstruct) under PyPy fails with `AssertionError: Multiple .egg-info directories found`. It works fine under CPython.

### Expected behavior

The package should be installed without issues.

### How to Reproduce

1. Get [PyPy 3.9](https://www.pypy.org/download.html)
3. git clone https://github.com/eerimoq/bitstruct.git
4. cd ./bitstruct
5. pip install .

### Output

```console
Successfully installed setuptools-68.2.2
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Running command pip subprocess to install backend dependencies
  Using pip 23.3.1 from /opt/hostedtoolcache/PyPy/3.9.18/x64/lib/pypy3.9/site-packages/pip (python 3.9)
  /opt/hostedtoolcache/PyPy/3.9.18/x64/lib/pypy3.9/site-packages/pip/_vendor/certifi/cacert.pem None
  Collecting wheel
    Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/312[73](https://github.com/zariiii9003/bitstruct/actions/runs/6657684616/job/18092909478#step:4:74)bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
  /opt/hostedtoolcache/PyPy/3.9.18/x64/lib/pypy3.9/site-packages/pip/_vendor/certifi/cacert.pem None
    Downloading wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
  Downloading wheel-0.41.2-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 2.9 MB/s eta 0:00:00
  Installing collected packages: wheel
    Creating /tmp/pip-build-env-z0j8mivu/normal/bin
    changing mode of /tmp/pip-build-env-z0j8mivu/normal/bin/wheel to [75](https://github.com/zariiii9003/bitstruct/actions/runs/6657684616/job/18092909478#step:4:76)5
  Successfully installed wheel-0.41.2
  Installing backend dependencies: finished with status 'done'
  Created temporary directory: /tmp/pip-modern-metadata-l20yvtoh
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/PyPy/3.9.18/x64/lib/pypy3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/hostedtoolcache/PyPy/3.9.18/x64/lib/pypy3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/hostedtoolcache/PyPy/3.9.18/x64/lib/pypy3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-z0j8mivu/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 398, in prepare_metadata_for_build_wheel
      self._bubble_up_info_directory(metadata_directory, ".egg-info")
    File "/tmp/pip-build-env-z0j8mivu/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 367, in _bubble_up_info_directory
      info_dir = self._find_info_directory(metadata_directory, suffix)
    File "/tmp/pip-build-env-z0j8mivu/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 3[78](https://github.com/zariiii9003/bitstruct/actions/runs/6657684616/job/18092909478#step:4:79), in _find_info_directory
      assert len(candidates) == 1, f"Multiple {suffix} directories found"
  AssertionError: Multiple .egg-info directories found
  error: subprocess-exited-with-error
```

[Here you can see the output of pip with high verbosity.](https://github.com/zariiii9003/bitstruct/actions/runs/6657684616/job/18092909478)

**Comment by zariiii9003** [comment]
Nevermind, i didn't call setuptools.setup() in case, that no C extensions are built. Works fine now.
