### ISSUE TITLE
[BUG] Dynamic version `attr` fails with namespace package

### ISSUE THREAD

**Issue by SimonBoothroyd** [pypa/setuptools#4106]
### setuptools version

68.2.2

### Python version

3.11.6

### OS

maxOS

### Additional environment information

This error also happens with the current `main` branch.

### Description

I am trying to dynamically set the version of my PEP 420 namespace package using a `pyproject.toml`:

```toml
[project]
name = "my-package"
dynamic = ["version"]

[tool.setuptools.packages.find]
namespaces = true
where = ["."]

[tool.setuptools.dynamic]
version = {attr = "my.package.__version__"}
```

based on a value returned by a function defined within the package. In particular, my namespace package is structured as

```
my/
├─ package/
│  ├─ __init__.py
│  ├─ _version.py
pyproject.toml
```

with `__init__.py` as:

```python
from . import _version

__version__ = _version.get_version()
```

and `_version.py` similar to:

```python
def get_version():
    return "0.0.1"
```

(in my real project `_version.py` is created by [`versioneer`](https://github.com/python-versioneer/python-versioneer) and is more complex).

`pip` installing this project however yields an `ast` parsing error.

If I try the same with a non-namespace package (i.e. move `__init__.py` and `_version.py` up a level and modify `pyproject.toml` accordingly) then the project installs with the correct version without error.

Additionally, if I replace `__version__ = _version.get_version()` with `__version__ = "0.0.1"` then the project also installs with the correct version without error.

So this issue seems to be tied to having the version set by a function in another file in combination with a namespace package.

### Expected behavior

The namespace package should install and show a version of `0.0.1`.

### How to Reproduce

1. Clone the simple reproducing case:

```shell
git clone https://github.com/SimonBoothroyd/setuptools-version-repro.git
cd setuptools-version-repro
```

3. Create a virtual env to install the package into:

```shell
python -m venv --clear .venv
```

4. Try to install the package:

```shell
pip install ./namespace
```

### Output

```console
% pip install ./namespace
Processing ./namespace
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [91 lines of output]
      Traceback (most recent call last):
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 81, in __getattr__
          return next(
                 ^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 82, in <genexpr>
          ast.literal_eval(value)
        File "<python-dir>/python3.11/ast.py", line 110, in literal_eval
          return _convert(node_or_string)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "<python-dir>/python3.11/ast.py", line 109, in _convert
          return _convert_signed_num(node)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<python-dir>/python3.11/ast.py", line 83, in _convert_signed_num
          return _convert_num(node)
                 ^^^^^^^^^^^^^^^^^^
        File "<python-dir>/python3.11/ast.py", line 74, in _convert_num
          _raise_malformed_node(node)
        File "<python-dir>/python3.11/ast.py", line 71, in _raise_malformed_node
          raise ValueError(msg + f': {node!r}')
      ValueError: malformed node or string on line 3: <ast.Call object at 0x10ed05ed0>
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 193, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 87, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: my.package has no attribute __version__
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<repo-dir>/setuptools-version-repro/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "<repo-dir>/setuptools-version-repro/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<repo-dir>/setuptools-version-repro/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 653, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 131, in read_configuration
          return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 156, in expand_configuration
          return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 204, in expand
          self._expand_all_dynamic(dist, package_dir)
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 249, in _expand_all_dynamic
          version=self._obtain_version(dist, package_dir),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 298, in _obtain_version
          return _expand.version(self._obtain(dist, "version", package_dir))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 287, in _obtain
          return self._expand_directive(
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 281, in _expand_directive
          return _expand.read_attr(directive["attr"], package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 196, in read_attr
          module = _load_spec(spec, module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<tmp-dir>/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 216, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<repo-dir>/setuptools-version-repro/namespace/my/package/__init__.py", line 1, in <module>
          from . import _version
      ModuleNotFoundError: No module named 'my'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by abravalheri** [comment]
Hi @SimonBoothroyd any chance the root package folder has the same name as the namespace?

What happens if instead of running `pip install ./namespace` you run `cd namespace  && pip install .`.

**Comment by abravalheri** [comment]
Hi @SimonBoothroyd any chance the root package folder has the same name as the namespace?

What happens if instead of running `pip install ./namespace` you run `cd namespace  && pip install .`?

Does the problem also happen in a src-layout project?

**Comment by SimonBoothroyd** [comment]
Hi @abravalheri

> any chance the root package folder has the same name as the namespace?

 Hmm in the cases I've been trying the root package folder has a different name

> What happens if instead of running pip install ./namespace you run cd namespace  && pip install .?

Same issue unfortunately!

> Does the problem also happen in a src-layout project?

I'm not sure - I'll give that a try as well.

**Comment by SimonBoothroyd** [comment]
> Does the problem also happen in a src-layout project?

It seems to be the same behavior - I see no error for a normal package in the src layout and the above error for a namespace package (assuming I set this up correctly!)

**Comment by qazwini** [comment]
this is literally so sad
