### ISSUE TITLE
[BUG] Setuptools python 3.8 incompatibility?

### ISSUE THREAD

**Issue by CamJN** [pypa/setuptools#4143]
### setuptools version

Presumably >=61.0 from pyproject.toml

### Python version

3.8

### OS

macOS 12.6.9 21G726

### Additional environment information

This was running in Github actions

### Description

When I run `python3 -m build`, I get an error from somewhere in setuptools.

### Expected behavior

No error like before, last good run Oct 4th.

### How to Reproduce

Fork https://github.com/getargv/getargv.py
remove following lines from workflow (not relevant to bug and you don't have access to the other repo):
```
    - uses: actions/checkout@v3
      with:
        repository: getargv/getargv
        path: getargv
        token: ${{ secrets.GH_PAT }}
    - name: Build libgetargv
      run: make install_dylib
      working-directory: getargv
```
commit & push to github fork
github actions should run and produce error as below:

### Output

```console
python3 -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=61.0, tomli>=2.0.1; python_version<'3.11')
* Getting build dependencies for sdist...
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 287, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/build-env-5c6ycfer/lib/python3.8/site-packages/setuptools/build_meta.py", line 328, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/build-env-5c6ycfer/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/build-env-5c6ycfer/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 20, in <module>
TypeError: 'type' object is not subscriptable

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
Error: Process completed with exit code 1.
```

**Comment by abravalheri** [comment]
Hi @CamJN,

After a quick look it seems that this problem is caused by the specific `setup.py` file of the project you are trying to build. Not necessarily setuptools...

But it is hard to be sure, this reproducer is quite complicated to reason about...

Could you please try simplifying to a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example)?

That would facilia lot... Ideally, if we can avoid relying on Github actions or external make files, it would be great!

Any chance you can also use some linters on the `setup.py` file to see if it is fine?

**Comment by CamJN** [comment]
Ah, I didn't realize that the setup.py file was read like a file rather than imported so the backtrace mention of "string" was my file. I guess this is indeed my error, though the backtrace would be much more comprehensible if setup.py was somehow named rather than "string".

**Comment by abravalheri** [comment]
> Ah, I didn't realize that the setup.py file was read like a file rather than imported so the backtrace mention of "string" was my file. I guess this is indeed my error, though the backtrace would be much more comprehensible if setup.py was somehow named rather than "string".

Please feel free to drop us a PR! Contributions are always welcomed ❤️
