### ISSUE TITLE
'module' object has no attribute 'packaging' in setuptools 18.2

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#418]
Originally reported by: **fraser28 (Bitbucket: [fraser28](http://bitbucket.org/fraser28), GitHub: Unknown)**

---

While executing easy_install, the following exception occurs:

```
[root@SZX-SRV-AUTOMATION setuptools-18.2]# easy_install
Traceback (most recent call last):
  File "/usr/local/bin/easy_install-2.7", line 9, in <module>
    load_entry_point('setuptools==18.2', 'console_scripts', 'easy_install-2.7')()
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 318, in load_entry_point
    def get_metadata_lines(name):
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 2221, in load_entry_point
    """Return a ``Requirement`` that matches this distribution exactly"""
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1954, in load
    return entry
  File "build/bdist.linux-i686/egg/setuptools/__init__.py", line 11, in <module>

  File "build/bdist.linux-i686/egg/setuptools/extension.py", line 8, in <module>
  File "build/bdist.linux-i686/egg/setuptools/dist.py", line 21, in <module>
AttributeError: 'module' object has no attribute 'packaging'
```

The error happend on this line in dist.py: packaging = pkg_resources.packaging
I was trying to modify to: packaging = pkg_resources._vendor.packaging
but got this error AttributeError: 'module' object has no attribute '_vendor'

I don't realize what's going on, please help to fix this, thanks.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/418

**Comment by Avasam** [comment]
Note that setuptools no longer relies on `pkg_resources`. So the MRE for this is now completely irrelevant.

**Comment by abravalheri** [comment]
Thank you very much @Avasam .


I will close this issue for now, but the author can re-open it with new information if necessary or create a new issue.
