### ISSUE TITLE
[BUG] : We can no longer add  options to requirements file 

### ISSUE THREAD

**Issue by T4mmi** [pypa/setuptools#4207]
### setuptools version

69.0.3

### Python version

3.10

### OS

Windows

### Description

It seems that adding options to `requirements.txt` is no longer working using setuptools ...

**pyproject.toml**
```ini
[project]
...
dynamic = ["dependencies"]

[build-system]
requires = [
    "setuptools>=61",
]
...

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
```
**requirements.txt**
```txt
numpy>=1.18
attrs>=23.1.0
typing-extensions>=4.4.0
tqdm>=4.64.1
psutil>=5.9.5

--extra-index-url https://test.pypi.org/simple/
deker-local-adapters==1.0.1b
```

building/installing such package ends up with :
```console
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "D:\Conda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Conda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Conda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 441, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 67, in apply_configuration
          return _apply(dist, config, filepath)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py", line 62, in apply
          dist._finalize_requires()
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\dist.py", line 364, in _finalize_requires
          self._normalize_requires()
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\dist.py", line 379, in _normalize_requires
          self.install_requires = list(map(str, _reqs.parse(install_requires)))
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected package name at the start of dependency specifier
          --extra-index-url https://test.pypi.org/simple/
 ```

basically, any non-package specification line in the requirements throws `setuptools.extern.packaging.requirements.InvalidRequirement: Expected package name at the start of dependency specifier `

### Expected behavior

this should works just as passing the arguments `--extra-index-url` to pip/build/wheel ... as it was the case previously

### How to Reproduce

build a package using a  **requirements.txt**
```txt
numpy>=1.18
attrs>=23.1.0
typing-extensions>=4.4.0
tqdm>=4.64.1
psutil>=5.9.5

--extra-index-url https://test.pypi.org/simple/
deker-local-adapters==1.0.1b
```
build it using setuptools !

### Output

```console
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "D:\Conda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Conda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Conda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 441, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 67, in apply_configuration
          return _apply(dist, config, filepath)
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py", line 62, in apply
          dist._finalize_requires()
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\dist.py", line 364, in _finalize_requires
          self._normalize_requires()
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\dist.py", line 379, in _normalize_requires
          self.install_requires = list(map(str, _reqs.parse(install_requires)))
        File "C:\Users\janviert\AppData\Local\Temp\pip-build-env-gynvx7t0\overlay\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected package name at the start of dependency specifier
          --extra-index-url https://test.pypi.org/simple/
```

**Comment by abravalheri** [comment]
Hi @T4mmi please note this never worked with setuptools.

It is also not a feature we are planning to support.

This behaviour is described in the [docs](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata):

> Also note that the file format for specifying dependencies resembles a requirements.txt file, however please keep in mind that all non-comment lines must conform with PEP 508 (pip-specify syntaxes, e.g. -c/-r/-e flags, are not supported).
