### ISSUE TITLE
[BUG] 69.1.0 gives error for python 3.7.3

### ISSUE THREAD

**Issue by StRuoff** [pypa/setuptools#4225]
### setuptools version

69.1.0

### Python version

3.7.3

### OS

Ubuntu

### Description

Setuptools 69.1.0 is installed, when I create a new conda environment for pyhton version 3.7.3, but is not supporting 3.7.3 anymore.

### Expected behavior

I don't know If it is a bug in setuptools or conda (or both)? But I expect that only the latest *compatible* version of setuptools is installed for the chosen python version.

### How to Reproduce

create a new conda environment via:
```bash
conda create -n testenv python=3.7.3 --yes
conda activate testenv
```
Install any package using setuptools (via `pip install -e .`)

or just check the version via (`conda list`):
```bash
setuptools                69.1.0             pyhd8ed1ab_0    conda-forge
```

### Output

```console
$ pip install -e .[test]
Obtaining file:///home/gitlab-runner/builds/KNLjtm-t/0/simfuel/probml
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/gitlab-runner/builds/KNLjtm-t/0/simfuel/probml/setup.py", line 51, in <module>
          "pytest_cov",
        File "/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/site-packages/setuptools/dist.py", line 634, in fetch_build_eggs
          from .installer import _fetch_build_eggs
        File "/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/site-packages/setuptools/installer.py", line 11, in <module>
          from .wheel import Wheel
        File "/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/site-packages/setuptools/wheel.py", line 18, in <module>
          from setuptools.command.egg_info import write_requirements, _egg_basename
        File "/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 23, in <module>
          from setuptools.command.sdist import sdist
        File "/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/site-packages/setuptools/command/sdist.py", line 8, in <module>
          from .build import _ORIGINAL_SUBCOMMANDS
        File "/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/site-packages/setuptools/command/build.py", line 1, in <module>
          from typing import Dict, List, Protocol
      ImportError: cannot import name 'Protocol' from 'typing' (/home/gitlab-runner/miniforge3/envs/testenv/lib/python3.7/typing.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by abravalheri** [comment]
Hi @StRuoff please note that Python 3.7 reached end-of-life (i.e. no support) on [2023-06-27](https://devguide.python.org/versions/), so we no longer support it.

Moreover Setuptools 69.1.0 explicitly sets a requirement on [`Python >= 3.8`](https://inspector.pypi.io/project/setuptools/69.1.0/packages/bb/0a/203797141ec9727344c7649f6d5f6cf71b89a6c28f8f55d4f18de7a1d352/setuptools-69.1.0-py3-none-any.whl/setuptools-69.1.0.dist-info/METADATA#line.20). I don't understand exactly how you ended up with `setuptools==69.1.0` in your environment... As far as I know `pip` does respect the `Requires-Python` metadata, so potentially this is related to the way `setuptools` is being packaged/installed via Conda?

I will go ahead for now and close this issue since it does not seem to be related to the code maintained in this GitHub repository.

If you absolutely need to use 3.7, I recommend using an older version of `setuptools`. Otherwise, maybe it is a good idea to migrate to 3.8 or newer versions of Python.

**Comment by StRuoff** [comment]
Thanks for the clarification. 

I just wanted to make sure I have to look for the error on my side or maybe even conda. 

For everyone stumbling over this issue:
I manually set the version to 69.0.3, which is working fine for me for the moment.
