### ISSUE TITLE
[BUG] In python 3.10.6, Microsoft Visual C++ 14.0 or greater is required happened in electronuserland/builder:wine docker images.

### ISSUE THREAD

**Issue by deco-dev** [pypa/setuptools#4256]
### setuptools version

setuptools=69.1.1

### Python version

Python3.10.6

### OS

Linux with wine(windows)

### Additional environment information

- use electronuserland/builder:wine image.
- python 3.8.10 packages installed well.
- python 3.10.6 packages does not installed.
- just run wine python/python.exe -m pip install -r requirements.txt

### Description

I want to make the execute binary of windows in linux env. So I use docker image that is electronuserland/builder:wine.
I want to use python3.10.6, however it did not install packages. But python 3.8.10 it install packages well.

### Expected behavior

install success.

### How to Reproduce

1. docker run electronuserland/builder:16-wine
2. install windows version's python 3.8 and python 3.10 using wine.
3. install packages.
```
colorama<=0.4.1
multiprocessing-logging<=0.3.4
pyfdt<=0.3
python-dateutil<=2.8.2
termgraph<=0.2.1
psutil<=5.9.0
pywin32<=303
wheel==0.37.0
sortedcontainers<=2.2.2
pycryptodome<=3.9.12
pandas==2.0.3
ipython==8.9.0
ipykernel==6.20.2
ipyparallel==8.5.1
capstone==5.0.0rc2
tqdm==4.65.0
prompt-toolkit==3.0.36
cloudpickle==2.2.1
yapf==0.40.2
pyelftools==0.28
```
4. error occur only python 3.10.6

### Output

```console
  Downloading sortedcontainers-2.2.2-py2.py3-none-any.whl.metadata (10 kB)
Collecting pycryptodome<=3.9.12 (from -r dicore/requirements-windows.txt (line 10))
  Downloading pycryptodome-3.9.9.tar.gz (15.5 MB)
     ---------------------------------------- 15.5/15.5 MB 41.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Testing support for clang
      Traceback (most recent call last):
        File "Z:\project\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "Z:\project\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "Z:\project\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\users\root\Temp\pip-build-env-ua1m7vxe\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\users\root\Temp\pip-build-env-ua1m7vxe\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\users\root\Temp\pip-build-env-ua1m7vxe\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\users\root\Temp\pip-build-env-ua1m7vxe\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 457, in <module>
        File "C:\users\root\Temp\pip-install-o43xa2pp\pycryptodome_008b8f1ab3634e75be635a34b1049545\compiler_opt.py", line 341, in set_compiler_options
          clang = compiler_is_clang()
        File "C:\users\root\Temp\pip-install-o43xa2pp\pycryptodome_008b8f1ab3634e75be635a34b1049545\compiler_opt.py", line 251, in compiler_is_clang
          return test_compilation(source, msg="clang")
        File "C:\users\root\Temp\pip-install-o43xa2pp\pycryptodome_008b8f1ab3634e75be635a34b1049545\compiler_opt.py", line 82, in test_compilation
          objects = compiler.compile([fname], extra_postargs=extra_cc_options)
        File "C:\users\root\Temp\pip-build-env-ua1m7vxe\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\users\root\Temp\pip-build-env-ua1m7vxe\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\users\root\Temp\pip-build-env-ua1m7vxe\overlay\Lib\site-packages\setuptools\msvc.py", line 228, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\users\root\Temp\pip-build-env-ua1m7vxe\overlay\Lib\site-packages\setuptools\msvc.py", line 185, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
```

**Comment by deco-dev** [comment]
I found the problem. It is related to pycryptome packages.
