### ISSUE TITLE
unable to install mongo-python-driver-3.0.3 driver

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#437]
Originally reported by: **Anonymous**

---

Hi There,
I am using **Python 2.7.10**. When I am trying to install mongo-python-driver-3.0.3 driver it's showing an error. Here, I am attaching the screenshot taken from my machine.

Thanks in advance for you quick help.

```
#!python

[root@localhost mongo-python-driver-3.0.3]# whereis python
python: /usr/bin/python /usr/bin/python2.4 /usr/lib/python2.4 /usr/local/bin/python2.7-config /usr/local/bin/python2.7 /usr/local/bin/python /usr/local/lib/python2.7 /usr/include/python2.4 /usr/share/man/man1/python.1.gz
[root@localhost mongo-python-driver-3.0.3]# which python
/usr/local/bin/python
[root@localhost mongo-python-driver-3.0.3]# python -V
Python 2.7.10
[root@localhost mongo-python-driver-3.0.3]# pwd
/root/mongo-python-driver-3.0.3
[root@localhost mongo-python-driver-3.0.3]# ls
bson  CONTRIBUTING.rst  doc  ez_setup.py  green_framework_test.py  gridfs  LICENSE  MANIFEST.in  pymongo  README.rst  RELEASE.rst  setup.py  test  tools  tox.ini
[root@localhost mongo-python-driver-3.0.3]# python setup.py install
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-1.4.2.tar.gz
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    use_setuptools()
  File "/root/mongo-python-driver-3.0.3/ez_setup.py", line 132, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/root/mongo-python-driver-3.0.3/ez_setup.py", line 110, in _do_download
    to_dir, download_delay)
  File "/root/mongo-python-driver-3.0.3/ez_setup.py", line 290, in download_setuptools
    downloader(url, saveto)
  File "/root/mongo-python-driver-3.0.3/ez_setup.py", line 215, in download_file_wget
    _clean_check(cmd, target)
  File "/root/mongo-python-driver-3.0.3/ez_setup.py", line 160, in _clean_check
    subprocess.check_call(cmd)
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', 'https://pypi.python.org/packages/source/s/setuptools/setuptools-1.4.2.tar.gz', '--quiet', '--output-document', '/root/mongo-python-driver-3.0.3/setuptools-1.4.2.tar.gz']' returned non-zero exit status 1

```

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/437

**Comment by pganssle** [comment]
`pip install pymongo` seems to work for this.
