### ISSUE TITLE
[BUG] setuptools not working with 3.13.0b1

### ISSUE THREAD

**Issue by jm-nab** [pypa/setuptools#4384]
### setuptools version

setuptools==70.0.0

### Python version

Python 3.13.0b1

### OS

linux/arm64, linux/amd64

### Description

unable pip install .

### Expected behavior

installs

### How to Reproduce

1. pip install -U pillow

### Output

```console
pip install -U pillow
Collecting pillow
  Using cached pillow-10.3.0.tar.gz (46.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/jm/repos/northgpt/vertexai_loaders/venv_313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/jm/repos/northgpt/vertexai_loaders/venv_313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jm/repos/northgpt/vertexai_loaders/venv_313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-7r2m69xg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7r2m69xg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-7r2m69xg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 33, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by jm-nab** [comment]
possibly related: https://github.com/python-pillow/Pillow/issues/8075
