### ISSUE TITLE
[BUG]  Pip fails with Python 3.13 Free Threading

### ISSUE THREAD

**Issue by FabriceSalvaire** [pypa/setuptools#4415]
### setuptools version

70.0.0

### Python version

3.13 ft

### OS

Fedora 39

### Additional environment information

https://github.com/pypa/pip/issues/12747

### Description

Pip fails to install a package (Pillow) with **Python 3.13 Free Threading**.
Pillow can be installed from source using `python3.13t setup.py install`.

I think this is annoying to perform Python 3.13 Free Threading crash test...

### Expected behavior

...

### How to Reproduce

1. Try to install a package with pip...

### Output

```
>pip install --upgrade pip
Requirement already satisfied: pip in /opt/python-virtual-env/free-thread/lib64/python3.13/site-packages (23.2.1)
Collecting pip
Obtaining dependency information for pip from https://files.pythonhosted.org/packages/8a/6a/19e9fe04fca059ccf770861c7d5721ab4c2aebc539889e97c7977528a53b/pip-24.0-py3-none-any.whl.metadata
Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.0-py3-none-any.whl (2.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 12.0 MB/s eta 0:00:00
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 23.2.1
Uninstalling pip-23.2.1:
Successfully uninstalled pip-23.2.1
Successfully installed pip-24.0

>pip install setuptools
Collecting setuptools
Using cached setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
Using cached setuptools-70.0.0-py3-none-any.whl (863 kB)
Installing collected packages: setuptools
Successfully installed setuptools-70.0.0
```

```
>pip install pillow
Collecting pillow
Downloading pillow-10.3.0.tar.gz (46.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.6/46.6 MB 14.3 MB/s eta 0:00:00
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [21 lines of output]
Traceback (most recent call last):
File "/opt/python-virtual-env/free-thread/lib64/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
main()
~~~~^^
File "/opt/python-virtual-env/free-thread/lib64/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
~~~~^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python-virtual-env/free-thread/lib64/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
return hook(config_settings)
File "/tmp/pip-build-env-cpz4twfh/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
return self._get_build_requires(config_settings, requirements=['wheel'])
~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-build-env-cpz4twfh/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
self.run_setup()
~~~~~~~~~~~~~~^^
File "/tmp/pip-build-env-cpz4twfh/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 311, in run_setup
exec(code, locals())
~~~~^^^^^^^^^^^^^^^^
File "<string>", line 33, in <module>
File "<string>", line 27, in get_version
KeyError: '__version__'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by abravalheri** [comment]
Hi @FabriceSalvaire , it seems that the code is crashing when running the following code on the `setup.py` of Pillow:

```python
def get_version():
    version_file = "src/PIL/_version.py"
    with open(version_file, encoding="utf-8") as f:
        exec(compile(f.read(), version_file, "exec"))
    return locals()["__version__"]
```

This seems like it is a problem with that specific `setup.py`? Maybe it is worth checking that particular implementation?

**Comment by lysnikolaou** [comment]
This was fixed on the Pillow side [here](https://github.com/python-pillow/Pillow/issues/8075).

**Comment by abravalheri** [comment]
> This was fixed on the Pillow side [here](https://github.com/python-pillow/Pillow/issues/8075).

Still it sounds like a limitation of that particular implementation of Python... Apparently it cannot handle and `exec` inside of another `exec`? Or is my interpretation wrong?

**Comment by FabriceSalvaire** [comment]
Ah ya it is Pillow, that works
```
pip install git+https://github.com/python-pillow/Pillow
```

**Comment by FabriceSalvaire** [comment]
@abravalheri It is due to PEP 667 locals
https://github.com/python/cpython/issues/118888#issuecomment-2104944287

**Comment by FabriceSalvaire** [comment]
I close since we have the explanation.

**Comment by jsbueno** [comment]
this also failed me o a custom Python 3.12 build - both for pillow 10.3.0 and pillow 10.3.0 - 10.4.0-dev0 from the pip install from git command line above worked.

**Comment by bje-** [comment]
Will a new version of pillow be pushed into PyPI soon that fixes this?
