### ISSUE TITLE
[BUG]: strange distutils.errors.DistutilsPlatformError raised on Windows

### ISSUE THREAD

**Issue by clin1234** [pypa/setuptools#4431]
### setuptools version

setuptools>=59

### Python version

3.13

### OS

Windows

### Description

I was trying to build `pyvex` for 3.13

### Expected behavior

Expected it to succeed.

### How to Reproduce

1. Launch the "Developer Command Prompt for VS 2022" in Windows Terminal
2. Clone https://github.com/angr/pyvex/
3. Go to the directory
4. `pip install . --verbose`

### Output

```console
Using pip 24.1 from C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\pip (python 3.13)
Processing c:\users\ךינשגכהד\src\pyvex
  Running command pip subprocess to install build dependencies
  Using pip 24.1 from C:\Users\ךינשגכהד\scoop\persist\python-alpha\Lib\site-packages\pip (python 3.13)
  Collecting setuptools>=59
    Obtaining dependency information for setuptools>=59 from https://files.pythonhosted.org/packages/55/b3/b3a3415d2debd837106ed417f8681d8af63037fed367fa1b85dbfef081f1/setuptools-70.1.0-py3-none-any.whl.metadata
    Using cached setuptools-70.1.0-py3-none-any.whl.metadata (6.0 kB)
  Collecting wheel
    Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/7d/cd/d7460c9a869b16c3dd4e1e403cce337df165368c71d6af229a74699622ce/wheel-0.43.0-py3-none-any.whl.metadata
    Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
  Collecting cffi>=1.0.3
    Using cached cffi-1.16.0.tar.gz (512 kB)
    Installing build dependencies: started
    Running command pip subprocess to install build dependencies
    Using pip 24.1 from C:\Users\ךינשגכהד\scoop\persist\python-alpha\Lib\site-packages\pip (python 3.13)
    Collecting setuptools>=66.1
      Obtaining dependency information for setuptools>=66.1 from https://files.pythonhosted.org/packages/55/b3/b3a3415d2debd837106ed417f8681d8af63037fed367fa1b85dbfef081f1/setuptools-70.1.0-py3-none-any.whl.metadata
      Using cached setuptools-70.1.0-py3-none-any.whl.metadata (6.0 kB)
    Using cached setuptools-70.1.0-py3-none-any.whl (882 kB)
    Installing collected packages: setuptools
    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    poetry 1.9.0.dev0 requires dulwich<0.22.0,>=0.21.2, but you have dulwich 0.22.1 which is incompatible.
    poetry 1.9.0.dev0 requires keyring<25.0.0,>=24.3.1, but you have keyring 25.2.1 which is incompatible.
    Successfully installed setuptools-70.1.0
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Running command Getting requirements to build wheel
    Traceback (most recent call last):
      File "C:\Users\ךינשגכהד\scoop\persist\python-alpha\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
        main()
        ~~~~^^
      File "C:\Users\ךינשגכהד\scoop\persist\python-alpha\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ךינשגכהד\scoop\persist\python-alpha\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
      File "C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-35xs_87a\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=[])
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-35xs_87a\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
        self.run_setup()
        ~~~~~~~~~~~~~~^^
      File "C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-35xs_87a\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
        exec(code, locals())
        ~~~~^^^^^^^^^^^^^^^^
      File "<string>", line 126, in <module>
      File "<string>", line 105, in uses_msvc
      File "C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-35xs_87a\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 220, in try_compile
        self._compile(body, headers, include_dirs, lang)
        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-35xs_87a\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-35xs_87a\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
        self.initialize()
        ~~~~~~~~~~~~~~~^^
      File "C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-35xs_87a\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-35xs_87a\overlay\Lib\site-packages\setuptools\msvc.py", line 232, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-35xs_87a\overlay\Lib\site-packages\setuptools\msvc.py", line 189, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: 'C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\python.exe' 'C:\Users\ךינשגכהד\scoop\persist\python-alpha\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\0BAC~1\AppData\Local\Temp\tmpyei06lf0'
    cwd: C:\Users\ךינשגכהד\AppData\Local\Temp\pip-install-y8vid60m\cffi_80d4a805fc3147d8b6f4398a96d91d72
    Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\python.exe' 'C:\Users\ךינשגכהד\scoop\persist\python-alpha\Lib\site-packages\pip\__pip-runner__.py' install --ignore-installed --no-user --prefix 'C:\Users\ךינשגכהד\AppData\Local\Temp\pip-build-env-y8ry2xx5\overlay' --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=59' wheel 'cffi >= 1.0.3'
  cwd: [inherit]
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by abravalheri** [comment]
Hi @clin1234 , what is the location of the `vcvarsall.bat` software in your computer?

**Comment by clin1234** [comment]
Fixed: forgot to install the MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)
