### ISSUE TITLE
[BUG] Building Cython extension on Windows triggers TypeError

### ISSUE THREAD

**Issue by daniel-larraz** [pypa/setuptools#4456]
### setuptools version

setuptools==70.2.0

### Python version

Python 3.12

### OS

Windows

### Additional environment information

MSYS2 MINGW64

### Description

Version 70.2.0 triggers a `TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'` when building a Cython extension on Windows using MSYS2 MINGW64. Previous versions of setuptools work fine.

### Expected behavior

The Cython extension should build successfully without any errors.

### How to Reproduce

1. Create a directory with three files `helloworld.pyx`, `setup.py`, and `setup.cfg`:
```
# helloworld.pyx
print("Hello World")
```
```
# setup.py
from setuptools import setup
from Cython.Build import cythonize

setup(
    ext_modules = cythonize("helloworld.pyx")
)
```
```
# setup.cfg
[build]
compiler = mingw32
```
3. Launch a MINGW64 environment and go to the directory above.
4. Run: `C:\path\to\python.exe setup.py build_ext --inplace`

### Output

```console
running build_ext
Traceback (most recent call last):
  File "C:\Users\Daniel\Desktop\reproducer\setup.py", line 4, in <module>
    setup(
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 970, in run_commands
    self.run_command(cmd)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 974, in run_command
    super().run_command(command)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
    cmd_obj.run()
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\build_ext.py", line 93, in run
    _build_ext.run(self)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 329, in run
    customize_compiler(self.compiler)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\sysconfig.py", line 333, in customize_compiler
    cpp = cc + " -E"  # not always
          ~~~^~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by abravalheri** [comment]
If I am not mistaken the `cc` variable comes from `sysconfig.get_config_var('CC')` (and/or the `CC` environment variable).

@daniel-larraz what is the return value of `sysconfig.get_config_var('CC')`? And is there any `CC` environment variable set (what is the output of `os.environ['CC']`)?

**Comment by daniel-larraz** [comment]
The return value of `sysconfig.get_config_var('CC')` is `None`. There is no `CC` environment variable set.

**Comment by lazka** [comment]
I assume you are using the official CPython Python?

Due to https://github.com/pypa/distutils/commit/2ad8784dfeb816829995613fb5fd9818f3e88922 I guess.

Previously customize_compiler() was skipped in that setup.

Two options:

* Guard customize_compiler() to not run with the official CPython like before (that means it will ignore env vars etc)
* Make customize_compiler() compatible to work with the official CPython (i.e. add some None checks)

**Comment by daniel-larraz** [comment]
Yes, I'm using the official CPython build.

**Comment by abravalheri** [comment]
@jaraco would it be possible to transfer this issue to `pypa/distutils` as indicated in laska's analysis in https://github.com/pypa/setuptools/issues/4456#issuecomment-2205285125.

**Comment by lazka** [comment]
I can reproduce the error locally, by patching the distutils test suite to default to GCC even for msvc CPython. The test suite passes otherwise.

**Comment by lazka** [comment]
I've created https://github.com/pypa/distutils/pull/267

I went with option (1), since (2) turned out to be not possible without major changes.

**Comment by jan-david-fischbach** [comment]
+1
