### ISSUE TITLE
[BUG] upgraded vendor copy of importlib_metadata breaks packages

### ISSUE THREAD

**Issue by novas0x2a** [pypa/setuptools#4489]
### setuptools version

setuptools==71.0.0 setuptools==71.0.1 setuptools==71.0.2

### Python version

3.9

### OS

ubuntu 22.04 (linux)

### Description

We have sdists that are not yet fully converted to pep517; however, they would build correctly with `pip wheel --use-pep517`. Unfortunately, importlib_metadata 8.0.0 landed this change (https://github.com/python/importlib_metadata/issues/371) which converts a None return into a KeyError.

### Expected behavior

I expected an existing package to keep working.

### How to Reproduce

This is with a specific internal package with code I can't share, but I can answer questions about it.

### Output

```console
(.venv-3.9) $ pip freeze --all
pip==24.1.2
setuptools==71.0.2
(.venv-3.9) $ pip wheel .
Processing $HOME/$PACKAGENAME-4.0.51
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running egg_info
      Traceback (most recent call last):
        File "$HOME/$PACKAGENAME-4.0.51/.venv-3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "$HOME/$PACKAGENAME-4.0.51/.venv-3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "$HOME/$PACKAGENAME-4.0.51/.venv-3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 45, in <module>
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.ensure_finalized()
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 258, in finalize_options
          key = getattr(pd, "key", None) or getattr(pd, "name", None)
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 460, in name
          return self.metadata['Name']
        File "/tmp/pip-build-env-95l81nvf/overlay/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/_adapters.py", line 54, in __getitem__
          raise KeyError(item)
      KeyError: 'Name'
      [end of output]


```

It looks like the egg_info command had a workaround for the scenario this package is triggering (https://github.com/pypa/setuptools/blob/17b735a260dc6e51cce1edbeb21eaaa5a32ef188/setuptools/command/egg_info.py#L258) and no longer does. If I add a try/except for KeyError around this code, the wheel builds as before.

I assume this is at least partially related to this internal package, but I don't actually know what I'd need to change to fix it. I'm also not sure if this scenario is _supposed_ to fail now, maybe there's some problem that we didn't notice with the old way?

**Comment by jaraco** [comment]
Thanks for the report. Yes, as part of the simplified vendoring process in Setuptools 71, the vendored packages were also updated, including the backward-incompatible behavior of importlib_metadata 8. It wasn't anticipated this change would have an effect on users, but it seems to have caught an issue unique to your environment where the relevant package does not have a Name metadata field.

I have a decent understanding of what's going on and I'll take a look in earnest tomorrow.

**Comment by jaraco** [comment]
It looks like maybe abravalheri added that change in #3823. If I revert that change, the tests still pass, and I'm not very confident in what that code is aiming to accomplish.

It looks like `pd` is a `importlib.metadata.PackageMetadata | None` and here is [the only place it's set](https://github.com/pypa/setuptools/blob/17b735a260dc6e51cce1edbeb21eaaa5a32ef188/setuptools/dist.py#L288C22-L288C35). Since [PackageMetadata doesn't have a .key property](https://github.com/python/cpython/blob/7b36b67b1e585c541b418eaa190c56e73f9a2d87/Lib/importlib/metadata/_meta.py#L11-L44), I'm thinking that check should be for just `pd.metadata.get('Name', None)`.

But wait! `pd` is never used and it's immediately cleared after altering its properties. I'm now beginning to think that anything having to do with `distribution._patched_dist` should just be removed.
