### ISSUE TITLE
[BUG] pyproject.toml based builds using setuptools.build_meta don't allow setup.py to import from the local project

### ISSUE THREAD

**Issue by zahlman** [pypa/setuptools#4764]
### setuptools version

75.6.0

### Python version

3.10

### OS

Linux Mint 21.3 Cinnamon

### Additional environment information

I doubt that the problem is specific to the above details to any significant extent.

### Description

Imports from `setup.py` to the local code fail (even within `setup.py`'s directory) when `setuptools.build_meta` is used as the backend. The path to `setup.py` is missing from `sys.path`, leading to the traceback shown below.

The build succeeds if `sys.path` is appropriately hacked in `setup.py`, e.g.
```
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent))
import content
```
; or if `setuptools.build_meta:__legacy__` is used instead (or if the `build-backend` key is omitted from `pyproject.toml` entirely.

The problem is *not* fixed by disabling build isolation, nor by using a different front-end (e.g. `pip wheel .`).

### Expected behavior

The build should succeed as is, since the historical user expectation is that `setup.py` can import code from the local project. (For example, this has been used to retrieve a `__version__` value and compute dynamic version metadata. While I understand that Setuptools provides its own mechanisms for this now, this is just one example of a use case generally expected to work.)

### How to Reproduce

```console
$ mkdir test_project && cd test_project
$ touch content.py
$ cat > setup.py
from setuptools import setup
import content

setup()
$ cat > pyproject.toml
[project]
name = "test"
version = "1.0.0"

[build-system]
requires = ["setuptools==75.6.0"]
build-backend = "setuptools.build_meta"
$ pyproject-build
```

### Output

Using `pyproject-build` (i.e., `build` installed by Pipx) - home path elided:

```console
$ pyproject-build
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools==75.6.0
* Getting build dependencies for sdist...
Traceback (most recent call last):
  File "~/.local/pipx/venvs/build/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
  File "~/.local/pipx/venvs/build/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
  File "~/.local/pipx/venvs/build/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 317, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/tmp/build-env-e17m7bci/lib/python3.10/site-packages/setuptools/build_meta.py", line 337, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/tmp/build-env-e17m7bci/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-e17m7bci/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
    exec(code, locals())
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'content'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
```
Similarly via Pip (aliased to Pipx's copy):
```console
$ pip wheel .
Processing /path/to/test_project
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "~/.local/pipx/shared/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "~/.local/pipx/shared/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "~/.local/pipx/shared/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-aafckipn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-aafckipn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-aafckipn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'content'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by abravalheri** [comment]
By design `setuptools.build_meta` does not add the current workdir to `sys.path`. This change was introduced on purpose many years ago upon the adoption of PEP 517 to avoid common pitfalls of local files overwriting modules from the stdlib or other 3rd party libs.

If you wish to import local files please add the adequate statements (e.g. `import sys; sys.path.insert(...)` before the relevant imports in your `setup.py` script.

**Comment by zahlman** [comment]
Is the change documented somewhere? It makes sense and I agree with it, but I can imagine many people being confused when they attempt to migrate from legacy setup.py-only build processes.

**Comment by abravalheri** [comment]
To be honest, it is actually a direct consequence of the way PEP 517 (so there was no real change in setuptools itself, just a decision to not add anything new given the previous rationale).

I.e., when you call `python setup.py ...` Python adds the current directory to `sys.path`. If you don't call that, then nothing is added to `sys.path`. Please feel free tonsend a PR If you would like this to be mentioned explicitly in the PRs (not sure if it already is...)

**Comment by zahlman** [comment]
Ah, of course - the old workflows were all invoking it directly, and nobody would go out of their way to use `-I` or whatever, so naturally it would seem to work.

I guess what I'm really looking for is more detail in the [modernization guide](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/) offered on packaging.python.org. If I figure out how to write it up effectively, I'll offer a PR over there instead.

Thanks for helping me think through it clearly.
