### ISSUE TITLE
[BUG] cannot import name 'splat' from 'jaraco.functools'

### ISSUE THREAD

**Issue by adriansev** [pypa/setuptools#4773]
### setuptools version

75.6.0

### Python version

3.9.21

### OS

EL9 (Alma9)

### Additional environment information

`python3 -c 'import setuptools'`

### Description

```
python3 -c 'import setuptools'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/adrian/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 22, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/home/adrian/.local/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/home/adrian/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 89, in do_override
    ensure_local_distutils()
  File "/home/adrian/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 75, in ensure_local_distutils
    core = importlib.import_module('distutils.core')
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/adrian/.local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 13, in <module>
    from .cmd import Command
  File "/home/adrian/.local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 12, in <module>
    from . import _modified, archive_util, dir_util, file_util, util
  File "/home/adrian/.local/lib/python3.9/site-packages/setuptools/_distutils/_modified.py", line 6, in <module>
    from jaraco.functools import splat
ImportError: cannot import name 'splat' from 'jaraco.functools' (/usr/lib/python3.9/site-packages/jaraco/functools.py)
```

### Expected behavior

I expected no error

### How to Reproduce

1. Alma9 (EL9), OS distributed python3
2. `python3 -m pip install --no-cache-dir --upgrade $( [[ -z ${VIRTUAL_ENV} ]] && echo "--user" ) pip setuptools wheel`
3. `python3 -c 'import setuptools'`

### Output

```console

[Friday 20.12.24 13:19 adrian@monitor] ~ $
python3 -m pip install --no-cache-dir --upgrade $( [[ -z ${VIRTUAL_ENV} ]] && echo "--user" ) pip setuptools wheel
Requirement already satisfied: pip in ./.local/lib/python3.9/site-packages (24.3.1)
Requirement already satisfied: setuptools in ./.local/lib/python3.9/site-packages (75.6.0)
Requirement already satisfied: wheel in ./.local/lib/python3.9/site-packages (0.45.1)

[Friday 20.12.24 13:20 adrian@monitor] ~ $
python3 -c 'import setuptools'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/adrian/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 22, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/home/adrian/.local/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/home/adrian/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 89, in do_override
    ensure_local_distutils()
  File "/home/adrian/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 75, in ensure_local_distutils
    core = importlib.import_module('distutils.core')
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/adrian/.local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 13, in <module>
    from .cmd import Command
  File "/home/adrian/.local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 12, in <module>
    from . import _modified, archive_util, dir_util, file_util, util
  File "/home/adrian/.local/lib/python3.9/site-packages/setuptools/_distutils/_modified.py", line 6, in <module>
    from jaraco.functools import splat
ImportError: cannot import name 'splat' from 'jaraco.functools' (/usr/lib/python3.9/site-packages/jaraco/functools.py)
```

**Comment by adriansev** [comment]
the reason for filling this bug is that while https://github.com/pypa/setuptools/pull/4666 seemingly fixed this on 11 Nov, pip 75.6.0 was tagged on 20 Nov, so it's clear that above fix does not work.. 
I traced back to this while trying to find out the error for pip installing pyjq

**Comment by adriansev** [comment]
workaround that seems to work:
`python3 -m pip install --no-cache-dir --upgrade jaraco.functools`

**Comment by Avasam** [comment]
`pip install -U setuptools[core]` to also install the dependencies ;)

https://setuptools.pypa.io/en/latest/userguide/quickstart.html#installation

You likely had an old version of `jaraco.functools` laying around in your environment, so setuptools didn't fallback to its vendored version. And without the `[core]` extra, setuptools doesn't declare any dependency, so it wasn't updated when you ran your initial command.

**Comment by adriansev** [comment]
Thanks a lot!
