### ISSUE TITLE
Pip Install UnicodeDecodeError

### ISSUE THREAD

**Issue by foxylad** [pypa/setuptools#531]
Trying to install the latest setuptools on Ubuntu 12.04.5 LTS is giving me a UnicodeDecodeError. I'm no expert, but I wonder if there is a bad character in the setuptools metadata for pip. Here's the exception:

```
Downloading/unpacking setuptools>=11.3 (from cryptography>=1.3->PyOpenSSL->ndg-httpsclient)
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "pkg_resources/__init__.py", line 2900, in <module>
        @_call_aside
      File "pkg_resources/__init__.py", line 2886, in _call_aside
        f(*args, **kwargs)
      File "pkg_resources/__init__.py", line 2913, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "pkg_resources/__init__.py", line 626, in _build_master
        ws = cls()
      File "pkg_resources/__init__.py", line 619, in __init__
        self.add_entry(entry)
      File "pkg_resources/__init__.py", line 675, in add_entry
        for dist in find_distributions(entry, True):
      File "pkg_resources/__init__.py", line 1955, in find_on_path
        path_item, entry, metadata, precedence=DEVELOP_DIST
      File "pkg_resources/__init__.py", line 2343, in from_location
        py_version=py_version, platform=platform, **kw
      File "pkg_resources/__init__.py", line 2660, in _reload_version
        md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
      File "pkg_resources/__init__.py", line 2308, in _version_from_file
        line = next(iter(version_lines), '')
      File "pkg_resources/__init__.py", line 2476, in _get_metadata
        for line in self.get_metadata_lines(name):
      File "pkg_resources/__init__.py", line 1846, in get_metadata_lines
        return yield_lines(self.get_metadata(name))
      File "pkg_resources/__init__.py", line 1841, in get_metadata
        metadata = f.read()
      File "/usr/lib/python2.7/codecs.py", line 296, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 147: invalid start byte
```

**Comment by jaraco** [comment]
I doubt I'll be able to replicate this issue. You'll need to dig deeper to identify the circumstances that lead to the error. For example, if you've removed setuptools from the host and you pip install setuptools, does the error still occur?

**Comment by foxylad** [comment]
Since no-one else has commented, this must be an issue with my environment. I'll close it, and will let you know if I find the cause.
