### ISSUE TITLE
distribute wheel build failure in setuptools>=20.2

### ISSUE THREAD

**Issue by dracos** [pypa/setuptools#535]
Setting up a virtualenv on Debian wheezy (using the Debian packaged virtualenv, and python 2) and wanting to use up-to-date setuptools, pip, and distribute within it (distribute still appears to need updating as otherwise bdist_wheel isn't found), the following works fine in setuptools 20.1.1 but gives a wheel error in 20.2.2 (though it still upgrades okay).

With 20.1.1, everything is fine:
```
$ virtualenv venv && source venv/bin/activate
[…]
(venv)$ curl --silent --location https://bootstrap.pypa.io/get-pip.py | python
[…]
Successfully installed pip-8.1.1 wheel-0.29.0
(venv)$ pip install setuptools==20.1.1
[…]
Successfully installed setuptools-20.1.1
(venv)$ python setup.py bdist_wheel # Show that we still need to upgrade distribute
[…] error: invalid command 'bdist_wheel'
(venv)$ pip install distribute==0.7.3
[…]
Building wheels for collected packages: distribute
  Running setup.py bdist_wheel for distribute ... done
Successfully built distribute
Successfully installed distribute-0.7.3
(venv)$ python setup.py bdist_wheel
[…successful output…]
```

Whereas with 20.2.2 you get an import error about `_markerlib`:
```
$ virtualenv venv && source venv/bin/activate
[…]
(venv)$ curl --silent --location https://bootstrap.pypa.io/get-pip.py | python
[…]
Successfully installed pip-8.1.1 wheel-0.29.0
(venv)$ pip install setuptools==20.2.2
[…]
Successfully installed setuptools-20.2.2
(venv)$ pip install distribute==0.7.3
[…]
Building wheels for collected packages: distribute
  Running setup.py bdist_wheel for distribute ... error
[…]
      from _markerlib import compile as compile_marker
  ImportError: No module named _markerlib
[…]
  Failed building wheel for distribute
  Running setup.py clean for distribute
Failed to build distribute
[…]
Successfully installed distribute-0.7.3
```

I see the history for 20.2 mentions _markerlib, but I don't understand what it changed that meant this no longer works. I'm not sure if this is actually an issue or whether another approach should be taken, but thought I'd raise it here, I couldn't find a similar ticket.

**Comment by earthgecko** [comment]
Ran onto this as well in the context of building with virtualenv (15.0.1) with pip 8.1.1 and setuptools 20.9.0 and 20.2.2

Whenever there appears to be a distribute in the mix it results in failures, so distribute cannot be installed with pip/setuptools (and virtualenv 15.0.1) since the new structure?

If you try to install the distribute package via pip or pip installing a requirements file that has distribute in it since 20.2 when _markerlib was removed (and virtualenv 15.0.1) it breaks.

```
Collecting distribute (from -r /opt/skyline/python-2.7.9.requirements.txt (line 10))
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/distribute.egg-info
    writing requirements to pip-egg-info/distribute.egg-info/requires.txt
    writing pip-egg-info/distribute.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/distribute.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/distribute.egg-info/dependency_links.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-O6QpsM/distribute/setup.py", line 58, in <module>
        setuptools.setup(**setup_params)
      File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setuptools/command/egg_info.py", line 177, in run
        writer = ep.load(installer=installer)
      File "pkg_resources.py", line 2241, in load
        if require: self.require(env, installer)
      File "pkg_resources.py", line 2254, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "pkg_resources.py", line 2471, in requires
        dm = self._dep_map
      File "pkg_resources.py", line 2682, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "pkg_resources.py", line 2699, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named _markerlib

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-O6QpsM/distribute/
```

Removing the `distribute` package from my requirements.txt and ensuring that my virtualenv was created **without** having OPTIONS `--distribute --setuptools` passed to it, resolved the issue in this case.

**Comment by jaraco** [comment]
Based on @earthgecko 's report, it sounds as if the issue is a lingering requirement for distribute, which has been deprecated for years. I should hope it's not necessary for late releases of setuptools to continue to support installations of distribute. Please let report back if the prescribed workaround isn't sufficient to work around the issue.

**Comment by dracos** [comment]
You still have an issue when distribute is not involved at all, see the following transcript:

```
$ virtualenv --setuptools pypavenv && source pypavenv/bin/activate
New python executable in pypavenv/bin/python
Installing setuptools............done.
Installing pip...............done.
(pypavenv)$ curl --silent --location https://bootstrap.pypa.io/get-pip.py | python
Collecting pip
  Using cached pip-8.1.1-py2.py3-none-any.whl
Collecting wheel
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Installing collected packages: pip, wheel
  Found existing installation: pip 1.1
    Uninstalling pip-1.1:
      Successfully uninstalled pip-1.1
Successfully installed pip-8.1.1 wheel-0.29.0
(pypavenv)$ pip install setuptools
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./pypavenv/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg
(pypavenv)$ pip install setuptools --upgrade
Collecting setuptools
  Using cached setuptools-20.9.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 0.6rc11
    Uninstalling setuptools-0.6rc11:
      Successfully uninstalled setuptools-0.6rc11
Successfully installed setuptools
Traceback (most recent call last):
  File ".../pypavenv/bin/pip", line 11, in <module>
    sys.exit(main())
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/basecommand.py", line 246, in main
    pip_version_check(session)
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 848, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 626, in __init__
    self.add_entry(entry)
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 682, in add_entry
    for dist in find_distributions(entry, True):
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2080, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1610, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1968, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1848, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File ".../pypavenv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1788, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '.../pypavenv/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg'
(pypavenv)$ 
```

It doesn't give this error if you upgrade setuptools before upgrading pip, but that's a less secure way round. Debian wheezy is in LTS until 2018, so it'd be great if one could upgrade pip/setuptools in such a virtualenv without issue.

**Comment by earthgecko** [comment]
@dracos what version of virtualenv are you using?

I found that the changes relating to `--distribute` and `--setuptools` OPTIONS in virtualenv in 15.0.1 and the addition of them upgrading to setuptools 20.2.2 and pip to 8.1.0 - https://virtualenv.pypa.io/en/latest/changes.html#id1 - prior to virtualenv 15.0.1 is going to be problematic in terms of setuptools I think.

It appear to me that since setuptools, pip and virtualenv all changed to the new setuptools and pkg_resources _markerlib related layout, they will not work together with lesser versions than those which all fulfil the new layout.

**Comment by dracos** [comment]
Yeah, precisely :-/ As mentioned, I'm using the Debian wheezy packaged version; I just thought it would be nice if this could be done without bootstrapping virtualenv, especially as it's been fine only until recently. &lt;shrug&gt;
