### ISSUE TITLE
With the version 20.7.0 he call extra in the environment

### ISSUE THREAD

**Issue by sbrunner** [pypa/setuptools#544]
Trace:
```
Traceback (most recent call last):
  File ".build/venv/bin/pot-create", line 11, in <module>
    sys.exit(main())
  File "/home/sbrunner/2.1/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/lingua/extract.py", line 252, in main
    register_babel_plugins()
  File "/home/sbrunner/2.1/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/lingua/extractors/babel.py", line 51, in register_babel_plugins
    extractor = entry_point.load(require=True)
  File "/home/sbrunner/2.1/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/home/sbrunner/2.1/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/home/sbrunner/2.1/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 808, in resolve
    if not req_extras.markers_pass(req):
  File "/home/sbrunner/2.1/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 993, in markers_pass
    return not req.marker or any(extra_evals) or req.marker.evaluate()
  File "/home/sbrunner/2.1/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/home/sbrunner/2.1/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/home/sbrunner/2.1/c2cgeoportal/.build/venv/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
pkg_resources._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```
With the entrypoint `jinja2 = jinja2.ext:babel_extract [i18n]`

**Comment by sbrunner** [comment]
Thanks @jaraco, I will test it :-)

**Comment by remyroy** [comment]
This issue seems present with version 21.0.0.
