### ISSUE TITLE
Cannot install latest version (20.9.0) with ez_setup.py

### ISSUE THREAD

**Issue by aleury** [pypa/setuptools#550]
We use the recommended method of installing setuptools described [here](https://pypi.python.org/pypi/setuptools#unix-wget) but am getting the following error
```
Extracting in /tmp/tmp7lPgUQ
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/ez_setup.py", line 415, in <module>
    sys.exit(main())
  File "/home/ubuntu/ez_setup.py", line 412, in main
    return _install(archive, _build_install_args(options))
  File "/home/ubuntu/ez_setup.py", line 52, in _install
    with archive_context(archive_filename):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/ubuntu/ez_setup.py", line 103, in archive_context
    with ContextualZipFile(filename) as archive:
  File "/home/ubuntu/ez_setup.py", line 87, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```
when running `sudo python ez_setup.py --version 20.9.0`.

**Comment by jaraco** [comment]
As seen in #549, the sdists for 20.9.0 did not upload properly. I just tested and it's fixed now (and I hope for future automated releases).
