### ISSUE TITLE
BadZipfile with version 21.0.0 on OSX

### ISSUE THREAD

**Issue by maethu** [pypa/setuptools#569]
Python 2.7.11
OSX 10.11.4
boostrap.py 2015-07-01

```
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-21.0.0.zip
Extracting in /var/folders/g8/qzn0zpn53yn346b4ldm8jh7h0000gn/T/tmpHTcW1l
Traceback (most recent call last):
  File "bootstrap.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 175, in use_setuptools
  File "<string>", line 126, in _do_download
  File "<string>", line 66, in _build_egg
  File "/Users/maethu/python/parts/opt/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 105, in archive_context
  File "<string>", line 89, in __new__
  File "/Users/maethu/python/parts/opt/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/Users/maethu/python/parts/opt/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

**Comment by maethu** [comment]
ahh duplicate of https://github.com/pypa/setuptools/issues/568 (sry miss to hit the submit button).
