### ISSUE TITLE
sdist 20.6.8 not installable from bootstrap script

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#579]
From report in #568, it seems that 20.6.8 fails to install from a bootstrap script:

```
$ env/bin/python ez_setup.py --version=20.6.8 
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-20.6.8.zip
Extracting in /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/tmp0l0ab10r
Traceback (most recent call last):
  File "ez_setup.py", line 425, in <module>
    sys.exit(main())
  File "ez_setup.py", line 422, in main
    return _install(archive, _build_install_args(options))
  File "ez_setup.py", line 56, in _install
    with archive_context(archive_filename):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "ez_setup.py", line 107, in archive_context
    with ContextualZipFile(filename) as archive:
  File "ez_setup.py", line 91, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by jaraco** [comment]
pypa.io redirects the request to a 404:

```
$ curl -v https://pypi.io/packages/source/s/setuptools/setuptools-20.6.8.zip > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 151.101.192.223...
* Connected to pypi.io (151.101.192.223) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: www.python.org
* Server certificate: DigiCert SHA2 Extended Validation Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /packages/source/s/setuptools/setuptools-20.6.8.zip HTTP/1.1
> Host: pypi.io
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-20.6.8.zip
< Content-Security-Policy: base-uri 'self'; block-all-mixed-content; connect-src 'self'; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.herokuapp.com/ https://secure.gravatar.com; referrer origin-when-cross-origin; reflected-xss block; script-src 'self'; style-src 'self' fonts.googleapis.com
< Content-Type: text/html; charset=UTF-8
< Content-Length: 278
< Accept-Ranges: bytes
< Date: Mon, 09 May 2016 20:59:57 GMT
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-iad2140-IAD
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1462827597.287123,VS0,VE16
< Vary: Accept-Encoding
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: none
< 
{ [278 bytes data]
100   278  100   278    0     0   1469      0 --:--:-- --:--:-- --:--:--  1478
* Connection #0 to host pypi.io left intact
$ curl -v https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-20.6.8.zip > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 172.111.67.6...
* Connected to files.pythonhosted.org (172.111.67.6) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: o.ssl.fastly.net
* Server certificate: GlobalSign CloudSSL CA - SHA256 - G3
* Server certificate: GlobalSign Root CA
> GET /packages/source/s/setuptools/setuptools-20.6.8.zip HTTP/1.1
> Host: files.pythonhosted.org
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Fastly-Debug-Digest: 658d9bf92065aed0e3da986f8264f6f9f86848cb5516d12ee6e51f3e8757bb96
< Content-Length: 0
< Accept-Ranges: bytes
< Date: Mon, 09 May 2016 21:00:40 GMT
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-iad2144-IAD, cache-sjc3647-SJC
< X-Cache: MISS, MISS
< X-Cache-Hits: 0, 0
< X-Timer: S1462827639.970564,VS0,VE196
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: none
< 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
* Connection #0 to host files.pythonhosted.org left intact
```

**Comment by jaraco** [comment]
Seems the release for v20.6.8 wasn't cut properly.

**Comment by jaraco** [comment]
https://pypi.python.org/pypi/setuptools/20.6.8 now shows a release, so this should fix the issue.
