### ISSUE TITLE
Bootstrap script unable to locate releases following 22.0.0

### ISSUE THREAD

**Issue by pabo3000** [pypa/setuptools#600]
How to test:

Download

https://bootstrap.pypa.io/bootstrap-buildout.py

At the time of this ticket, __version__ of this file is 2015-07-01.

Run

`python bootstrap-buildout.py`

You get

```
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-22.0.0.zip
Extracting in /tmp/tmphdbup5
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 177, in use_setuptools
  File "<string>", line 128, in _do_download
  File "<string>", line 68, in _build_egg
  File "/home/pab/workspace/buildout.python/parts/opt/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 107, in archive_context
  File "<string>", line 91, in __new__
  File "/home/pab/workspace/buildout.python/parts/opt/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/home/pab/workspace/buildout.python/parts/opt/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

```

**Comment by pabo3000** [comment]
doublet
