### ISSUE TITLE
distutils fails on sshuttle: setuptools-scm was unable to detect version

### ISSUE THREAD

**Issue by yurivict** [pypa/setuptools#607]
When I run distutils on this project https://github.com/apenwarr/sshuttle it fails:
```
Installed /usr/ports/security/sshuttle/work/sshuttle-0.78.0/.eggs/setuptools_scm-1.11.0-py2.7.egg
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 60, in <module>
    keywords="ssh vpn",
  File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "build/bdist.freebsd-10.3-STABLE-amd64/egg/setuptools_scm/integration.py", line 19, in version_keyword
  File "build/bdist.freebsd-10.3-STABLE-amd64/egg/setuptools_scm/__init__.py", line 104, in get_version
  File "build/bdist.freebsd-10.3-STABLE-amd64/egg/setuptools_scm/__init__.py", line 82, in _do_parse
LookupError: setuptools-scm was unable to detect version for '/usr/ports/security/sshuttle/work/sshuttle-0.78.0'.
```

Found this in the context of the FreeBSD port using distutils.
Version 20.0.

**Comment by jaraco** [comment]
I'm pretty sure this isn't a Setuptools bug. It's possibly a bug with Setuptools-scm or maybe with sshuttle. My guess is that you're trying to run setup.py on a copy of the code without the scm metadata and without the version info that would have come with an sdist.
