### ISSUE TITLE
AttributeError: 'module' object has no attribute 'chdir' when installing 25.0.1

### ISSUE THREAD

**Issue by jwg4** [pypa/setuptools#692]
I create a fresh virtualenv, activate it, and do

    venv/bin/pip install --upgrade setuptools

I get a failure as follows:

    Running setup.py egg_info for package setuptools
      Traceback (most recent call last):
        File "<string>", line 16, in <module>
        File "/var/lib/jenkins-slave/workspace/quotes_selenium/venv/build/setuptools/setup.py", line 194, in <module>
          here and os.path.chdir(here)
      AttributeError: 'module' object has no attribute 'chdir'
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):
     
    File "<string>", line 16, in <module>
     
    File "/var/lib/jenkins-slave/workspace/quotes_selenium/venv/build/setuptools/setup.py", line 194, in <module>
     
      here and os.path.chdir(here)
     
     AttributeError: 'module' object has no attribute 'chdir'

This has started happening in our automated builds this morning. The most recent successful build installed version 25.0.0

**Comment by jwg4** [comment]
Sorry, just seen that this was fixed. I stupidly searched for open issues not all issues.
