### ISSUE TITLE
"ImportError: No module named ..." error

### ISSUE THREAD

**Issue by unai-ttxu** [pypa/setuptools#693]
Using the 25.0.1 version we get the following error:

```
ERROR: Failure: ImportError (No module named 'tests.mock_decorators')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Documents/projects/project-name/env-ut/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/Documents/projects/project-name/env-ut/lib/python3.4/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/Documents/projects/project-name/env-ut/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/Documents/projects/project-name/env-ut/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/Documents/projects/project-name/env-ut/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/Documents/projects/project-name/env-ut/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/Documents/projects/project-name/tests/tests_ut/test_aux_json.py", line 12, in <module>
    from tests.mock_decorators.attribute_mock import AttributeMock
ImportError: No module named 'tests.mock_decorators'
```

We change the version to 24.3.1 and it works perfect.

**Comment by jaraco** [comment]
This issue is probably due to the intentional change with 25.0, which changes the default path ordering. The fact that you're importing from a package called `tests` leads me to believe that you probably have something masking that package name in the local install that in earlier versions of Setuptools had precedence.

Do this for me - in the code that is failing to test:

```
import tests
print(tests.__file__)
```

That'll reveal where tests is being found and why it doesn't have a mock_decorators member/module.
