### ISSUE TITLE
Error on CI servers wth version 25

### ISSUE THREAD

**Issue by goanpeca** [pypa/setuptools#727]
Projects using continuous integrations services (travis, circle ci, appveyor) report this error with version 25. Not sure what it means, but had to revert to 23, which works fine.

We are using 

`python setup.py develop`

``` bash
$PYTHON_TEST binstar_client/tests/runtests.py
<module 'binstar_client' from '/home/ubuntu/miniconda/envs/test/lib/python2.7/site-packages/binstar_client/__init__.pyc'>
Discover /home/ubuntu/miniconda/envs/test/lib/python2.7/site-packages/
Traceback (most recent call last):
  File "binstar_client/tests/runtests.py", line 46, in <module>
    main()
  File "binstar_client/tests/runtests.py", line 31, in main
    tests = loader.discover(discover_dir)
  File "/home/ubuntu/miniconda/envs/test/lib/python2.7/unittest/loader.py", line 206, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/home/ubuntu/miniconda/envs/test/lib/python2.7/unittest/loader.py", line 287, in _find_tests
    for test in self._find_tests(full_path, pattern):
  File "/home/ubuntu/miniconda/envs/test/lib/python2.7/unittest/loader.py", line 267, in _find_tests
    raise ImportError(msg % (mod_name, module_dir, expected_dir))
ImportError: 'test' module incorrectly imported from '/home/ubuntu/miniconda/envs/test/lib/python2.7/site-packages'. Expected '/home/ubuntu/miniconda/envs/test/lib/python2.7/site-packages/py'. Is this module globally installed?

$PYTHON_TEST binstar_client/tests/runtests.py returned exit code 1
```

**Comment by abravalheri** [comment]
Thank you very much for reporting this.

It seems that whatever error was happening, it might has been corrected in following versions... So I think we can close this issue now.

Please let me know if the issue persists in the latest versions of setuptools and I will re-open the ticket.
