### ISSUE TITLE
TypeError: dist must be a Distribution instance

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#73]
Originally reported by: **Anonymous**

---

This works on a fresh clean precise vm:

```
wget https://pypi.python.org/packages/source/s/setuptools/setuptools-0.9.8.tar.gz
tar zxvf setuptools-0.9.8.tar.gz
cd setuptools-0.9.8/
sudo python setup.py install
cd
sudo easy_install pip
sudo aptitude install libffi-dev
git clone git@github.com:openstack/swift.git
cd swift/
sudo python setup.py install
```

If I s/setuptools-0.9.8/setuptools-1.1/g those commands, the swift install fails with the Distribution TypeError

```
Processing dependencies for swift==1.9.2.39.g261142d
Searching for python-swiftclient
Reading https://pypi.python.org/simple/python-swiftclient/
Best match: python-swiftclient 1.5.0
Downloading https://pypi.python.org/packages/source/p/python-swiftclient/python-swiftclient-1.5.0.tar.gz#md5=717ade4e91c0f5372f6fa6d545e7bab7
Processing python-swiftclient-1.5.0.tar.gz
Writing /tmp/easy_install-5ywEpr/python-swiftclient-1.5.0/setup.cfg
Running python-swiftclient-1.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5ywEpr/python-swiftclient-1.5.0/egg-dist-tmp-wk8goo
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'd2to1'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'setup_requires'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    pbr=True)
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/clayg/setuptools-1.1/setuptools/command/develop.py", line 27, in run
    self.install_for_development()
  File "/home/clayg/setuptools-1.1/setuptools/command/develop.py", line 129, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/clayg/setuptools-1.1/setuptools/command/easy_install.py", line 684, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/clayg/setuptools-1.1/pkg_resources.py", line 568, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/home/clayg/setuptools-1.1/pkg_resources.py", line 806, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/home/clayg/setuptools-1.1/pkg_resources.py", line 818, in obtain
    return installer(requirement)
  File "/home/clayg/setuptools-1.1/setuptools/command/easy_install.py", line 606, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/clayg/setuptools-1.1/setuptools/command/easy_install.py", line 636, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/clayg/setuptools-1.1/setuptools/command/easy_install.py", line 822, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/clayg/setuptools-1.1/setuptools/command/easy_install.py", line 1084, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/clayg/setuptools-1.1/setuptools/command/easy_install.py", line 1069, in run_setup
    run_setup(setup_script, args)
  File "/home/clayg/setuptools-1.1/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/home/clayg/setuptools-1.1/setuptools/sandbox.py", line 120, in run
    return func()
  File "/home/clayg/setuptools-1.1/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 21, in <module>
    setup_requires=['pbr>=0.5.21,<1.0'],
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 970, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/home/clayg/setuptools-1.1/setuptools/__init__.py", line 60, in __init__
    _Command.__init__(self,dist)
  File "/usr/lib/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
```

It has something to do with distutils/core.py's Distribution class not being patched to setuptools.dist.Distribution in time during the dependency installation, because the "TypeError: dist must be a Distribution instance" that's being raised is from the distutils code is lazy importing distutils.dist.Distribution and gets setuptools.dist.Distribution, but the "dist" instance is checking is_subclass on is really a distutils.dist.Distribution - because it was instantiated as such back in the dependencies call to setuptools.setup (which I guess is _really_ distutils.core.setup).

What's curious is that when I drop a pdb.set_trace() in distutils.core around line # 102 to catch the case where `Distribution.__module__.startswith('distutils')` - I find it's _only_ distutils.core.Distribution that's un-patched. sys.modules['distutils'].dist.Distribution verifies that there it is in fact setuptools.dist.Distribution, but that must have happened after this module imported it. If I reload(sys.modules['setuptools.dist']) the side-effect monkey patching fixes everything and the install completes just fine.

If I patch the setuptools source before I install it like so:

curl http://paste.openstack.org/raw/45403/ | patch -p1

It seems to work.

I think this bug effects any project who's dependencies have a setup_requires line - maybe.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/73

**Comment by JensTimmerman** [comment]
this isn't just a nose issue, Other projects are also running into this.
http://stackoverflow.com/questions/21136266/typeerror-dist-must-be-a-distribution-instance-when-resolving-beautifulsoup-d
https://github.com/numpy/numpy/issues/7235
https://bugs.launchpad.net/pbr/+bug/1412875
https://bugs.launchpad.net/pbr/+bug/1324784
https://groups.google.com/forum/#!topic/cython-users/VP44IsQrJ60
https://ask.openstack.org/en/question/5478/how-do-i-work-around-the-typeerror-dist-must-be-a-distribution-instance-problem-when-following-the-swift-all-in-one-instructions/

this is driving a lot of people insane!

**Comment by nickelchen** [comment]
I have a project with dependency of `oslo.config` `oslo.utils` `pytz` and when I execute
     `python setup.py develop` 
this issue arise. work around is install these dependencies with pip separately.
`pip install oslo.config`
`pip install oslo.utils`
then
`python setup.py develop`
