### ISSUE TITLE
setup.py develop fails to install non ascii scripts

### ISSUE THREAD

**Issue by maxyz** [pypa/setuptools#761]
Using a minimal setup.py:

``` python
#!/usr/bin/python
from setuptools import setup
setup(name="test",
      scripts=['bin/non_ascii'],
      )
```

With bin/non_ascii as:

``` sh
#!/bin/sh
# á

non_python_fn() {
}
```

setup develop fails with:

``` sh
$ ./setup.py develop --user
running develop
running egg_info
writing test.egg-info/PKG-INFO
writing top-level names to test.egg-info/top_level.txt
writing dependency_links to test.egg-info/dependency_links.txt
reading manifest file 'test.egg-info/SOURCES.txt'
writing manifest file 'test.egg-info/SOURCES.txt'
running build_ext
Creating /home/user/.local/lib/python2.7/site-packages/test.egg-link (link to .)
test 0.0.0 is already the active version in easy-install.pth
Installing non_ascii script to /home/user/.local/bin
Traceback (most recent call last):
  File "./setup.py", line 5, in <module>
    scripts=['bin/non_ascii'],
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/develop.py", line 133, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 720, in process_distribution
    self.install_egg_scripts(dist)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/develop.py", line 169, in install_egg_scripts
    self.install_script(dist, script_name, script_text, script_path)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 798, in install_script
    self.write_script(script_name, _to_ascii(script_text), 'b')
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 830, in write_script
    f.write(contents)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 12: ordinal not in range(128)
```

Same goes for python3:

``` sh
$ python3 ./setup.py develop --user
running develop
running egg_info
writing dependency_links to test.egg-info/dependency_links.txt
writing test.egg-info/PKG-INFO
writing top-level names to test.egg-info/top_level.txt
reading manifest file 'test.egg-info/SOURCES.txt'
writing manifest file 'test.egg-info/SOURCES.txt'
running build_ext
Creating /home/user/.local/lib/python3.5/site-packages/test.egg-link (link to .)
Adding test 0.0.0 to easy-install.pth file
Traceback (most recent call last):
  File "./setup.py", line 5, in <module>
    scripts=['bin/non_ascii'],
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 133, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 720, in process_distribution
    self.install_egg_scripts(dist)
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 169, in install_egg_scripts
    self.install_script(dist, script_name, script_text, script_path)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 798, in install_script
    self.write_script(script_name, _to_ascii(script_text), 'b')
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 98, in _to_ascii
    return s.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 12: ordinal not in range(128)
```

Happy hacking,

**Comment by jaraco** [comment]
The call to `_to_ascii` appears to indicate to me that setuptools intentionally only supports ascii scripts. I would not be opposed to someone contributing to make Setuptools accept general unicode text, but someone would have to volunteer the implementation.

May I suggest instead only using the `console_scripts` feature to have setuptools generate your scripts or use `python -m` to launch the modules directly from your package, avoiding the script handlers altogether?

**Comment by maxyz** [comment]
Just to be clear, the issue only appears when using develop, when installing the module it works as expected. So I guess that develop hitting the _to_ascii while install might not.

Also, this issue is for non python scripts, so console_scripts is not really useful for my use case.

**Comment by spluque** [comment]
The error also occurs when using `setup.py develop --exclude-scripts`.  Is that expected when using this flag?

**Comment by FRidh** [comment]
We often encounter this error when testing packages and setting `LC_ALL="en_US.UTF-8"`  is sufficient in those cases. Anyway, odd that it only occurs with development mode.
