### ISSUE TITLE
27.1.1 broken

### ISSUE THREAD

**Issue by jone** [pypa/setuptools#779]
Seems that the latest release is broken:

```
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-27.1.1.zip
Extracting in /var/folders/sl/zm2jlwhx5vg91v5th340r5dw0000gn/T/tmpUr9V2u
Now working in /var/folders/sl/zm2jlwhx5vg91v5th340r5dw0000gn/T/tmpUr9V2u/setuptools-27.1.1
Building a Setuptools egg in /var/folders/sl/zm2jlwhx5vg91v5th340r5dw0000gn/T/tmpgk66xP
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/private/var/folders/sl/zm2jlwhx5vg91v5th340r5dw0000gn/T/tmpUr9V2u/setuptools-27.1.1/setuptools/__init__.py", line 13, in <module>
    from setuptools.extension import Extension
  File "/private/var/folders/sl/zm2jlwhx5vg91v5th340r5dw0000gn/T/tmpUr9V2u/setuptools-27.1.1/setuptools/extension.py", line 9, in <module>
    from .monkey import get_unpatched
  File "/private/var/folders/sl/zm2jlwhx5vg91v5th340r5dw0000gn/T/tmpUr9V2u/setuptools-27.1.1/setuptools/monkey.py", line 10, in <module>
    from . import msvc
  File "/private/var/folders/sl/zm2jlwhx5vg91v5th340r5dw0000gn/T/tmpUr9V2u/setuptools-27.1.1/setuptools/msvc.py", line 27, in <module>
    from . import monkey
ImportError: cannot import name monkey
/var/folders/sl/zm2jlwhx5vg91v5th340r5dw0000gn/T/tmpgk66xP/setuptools-27.1.1-py2.7.egg
Traceback (most recent call last):
  File "bootstrap.py", line 92, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 178, in use_setuptools
  File "<string>", line 129, in _do_download
  File "<string>", line 75, in _build_egg
IOError: Could not build the egg.
```

There is a circular import from `setuptools/monkey.py` and `setuptools/__init__.py`.

**Comment by mbarkhau** [comment]
see also https://github.com/pypa/setuptools/issues/780

**Comment by jone** [comment]
Duplicate #780

**Comment by jaraco** [comment]
I'll pull it from pypi now.
