### ISSUE TITLE
ImportError: cannot import name monkey

### ISSUE THREAD

**Issue by mbarkhau** [pypa/setuptools#780]
```
user@hostname:~/project$ venv/bin/pip install -U setuptools==27.1.0
Collecting setuptools==27.1.0
  Downloading setuptools-27.1.0-py2.py3-none-any.whl (464kB)
    100% |████████████████████████████████| 471kB 1.6MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 27.1.1
    Uninstalling setuptools-27.1.1:
      Successfully uninstalled setuptools-27.1.1
Successfully installed setuptools-27.1.0
user@hostname:~/project$ venv/bin/python -c "import setuptools"
user@hostname:~/project$ venv/bin/pip install -U setuptools==27.1.1
Collecting setuptools==27.1.1
  Using cached setuptools-27.1.1-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 27.1.0
    Uninstalling setuptools-27.1.0:
      Successfully uninstalled setuptools-27.1.0
Successfully installed setuptools-27.1.1
user@hostname:~/project$ venv/bin/python -c "import setuptools"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/project/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 13, in <module>
    from setuptools.extension import Extension
  File "/home/user/project/venv/local/lib/python2.7/site-packages/setuptools/extension.py", line 9, in <module>
    from .monkey import get_unpatched
  File "/home/user/project/venv/local/lib/python2.7/site-packages/setuptools/monkey.py", line 10, in <module>
    from . import msvc
  File "/home/user/project/venv/local/lib/python2.7/site-packages/setuptools/msvc.py", line 27, in <module>
    from . import monkey
ImportError: cannot import name monkey
user@hostname:~/project$ 
```

**Comment by mbarkhau** [comment]
In case it isn't obvoius, the log demonstrates that 27.1.0 is ok while 27.1.1 throws the error.

**Comment by jone** [comment]
This is a circular import `setuptools/__init__.py` => `setuptools/monkey.py` => `setuptools/__init__.py`

**Comment by mbarkhau** [comment]
Probably introduced here:
https://github.com/pypa/setuptools/commit/b3b6751926037b55c45787192719b7f9372622a8

**Comment by studioj** [comment]
same here on my windows machine
Running Python 2.7.11 and 2.7.12

**Comment by d0ugal** [comment]
27.1.2 is now out and fixes this.

**Comment by jone** [comment]
Awesome, thanks for the fast fix!! 🎉 ✨

**Comment by twheys** [comment]
On 27.2.0 I am still getting this issue, is it possible that it was reintroduced?

```
20-Sep-2016 07:24:36	Upgrading setuptools and coverage
20-Sep-2016 07:24:37	Collecting setuptools
20-Sep-2016 07:24:37	  Using cached setuptools-27.2.0-py2.py3-none-any.whl
20-Sep-2016 07:24:38	Collecting coverage
20-Sep-2016 07:24:38	  Using cached coverage-4.2.tar.gz
20-Sep-2016 07:24:38	Could not import setuptools which is required to install from a source distribution.
20-Sep-2016 07:24:38	Traceback (most recent call last):
20-Sep-2016 07:24:38	  File "/home/bamboo/bandit-tests/lib/python3.4/site-packages/pip/req/req_install.py", line 372, in setup_py
20-Sep-2016 07:24:38	    import setuptools  # noqa
20-Sep-2016 07:24:38	  File "/home/bamboo/bandit-tests/lib/python3.4/site-packages/setuptools/__init__.py", line 13, in <module>
20-Sep-2016 07:24:38	    from setuptools.extension import Extension
20-Sep-2016 07:24:38	  File "/home/bamboo/bandit-tests/lib/python3.4/site-packages/setuptools/extension.py", line 9, in <module>
20-Sep-2016 07:24:38	    from .monkey import get_unpatched
20-Sep-2016 07:24:38	  File "/home/bamboo/bandit-tests/lib/python3.4/site-packages/setuptools/monkey.py", line 10, in <module>
20-Sep-2016 07:24:38	    from . import msvc
20-Sep-2016 07:24:38	  File "/home/bamboo/bandit-tests/lib/python3.4/site-packages/setuptools/msvc.py", line 27, in <module>
20-Sep-2016 07:24:38	    from . import monkey
20-Sep-2016 07:24:38	ImportError: cannot import name 'monkey'
```

**Comment by jaraco** [comment]
@twheys 

No. You have an old install lingering (probably due to upgrading a pip-installed setuptools with easy_install).  Notice "monkey.py" line 10 has `from . import msvc`. That code no longer exists.

**Comment by sushant711** [comment]
I have setuptools `36.0.1`, but still facing same issue.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, map
  File "/usr/local/lib/python2.7/site-packages/setuptools/setuptools/__init__.py", line 15, in <module>
    from setuptools.dist import Distribution, Feature, _get_unpatched
  File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 24, in <module>
    from setuptools.monkey import get_unpatched
ImportError: No module named monkey
```

**Comment by jaraco** [comment]
@sushant711, you have a corrupted install. There shouldn't be `setuptools` in a `setuptools` directory.

**Comment by SyedNawaz** [comment]
I have setuptools 37.0.0 but still face this issue

  File "/opt/aruba/central/apps/simulator/ENV/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/opt/aruba/central/apps/simulator/ENV/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/aruba/central/apps/simulator/sim_run.py", line 5, in <module>
    mpatch()
  File "/opt/aruba/central/apps/simulator/utils.py", line 14, in mpatch
    from gevent import monkey
ImportError: cannot import name monkey

**Comment by benoit-pierre** [comment]
@SyedNawaz: that's not the same issue: your traceback shows that the error occurs in your application's code, not in setuptools/pkg_resources.
