### ISSUE TITLE
wheel with extra_requires build with bdist_wheel not installable with pip 

### ISSUE THREAD

**Issue by pombredanne** [pypa/setuptools#782]
* Pip version: 8.12
* Setuptools version: 25.2.0
* wheel version: 0.29.0
* Python version: 2.7.6
* Operating System: Ubuntu x64 14.04 desktop

The full details are here: https://github.com/pypa/pip/issues/3958 
I am entering a ticket here too as somehow environment markers accepted by setuptools ended up not installable in pip. The issue was using was minor but hard to find. It would be best if the behaviour of wheel/setuptools/pip were the same when handling and validating/parsing markers.

This version of setup.py was building a proper wheel with setup.py bdist_wheel, but the wheel was failing to install with pip
https://github.com/nexB/scancode-toolkit/blob/a3ac6814508dda3ed5c52ab4feae127e71881a29/setup.py

I got this output:
```
$ pip install --upgrade -vv thirdparty/prod/scancode_toolkit-2.0.0.dev1-py2-none-any.whl 
Processing ./thirdparty/prod/scancode_toolkit-2.0.0.dev1-py2-none-any.whl
Cleaning up...
Invalid requirement: 'lxml==3.6.4; linux in "sys_platform"'
Traceback (most recent call last):
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'; linux '"

Exception information:
Traceback (most recent call last):
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/req/req_set.py", line 669, in _prepare_file
    add_req(subreq)
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/req/req_set.py", line 639, in add_req
    wheel_cache=self._wheel_cache,
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/req/req_install.py", line 87, in __init__
    "Invalid requirement: '%s'\n%s" % (req, add_msg))
InstallationError: Invalid requirement: 'lxml==3.6.4; linux in "sys_platform"'
Traceback (most recent call last):
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/home/pombreda/w421/conan/local/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'; linux '"
```

This corrected version does build with setuptools and installs with pip alright: 
https://github.com/nexB/scancode-toolkit/blob/e229862af7822ccfbe2f89149d74b1be2e76b5bb/setup.py#L111

**Comment by jaraco** [comment]
I see you've closed the upstream issue. If you still think there's an issue with setuptools, could you put together a minimal project that replicates the failure and show at least how the resultant wheel produced by setuptools has some unexpected characteristic?

**Comment by pombredanne** [comment]
Sure. Let me post that tomorrow

**Comment by pombredanne** [comment]
Here it is:
```
$ python setup-buggy.py bdist_wheel
[...]
$ pip install dist/setuptools_bug_failing-1.0.0-py2-none-any.whl 
Processing ./dist/setuptools_bug_failing-1.0.0-py2-none-any.whl
Invalid requirement: 'lxml==3.6.4; linux in "sys_platform"'
Traceback (most recent call last):
  File "/home/pombreda/w421/setuptools-782/tmp/local/lib/python2.7/site-packages/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/home/pombreda/w421/setuptools-782/tmp/local/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "'; linux '"
```

But 
```
$ pip install dist/setuptools_bug_good-1.0.0-py2-none-any.whl

**Comment by pombredanne** [comment]
wrong button

**Comment by jaraco** [comment]
More detail - 

```
$ python -m rwt wheel -- setup-buggy.py bdist_wheel -k    
Loading requirements using wheel
running bdist_wheel
running build
running build_py
running egg_info
writing src/setuptools_bug_failing.egg-info/PKG-INFO
writing dependency_links to src/setuptools_bug_failing.egg-info/dependency_links.txt
writing entry points to src/setuptools_bug_failing.egg-info/entry_points.txt
writing requirements to src/setuptools_bug_failing.egg-info/requires.txt
writing top-level names to src/setuptools_bug_failing.egg-info/top_level.txt
reading manifest file 'src/setuptools_bug_failing.egg-info/SOURCES.txt'
writing manifest file 'src/setuptools_bug_failing.egg-info/SOURCES.txt'
installing to build/bdist.macosx-10.6-intel/wheel
running install
running install_lib
creating build/bdist.macosx-10.6-intel/wheel
copying build/lib/bug.py -> build/bdist.macosx-10.6-intel/wheel
running install_egg_info
Copying src/setuptools_bug_failing.egg-info to build/bdist.macosx-10.6-intel/wheel/setuptools_bug_failing-1.0.0-py3.6.egg-info
running install_scripts
creating build/bdist.macosx-10.6-intel/wheel/setuptools_bug_failing-1.0.0.dist-info/WHEEL
$ cat build/bdist.macosx-10.6-intel/wheel/setuptools_bug_failing-1.0.0.dist-info/metadata.json | jq
{
  "classifiers": [
    "Development Status :: 4 - Beta"
  ],
  "extensions": {
    "python.commands": {
      "wrap_console": {
        "bug": "bug:run"
      }
    },
    "python.details": {
      "document_names": {
        "description": "DESCRIPTION.rst",
        "license": "LICENSE.txt"
      },
      "project_urls": {
        "Home": "https://github.com/pombredanne/setuptools-782"
      }
    },
    "python.exports": {
      "console_scripts": {
        "bug": "bug:run"
      }
    }
  },
  "extras": [],
  "generator": "bdist_wheel (0.29.0)",
  "license": "Apache-2.0",
  "metadata_version": "2.0",
  "name": "setuptools-bug-failing",
  "run_requires": [
    {
      "requires": [
        "unicodecsv"
      ]
    },
    {
      "environment": "\"darwin\" in sys_platform",
      "requires": [
        "lxml (==3.6.4)"
      ]
    },
    {
      "environment": "\"linux\" in sys_platform",
      "requires": [
        "lxml (==3.6.4)"
      ]
    },
    {
      "environment": "sys_platform == \"win32\"",
      "requires": [
        "lxml (==3.6.0)"
      ]
    }
  ],
  "summary": "https://github.com/pypa/setuptools/issues/782",
  "version": "1.0.0"
}
```

So it seems the extras are correct at the time the build is generated.

**Comment by jaraco** [comment]
Also, when I extract the generated .whl file, it also has the metadata formatted correctly. Same for METADATA in the .dist-info directory.

So whatever is munging the extra is on the consumer side.

**Comment by jaraco** [comment]
I'm pushing this ticket back to pip. Thanks for the repo which made it easy to replicate the failure.

**Comment by pombredanne** [comment]
@jaraco you are a prince! And I know now more on how to investigate these metadata issues. :bow:
