### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 11295: ordinal not in range(128)

### ISSUE THREAD

**Issue by stuertz** [pypa/setuptools#823]
Since setuptools 25.0.0 setuptools can't be installed with python 2.6
setuptools 24.2.0 seems to be the last version that still work with python 2.6, 
python 2.7 also works with later versions

Python version:
Python 2.6 (r26:66721, Oct  2 2008, 11:35:03) [MSC v.1500 32 bit (Intel)] on win32

```
[16:21:31,43] c:\temp> python ez_setup.py --version 25.0.0
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-25.0.0.zip
Extracting in c:\temp\tmp8iiskc
Now working in c:\temp\tmp8iiskc\setuptools-25.0.0
Installing Setuptools
running install
running bdist_egg
running egg_info
writing requirements to setuptools.egg-info\requires.txt
writing setuptools.egg-info\PKG-INFO
Traceback (most recent call last):
  File "setup.py", line 174, in <module>
    dist = setuptools.setup(**setup_params)
  File "c:\sdk\win32\1.1\Python26\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "c:\sdk\win32\1.1\Python26\lib\distutils\dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "c:\sdk\win32\1.1\Python26\lib\distutils\dist.py", line 995, in run_command
    cmd_obj.run()
  File "c:\temp\tmp8iiskc\setuptools-25.0.0\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "c:\temp\tmp8iiskc\setuptools-25.0.0\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "c:\sdk\win32\1.1\Python26\lib\distutils\cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "c:\sdk\win32\1.1\Python26\lib\distutils\dist.py", line 995, in run_command
    cmd_obj.run()
  File "c:\temp\tmp8iiskc\setuptools-25.0.0\setuptools\command\bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "c:\sdk\win32\1.1\Python26\lib\distutils\cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "c:\sdk\win32\1.1\Python26\lib\distutils\dist.py", line 995, in run_command
    cmd_obj.run()
  File "c:\temp\tmp8iiskc\setuptools-25.0.0\setuptools\command\egg_info.py", line 188, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "c:\temp\tmp8iiskc\setuptools-25.0.0\setuptools\command\egg_info.py", line 403, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "c:\sdk\win32\1.1\Python26\lib\distutils\dist.py", line 1077, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "c:\temp\tmp8iiskc\setuptools-25.0.0\setuptools\dist.py", line 71, in write_pkg_file
    file.write('Description: %s\n' % long_desc)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 11295: ordinal not in range(128)
Something went wrong during the installation.
See the error message above.

```

**Comment by jaraco** [comment]
Can you find precisely in which version it fails? There are a few releases between 24.2.0 and 25.0.0.

**Comment by jaraco** [comment]
Nevermind - you did say 24.2.0 was the last one that works, so the first failing one must be 24.2.1. Here's [what changed between those two](https://github.com/pypa/setuptools/compare/v24.2.0...v24.2.1), and it does seem that the code added in d079163e is implicated in the traceback. @xavfernandez Can you help devise a solution?

**Comment by xavfernandez** [comment]
Hmm, I took the `write_pkg_file` from python3 but apparently the python2 version was based on `self._write_field` which took care of encoding.

**Comment by xavfernandez** [comment]
@stuertz Does #824 fix your issue ? I tried to make the code equivalent to the distutils code.

**Comment by stuertz** [comment]
Yes. That fixes the issue. Looks good.

**Comment by xavfernandez** [comment]
Somehow I cannot create a failing test for 2.6 that exhibits this issue :-/
Feedback welcome on #824

**Comment by xavfernandez** [comment]
With python 2.6.9, `python ez_setup.py --version 25.0.0` works fine on my machine (linux), so there must be something else...

**Comment by stuertz** [comment]
Sorry for not updating over the weekend. I can reproduce this up to python 2.6.4 on windows. Since 2.6.5 the issue does not occur. :-( Sorry for having such an old python version.

**Comment by jaraco** [comment]
Given that it works with later versions of Python 2.6, I'll assume it was an upstream bug and avoid complicating the code. My recommendation for users encountering this issue is to upgrade to Python 2.6.5 or downgrade Setuptools.

I might consider additional protections to warn about these broken versions of Python, but I'm guessing the value is not worth the effort. Thanks to xavfernandez for working out a solution here - and thanks to stuertz for following up with extended testing.
