### ISSUE TITLE
Raw Linux Installation

### ISSUE THREAD

**Issue by a1rwulf** [pypa/setuptools#876]
I tried to follow the "How to install on Linux" instructions.
`a1rwulf-i5:~ # wget https://bootstrap.pypa.io/ez_setup.py -O - | python
Connecting to bootstrap.pypa.io (151.101.36.175:443)
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-30.2.0.zip
Extracting in /tmp/tmp4jgJyJ
Now working in /tmp/tmp4jgJyJ/setuptools-30.2.0
Installing Setuptools
running install
Traceback (most recent call last):
  File "setup.py", line 181, in <module>
    dist = setuptools.setup(**setup_params)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
  File "/tmp/tmp4jgJyJ/setuptools-30.2.0/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/tmp/tmp4jgJyJ/setuptools-30.2.0/setuptools/command/install.py", line 98, in do_egg_install
    easy_install = self.distribution.get_command_class('easy_install')
  File "/tmp/tmp4jgJyJ/setuptools-30.2.0/setuptools/dist.py", line 479, in get_command_class
    self.cmdclass[command] = cmdclass = ep.load()
  File "/tmp/tmp4jgJyJ/setuptools-30.2.0/pkg_resources/__init__.py", line 2287, in load
    return self.resolve()
  File "/tmp/tmp4jgJyJ/setuptools-30.2.0/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/tmp4jgJyJ/setuptools-30.2.0/setuptools/command/easy_install.py", line 48, in <module>
    from setuptools.py31compat import get_path, get_config_vars
  File "/tmp/tmp4jgJyJ/setuptools-30.2.0/setuptools/py31compat.py", line 2, in <module>
    import unittest
ImportError: No module named unittest
Something went wrong during the installation.
See the error message above.`

Seems there is a dependency on unittest.
Did I miss it in the docs?
Imho this would be worth menioning in the Installation Instructions.

**Comment by yan12125** [comment]
```unittest``` module comes with Python. If your Python does not have unittest, there's something wrong.
```
$ python2
Python 2.7.12 (default, Nov  7 2016, 11:55:55) 
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import unittest
>>> unittest
<module 'unittest' from '/usr/lib/python2.7/unittest/__init__.pyc'>
```

**Comment by a1rwulf** [comment]
Mhm, thought about that - should have mentioned that I was installing on some custom linux, that is all about being as lightweight as possible.
Sorry for the noise.
