### ISSUE TITLE
"UndefinedEnvironmentName: 'extra' does not exist in evaluation environment."

### ISSUE THREAD

**Issue by rwillmer** [pypa/setuptools#887]
I'd like to reopen #523 

I've provided a repeatable failure there in the form of a Dockerfile, and a workaround

**Comment by peterbrittain** [comment]
I've been trying to use `extra` to create an optional install in my project and am hitting exactly the same problem (https://github.com/peterbrittain/asciimatics/issues/95).  The workaround in #523 of using v20.4 works, but I don't really want to push a new version of my package out there that insists on downgrading setuptools to this level...

**Comment by rooterkyberian** [comment]
I tried to use `extra == "flag"` maker in my `install_requires`, but they seem to be broken since 36.2.0 (https://setuptools.readthedocs.io/en/latest/history.html#v36-2-0).

minimal example:
```
from setuptools import setup

setup(
    name="thingy",
    url="http://www.cluepoints.com",
    install_requires=["requests; extra =='please'"],
    packages=find_packages(),
)
```
using latests setuptools-40.8.0
```
$ python setup.py install
running install
running bdist_egg
running egg_info
creating thingy.egg-info
writing thingy.egg-info/PKG-INFO
writing dependency_links to thingy.egg-info/dependency_links.txt
writing requirements to thingy.egg-info/requires.txt
writing top-level names to thingy.egg-info/top_level.txt
writing manifest file 'thingy.egg-info/SOURCES.txt'
reading manifest file 'thingy.egg-info/SOURCES.txt'
writing manifest file 'thingy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying thingy.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thingy.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thingy.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thingy.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thingy.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/thingy-0.0.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing thingy-0.0.0-py3.6.egg
Copying thingy-0.0.0-py3.6.egg to /tmp/extra_test/.venv/lib/python3.6/site-packages
Adding thingy 0.0.0 to easy-install.pth file

Installed /tmp/extra_test/.venv/lib/python3.6/site-packages/thingy-0.0.0-py3.6.egg
Processing dependencies for thingy==0.0.0
Traceback (most recent call last):
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2664, in _dep_map
    return self.__dep_map
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2756, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    install_requires=["requests; extra =='please'"],
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 794, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in requires
    dm = self._dep_map
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2666, in _dep_map
    self.__dep_map = self._filter_extras(self._build_dep_map())
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2681, in _filter_extras
    invalid_marker(marker)
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1360, in invalid_marker
    evaluate_marker(text)
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1378, in evaluate_marker
    return marker.evaluate()
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/markers.py", line 301, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/markers.py", line 226, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/tmp/extra_test/.venv/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/markers.py", line 208, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
pkg_resources.extern.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```
