### ISSUE TITLE
KeyError: 'setuptools.msvc'

### ISSUE THREAD

**Issue by tkdchen** [pypa/setuptools#922]
- ``python2-setuptools-25.1.1-1.fc25.noarch``
- ``python2-virtualenv-15.0.3-2.fc25.noarch``
- ``pip 9.0.1``

```
[vagrant@localhost ~]$ virtualenv  tcmsenv
New python executable in /home/vagrant/tcmsenv/bin/python2
Not overwriting existing python script /home/vagrant/tcmsenv/bin/python (you must use /home/vagrant/tcmsenv/bin/python2)
Installing setuptools, pip, wheel...done.
[vagrant@localhost ~]$ . tcmsenv/bin/activate
(tcmsenv) [vagrant@localhost ~]$ pip install django-kombu
Collecting django-kombu
  Using cached django-kombu-0.9.4.tar.gz
>>> setuptools.msvc
Exception:
Traceback (most recent call last):
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/setuptools/__init__.py", line 160, in <module>
    monkey.patch_all()
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/setuptools/monkey.py", line 98, in patch_all
    patch_for_msvc_specialized_compiler()
  File "/home/vagrant/tcmsenv/lib/python2.7/site-packages/setuptools/monkey.py", line 150, in patch_for_msvc_specialized_compiler
    msvc = import_module('setuptools.msvc')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 38, in import_module
    return sys.modules[name]
KeyError: 'setuptools.msvc'
```

**Comment by jaraco** [comment]
Does the issue happen if you upgrade to the latest setuptools. Can you double-check your virtual environment to ensure that you have only one version of setuptools installed? [Looking at the code for Setuptools v25.1.1](https://github.com/pypa/setuptools/tree/v25.1.1/setuptools), it doesn't even have a monkey module, so you have some sort of mismatch going on.

Furthermore, your reported output seems incorrect. It appears as if you're getting a Python interactive prompt from a pip install command, which just doesn't happen, so you should more carefully report the steps you used to encounter the issue.
