### ISSUE TITLE
33.1.0 broke pytest-runner

### ISSUE THREAD

**Issue by felixonmars** [pypa/setuptools#923]
Hmm, I am not familiar with the details here, so I am not sure if this should be fixed here or in pytest-runner:

```
running test
running egg_info
writing setuptools.egg-info/PKG-INFO
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
writing requirements to setuptools.egg-info/requires.txt
writing top-level names to setuptools.egg-info/top_level.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'setuptools/_vendor'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 181, in <module>
    dist = setuptools.setup(**setup_params)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/build/python-setuptools/src/setuptools/setuptools/command/test.py", line 211, in run
    self.run_tests()
  File "/build/python-setuptools/src/setuptools/setuptools/command/test.py", line 234, in run_tests
    **exit_kwarg
  File "/usr/lib/python3.6/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/usr/lib/python3.6/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/build/python-setuptools/src/setuptools/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/build/python-setuptools/src/setuptools/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/build/python-setuptools/src/setuptools/setuptools/tests/test_msvc.py", line 20, in <module>
    pytest.importorskip("distutils.msvc9compiler")
  File "/usr/lib/python3.6/site-packages/_pytest/runner.py", line 562, in importorskip
    raise Skipped("could not import %r" %(modname,), allow_module_level=True)
Skipped: could not import 'distutils.msvc9compiler'
```

**Comment by jaraco** [comment]
In an earlier version of setuptools, we started using tox rather than pytest-runner as the preferred test runner for setuptools. In 93d8715bff, I removed the alias that made `setup.py test` invoke pytest-runner. As a result, `setup.py test` is now invoking unittest, which is not supported. I recommend you adapt your tests to use tox (following the technique that the .travis.yml or appveyor.yml files employ). If you wish to continue using pytest-runner, you're welcome to do so, but you'll want to invoke `setup.py pytest` rather than rely on the alias that I would prefer to leave removed so as not to incentivize use of that technique.

**Comment by felixonmars** [comment]
Thanks, running with `setup.py pytest` works fine here.

**Comment by silkentrance** [comment]
@jaroco running with setup.py pytest does not work anymore. I seems as everything is back to tox again 😁 . So pip install tox and then first running bootstrap.py and then tox will do the trick.

**Comment by jaraco** [comment]
I'm not sure if it works or doesn't or when it might have stopped working, but surely that's a different issue than `setup.py test` stopping working. And since the CI is using tox, that really is the only supported approach (though the project could surely accept a PR to keep setup.py pytest working if thath's of value).
