### ISSUE TITLE
 has no 'check_specifier' attribute error in setuptools 33.1.1

### ISSUE THREAD

**Issue by AdCastle** [pypa/setuptools#928]
Hi,

On a recent update to my Plone site I am getting a setuptools error on version 33.1.1. I am not sure if this is a zc.buildout error or a setuptools one but I am getting a setuptools error.

```
raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'setuptools.dist' from '/tmp/website/lib/python2.7/site-packages/setuptools/dist.pyc'> has no 'check_specifier' attribute
```
Is there a fix for this or I am doing something wrong? 

Thanks in advance.

Adam

Full traceback
===========

```
Installed /tmp/website/lib/python2.7/site-packages/zc.buildout-2.5.3-py2.7.egg
Processing dependencies for zc.buildout==2.5.3
Searching for setuptools>=8.0
Reading https://pypi.python.org/simple/setuptools/
Best match: setuptools 33.1.1
Downloading https://pypi.python.org/packages/dc/8c/7c9869454bdc53e72fb87ace63eac39336879eef6f2bf96e946edbf03e90/setuptools-33.1.1.zip#md5=7963d41d97b94e450e3f8a217be06ffe
Processing setuptools-33.1.1.zip
Writing /tmp/easy_install-7nmnfG/setuptools-33.1.1/setup.cfg
Running setuptools-33.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7nmnfG/setuptools-33.1.1/egg-dist-tmp-hco4vD
Traceback (most recent call last):
  File "bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==0.9.8', 'console_scripts', 'easy_install')()
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1992, in main
    with_ei_usage(lambda:
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1979, in with_ei_usage
    return f()
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1996, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 706, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/tmp/website/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/tmp/website/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/tmp/website/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
    return installer(requirement)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup
    run_setup(setup_script, args)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/tmp/website/lib/python2.7/site-packages/setuptools/sandbox.py", line 120, in run
    return func()
  File "/tmp/website/lib/python2.7/site-packages/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 181, in <module>

  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/website/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/tmp/website/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
    ep.load()(self, ep.name, value)
  File "/tmp/website/lib/python2.7/site-packages/pkg_resources.py", line 2265, in load
    raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'setuptools.dist' from '/tmp/website/lib/python2.7/site-packages/setuptools/dist.pyc'> has no 'check_specifier' attribute
```

**Comment by jaraco** [comment]
This error probably indicates an issue with a mismatch of metadata and install. Do you get the error if you rebuild from scratch?

**Comment by AdCastle** [comment]
Hi @jaraco this was from a completely clean buildout on a clean VM. I noticed that this started to happen after an upgrade from setuptools 29.0. I pinned to 29.0 again and it worked.

**Comment by jaraco** [comment]
I don't get the issue when I do a clean buildout with the latest buildout bootstrap script:

```
$ python bootstrap/bootstrap.py 
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/tmpkrmnj0w6
Now working in /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/tmpkrmnj0w6/setuptools-33.1.1
Building a Setuptools egg in /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/bootstrap-puzbv002
warning: no files found matching '*' under directory 'setuptools/_vendor'
/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/bootstrap-puzbv002/setuptools-33.1.1-py3.6.egg
Creating directory '/Users/jaraco/Dropbox/code/public/buildout/eggs'.
Creating directory '/Users/jaraco/Dropbox/code/public/buildout/bin'.
Creating directory '/Users/jaraco/Dropbox/code/public/buildout/parts'.
Creating directory '/Users/jaraco/Dropbox/code/public/buildout/develop-eggs'.
Generated script '/Users/jaraco/Dropbox/code/public/buildout/bin/buildout'.
```

I can see in your output that you're somehow getting setuptools 0.9.8, which is pretty old. There are known upgrade issues (see #315). It was [in 24.2.0 that the reference to check_specifier was added](https://github.com/pypa/setuptools/compare/v24.1.1...v24.2.0), so that seems unrelated to what you've reported above.

I've tried installing Setuptools 0.9.8 in a clean environment in order to try an easy_install upgrade from 0.9.8 to a late version, but I gave up with 0.9.8 didn't install on Python 3.6.

If you think you have a regression, please trace the issue to the exact setuptools version in which the problem first exhibits itself, then please provide steps to replicate the issue. If possible, please also trace the issue, characterizing where in the setuptools code you think the logic is going wrong.

I'm going to close this ticket, but if you can provide more detail that reveals an issue, then I'll happily re-open it.

**Comment by geofflangenderfer** [comment]
I'm having issues with check_specifier as well. Here's how the error is produced:

```
(venv) geoff@ubuntu:~/work/Assignments/test$ pip3 install memory_profiler
Collecting memory_profiler
  Using cached https://files.pythonhosted.org/packages/9f/fe/1fca7273dd111108f204a686b12a12b6422d405fe4614087aa7d5a66ea87/memory_profiler-0.55.0.tar.gz
Collecting psutil (from memory_profiler)
  Using cached https://files.pythonhosted.org/packages/1c/ca/5b8c1fe032a458c2c4bcbe509d1401dca9dda35c7fc46b36bb81c2834740/psutil-5.6.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "/home/geoff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2237, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lg6oiqdg/psutil/setup.py", line 350, in <module>
        main()
      File "/tmp/pip-install-lg6oiqdg/psutil/setup.py", line 346, in main
        setup(**kwargs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/geoff/.local/lib/python3.6/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/home/geoff/.local/lib/python3.6/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/geoff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/home/geoff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2239, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lg6oiqdg/psutil/

```
