### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by flyboy2017** [pypa/setuptools#975]
[root@server1 setuptools-34.2.0]# python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/root/setuptools-34.2.0/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/root/setuptools-34.2.0/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/root/setuptools-34.2.0/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

**Comment by flyboy2017** [comment]
system platform: Red Hat Enterprise Linux Server release 6.8 
program platform: python 2.7

execute Installation instruction Throw the above error  (bug), What is the cause of this problem? 

How to solve

**Comment by flyboy2017** [comment]
program: setuptools-34.2.0

**Comment by jaraco** [comment]
That issue occurs when you have pyparsing prior to 2.0.2 installed. That error has been reported before.

**Comment by jaraco** [comment]
#969
