### ISSUE TITLE
Having two PEP 420 implicit namespace levels in a package breaks setuptools

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#98]
Originally reported by: **petri_savolainen (Bitbucket: [petri_savolainen](http://bitbucket.org/petri_savolainen), GitHub: Unknown)**

---

This happens on Python >= 3.3 on OSX 10.9, within a python3 virtualenv (pyvenv).

When there are two namespace (sub)package levels, for example in mypkg.subpkg.sub2pkg, invoking python setup.py the second time fails, regardless of the command used (build / develop). Invoking setup.py [command] just once works perfectly. 

Invoking setup.py on ANY other package within the same Python installation also subsequently always fails.

Removing the .egg-info directory that's been generated by the first invocation removes the problem.

It does not happen when there is only one new-style namespace package, as in mypkg.subpkg. I was also not able to repeat the problem in Debian Linux.

After creating a banking.statements.osuuspankki pkg, with banking & banking.statements as namespace packages (without `__init__.py` in them) and invoking setup.py develop (or build, or..) second time:

``` python
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from setuptools import setup
  File "<frozen importlib._bootstrap>", line 1599, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1566, in _find_and_load_unlocked
  File "/Users/petri/Code/koodaamo/tilit/lib/python3.4/site-packages/setuptools-1.1.7-py3.4.egg/setuptools/__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1599, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1566, in _find_and_load_unlocked
  File "/Users/petri/Code/koodaamo/tilit/lib/python3.4/site-packages/setuptools-1.1.7-py3.4.egg/setuptools/extension.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1599, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1566, in _find_and_load_unlocked
  File "/Users/petri/Code/koodaamo/tilit/lib/python3.4/site-packages/setuptools-1.1.7-py3.4.egg/setuptools/dist.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1599, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1566, in _find_and_load_unlocked
  File "/Users/petri/Code/koodaamo/tilit/lib/python3.4/site-packages/setuptools-1.1.7-py3.4.egg/pkg_resources.py", line 2813, in <module>
  File "/Users/petri/Code/koodaamo/tilit/lib/python3.4/site-packages/setuptools-1.1.7-py3.4.egg/pkg_resources.py", line 686, in subscribe
  File "/Users/petri/Code/koodaamo/tilit/lib/python3.4/site-packages/setuptools-1.1.7-py3.4.egg/pkg_resources.py", line 2813, in <lambda>
  File "/Users/petri/Code/koodaamo/tilit/lib/python3.4/site-packages/setuptools-1.1.7-py3.4.egg/pkg_resources.py", line 2346, in activate
  File "/Users/petri/Code/koodaamo/tilit/lib/python3.4/site-packages/setuptools-1.1.7-py3.4.egg/pkg_resources.py", line 1930, in declare_namespace
KeyError: 'banking'
```

(googling for information, I found an issue in distribute, prior to its merge back to setuptools that may be similar: http://bitbucket.org/tarek/distribute/issue/204)

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/98

**Comment by Avasam** [comment]
Setuptools no longer relies on pkg_resources. If this is still relevant, the trace would now be quite different.

**Comment by abravalheri** [comment]
Thank you very much @Avasam .


I will close this issue as stale for now, but the author can re-open it with new information if necessary or create a new issue.
