### ISSUE TITLE
setuptools version 34.3.0 is unable to parse version

### ISSUE THREAD

**Issue by naoko** [pypa/setuptools#989]
Attempt to install package generated the following error:
```
Collecting nextdata
  Downloading http://pypi.nextiva.xyz/root/dev/+f/10a/fcda35b460253/nextdata-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qg52v6sf/nextdata/setup.py", line 54, in <module>
        tests_require=test_requirements,
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/srv/transporter/venv/lib/python3.5/site-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/srv/transporter/venv/lib/python3.5/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/srv/transporter/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/srv/transporter/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/srv/transporter/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/srv/transporter/venv/lib/python3.5/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/srv/transporter/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 662, in easy_install
        not self.always_copy, self.local_index
      File "/srv/transporter/venv/lib/python3.5/site-packages/setuptools/package_index.py", line 631, in fetch_distribution
        self.prescan()
      File "/srv/transporter/venv/lib/python3.5/site-packages/setuptools/package_index.py", line 532, in prescan
        list(map(self.scan_url, self.to_scan))
      File "/srv/transporter/venv/lib/python3.5/site-packages/setuptools/package_index.py", line 808, in scan_url
        self.process_url(url, True)
      File "/srv/transporter/venv/lib/python3.5/site-packages/setuptools/package_index.py", line 359, in process_url
        self.process_url(link)
      File "/srv/transporter/venv/lib/python3.5/site-packages/setuptools/package_index.py", line 329, in process_url
        list(map(self.add, dists))
      File "/srv/transporter/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1101, in add
        dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
      File "/srv/transporter/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2458, in hashcmp
        self.parsed_version,
      File "/srv/transporter/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2505, in parsed_version
        self._parsed_version = parse_version(self.version)
      File "/srv/transporter/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 201, in parse_version
        return SetuptoolsVersion(v)
      File "/srv/transporter/venv/lib/python3.5/site-packages/packaging/version.py", line 202, in __init__
        raise InvalidVersion("Invalid version: '{0}'".format(version))
    packaging.version.InvalidVersion: Invalid version: ''
```

The version number is "0.1.2".
I've even hard-coded version in setup
```
setup(
    version="0.1.2",
   .....
)
```
but the same error.
Downgraded to setuptools version`32.3.1` resolve the issue.

Please let me know if there is any other info I can provide.

**Comment by jaraco** [comment]
Hi Naoko. The problem isn't in the package you're installing or even in that dependency that's being installed, but probably in the index page for one of its dependencies. What are the dependencies of nextdata? What do the pages for each of those dependencies look like for `/root/dev/+simple/{pkg_name}` for each of those dependencies?

There were quite a few changes between 32.3.1 and 34.3.0. If you could narrow down exactly which version in which the error occurs, that will help us identify what we're looking for.

**Comment by naoko** [comment]
@jaraco , dependencies includes a few internal packages and I've reviewed index page for all and mostly
```
<package_name>-<num>.<num>.<num>.tar.gz
<package_name>-<num>.<num>.<num>-py2.py3-none-any.whl
```

one of the internal package has
```
<package_name>-<num>.<num>.<num>.linux-x86_64.tar.gz
<package_name>-<num>.<num>.<num>-py3.4.egg
```

and one packages that stood out was `marshmallow` contained alphabet in version
```
root/pypi marshmallow-3.0.0a1.tar.gz
root/pypi marshmallow-3.0.0a1-py2.py3-none-any.whl
```
could this be the cause?

**Comment by jaraco** [comment]
Those all look fine to me. Another thing to look for is what are the setup_requires for nextdata?

**Comment by naoko** [comment]
I have `setup_requires=['pytest-runner'],`

**Comment by jaraco** [comment]
Unfortunately, that's not it. I tried installing a package with a `setup_requires=['pytest-runner']`, but it installed fine. At this point, the best I can recommend is to bisect setuptools versions until you can find the version implicated.

**Comment by naoko** [comment]
Got it. Thank you very much for taking your time. I really appreciated it. I will close this now.
